// songs.js — מאגר השירים של האתר (500 שירים).
//
// סכימה לכל שיר:
//   title      — שם השיר (חובה)
//   artist     — שם האומן/הלהקה (חובה)
//   year       — שנת יציאה (חובה, מספר)
//   youtubeId  — מזהה סרטון YouTube מדויק (אופציונלי). קיים → מנגן בדיוק אותו סרטון.
//                חסר/ריק ("") → האתר נופל לחיפוש אוטומטי לפי "אומן שם-שיר".

window.SONGS = [
  { title: "איך שהיא רוקדת", artist: "עדן חסון, אופק אדנק, אגם בוחבוט", year: 2026, youtubeId: "" },
  { title: "כולם גנבים", artist: "אושר כהן", year: 2026, youtubeId: "" },
  { title: "אבי הטחול", artist: "רואי אדם", year: 2026, youtubeId: "" },
  { title: "עשר רמות מעליו", artist: "אודיה", year: 2026, youtubeId: "" },
  { title: "06", artist: "איתי לוי", year: 2026, youtubeId: "" },
  { title: "יוצאת מן הכלל", artist: "ליעד מאיר ואופק אדנק", year: 2026, youtubeId: "" },
  { title: "בשעות הבודדות", artist: "איתי לוי", year: 2026, youtubeId: "" },
  { title: "בן 32", artist: "עומר אדם", year: 2026, youtubeId: "" },
  { title: "או לה פופה", artist: "נועה קירל", year: 2026, youtubeId: "" },
  { title: "MICHELLE", artist: "נועם בתן", year: 2026, youtubeId: "" },
  { title: "בית ביפו", artist: "דודו טסה", year: 2026, youtubeId: "" },
  { title: "הלוואי", artist: "חנן בן ארי, פאר טסי", year: 2026, youtubeId: "" },
  { title: "אבי הטחול", artist: "רואי אדם", year: 2026, youtubeId: "" },
  { title: "המזרח הרחוק", artist: "שרית חדד", year: 2026, youtubeId: "" },
  { title: "ילדה מטורפת", artist: "בר צברי", year: 2026, youtubeId: "" },
  { title: "תמיד אוהב אותי", artist: "ששון איפרם שאולוב", year: 2025, youtubeId: "" },
  { title: "מלכת הדור", artist: "עומר אדם", year: 2025, youtubeId: "" },
  { title: "סופרמן", artist: "עידן עמדי", year: 2025, youtubeId: "" },
  { title: "אם את כבר הולכת", artist: "נדב חנציס", year: 2025, youtubeId: "" },
  { title: "היא לא יודעת למה", artist: "פאר טסי", year: 2025, youtubeId: "" },
  { title: "כל עכבה לטובה", artist: "בן צור", year: 2025, youtubeId: "" },
  { title: "אהובתי כבר לא רואה אותי", artist: "עומר אדם", year: 2025, youtubeId: "" },
  { title: "את לא יודעת כמה שאני אוהב אותך", artist: "אודיה", year: 2025, youtubeId: "" },
  { title: "פרפרים", artist: "אודיה", year: 2025, youtubeId: "" },
  { title: "רשימת קניות", artist: "נס, סטילה, אודיה", year: 2025, youtubeId: "" },
  { title: "פאפי", artist: "אודיה", year: 2025, youtubeId: "" },
  { title: "אליס", artist: "אודיה", year: 2025, youtubeId: "" },
  { title: "אם הייתי", artist: "איתי לוי", year: 2025, youtubeId: "" },
  { title: "טוב לי", artist: "אושר כהן", year: 2025, youtubeId: "" },
  { title: "מה יהיה מחר", artist: "פאר טסי", year: 2025, youtubeId: "" },
  { title: "מה יהיה מחר", artist: "פאר טסי", year: 2024, youtubeId: "" },
  { title: "אהבה חולה", artist: "פאר טסי", year: 2024, youtubeId: "" },
  { title: "פרפרים", artist: "אודיה", year: 2024, youtubeId: "" },
  { title: "אין אותי", artist: "פאר טסי", year: 2024, youtubeId: "" },
  { title: "מגבות", artist: "אושר כהן", year: 2024, youtubeId: "" },
  { title: "נאדי באדי", artist: "סטטיק", year: 2024, youtubeId: "" },
  { title: "חרבו דרבו", artist: "נס וסטילה", year: 2024, youtubeId: "" },
  { title: "עם ישראל חי", artist: "אייל גולן", year: 2024, youtubeId: "" },
  { title: "לצאת מדיכאון", artist: "יגל אושרי", year: 2024, youtubeId: "" },
  { title: "פחד אלוהים", artist: "כפיר צפריר", year: 2024, youtubeId: "" },
  { title: "מנגן ושר", artist: "אושר כהן", year: 2024, youtubeId: "" },
  { title: "צמוד צמוד", artist: "סטטיק ובן אל", year: 2024, youtubeId: "" },
  { title: "סופרמן", artist: "עידן עמדי", year: 2024, youtubeId: "" },
  { title: "הלוואי", artist: "חנן בן ארי", year: 2024, youtubeId: "" },
  { title: "אולי", artist: "אודיה", year: 2024, youtubeId: "" },
  { title: "יהלומים", artist: "נועה קירל", year: 2023, youtubeId: "" },
  { title: "מיליון דולר", artist: "נועה קירל", year: 2023, youtubeId: "" },
  { title: "אהבה ממבט ראשון", artist: "אושר כהן", year: 2023, youtubeId: "" },
  { title: "סוף העולם", artist: "אודיה", year: 2023, youtubeId: "" },
  { title: "פנתרה", artist: "נועה קירל", year: 2023, youtubeId: "" },
  { title: "לצאת מדיכאון", artist: "יגל אושרי", year: 2023, youtubeId: "" },
  { title: "מנגן ושר", artist: "אושר כהן", year: 2023, youtubeId: "" },
  { title: "חרבו דרבו", artist: "נס וסטילה", year: 2023, youtubeId: "" },
  { title: "אוהב אותך", artist: "אושר כהן", year: 2023, youtubeId: "" },
  { title: "כולם גנבים", artist: "אושר כהן", year: 2023, youtubeId: "" },
  { title: "תיק קטן", artist: "נטע ברזילי", year: 2023, youtubeId: "" },
  { title: "אורות", artist: "אודיה", year: 2023, youtubeId: "" },
  { title: "אין לי מקום אחר", artist: "איתי לוי", year: 2023, youtubeId: "" },
  { title: "רק שיישאר", artist: "אודיה", year: 2023, youtubeId: "" },
  { title: "הלב שלי", artist: "ישי ריבו", year: 2023, youtubeId: "" },
  { title: "סיבת הסיבות", artist: "ישי ריבו", year: 2022, youtubeId: "" },
  { title: "לצאת מדיכאון", artist: "יגל אושרי", year: 2022, youtubeId: "" },
  { title: "פחד אלוהים", artist: "כפיר צפריר", year: 2022, youtubeId: "" },
  { title: "מועבט", artist: "עדן בן זקן", year: 2022, youtubeId: "" },
  { title: "סופרסטאר", artist: "סטטיק", year: 2022, youtubeId: "" },
  { title: "בא לי אותך", artist: "אושר כהן", year: 2022, youtubeId: "" },
  { title: "הלב שלי", artist: "ישי ריבו", year: 2022, youtubeId: "" },
  { title: "אני", artist: "נועה קירל", year: 2022, youtubeId: "" },
  { title: "קפה וסיגריה", artist: "רביד פלוטניק", year: 2022, youtubeId: "" },
  { title: "תוך כדי תנועה", artist: "קרן פלס", year: 2022, youtubeId: "" },
  { title: "אהבה שלי", artist: "אודיה", year: 2022, youtubeId: "" },
  { title: "אין לי", artist: "איתי לוי", year: 2022, youtubeId: "" },
  { title: "אם הייתי", artist: "אודיה", year: 2022, youtubeId: "" },
  { title: "מכתוב", artist: "סטטיק", year: 2022, youtubeId: "" },
  { title: "שיר אהבה", artist: "עדן חסון", year: 2022, youtubeId: "" },
  { title: "מועבט", artist: "עדן בן זקן", year: 2021, youtubeId: "" },
  { title: "פנתרה", artist: "נועה קירל", year: 2021, youtubeId: "" },
  { title: "סיבת הסיבות", artist: "ישי ריבו", year: 2021, youtubeId: "" },
  { title: "שבט אחים ואחיות", artist: "עידן רייכל", year: 2021, youtubeId: "" },
  { title: "לייק דיס", artist: "סטטיק", year: 2021, youtubeId: "" },
  { title: "ככה וככה", artist: "אושר כהן", year: 2021, youtubeId: "" },
  { title: "תישארי", artist: "יובל דיין", year: 2021, youtubeId: "" },
  { title: "אין יותר טוב מזה", artist: "עדן חסון", year: 2021, youtubeId: "" },
  { title: "אוהב אותך", artist: "אייל גולן", year: 2021, youtubeId: "" },
  { title: "CEO", artist: "נטע ברזילי", year: 2021, youtubeId: "" },
  { title: "בום", artist: "רביד פלוטניק", year: 2021, youtubeId: "" },
  { title: "אני זכיתי", artist: "סטטיק", year: 2021, youtubeId: "" },
  { title: "שאריות של החיים", artist: "עידן רייכל", year: 2021, youtubeId: "" },
  { title: "שדות של אירוסים", artist: "שלמה ארצי", year: 2021, youtubeId: "" },
  { title: "הולך לי טוב", artist: "עומר אדם", year: 2021, youtubeId: "" },
  { title: "רק שלך", artist: "עומר אדם", year: 2020, youtubeId: "" },
  { title: "שקיעות אדומות", artist: "עדן חסון", year: 2020, youtubeId: "" },
  { title: "ננה בננה", artist: "נטע ברזילי", year: 2020, youtubeId: "" },
  { title: "נחכה לך", artist: "ישי ריבו", year: 2020, youtubeId: "" },
  { title: "שלוש בלילה", artist: "רביד פלוטניק", year: 2020, youtubeId: "" },
  { title: "טרילילי טרללה", artist: "נועה קירל", year: 2020, youtubeId: "" },
  { title: "אבינו מלכנו", artist: "שלומי שבת", year: 2020, youtubeId: "" },
  { title: "לב קבור", artist: "דודו אהרון", year: 2020, youtubeId: "" },
  { title: "אור גדול", artist: "מירי מסיקה", year: 2020, youtubeId: "" },
  { title: "תן לי רגע", artist: "הראל סקעת", year: 2020, youtubeId: "" },
  { title: "זאת האהבה שלנו", artist: "עברי לידר", year: 2020, youtubeId: "" },
  { title: "בין המילים", artist: "רוני דלומי", year: 2020, youtubeId: "" },
  { title: "אולי", artist: "דנה ברגר", year: 2020, youtubeId: "" },
  { title: "אהבה", artist: "אושר כהן", year: 2020, youtubeId: "" },
  { title: "לאלף את הסוסים", artist: "ריטה", year: 2020, youtubeId: "" },
  { title: "פולארויד", artist: "עומר אדם", year: 2019, youtubeId: "" },
  { title: "פאוץ'", artist: "נועה קירל", year: 2019, youtubeId: "" },
  { title: "קילר", artist: "נועה קירל", year: 2019, youtubeId: "" },
  { title: "מתפוצץ לי הראש", artist: "עדן חסון", year: 2019, youtubeId: "" },
  { title: "תן לי את האור", artist: "רביד פלוטניק", year: 2019, youtubeId: "" },
  { title: "נתראה בגלגול הבא", artist: "רביד פלוטניק", year: 2019, youtubeId: "" },
  { title: "באסה סבבה", artist: "נטע ברזילי", year: 2019, youtubeId: "" },
  { title: "אפס מאמץ", artist: "סטטיק ובן אל", year: 2019, youtubeId: "" },
  { title: "לשון הרע לא מדבר אליי", artist: "ישי ריבו", year: 2019, youtubeId: "" },
  { title: "ואם תבואי אליי", artist: "עידן רייכל", year: 2019, youtubeId: "" },
  { title: "אני בא", artist: "שלמה ארצי", year: 2019, youtubeId: "" },
  { title: "כל הכוכבים", artist: "פאר טסי", year: 2019, youtubeId: "" },
  { title: "תשמח", artist: "אייל גולן", year: 2019, youtubeId: "" },
  { title: "לא הצלחתי", artist: "אריק ברמן", year: 2019, youtubeId: "" },
  { title: "תישארי", artist: "יובל דיין", year: 2019, youtubeId: "" },
  { title: "הוזה אותך מולי", artist: "אייל גולן", year: 2018, youtubeId: "" },
  { title: "זה אני", artist: "אייל גולן", year: 2018, youtubeId: "" },
  { title: "שני משוגעים", artist: "עומר אדם", year: 2018, youtubeId: "" },
  { title: "מלכת השושנים", artist: "עדן בן זקן", year: 2018, youtubeId: "" },
  { title: "אין אותי", artist: "נועה קירל", year: 2018, youtubeId: "" },
  { title: "קילר", artist: "נועה קירל", year: 2018, youtubeId: "" },
  { title: "טודו בום", artist: "סטטיק ובן אל", year: 2018, youtubeId: "" },
  { title: "זהב", artist: "סטטיק ובן אל", year: 2018, youtubeId: "" },
  { title: "גומיגם", artist: "סטטיק ובן אל", year: 2018, youtubeId: "" },
  { title: "ימים יגידו", artist: "הראל סקעת", year: 2018, youtubeId: "" },
  { title: "מלך", artist: "מירי מסיקה", year: 2018, youtubeId: "" },
  { title: "גלים", artist: "אמיר דדון", year: 2018, youtubeId: "" },
  { title: "מחמל נפשי", artist: "שלמה ארצי", year: 2018, youtubeId: "" },
  { title: "היא לא יודעת", artist: "איתי לוי", year: 2018, youtubeId: "" },
  { title: "מעבר לנהר", artist: "קרן פלס", year: 2018, youtubeId: "" },
  { title: "שני משוגעים", artist: "עומר אדם", year: 2017, youtubeId: "" },
  { title: "מסיבה בחיפה", artist: "עדן בן זקן", year: 2017, youtubeId: "" },
  { title: "כביש החוף", artist: "סטטיק ובן אל", year: 2017, youtubeId: "" },
  { title: "טודו בום", artist: "סטטיק ובן אל", year: 2017, youtubeId: "" },
  { title: "לשוב הביתה", artist: "ישי ריבו", year: 2017, youtubeId: "" },
  { title: "סדר העבודה", artist: "ישי ריבו", year: 2017, youtubeId: "" },
  { title: "תל אביב בלילה", artist: "עדן חסון", year: 2017, youtubeId: "" },
  { title: "חצי", artist: "אמיר דדון", year: 2017, youtubeId: "" },
  { title: "מעגלים", artist: "עידן רייכל", year: 2017, youtubeId: "" },
  { title: "סוף שבוע", artist: "רביד פלוטניק", year: 2017, youtubeId: "" },
  { title: "אוהבת אותי אמיתי", artist: "עומר אדם", year: 2017, youtubeId: "" },
  { title: "רוז", artist: "פאר טסי", year: 2017, youtubeId: "" },
  { title: "שבט אחים ואחיות", artist: "עידן רייכל", year: 2017, youtubeId: "" },
  { title: "בואי ניפגש", artist: "איתי לוי", year: 2017, youtubeId: "" },
  { title: "תלתלים", artist: "רוני דלומי", year: 2017, youtubeId: "" },
  { title: "פעם בחיים", artist: "עומר אדם", year: 2016, youtubeId: "" },
  { title: "אוהבת אותי אמיתי", artist: "עומר אדם", year: 2016, youtubeId: "" },
  { title: "תזיזו", artist: "עדן בן זקן", year: 2016, youtubeId: "" },
  { title: "ברבי", artist: "סטטיק ובן אל", year: 2016, youtubeId: "" },
  { title: "משקה יקר", artist: "פאר טסי", year: 2016, youtubeId: "" },
  { title: "תן", artist: "רוני דלומי", year: 2016, youtubeId: "" },
  { title: "לאלף את הסוסים", artist: "ריטה", year: 2016, youtubeId: "" },
  { title: "עוד יגיע היום", artist: "הראל סקעת", year: 2016, youtubeId: "" },
  { title: "שיר תקווה", artist: "מירי מסיקה", year: 2016, youtubeId: "" },
  { title: "אמא", artist: "דודו אהרון", year: 2016, youtubeId: "" },
  { title: "תבואי היום", artist: "אייל גולן", year: 2016, youtubeId: "" },
  { title: "מנגינה", artist: "עדן בן זקן", year: 2016, youtubeId: "" },
  { title: "שקופים", artist: "קרן פלס", year: 2016, youtubeId: "" },
  { title: "תלתלים", artist: "רוני דלומי", year: 2016, youtubeId: "" },
  { title: "מחכה", artist: "עברי לידר", year: 2016, youtubeId: "" },
  { title: "מהפכה של שמחה", artist: "עומר אדם", year: 2015, youtubeId: "" },
  { title: "מודה אני", artist: "עומר אדם", year: 2015, youtubeId: "" },
  { title: "דרך השלום", artist: "פאר טסי", year: 2015, youtubeId: "" },
  { title: "מלכת השושנים", artist: "עדן בן זקן", year: 2015, youtubeId: "" },
  { title: "שרק תחייך", artist: "יובל דיין", year: 2015, youtubeId: "" },
  { title: "לבחור נכון", artist: "אמיר דדון", year: 2015, youtubeId: "" },
  { title: "שותפים", artist: "הדג נחש", year: 2015, youtubeId: "" },
  { title: "אם אלה החיים", artist: "קרן פלס", year: 2015, youtubeId: "" },
  { title: "הלב", artist: "שלומי שבת", year: 2015, youtubeId: "" },
  { title: "רק תבואי", artist: "עברי לידר", year: 2015, youtubeId: "" },
  { title: "בין קירות ביתי", artist: "עידן רייכל", year: 2015, youtubeId: "" },
  { title: "אולי", artist: "איתי לוי", year: 2015, youtubeId: "" },
  { title: "מילים יפות מאלה", artist: "עידן רייכל", year: 2015, youtubeId: "" },
  { title: "שיר השירים", artist: "הדג נחש", year: 2015, youtubeId: "" },
  { title: "אישתי", artist: "רוני דלומי", year: 2015, youtubeId: "" },
  { title: "מתאימה לי", artist: "עומר אדם", year: 2014, youtubeId: "" },
  { title: "יפה שלי", artist: "עומר אדם", year: 2014, youtubeId: "" },
  { title: "ימים יגידו", artist: "אייל גולן", year: 2014, youtubeId: "" },
  { title: "אין כמו אהבה", artist: "דודו אהרון", year: 2014, youtubeId: "" },
  { title: "אף אחת", artist: "מירי מסיקה", year: 2014, youtubeId: "" },
  { title: "כמו כולם", artist: "הראל סקעת", year: 2014, youtubeId: "" },
  { title: "שמות", artist: "אריק ברמן", year: 2014, youtubeId: "" },
  { title: "פנים אל מול פנים", artist: "יהודה פוליקר", year: 2014, youtubeId: "" },
  { title: "הכל עובר", artist: "קרן פלס", year: 2014, youtubeId: "" },
  { title: "בדיוק כמו הירח", artist: "יובל דיין", year: 2014, youtubeId: "" },
  { title: "בואי", artist: "ריטה", year: 2014, youtubeId: "" },
  { title: "כמו ציפור", artist: "אמיר דדון", year: 2014, youtubeId: "" },
  { title: "כמו כולם", artist: "דנה ברגר", year: 2014, youtubeId: "" },
  { title: "אהבה ראשונה", artist: "דודו אהרון", year: 2014, youtubeId: "" },
  { title: "תישארי", artist: "עברי לידר", year: 2014, youtubeId: "" },
  { title: "קאקדילה", artist: "עומר אדם", year: 2013, youtubeId: "" },
  { title: "בוקר טוב", artist: "עומר אדם", year: 2013, youtubeId: "" },
  { title: "לבדי", artist: "אייל גולן", year: 2013, youtubeId: "" },
  { title: "השיר של איתי", artist: "יובל דיין", year: 2013, youtubeId: "" },
  { title: "רוב השעות", artist: "עידן רייכל", year: 2013, youtubeId: "" },
  { title: "הכל זה מלמעלה", artist: "דודו אהרון", year: 2013, youtubeId: "" },
  { title: "חלל", artist: "אמיר דדון", year: 2013, youtubeId: "" },
  { title: "תן לי מנגינה", artist: "הדג נחש", year: 2013, youtubeId: "" },
  { title: "מילים", artist: "הראל סקעת", year: 2013, youtubeId: "" },
  { title: "רגע פרטי", artist: "ריטה", year: 2013, youtubeId: "" },
  { title: "בואי נדבר", artist: "דנה ברגר", year: 2013, youtubeId: "" },
  { title: "תודה", artist: "שלומי שבת", year: 2013, youtubeId: "" },
  { title: "אהבה כמו שלנו", artist: "קרן פלס", year: 2013, youtubeId: "" },
  { title: "מלאת אהבה", artist: "עומר אדם", year: 2013, youtubeId: "" },
  { title: "בואי אליי", artist: "עידן רייכל", year: 2013, youtubeId: "" },
  { title: "תל אביב", artist: "עומר אדם", year: 2012, youtubeId: "" },
  { title: "יפה שלי", artist: "עומר אדם", year: 2012, youtubeId: "" },
  { title: "מודה אני", artist: "עומר אדם", year: 2012, youtubeId: "" },
  { title: "תשאל את המים", artist: "יובל דיין", year: 2012, youtubeId: "" },
  { title: "ארץ חדשה", artist: "שלמה ארצי", year: 2012, youtubeId: "" },
  { title: "יש לך אותך", artist: "מירי מסיקה", year: 2012, youtubeId: "" },
  { title: "אדוני", artist: "עברי לידר", year: 2012, youtubeId: "" },
  { title: "חצי", artist: "אמיר דדון", year: 2012, youtubeId: "" },
  { title: "מילים", artist: "הראל סקעת", year: 2012, youtubeId: "" },
  { title: "שמות", artist: "אריק ברמן", year: 2012, youtubeId: "" },
  { title: "חולם אותך", artist: "יהודה פוליקר", year: 2012, youtubeId: "" },
  { title: "תוך כדי תנועה", artist: "קרן פלס", year: 2012, youtubeId: "" },
  { title: "אין כמו אהבה", artist: "דודו אהרון", year: 2012, youtubeId: "" },
  { title: "רוב השעות", artist: "עידן רייכל", year: 2012, youtubeId: "" },
  { title: "תן לי מנגינה", artist: "הדג נחש", year: 2012, youtubeId: "" },
  { title: "דרך לחיים", artist: "אייל גולן", year: 2011, youtubeId: "" },
  { title: "כשאת איתו", artist: "אייל גולן", year: 2011, youtubeId: "" },
  { title: "קלרה", artist: "עומר אדם", year: 2011, youtubeId: "" },
  { title: "מילים", artist: "הראל סקעת", year: 2011, youtubeId: "" },
  { title: "עוד אח אחד", artist: "הדג נחש", year: 2011, youtubeId: "" },
  { title: "ואת", artist: "קרן פלס", year: 2011, youtubeId: "" },
  { title: "הרי את מקודשת לי", artist: "שלומי שבת", year: 2011, youtubeId: "" },
  { title: "אהבה ראשונה", artist: "דודו אהרון", year: 2011, youtubeId: "" },
  { title: "רגע פרטי", artist: "ריטה", year: 2011, youtubeId: "" },
  { title: "רוב השעות", artist: "עידן רייכל", year: 2011, youtubeId: "" },
  { title: "תישארי", artist: "יובל דיין", year: 2011, youtubeId: "" },
  { title: "באה אליכם", artist: "מירי מסיקה", year: 2011, youtubeId: "" },
  { title: "נאחז באוויר", artist: "גידי גוב", year: 2011, youtubeId: "" },
  { title: "מלטף ומשקר", artist: "עברי לידר", year: 2011, youtubeId: "" },
  { title: "עוד", artist: "אמיר דדון", year: 2011, youtubeId: "" },
  { title: "מחוזקים לעולם", artist: "אמיר דדון", year: 2010, youtubeId: "" },
  { title: "אור גדול", artist: "אמיר דדון", year: 2010, youtubeId: "" },
  { title: "מלכת היופי שלי", artist: "אייל גולן", year: 2010, youtubeId: "" },
  { title: "נולדת בשבילי", artist: "אייל גולן", year: 2010, youtubeId: "" },
  { title: "כמו אז", artist: "שלמה ארצי", year: 2010, youtubeId: "" },
  { title: "אחרי הכול את שיר", artist: "שלמה ארצי", year: 2010, youtubeId: "" },
  { title: "לא מספיק", artist: "הדג נחש", year: 2010, youtubeId: "" },
  { title: "כמו ציפור", artist: "ריטה", year: 2010, youtubeId: "" },
  { title: "באה אליכם", artist: "מירי מסיקה", year: 2010, youtubeId: "" },
  { title: "רק אלוהים ישפוט אותי", artist: "קרן פלס", year: 2010, youtubeId: "" },
  { title: "בית משוגעים", artist: "רוני דלומי", year: 2010, youtubeId: "" },
  { title: "תגידי לי", artist: "דודו אהרון", year: 2010, youtubeId: "" },
  { title: "מלטף ומשקר", artist: "עברי לידר", year: 2010, youtubeId: "" },
  { title: "בואי נדבר", artist: "ארקדי דוכין", year: 2010, youtubeId: "" },
  { title: "רכבת", artist: "דנה ברגר", year: 2010, youtubeId: "" },
  { title: "מי שמאמין", artist: "אייל גולן", year: 2009, youtubeId: "" },
  { title: "היא לא יודעת מה עובר עליי", artist: "אייל גולן", year: 2009, youtubeId: "" },
  { title: "מכל האהבות", artist: "דודו אהרון", year: 2009, youtubeId: "" },
  { title: "הנני כאן", artist: "הראל סקעת", year: 2009, youtubeId: "" },
  { title: "שיר תקווה", artist: "מירי מסיקה", year: 2009, youtubeId: "" },
  { title: "בגלל הרוח", artist: "שלומי שבת", year: 2009, youtubeId: "" },
  { title: "האם אתה מאושר", artist: "ריטה", year: 2009, youtubeId: "" },
  { title: "אני מאמין", artist: "הדג נחש", year: 2009, youtubeId: "" },
  { title: "רק אלוהים ישפוט אותי", artist: "קרן פלס", year: 2009, youtubeId: "" },
  { title: "אהבה ממבט ראשון", artist: "אריק ברמן", year: 2009, youtubeId: "" },
  { title: "בוקר טוב", artist: "עברי לידר", year: 2009, youtubeId: "" },
  { title: "תגידי לי", artist: "דודו אהרון", year: 2009, youtubeId: "" },
  { title: "כמו כולם", artist: "דנה ברגר", year: 2009, youtubeId: "" },
  { title: "שוב", artist: "ארקדי דוכין", year: 2009, youtubeId: "" },
  { title: "לא דומה", artist: "דודו אהרון", year: 2009, youtubeId: "" },
  { title: "הוזה אותך מולי", artist: "אייל גולן", year: 2008, youtubeId: "" },
  { title: "זה אני", artist: "אייל גולן", year: 2008, youtubeId: "" },
  { title: "נובמבר", artist: "מירי מסיקה", year: 2008, youtubeId: "" },
  { title: "תמיד אהבה", artist: "עברי לידר", year: 2008, youtubeId: "" },
  { title: "בואי ניפרד", artist: "גידי גוב", year: 2008, youtubeId: "" },
  { title: "עיניים שלי", artist: "יהודה פוליקר", year: 2008, youtubeId: "" },
  { title: "המתוקות האחרונות", artist: "אריק ברמן", year: 2008, youtubeId: "" },
  { title: "כמו פעם", artist: "ארקדי דוכין", year: 2008, youtubeId: "" },
  { title: "משבר אמון", artist: "ריטה", year: 2008, youtubeId: "" },
  { title: "מילים יפות", artist: "עידן רייכל", year: 2008, youtubeId: "" },
  { title: "רכבת", artist: "דנה ברגר", year: 2008, youtubeId: "" },
  { title: "כמו ציפור", artist: "יובל דיין", year: 2008, youtubeId: "" },
  { title: "ימים יגידו", artist: "הראל סקעת", year: 2008, youtubeId: "" },
  { title: "אהבה ראשונה", artist: "דודו אהרון", year: 2008, youtubeId: "" },
  { title: "תן", artist: "רוני דלומי", year: 2008, youtubeId: "" },
  { title: "אם יש גן עדן", artist: "אייל גולן", year: 2007, youtubeId: "" },
  { title: "תתארו לכם", artist: "שלמה ארצי", year: 2007, youtubeId: "" },
  { title: "איסלנד", artist: "שלמה ארצי", year: 2007, youtubeId: "" },
  { title: "הנה אני בא", artist: "הדג נחש", year: 2007, youtubeId: "" },
  { title: "אני מאמין", artist: "הדג נחש", year: 2007, youtubeId: "" },
  { title: "אהבה ממבט ראשון", artist: "אריק ברמן", year: 2007, youtubeId: "" },
  { title: "יום חדש נפלא", artist: "אריק ברמן", year: 2007, youtubeId: "" },
  { title: "שביל הבריחה", artist: "עברי לידר", year: 2007, youtubeId: "" },
  { title: "מילים", artist: "הראל סקעת", year: 2007, youtubeId: "" },
  { title: "אם אלה החיים", artist: "קרן פלס", year: 2007, youtubeId: "" },
  { title: "תן", artist: "רוני דלומי", year: 2007, youtubeId: "" },
  { title: "בואי", artist: "ריטה", year: 2007, youtubeId: "" },
  { title: "ממעמקים", artist: "עידן רייכל", year: 2007, youtubeId: "" },
  { title: "לשם", artist: "מירי מסיקה", year: 2007, youtubeId: "" },
  { title: "בוא", artist: "עברי לידר", year: 2007, youtubeId: "" },
  { title: "אל תלכי לי", artist: "אייל גולן", year: 2006, youtubeId: "" },
  { title: "אתה ואני", artist: "הראל סקעת", year: 2006, youtubeId: "" },
  { title: "ואת", artist: "הראל סקעת", year: 2006, youtubeId: "" },
  { title: "השקט שנשאר", artist: "שירי מימון", year: 2006, youtubeId: "" },
  { title: "אור", artist: "שירי מימון", year: 2006, youtubeId: "" },
  { title: "מפחד עלייך", artist: "מירי מסיקה", year: 2006, youtubeId: "" },
  { title: "אני שוב מתאהב", artist: "גידי גוב", year: 2006, youtubeId: "" },
  { title: "לומדת לעוף", artist: "דנה ברגר", year: 2006, youtubeId: "" },
  { title: "ממעמקים", artist: "הפרויקט של עידן רייכל", year: 2006, youtubeId: "" },
  { title: "הנה אני בא", artist: "הדג נחש", year: 2006, youtubeId: "" },
  { title: "זכיתי לאהוב", artist: "עברי לידר", year: 2006, youtubeId: "" },
  { title: "בואי", artist: "ריטה", year: 2006, youtubeId: "" },
  { title: "יש בי אהבה", artist: "אריק איינשטיין", year: 2006, youtubeId: "" },
  { title: "שביל הבריחה", artist: "עברי לידר", year: 2006, youtubeId: "" },
  { title: "מחכה", artist: "ריטה", year: 2006, youtubeId: "" },
  { title: "מצטער", artist: "אייל גולן", year: 2005, youtubeId: "" },
  { title: "ממעמקים", artist: "הפרויקט של עידן רייכל", year: 2005, youtubeId: "" },
  { title: "הנך יפה", artist: "הפרויקט של עידן רייכל", year: 2005, youtubeId: "" },
  { title: "מדברים בשקט", artist: "הפרויקט של עידן רייכל", year: 2005, youtubeId: "" },
  { title: "לשם", artist: "מירי מסיקה", year: 2005, youtubeId: "" },
  { title: "אם זאת אהבה", artist: "מירי מסיקה", year: 2005, youtubeId: "" },
  { title: "ניסים", artist: "עברי לידר", year: 2005, youtubeId: "" },
  { title: "רוב השעות", artist: "עידן רייכל", year: 2005, youtubeId: "" },
  { title: "שלל שרב", artist: "גידי גוב", year: 2005, youtubeId: "" },
  { title: "איך קוראים לאהבה שלי", artist: "יהודה פוליקר", year: 2005, youtubeId: "" },
  { title: "בוא", artist: "עברי לידר", year: 2005, youtubeId: "" },
  { title: "באה אליכם", artist: "מירי מסיקה", year: 2005, youtubeId: "" },
  { title: "תמיד אהבה", artist: "עברי לידר", year: 2005, youtubeId: "" },
  { title: "מילים יפות מאלה", artist: "עידן רייכל", year: 2005, youtubeId: "" },
  { title: "אני מאמין", artist: "הדג נחש", year: 2005, youtubeId: "" },
  { title: "בואי", artist: "עברי לידר", year: 2004, youtubeId: "" },
  { title: "כשתבוא", artist: "הדג נחש", year: 2004, youtubeId: "" },
  { title: "שירת הסטיקר", artist: "הדג נחש", year: 2004, youtubeId: "" },
  { title: "גבי ודבי", artist: "הדג נחש", year: 2004, youtubeId: "" },
  { title: "מי אוהב אותך יותר ממני", artist: "ארקדי דוכין", year: 2004, youtubeId: "" },
  { title: "בחוף של טרפטוני", artist: "שלומי שבת", year: 2004, youtubeId: "" },
  { title: "כשתגדל", artist: "יהודה פוליקר", year: 2004, youtubeId: "" },
  { title: "האהבה הישנה", artist: "שלמה ארצי", year: 2004, youtubeId: "" },
  { title: "אתה בכל זאת", artist: "ריטה", year: 2004, youtubeId: "" },
  { title: "מישהו פעם", artist: "עברי לידר", year: 2004, youtubeId: "" },
  { title: "איך קוראים לאהבה שלי", artist: "יהודה פוליקר", year: 2004, youtubeId: "" },
  { title: "בואי", artist: "ריטה", year: 2004, youtubeId: "" },
  { title: "יותר טוב כלום מכמעט", artist: "עברי לידר", year: 2004, youtubeId: "" },
  { title: "לזוז", artist: "הדג נחש", year: 2004, youtubeId: "" },
  { title: "המתוקות האחרונות", artist: "אריק ברמן", year: 2004, youtubeId: "" },
  { title: "לזוז", artist: "הדג נחש", year: 2003, youtubeId: "" },
  { title: "אומרים ישנה ארץ", artist: "שלמה ארצי", year: 2003, youtubeId: "" },
  { title: "יותר טוב כלום מכמעט", artist: "עברי לידר", year: 2003, youtubeId: "" },
  { title: "אף פעם לא תדעי", artist: "שלמה ארצי", year: 2003, youtubeId: "" },
  { title: "מי אוהב אותך יותר ממני", artist: "ארקדי דוכין", year: 2003, youtubeId: "" },
  { title: "בחוף של טרפטוני", artist: "שלומי שבת", year: 2003, youtubeId: "" },
  { title: "דברים שרציתי לומר", artist: "יהודה פוליקר", year: 2003, youtubeId: "" },
  { title: "כשתגדל", artist: "יהודה פוליקר", year: 2003, youtubeId: "" },
  { title: "שביל הבריחה", artist: "ריטה", year: 2003, youtubeId: "" },
  { title: "בוא", artist: "ריטה", year: 2003, youtubeId: "" },
  { title: "ממעמקים", artist: "עידן רייכל", year: 2003, youtubeId: "" },
  { title: "בואי", artist: "עברי לידר", year: 2003, youtubeId: "" },
  { title: "מילים יפות מאלה", artist: "עידן רייכל", year: 2003, youtubeId: "" },
  { title: "כמו ציפור", artist: "ריטה", year: 2003, youtubeId: "" },
  { title: "אני מאמין", artist: "הדג נחש", year: 2003, youtubeId: "" },
  { title: "אם תלך", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "" },
  { title: "הנך יפה", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "" },
  { title: "בואי", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "" },
  { title: "שושנים", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "" },
  { title: "ממעמקים", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "" },
  { title: "תודה", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "" },
  { title: "מכל האהבות", artist: "עידן רייכל", year: 2002, youtubeId: "" },
  { title: "פחות אבל כואב", artist: "יהודה פוליקר", year: 2002, youtubeId: "" },
  { title: "עד הקצה", artist: "דנה ברגר", year: 2002, youtubeId: "" },
  { title: "אתה בכל זאת", artist: "ריטה", year: 2002, youtubeId: "" },
  { title: "זכיתי לאהוב", artist: "עברי לידר", year: 2002, youtubeId: "" },
  { title: "כשתבוא", artist: "הדג נחש", year: 2002, youtubeId: "" },
  { title: "שביל הבריחה", artist: "ריטה", year: 2002, youtubeId: "" },
  { title: "בואי", artist: "עברי לידר", year: 2002, youtubeId: "" },
  { title: "מי אוהב אותך יותר ממני", artist: "ארקדי דוכין", year: 2002, youtubeId: "" },
  { title: "זכיתי לאהוב", artist: "עברי לידר", year: 2001, youtubeId: "" },
  { title: "אמא", artist: "שלומי שבת", year: 2001, youtubeId: "" },
  { title: "דברים שרציתי לומר", artist: "יהודה פוליקר", year: 2001, youtubeId: "" },
  { title: "בוא", artist: "ריטה", year: 2001, youtubeId: "" },
  { title: "מישהו פעם", artist: "עברי לידר", year: 2001, youtubeId: "" },
  { title: "אני ואתה", artist: "אריק איינשטיין", year: 2001, youtubeId: "" },
  { title: "ירח", artist: "שלמה ארצי", year: 2001, youtubeId: "" },
  { title: "מי אוהב אותך יותר ממני", artist: "ארקדי דוכין", year: 2001, youtubeId: "" },
  { title: "כמו פעם", artist: "ארקדי דוכין", year: 2001, youtubeId: "" },
  { title: "בגלל הרוח", artist: "שלומי שבת", year: 2001, youtubeId: "" },
  { title: "מחכה", artist: "ריטה", year: 2001, youtubeId: "" },
  { title: "האהבה הישנה", artist: "שלמה ארצי", year: 2001, youtubeId: "" },
  { title: "יותר טוב כלום מכמעט", artist: "עברי לידר", year: 2001, youtubeId: "" },
  { title: "ממעמקים", artist: "עידן רייכל", year: 2001, youtubeId: "" },
  { title: "כשתגדל", artist: "יהודה פוליקר", year: 2001, youtubeId: "" },
  { title: "מישהו פעם", artist: "עברי לידר", year: 2000, youtubeId: "" },
  { title: "לא פראיירים", artist: "הדג נחש", year: 2000, youtubeId: "" },
  { title: "אתה לי ארץ", artist: "שלמה ארצי", year: 2000, youtubeId: "" },
  { title: "ירח", artist: "שלמה ארצי", year: 2000, youtubeId: "" },
  { title: "גוליית", artist: "גידי גוב", year: 2000, youtubeId: "" },
  { title: "נאחז באוויר", artist: "גידי גוב", year: 2000, youtubeId: "" },
  { title: "היא", artist: "דנה ברגר", year: 2000, youtubeId: "" },
  { title: "יש בי אהבה", artist: "ארקדי דוכין", year: 2000, youtubeId: "" },
  { title: "מחכה", artist: "ריטה", year: 2000, youtubeId: "" },
  { title: "דברים שרציתי לומר", artist: "יהודה פוליקר", year: 2000, youtubeId: "" },
  { title: "אהבה כמו שלנו", artist: "קרן פלס", year: 2000, youtubeId: "" },
  { title: "מכל האהבות", artist: "דודו אהרון", year: 2000, youtubeId: "" },
  { title: "בוא", artist: "עברי לידר", year: 2000, youtubeId: "" },
  { title: "מי אוהב אותך יותר ממני", artist: "ארקדי דוכין", year: 2000, youtubeId: "" },
  { title: "אני מאמין", artist: "הדג נחש", year: 2000, youtubeId: "" },
  { title: "מיליארד טועים", artist: "אביב גפן", year: 1999, youtubeId: "" },
  { title: "האם להיות בך מאוהב", artist: "אביב גפן", year: 1999, youtubeId: "" },
  { title: "שיר תקווה", artist: "אביב גפן", year: 1999, youtubeId: "" },
  { title: "רכבת לילה לקהיר", artist: "משינה", year: 1999, youtubeId: "" },
  { title: "אהובתי", artist: "משינה", year: 1999, youtubeId: "" },
  { title: "אני חיה לי מיום ליום", artist: "ריטה", year: 1999, youtubeId: "" },
  { title: "מחכה", artist: "ריטה", year: 1999, youtubeId: "" },
  { title: "כשהלב הוא חופשי", artist: "ריטה", year: 1999, youtubeId: "" },
  { title: "אין מקום אחר", artist: "משינה", year: 1999, youtubeId: "" },
  { title: "ירח", artist: "שלמה ארצי", year: 1999, youtubeId: "" },
  { title: "שיר לשירה", artist: "קורין אלאל", year: 1998, youtubeId: "" },
  { title: "זה מה שנשאר", artist: "שלמה ארצי", year: 1998, youtubeId: "" },
  { title: "אור הירח", artist: "אביב גפן", year: 1998, youtubeId: "" },
  { title: "עונות", artist: "אביב גפן", year: 1998, youtubeId: "" },
  { title: "גשם כבד", artist: "אביב גפן", year: 1998, youtubeId: "" },
  { title: "לבכות לך", artist: "אביב גפן", year: 1998, youtubeId: "" },
  { title: "הכוכבים דולקים על אש קטנה", artist: "משינה", year: 1998, youtubeId: "" },
  { title: "אני ואתה", artist: "אריק איינשטיין", year: 1998, youtubeId: "" },
  { title: "עטור מצחך", artist: "אריק איינשטיין", year: 1998, youtubeId: "" },
  { title: "אין לי ארץ אחרת", artist: "גידי גוב", year: 1998, youtubeId: "" },
  { title: "זה מה שנשאר", artist: "שלמה ארצי", year: 1997, youtubeId: "" },
  { title: "אני מאמין", artist: "שלמה ארצי", year: 1997, youtubeId: "" },
  { title: "לבכות לך", artist: "אביב גפן", year: 1997, youtubeId: "" },
  { title: "עונות", artist: "אביב גפן", year: 1997, youtubeId: "" },
  { title: "אור הירח", artist: "אביב גפן", year: 1997, youtubeId: "" },
  { title: "כמו ציפור", artist: "ריטה", year: 1997, youtubeId: "" },
  { title: "מחכים למשיח", artist: "שלום חנוך", year: 1997, youtubeId: "" },
  { title: "רק בגלל הרוח", artist: "שלמה ארצי", year: 1997, youtubeId: "" },
  { title: "באה מאהבה", artist: "יהודית רביץ", year: 1997, youtubeId: "" },
  { title: "אין לי ארץ אחרת", artist: "גידי גוב", year: 1997, youtubeId: "" },
  { title: "כשהלב הוא חופשי", artist: "ריטה", year: 1996, youtubeId: "" },
  { title: "אני חיה לי מיום ליום", artist: "ריטה", year: 1996, youtubeId: "" },
  { title: "משבר אמון", artist: "ריטה", year: 1996, youtubeId: "" },
  { title: "אור הירח", artist: "אביב גפן", year: 1996, youtubeId: "" },
  { title: "האם להיות בך מאוהב", artist: "אביב גפן", year: 1996, youtubeId: "" },
  { title: "לבכות לך", artist: "אביב גפן", year: 1996, youtubeId: "" },
  { title: "מיליארד טועים", artist: "אביב גפן", year: 1996, youtubeId: "" },
  { title: "רק בגלל הרוח", artist: "שלמה ארצי", year: 1996, youtubeId: "" },
  { title: "ירח", artist: "שלמה ארצי", year: 1996, youtubeId: "" },
  { title: "אין לי ארץ אחרת", artist: "גידי גוב", year: 1996, youtubeId: "" },
  { title: "אור הירח", artist: "אביב גפן", year: 1995, youtubeId: "" },
  { title: "האם להיות בך מאוהב", artist: "אביב גפן", year: 1995, youtubeId: "" },
  { title: "מיליארד טועים", artist: "אביב גפן", year: 1995, youtubeId: "" },
  { title: "עונות", artist: "אביב גפן", year: 1995, youtubeId: "" },
  { title: "לבכות לך", artist: "אביב גפן", year: 1995, youtubeId: "" },
  { title: "רכבת לילה לקהיר", artist: "משינה", year: 1995, youtubeId: "" },
  { title: "שלח לי מלאך", artist: "משינה", year: 1995, youtubeId: "" },
  { title: "אהובתי", artist: "משינה", year: 1995, youtubeId: "" },
  { title: "רק בגלל הרוח", artist: "שלמה ארצי", year: 1995, youtubeId: "" },
  { title: "ירח", artist: "שלמה ארצי", year: 1995, youtubeId: "" },
  { title: "שיר תקווה", artist: "אביב גפן", year: 1994, youtubeId: "" },
  { title: "גשם כבד", artist: "אביב גפן", year: 1994, youtubeId: "" },
  { title: "לבכות לך", artist: "אביב גפן", year: 1994, youtubeId: "" },
  { title: "אהובתי", artist: "משינה", year: 1994, youtubeId: "" },
  { title: "אין מקום אחר", artist: "משינה", year: 1994, youtubeId: "" },
  { title: "ריקוד ירח", artist: "ריטה", year: 1994, youtubeId: "" },
  { title: "מחכה", artist: "ריטה", year: 1994, youtubeId: "" },
  { title: "משבר אמון", artist: "ריטה", year: 1994, youtubeId: "" },
  { title: "רק בגלל הרוח", artist: "שלמה ארצי", year: 1994, youtubeId: "" },
  { title: "ירח", artist: "שלמה ארצי", year: 1994, youtubeId: "" },
  { title: "לילה בעיר", artist: "משינה", year: 1993, youtubeId: "" },
  { title: "גשם כבד", artist: "אביב גפן", year: 1993, youtubeId: "" },
  { title: "לבכות לך", artist: "אביב גפן", year: 1993, youtubeId: "" },
  { title: "מיליארד טועים", artist: "אביב גפן", year: 1993, youtubeId: "" },
  { title: "רק בגלל הרוח", artist: "שלמה ארצי", year: 1993, youtubeId: "" },
  { title: "ירח", artist: "שלמה ארצי", year: 1993, youtubeId: "" },
  { title: "אני חיה לי מיום ליום", artist: "ריטה", year: 1993, youtubeId: "" },
  { title: "כשהלב הוא חופשי", artist: "ריטה", year: 1993, youtubeId: "" },
  { title: "אין לי ארץ אחרת", artist: "גידי גוב", year: 1993, youtubeId: "" },
  { title: "הכוכבים דולקים על אש קטנה", artist: "משינה", year: 1993, youtubeId: "" },
  { title: "אין מקום אחר", artist: "משינה", year: 1992, youtubeId: "" },
  { title: "מיליארד טועים", artist: "אביב גפן", year: 1992, youtubeId: "" },
  { title: "עונות", artist: "אביב גפן", year: 1992, youtubeId: "" },
  { title: "ירח", artist: "שלמה ארצי", year: 1992, youtubeId: "" },
  { title: "אני חיה לי מיום ליום", artist: "ריטה", year: 1992, youtubeId: "" },
  { title: "הכוכבים דולקים על אש קטנה", artist: "משינה", year: 1991, youtubeId: "" },
  { title: "רכבת לילה לקהיר", artist: "משינה", year: 1991, youtubeId: "" },
  { title: "אהובתי", artist: "משינה", year: 1991, youtubeId: "" },
  { title: "אין מקום אחר", artist: "משינה", year: 1991, youtubeId: "" },
  { title: "כשהלב הוא חופשי", artist: "ריטה", year: 1991, youtubeId: "" },
  { title: "רכבת לילה לקהיר", artist: "משינה", year: 1990, youtubeId: "" },
  { title: "אמא", artist: "שלמה ארצי", year: 1990, youtubeId: "" },
  { title: "אחרי הכול את שיר", artist: "שלמה ארצי", year: 1990, youtubeId: "" },
  { title: "ריקוד ירח", artist: "ריטה", year: 1990, youtubeId: "" },
  { title: "כמו שאתה", artist: "מרגלית צנעני", year: 1990, youtubeId: "" },
  { title: "רק בגלל הרוח", artist: "שלמה ארצי", year: 1989, youtubeId: "" },
  { title: "שיר לשירה", artist: "קורין אלאל", year: 1989, youtubeId: "" },
  { title: "דרך ארוכה", artist: "גידי גוב", year: 1989, youtubeId: "" },
  { title: "שלח לי מלאך", artist: "משינה", year: 1988, youtubeId: "" },
  { title: "בדרך אל הים", artist: "משינה", year: 1988, youtubeId: "" },
  { title: "עוף גוזל", artist: "אריק איינשטיין", year: 1987, youtubeId: "" },
  { title: "לתת", artist: "בועז שרעבי", year: 1987, youtubeId: "" },
  { title: "אוהב להיות בבית", artist: "אריק איינשטיין", year: 1986, youtubeId: "" },
  { title: "מחכים למשיח", artist: "שלום חנוך", year: 1985, youtubeId: "" },
  { title: "מאיה", artist: "שלום חנוך", year: 1984, youtubeId: "" }
];
