// songs.js — מאגר השירים של האתר (שירים ייחודיים, ללא כפילויות).
//
// סכימה לכל שיר:
//   title      — שם השיר (חובה)
//   artist     — שם האומן/הלהקה (חובה)
//   year       — שנת יציאה (חובה, מספר)
//   youtubeId  — מזהה סרטון YouTube מדויק (אופציונלי). קיים → מנגן בדיוק אותו סרטון.
//                חסר/ריק ("") → האתר נופל לחיפוש אוטומטי לפי "אומן שם-שיר".
//
// הערה: הרשימה המקורית (500 שורות) הכילה כפילויות — אותו שיר שהופיע בכמה
// שנים כי נשאר פופולרי לאורך זמן. הן סוננו, נשאר מופע ראשון של כל צירוף
// שיר+אומן (השנה שנשמרה היא זו של המופע המוקדם ביותר ברשימה המקורית).

window.SONGS = [
  { title: "איך שהיא רוקדת", artist: "עדן חסון, אופק אדנק, אגם בוחבוט", year: 2026, youtubeId: "eaqW5eQXTdM" },
  { title: "כולם גנבים", artist: "אושר כהן", year: 2026, youtubeId: "INKpPFwOQLY" },
  { title: "אבי הטחול", artist: "רואי אדם", year: 2026, youtubeId: "yrlyruDX5vI" },
  { title: "עשר רמות מעליו", artist: "אודיה", year: 2026, youtubeId: "VFH6mJHFILc" },
  { title: "06", artist: "איתי לוי", year: 2026, youtubeId: "O4zEeaMtmHI" },
  { title: "יוצאת מן הכלל", artist: "ליעד מאיר ואופק אדנק", year: 2026, youtubeId: "1ZlX-M3l7R8" },
  { title: "בשעות הבודדות", artist: "איתי לוי", year: 2026, youtubeId: "TGv3akMUreA" },
  { title: "בן 32", artist: "עומר אדם", year: 2026, youtubeId: "7PE611GuMAk" },
  { title: "או לה פופה", artist: "נועה קירל", year: 2026, youtubeId: "aQfI0WP-fcE" },
  { title: "MICHELLE", artist: "נועם בתן", year: 2026, youtubeId: "xWCnWSoG8nI" },
  { title: "בית ביפו", artist: "דודו טסה", year: 2026, youtubeId: "zXwkMXMyYJc" },
  { title: "הלוואי", artist: "חנן בן ארי, פאר טסי", year: 2026, youtubeId: "4DbqBFPv1aE" },
  { title: "המזרח הרחוק", artist: "שרית חדד", year: 2026, youtubeId: "foy3MEZTP50" },
  { title: "ילדה מטורפת", artist: "בר צברי", year: 2026, youtubeId: "53Y37uuuvOM" },
  { title: "תמיד אוהב אותי", artist: "ששון איפרם שאולוב", year: 2025, youtubeId: "rgSvk335zis" },
  { title: "מלכת הדור", artist: "עומר אדם", year: 2025, youtubeId: "fVMihvd4Xzs" },
  { title: "סופרמן", artist: "עידן עמדי", year: 2025, youtubeId: "zv7l6nRI--M" },
  { title: "אם את כבר הולכת", artist: "נדב חנציס", year: 2025, youtubeId: "Ki94rmDMoPk" },
  { title: "היא לא יודעת למה", artist: "פאר טסי", year: 2025, youtubeId: "Dl4RKBYRUxQ" },
  { title: "כל עכבה לטובה", artist: "בן צור", year: 2025, youtubeId: "1u8-tOmOVyU" },
  { title: "אהובתי כבר לא רואה אותי", artist: "עומר אדם", year: 2025, youtubeId: "QzDpV_8HVXk" },
  { title: "את לא יודעת כמה שאני אוהב אותך", artist: "אודיה", year: 2025, youtubeId: "J-q28gVKEcA" },
  { title: "פרפרים", artist: "אודיה", year: 2025, youtubeId: "GmagbJ_bGZI" },
  { title: "רשימת קניות", artist: "נס, סטילה, אודיה", year: 2025, youtubeId: "kYntjh4XEto" },
  { title: "פאפי", artist: "אודיה", year: 2025, youtubeId: "zgcBg0ofc0c" },
  { title: "אליס", artist: "אודיה", year: 2025, youtubeId: "N-eAGk1uySY" },
  { title: "אם הייתי", artist: "איתי לוי", year: 2025, youtubeId: "_6HXt6s4b7k" },
  { title: "טוב לי", artist: "אושר כהן", year: 2025, youtubeId: "SlE5Dh9GkpQ" },
  { title: "מה יהיה מחר", artist: "פאר טסי", year: 2025, youtubeId: "Iay1xdXljb4" },
  { title: "אהבה חולה", artist: "פאר טסי", year: 2024, youtubeId: "SNRBruxYezA" },
  { title: "אין אותי", artist: "פאר טסי", year: 2024, youtubeId: "h3iqvIWAfck" },
  { title: "מגבות", artist: "אושר כהן", year: 2024, youtubeId: "9EtqfxPt7p4" },
  { title: "נאדי באדי", artist: "סטטיק", year: 2024, youtubeId: "xqr9rZ8eBBc" },
  { title: "חרבו דרבו", artist: "נס וסטילה", year: 2024, youtubeId: "1rk3n9V-aQs" },
  { title: "עם ישראל חי", artist: "אייל גולן", year: 2024, youtubeId: "1HgKB4-kQdA" },
  { title: "לצאת מדיכאון", artist: "יגל אושרי", year: 2024, youtubeId: "9XIZ_T_vg_E" },
  { title: "פחד אלוהים", artist: "כפיר צפריר", year: 2024, youtubeId: "kBLdR1J8Je4" },
  { title: "מנגן ושר", artist: "אושר כהן", year: 2024, youtubeId: "AZMuSrWcsEg" },
  { title: "צמוד צמוד", artist: "סטטיק ובן אל", year: 2024, youtubeId: "dFqAtitDNvs" },
  { title: "הלוואי", artist: "חנן בן ארי", year: 2024, youtubeId: "4DbqBFPv1aE" },
  { title: "אולי", artist: "אודיה", year: 2024, youtubeId: "anQ-E7C1bPI" },
  { title: "יהלומים", artist: "נועה קירל", year: 2023, youtubeId: "X7iLyas7Oi4" },
  { title: "מיליון דולר", artist: "נועה קירל", year: 2023, youtubeId: "oQbh5Kvet04" },
  { title: "אהבה ממבט ראשון", artist: "אושר כהן", year: 2023, youtubeId: "K1nQX_hdop0" },
  { title: "סוף העולם", artist: "אודיה", year: 2023, youtubeId: "YIlpBbJG-wM" },
  { title: "פנתרה", artist: "נועה קירל", year: 2023, youtubeId: "ZOf7aMbzQAM" },
  { title: "אוהב אותך", artist: "אושר כהן", year: 2023, youtubeId: "p1z6MInHFrM" },
  { title: "תיק קטן", artist: "נטע ברזילי", year: 2023, youtubeId: "ClhlOrw-uyY" },
  { title: "אורות", artist: "אודיה", year: 2023, youtubeId: "Z4WQrHYEGY4" },
  { title: "אין לי מקום אחר", artist: "איתי לוי", year: 2023, youtubeId: "RAsTZqalx-g" },
  { title: "רק שיישאר", artist: "אודיה", year: 2023, youtubeId: "yhOc8kIsCsc" },
  { title: "הלב שלי", artist: "ישי ריבו", year: 2023, youtubeId: "6U_5KhaH6IM" },
  { title: "סיבת הסיבות", artist: "ישי ריבו", year: 2022, youtubeId: "T5Wf3gmF6Do" },
  { title: "מועבט", artist: "עדן בן זקן", year: 2022, youtubeId: "yoIeg9B8EEg" },
  { title: "סופרסטאר", artist: "סטטיק", year: 2022, youtubeId: "Yk7ujZ7bu-A" },
  { title: "בא לי אותך", artist: "אושר כהן", year: 2022, youtubeId: "71VqdvZf2qM" },
  { title: "אני", artist: "נועה קירל", year: 2022, youtubeId: "jmSuPQu7xNA" },
  { title: "קפה וסיגריה", artist: "רביד פלוטניק", year: 2022, youtubeId: "dmUGuJf-cgg" },
  { title: "תוך כדי תנועה", artist: "קרן פלס", year: 2022, youtubeId: "u1k1CdFtHjE" },
  { title: "אהבה שלי", artist: "אודיה", year: 2022, youtubeId: "roop3ndu_BY" },
  { title: "אין לי", artist: "איתי לוי", year: 2022, youtubeId: "RAsTZqalx-g" },
  { title: "אם הייתי", artist: "אודיה", year: 2022, youtubeId: "cSkTzkGoot0" },
  { title: "מכתוב", artist: "סטטיק", year: 2022, youtubeId: "LvxZC4lfIts" },
  { title: "שיר אהבה", artist: "עדן חסון", year: 2022, youtubeId: "th5Br6OAEbg" },
  { title: "שבט אחים ואחיות", artist: "עידן רייכל", year: 2021, youtubeId: "xWx3R7WaAQY" },
  { title: "לייק דיס", artist: "סטטיק", year: 2021, youtubeId: "lYfrKmEYpdA" },
  { title: "ככה וככה", artist: "אושר כהן", year: 2021, youtubeId: "KmuH00cOKno" },
  { title: "תישארי", artist: "יובל דיין", year: 2021, youtubeId: "3qmvZ_tjU7Y" },
  { title: "אין יותר טוב מזה", artist: "עדן חסון", year: 2021, youtubeId: "hySvIlHhCgA" },
  { title: "אוהב אותך", artist: "אייל גולן", year: 2021, youtubeId: "gz3_IZc5NSk" },
  { title: "CEO", artist: "נטע ברזילי", year: 2021, youtubeId: "CuI9hg7tuhI" },
  { title: "בום", artist: "רביד פלוטניק", year: 2021, youtubeId: "x8gw0WcESFE" },
  { title: "אני זכיתי", artist: "סטטיק", year: 2021, youtubeId: "gn7x1PvJUdc" },
  { title: "שאריות של החיים", artist: "עידן רייכל", year: 2021, youtubeId: "xYYYctLmnt4" },
  { title: "שדות של אירוסים", artist: "שלמה ארצי", year: 2021, youtubeId: "L3uG2knMb4s" },
  { title: "הולך לי טוב", artist: "עומר אדם", year: 2021, youtubeId: "171Ex5ZV7fo" },
  { title: "רק שלך", artist: "עומר אדם", year: 2020, youtubeId: "Jw02uPan7RU" },
  { title: "שקיעות אדומות", artist: "עדן חסון", year: 2020, youtubeId: "VTbqsoJYAZA" },
  { title: "ננה בננה", artist: "נטע ברזילי", year: 2020, youtubeId: "kSLtroWy4O0" },
  { title: "נחכה לך", artist: "ישי ריבו", year: 2020, youtubeId: "ryTO71_eMO4" },
  { title: "שלוש בלילה", artist: "רביד פלוטניק", year: 2020, youtubeId: "nFjDqwtXdKw" },
  { title: "טרילילי טרללה", artist: "נועה קירל", year: 2020, youtubeId: "QB8NuvDML2I" },
  { title: "אבינו מלכנו", artist: "שלומי שבת", year: 2020, youtubeId: "AqZn3zX9Kow" },
  { title: "לב קבור", artist: "דודו אהרון", year: 2020, youtubeId: "b_7kijmY4Ng" },
  { title: "אור גדול", artist: "מירי מסיקה", year: 2020, youtubeId: "ForWfsdjZUc" },
  { title: "תן לי רגע", artist: "הראל סקעת", year: 2020, youtubeId: "hG9ZibRy26c" },
  { title: "זאת האהבה שלנו", artist: "עברי לידר", year: 2020, youtubeId: "XJrVizZpMIA" },
  { title: "בין המילים", artist: "רוני דלומי", year: 2020, youtubeId: "5leHbORRtXY" },
  { title: "אולי", artist: "דנה ברגר", year: 2020, youtubeId: "0WFaz60f_4E" },
  { title: "אהבה", artist: "אושר כהן", year: 2020, youtubeId: "K1nQX_hdop0" },
  { title: "לאלף את הסוסים", artist: "ריטה", year: 2020, youtubeId: "QmeFmeVCviM" },
  { title: "פולארויד", artist: "עומר אדם", year: 2019, youtubeId: "KGRQ0GsUFvo" },
  { title: "פאוץ'", artist: "נועה קירל", year: 2019, youtubeId: "5TUN30--lUw" },
  { title: "קילר", artist: "נועה קירל", year: 2019, youtubeId: "_pGjSmrxZ7s" },
  { title: "מתפוצץ לי הראש", artist: "עדן חסון", year: 2019, youtubeId: "a4Sd7aazEw4" },
  { title: "תן לי את האור", artist: "רביד פלוטניק", year: 2019, youtubeId: "Jg7YL6N5bOs" },
  { title: "נתראה בגלגול הבא", artist: "רביד פלוטניק", year: 2019, youtubeId: "Maf6BaEhCzY" },
  { title: "באסה סבבה", artist: "נטע ברזילי", year: 2019, youtubeId: "jV1sjm9Lz_Q" },
  { title: "אפס מאמץ", artist: "סטטיק ובן אל", year: 2019, youtubeId: "NpDAFKqeUDw" },
  { title: "לשון הרע לא מדבר אליי", artist: "ישי ריבו", year: 2019, youtubeId: "yX7AniVDw0w" },
  { title: "ואם תבואי אליי", artist: "עידן רייכל", year: 2019, youtubeId: "nI8n20UpaBY" },
  { title: "אני בא", artist: "שלמה ארצי", year: 2019, youtubeId: "yzk3t81glZE" },
  { title: "כל הכוכבים", artist: "פאר טסי", year: 2019, youtubeId: "doYvXHat8gU" },
  { title: "תשמח", artist: "אייל גולן", year: 2019, youtubeId: "joStlhuYjfk" },
  { title: "לא הצלחתי", artist: "אריק ברמן", year: 2019, youtubeId: "Hacg4KrJlSE" },
  { title: "הוזה אותך מולי", artist: "אייל גולן", year: 2018, youtubeId: "iWodhfNtdFY" },
  { title: "זה אני", artist: "אייל גולן", year: 2018, youtubeId: "WvaTAan0OFA" },
  { title: "שני משוגעים", artist: "עומר אדם", year: 2018, youtubeId: "WLMmX17D2uw" },
  { title: "מלכת השושנים", artist: "עדן בן זקן", year: 2018, youtubeId: "nwpLIXdrHS0" },
  { title: "אין אותי", artist: "נועה קירל", year: 2018, youtubeId: "h3iqvIWAfck" },
  { title: "טודו בום", artist: "סטטיק ובן אל", year: 2018, youtubeId: "Y_OLslE3bX8" },
  { title: "זהב", artist: "סטטיק ובן אל", year: 2018, youtubeId: "cRGrIn2VHTE" },
  { title: "גומיגם", artist: "סטטיק ובן אל", year: 2018, youtubeId: "9aFz_aLuFhI" },
  { title: "ימים יגידו", artist: "הראל סקעת", year: 2018, youtubeId: "maTcKfZ4eqo" },
  { title: "מלך", artist: "מירי מסיקה", year: 2018, youtubeId: "E6uKhiJgziM" },
  { title: "גלים", artist: "אמיר דדון", year: 2018, youtubeId: "N2TRnC7g6Jo" },
  { title: "מחמל נפשי", artist: "שלמה ארצי", year: 2018, youtubeId: "IE2jnIvCxn4" },
  { title: "היא לא יודעת", artist: "איתי לוי", year: 2018, youtubeId: "vNViGyjZpq0" },
  { title: "מעבר לנהר", artist: "קרן פלס", year: 2018, youtubeId: "E6fgnGEsocE" },
  { title: "מסיבה בחיפה", artist: "עדן בן זקן", year: 2017, youtubeId: "UseUJLcBA7E" },
  { title: "כביש החוף", artist: "סטטיק ובן אל", year: 2017, youtubeId: "t2fakms1QWo" },
  { title: "לשוב הביתה", artist: "ישי ריבו", year: 2017, youtubeId: "Y30pfWIQfoo" },
  { title: "סדר העבודה", artist: "ישי ריבו", year: 2017, youtubeId: "ECy3CMxShIQ" },
  { title: "תל אביב בלילה", artist: "עדן חסון", year: 2017, youtubeId: "KuCPWqK46aY" },
  { title: "חצי", artist: "אמיר דדון", year: 2017, youtubeId: "kCl_yVJKsiw" },
  { title: "מעגלים", artist: "עידן רייכל", year: 2017, youtubeId: "5gemebkLaYY" },
  { title: "סוף שבוע", artist: "רביד פלוטניק", year: 2017, youtubeId: "DHPrIoolu9g" },
  { title: "אוהבת אותי אמיתי", artist: "עומר אדם", year: 2017, youtubeId: "31DIsGbFVgY" },
  { title: "רוז", artist: "פאר טסי", year: 2017, youtubeId: "6EvjmgtR2rI" },
  { title: "בואי ניפגש", artist: "איתי לוי", year: 2017, youtubeId: "RdfIcnPy3cA" },
  { title: "תלתלים", artist: "רוני דלומי", year: 2017, youtubeId: "y4yCoGAoXd0" },
  { title: "פעם בחיים", artist: "עומר אדם", year: 2016, youtubeId: "Iwv-aggzNbk" },
  { title: "תזיזו", artist: "עדן בן זקן", year: 2016, youtubeId: "ryHLrr4J1M4" },
  { title: "ברבי", artist: "סטטיק ובן אל", year: 2016, youtubeId: "YJsi8g_Hsvo" },
  { title: "משקה יקר", artist: "פאר טסי", year: 2016, youtubeId: "VhQFyNWN2uc" },
  { title: "תן", artist: "רוני דלומי", year: 2016, youtubeId: "spCQCjDPMvE" },
  { title: "עוד יגיע היום", artist: "הראל סקעת", year: 2016, youtubeId: "oeItkHVzO-I" },
  { title: "שיר תקווה", artist: "מירי מסיקה", year: 2016, youtubeId: "Lh9PEh0sIYQ" },
  { title: "אמא", artist: "דודו אהרון", year: 2016, youtubeId: "2f8BdHwPGgM" },
  { title: "תבואי היום", artist: "אייל גולן", year: 2016, youtubeId: "3VT3VIRQPKA" },
  { title: "מנגינה", artist: "עדן בן זקן", year: 2016, youtubeId: "fMyhIe_bV_s" },
  { title: "שקופים", artist: "קרן פלס", year: 2016, youtubeId: "4g9mJjJ9WU0" },
  { title: "מחכה", artist: "עברי לידר", year: 2016, youtubeId: "hAX2ku9ifEs" },
  { title: "מהפכה של שמחה", artist: "עומר אדם", year: 2015, youtubeId: "tbNURvMcAiE" },
  { title: "מודה אני", artist: "עומר אדם", year: 2015, youtubeId: "YQ5f1OMFFL0" },
  { title: "דרך השלום", artist: "פאר טסי", year: 2015, youtubeId: "VD9F_7N_MbI" },
  { title: "שרק תחייך", artist: "יובל דיין", year: 2015, youtubeId: "nzT5YPAIGZA" },
  { title: "לבחור נכון", artist: "אמיר דדון", year: 2015, youtubeId: "yjJcnqZqciU" },
  { title: "שותפים", artist: "הדג נחש", year: 2015, youtubeId: "i1FITLtNA0g" },
  { title: "אם אלה החיים", artist: "קרן פלס", year: 2015, youtubeId: "RlxmsqMRmR8" },
  { title: "הלב", artist: "שלומי שבת", year: 2015, youtubeId: "Jr7lGLkx3iI" },
  { title: "רק תבואי", artist: "עברי לידר", year: 2015, youtubeId: "jTX6mWrXvNE" },
  { title: "בין קירות ביתי", artist: "עידן רייכל", year: 2015, youtubeId: "9RYwXYtzru0" },
  { title: "אולי", artist: "איתי לוי", year: 2015, youtubeId: "TGv3akMUreA" },
  { title: "מילים יפות מאלה", artist: "עידן רייכל", year: 2015, youtubeId: "j_oajsiBiQA" },
  { title: "שיר השירים", artist: "הדג נחש", year: 2015, youtubeId: "L-5ybcno_A4" },
  { title: "אישתי", artist: "רוני דלומי", year: 2015, youtubeId: "1zS9D2JHUf4" },
  { title: "מתאימה לי", artist: "עומר אדם", year: 2014, youtubeId: "PburljbL-fo" },
  { title: "יפה שלי", artist: "עומר אדם", year: 2014, youtubeId: "PburljbL-fo" },
  { title: "ימים יגידו", artist: "אייל גולן", year: 2014, youtubeId: "maTcKfZ4eqo" },
  { title: "אין כמו אהבה", artist: "דודו אהרון", year: 2014, youtubeId: "JeWbelR1k4I" },
  { title: "אף אחת", artist: "מירי מסיקה", year: 2014, youtubeId: "SGIYmCdtbzg" },
  { title: "כמו כולם", artist: "הראל סקעת", year: 2014, youtubeId: "og5dskyoEb8" },
  { title: "שמות", artist: "אריק ברמן", year: 2014, youtubeId: "df7xKFTm7Is" },
  { title: "פנים אל מול פנים", artist: "יהודה פוליקר", year: 2014, youtubeId: "wfpEjXxGTlk" },
  { title: "הכל עובר", artist: "קרן פלס", year: 2014, youtubeId: "qAP4XWJxDaY" },
  { title: "בדיוק כמו הירח", artist: "יובל דיין", year: 2014, youtubeId: "V4qsi4V-NFY" },
  { title: "בואי", artist: "ריטה", year: 2014, youtubeId: "RrYmegnmRXo" },
  { title: "כמו ציפור", artist: "אמיר דדון", year: 2014, youtubeId: "g1YAoxyv6Ik" },
  { title: "כמו כולם", artist: "דנה ברגר", year: 2014, youtubeId: "Qe8dDv220PQ" },
  { title: "אהבה ראשונה", artist: "דודו אהרון", year: 2014, youtubeId: "nI2k_LzUyug" },
  { title: "תישארי", artist: "עברי לידר", year: 2014, youtubeId: "1BJSNvQ4ukY" },
  { title: "קאקדילה", artist: "עומר אדם", year: 2013, youtubeId: "fXFLjct5agw" },
  { title: "בוקר טוב", artist: "עומר אדם", year: 2013, youtubeId: "JRE-30sKXqs" },
  { title: "לבדי", artist: "אייל גולן", year: 2013, youtubeId: "nPc-ahsDqas" },
  { title: "השיר של איתי", artist: "יובל דיין", year: 2013, youtubeId: "nzT5YPAIGZA" },
  { title: "רוב השעות", artist: "עידן רייכל", year: 2013, youtubeId: "qD4mkJiQPKY" },
  { title: "הכל זה מלמעלה", artist: "דודו אהרון", year: 2013, youtubeId: "Y1pK0woqv58" },
  { title: "חלל", artist: "אמיר דדון", year: 2013, youtubeId: "5YqlqjAzm5Q" },
  { title: "תן לי מנגינה", artist: "הדג נחש", year: 2013, youtubeId: "nGPF-HYF7SY" },
  { title: "מילים", artist: "הראל סקעת", year: 2013, youtubeId: "jZMZGLBvOGw" },
  { title: "רגע פרטי", artist: "ריטה", year: 2013, youtubeId: "LY3baJOd9To" },
  { title: "בואי נדבר", artist: "דנה ברגר", year: 2013, youtubeId: "MxxzQzsYN64" },
  { title: "תודה", artist: "שלומי שבת", year: 2013, youtubeId: "eQZn3j3LFuo" },
  { title: "אהבה כמו שלנו", artist: "קרן פלס", year: 2013, youtubeId: "6UduwaNze6M" },
  { title: "מלאת אהבה", artist: "עומר אדם", year: 2013, youtubeId: "clOxTPsyFao" },
  { title: "בואי אליי", artist: "עידן רייכל", year: 2013, youtubeId: "_uJLsc05ZE4" },
  { title: "תל אביב", artist: "עומר אדם", year: 2012, youtubeId: "nMQw29nfzpg" },
  { title: "תשאל את המים", artist: "יובל דיין", year: 2012, youtubeId: "aPmOiRA5WrY" },
  { title: "ארץ חדשה", artist: "שלמה ארצי", year: 2012, youtubeId: "DRgJz2uRopQ" },
  { title: "יש לך אותך", artist: "מירי מסיקה", year: 2012, youtubeId: "UzlVFA9eu7Y" },
  { title: "אדוני", artist: "עברי לידר", year: 2012, youtubeId: "IjUhjU5AKJs" },
  { title: "חולם אותך", artist: "יהודה פוליקר", year: 2012, youtubeId: "xTpOhPzCphQ" },
  { title: "דרך לחיים", artist: "אייל גולן", year: 2011, youtubeId: "IT_mMBfeOBg" },
  { title: "כשאת איתו", artist: "אייל גולן", year: 2011, youtubeId: "g4t2GDIoquE" },
  { title: "קלרה", artist: "עומר אדם", year: 2011, youtubeId: "UeyqIxH5g2k" },
  { title: "עוד אח אחד", artist: "הדג נחש", year: 2011, youtubeId: "Rz-xsKZYnPw" },
  { title: "ואת", artist: "קרן פלס", year: 2011, youtubeId: "BEfnSNRsaYY" },
  { title: "הרי את מקודשת לי", artist: "שלומי שבת", year: 2011, youtubeId: "cuvsBPOanQA" },
  { title: "באה אליכם", artist: "מירי מסיקה", year: 2011, youtubeId: "7IaJXfVY5Pk" },
  { title: "נאחז באוויר", artist: "גידי גוב", year: 2011, youtubeId: "l-tRKBTJVE0" },
  { title: "מלטף ומשקר", artist: "עברי לידר", year: 2011, youtubeId: "ebJKjN6xdFI" },
  { title: "עוד", artist: "אמיר דדון", year: 2011, youtubeId: "B1Zp_fAXy5Y" },
  { title: "מחוזקים לעולם", artist: "אמיר דדון", year: 2010, youtubeId: "HNCQ9aQdAJA" },
  { title: "אור גדול", artist: "אמיר דדון", year: 2010, youtubeId: "jeU9Sbq0D0A" },
  { title: "מלכת היופי שלי", artist: "אייל גולן", year: 2010, youtubeId: "KIjKR3LxoWM" },
  { title: "נולדת בשבילי", artist: "אייל גולן", year: 2010, youtubeId: "0DXZzKDabSI" },
  { title: "כמו אז", artist: "שלמה ארצי", year: 2010, youtubeId: "PBMg6yvjOHU" },
  { title: "אחרי הכול את שיר", artist: "שלמה ארצי", year: 2010, youtubeId: "P4KnqxpoKkM" },
  { title: "לא מספיק", artist: "הדג נחש", year: 2010, youtubeId: "cpyPi8_RQs0" },
  { title: "כמו ציפור", artist: "ריטה", year: 2010, youtubeId: "r81U6hPqu-k" },
  { title: "רק אלוהים ישפוט אותי", artist: "קרן פלס", year: 2010, youtubeId: "r4qTj8ZiGyQ" },
  { title: "בית משוגעים", artist: "רוני דלומי", year: 2010, youtubeId: "6iwMXfLQ988" },
  { title: "תגידי לי", artist: "דודו אהרון", year: 2010, youtubeId: "1NsjpSZZaRo" },
  { title: "בואי נדבר", artist: "ארקדי דוכין", year: 2010, youtubeId: "AT1Ng-ANk00" },
  { title: "רכבת", artist: "דנה ברגר", year: 2010, youtubeId: "w3fR9Ys5t20" },
  { title: "מי שמאמין", artist: "אייל גולן", year: 2009, youtubeId: "-CZqRKYznrM" },
  { title: "היא לא יודעת מה עובר עליי", artist: "אייל גולן", year: 2009, youtubeId: "WHDQ-JHI6Z8" },
  { title: "מכל האהבות", artist: "דודו אהרון", year: 2009, youtubeId: "f2aFGTdDEg0" },
  { title: "הנני כאן", artist: "הראל סקעת", year: 2009, youtubeId: "867VJMEXQ3M" },
  { title: "בגלל הרוח", artist: "שלומי שבת", year: 2009, youtubeId: "nli5tcVRjG4" },
  { title: "האם אתה מאושר", artist: "ריטה", year: 2009, youtubeId: "GgX8WpSYJVE" },
  { title: "אני מאמין", artist: "הדג נחש", year: 2009, youtubeId: "HTkmOPkuIpo" },
  { title: "אהבה ממבט ראשון", artist: "אריק ברמן", year: 2009, youtubeId: "F9NNNqGL5NE" },
  { title: "בוקר טוב", artist: "עברי לידר", year: 2009, youtubeId: "0SxcAL_XjGo" },
  { title: "שוב", artist: "ארקדי דוכין", year: 2009, youtubeId: "GuTwCVv-DAY" },
  { title: "לא דומה", artist: "דודו אהרון", year: 2009, youtubeId: "yI4kTq2OKlA" },
  { title: "נובמבר", artist: "מירי מסיקה", year: 2008, youtubeId: "yS_tA7WNghM" },
  { title: "תמיד אהבה", artist: "עברי לידר", year: 2008, youtubeId: "eWieCfG6634" },
  { title: "בואי ניפרד", artist: "גידי גוב", year: 2008, youtubeId: "eZE653Z74sg" },
  { title: "עיניים שלי", artist: "יהודה פוליקר", year: 2008, youtubeId: "fpEc_7kXlQM" },
  { title: "המתוקות האחרונות", artist: "אריק ברמן", year: 2008, youtubeId: "0SlAGZMPmVA" },
  { title: "כמו פעם", artist: "ארקדי דוכין", year: 2008, youtubeId: "EuYPBIoiNn4" },
  { title: "משבר אמון", artist: "ריטה", year: 2008, youtubeId: "tiqOjCWydXU" },
  { title: "מילים יפות", artist: "עידן רייכל", year: 2008, youtubeId: "j_oajsiBiQA" },
  { title: "כמו ציפור", artist: "יובל דיין", year: 2008, youtubeId: "V4qsi4V-NFY" },
  { title: "אם יש גן עדן", artist: "אייל גולן", year: 2007, youtubeId: "nLLS924fGUU" },
  { title: "תתארו לכם", artist: "שלמה ארצי", year: 2007, youtubeId: "Y0KxZz5k-RE" },
  { title: "איסלנד", artist: "שלמה ארצי", year: 2007, youtubeId: "zaZUNFPmFB0" },
  { title: "הנה אני בא", artist: "הדג נחש", year: 2007, youtubeId: "JNwJFLkoX80" },
  { title: "יום חדש נפלא", artist: "אריק ברמן", year: 2007, youtubeId: "TFFAjojBe1k" },
  { title: "שביל הבריחה", artist: "עברי לידר", year: 2007, youtubeId: "Roi8jO91MLE" },
  { title: "ממעמקים", artist: "עידן רייכל", year: 2007, youtubeId: "kmW2yAYhMmM" },
  { title: "לשם", artist: "מירי מסיקה", year: 2007, youtubeId: "iQoxiA4K72w" },
  { title: "בוא", artist: "עברי לידר", year: 2007, youtubeId: "F_BxJvYPtpk" },
  { title: "אל תלכי לי", artist: "אייל גולן", year: 2006, youtubeId: "8RrMom7EonE" },
  { title: "אתה ואני", artist: "הראל סקעת", year: 2006, youtubeId: "ApjfPKgDdMc" },
  { title: "ואת", artist: "הראל סקעת", year: 2006, youtubeId: "AcpgsbFvnbM" },
  { title: "השקט שנשאר", artist: "שירי מימון", year: 2006, youtubeId: "_xsI9tgyj1A" },
  { title: "אור", artist: "שירי מימון", year: 2006, youtubeId: "-2ZQul7c8uY" },
  { title: "מפחד עלייך", artist: "מירי מסיקה", year: 2006, youtubeId: "Fr8gix_aqO8" },
  { title: "אני שוב מתאהב", artist: "גידי גוב", year: 2006, youtubeId: "qoGurrdtz6Q" },
  { title: "לומדת לעוף", artist: "דנה ברגר", year: 2006, youtubeId: "Wtup9AJmP3c" },
  { title: "ממעמקים", artist: "הפרויקט של עידן רייכל", year: 2006, youtubeId: "kmW2yAYhMmM" },
  { title: "זכיתי לאהוב", artist: "עברי לידר", year: 2006, youtubeId: "nUJro16dpbs" },
  { title: "יש בי אהבה", artist: "אריק איינשטיין", year: 2006, youtubeId: "5WEggKymynE" },
  { title: "מחכה", artist: "ריטה", year: 2006, youtubeId: "hAX2ku9ifEs" },
  { title: "מצטער", artist: "אייל גולן", year: 2005, youtubeId: "VSQ5haTLKB8" },
  { title: "הנך יפה", artist: "הפרויקט של עידן רייכל", year: 2005, youtubeId: "-qxrnxoHl6A" },
  { title: "מדברים בשקט", artist: "הפרויקט של עידן רייכל", year: 2005, youtubeId: "J_g6c6IZ6VY" },
  { title: "אם זאת אהבה", artist: "מירי מסיקה", year: 2005, youtubeId: "FgoGB0cSg60" },
  { title: "ניסים", artist: "עברי לידר", year: 2005, youtubeId: "-SubcIwy0Vs" },
  { title: "שלל שרב", artist: "גידי גוב", year: 2005, youtubeId: "ojBKxaVL5Fw" },
  { title: "איך קוראים לאהבה שלי", artist: "יהודה פוליקר", year: 2005, youtubeId: "sFzVHbvnEnk" },
  { title: "בואי", artist: "עברי לידר", year: 2004, youtubeId: "F_BxJvYPtpk" },
  { title: "כשתבוא", artist: "הדג נחש", year: 2004, youtubeId: "iK57GQbNjfQ" },
  { title: "שירת הסטיקר", artist: "הדג נחש", year: 2004, youtubeId: "QflL6R2-k-8" },
  { title: "גבי ודבי", artist: "הדג נחש", year: 2004, youtubeId: "70i9PvrsvJ0" },
  { title: "מי אוהב אותך יותר ממני", artist: "ארקדי דוכין", year: 2004, youtubeId: "l0WYMRSs9C4" },
  { title: "בחוף של טרפטוני", artist: "שלומי שבת", year: 2004, youtubeId: "KGk2BOsVpno" },
  { title: "כשתגדל", artist: "יהודה פוליקר", year: 2004, youtubeId: "CZYtx-JIu3g" },
  { title: "האהבה הישנה", artist: "שלמה ארצי", year: 2004, youtubeId: "02uV8M6XSto" },
  { title: "אתה בכל זאת", artist: "ריטה", year: 2004, youtubeId: "r1YHVXL74IY" },
  { title: "מישהו פעם", artist: "עברי לידר", year: 2004, youtubeId: "3kJiCtRlVTo" },
  { title: "יותר טוב כלום מכמעט", artist: "עברי לידר", year: 2004, youtubeId: "TmqmH0n7EXY" },
  { title: "לזוז", artist: "הדג נחש", year: 2004, youtubeId: "JC_s0yRDUoE" },
  { title: "אומרים ישנה ארץ", artist: "שלמה ארצי", year: 2003, youtubeId: "SKMdUcDV0CA" },
  { title: "אף פעם לא תדעי", artist: "שלמה ארצי", year: 2003, youtubeId: "8GmoiZ9j2YM" },
  { title: "דברים שרציתי לומר", artist: "יהודה פוליקר", year: 2003, youtubeId: "vWFKdqvdLO4" },
  { title: "שביל הבריחה", artist: "ריטה", year: 2003, youtubeId: "thcsC9PpHvM" },
  { title: "בוא", artist: "ריטה", year: 2003, youtubeId: "RrYmegnmRXo" },
  { title: "אם תלך", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "CtpCGfRRToo" },
  { title: "בואי", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "_uJLsc05ZE4" },
  { title: "שושנים", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "egtOB8arAN0" },
  { title: "תודה", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "hzGH_oZmtxU" },
  { title: "מכל האהבות", artist: "עידן רייכל", year: 2002, youtubeId: "Wa0Nmruih_A" },
  { title: "פחות אבל כואב", artist: "יהודה פוליקר", year: 2002, youtubeId: "wlYpgESy6UY" },
  { title: "עד הקצה", artist: "דנה ברגר", year: 2002, youtubeId: "fEAB2iDVw-w" },
  { title: "אמא", artist: "שלומי שבת", year: 2001, youtubeId: "KMISUbgXhCY" },
  { title: "אני ואתה", artist: "אריק איינשטיין", year: 2001, youtubeId: "gP6PS-poyMg" },
  { title: "ירח", artist: "שלמה ארצי", year: 2001, youtubeId: "hGiNUsSHkr0" },
  { title: "לא פראיירים", artist: "הדג נחש", year: 2000, youtubeId: "qHM3uTxvPRg" },
  { title: "אתה לי ארץ", artist: "שלמה ארצי", year: 2000, youtubeId: "w8PNR_YF9Xw" },
  { title: "גוליית", artist: "גידי גוב", year: 2000, youtubeId: "B0xWYu3zasE" },
  { title: "היא", artist: "דנה ברגר", year: 2000, youtubeId: "2bQeHFZvdKE" },
  { title: "יש בי אהבה", artist: "ארקדי דוכין", year: 2000, youtubeId: "XIgkTSmWQO0" },
  { title: "מיליארד טועים", artist: "אביב גפן", year: 1999, youtubeId: "_ChMp1XsH90" },
  { title: "האם להיות בך מאוהב", artist: "אביב גפן", year: 1999, youtubeId: "_u8wImTMh3k" },
  { title: "שיר תקווה", artist: "אביב גפן", year: 1999, youtubeId: "csOuqrL9NvQ" },
  { title: "רכבת לילה לקהיר", artist: "משינה", year: 1999, youtubeId: "0y0gaLiyiak" },
  { title: "אהובתי", artist: "משינה", year: 1999, youtubeId: "Hd9ubTcJc7E" },
  { title: "אני חיה לי מיום ליום", artist: "ריטה", year: 1999, youtubeId: "M8qfRZ5w2qY" },
  { title: "כשהלב הוא חופשי", artist: "ריטה", year: 1999, youtubeId: "ixCdnB_eMhs" },
  { title: "אין מקום אחר", artist: "משינה", year: 1999, youtubeId: "PVAD3KWgQrQ" },
  { title: "שיר לשירה", artist: "קורין אלאל", year: 1998, youtubeId: "5Dnu2RvttBw" },
  { title: "זה מה שנשאר", artist: "שלמה ארצי", year: 1998, youtubeId: "2zk_cTSeLUk" },
  { title: "אור הירח", artist: "אביב גפן", year: 1998, youtubeId: "TeJQz1Bco84" },
  { title: "עונות", artist: "אביב גפן", year: 1998, youtubeId: "SzGr282fgAM" },
  { title: "גשם כבד", artist: "אביב גפן", year: 1998, youtubeId: "P9u_svtR3Sg" },
  { title: "לבכות לך", artist: "אביב גפן", year: 1998, youtubeId: "XjVUzfb_oBo" },
  { title: "הכוכבים דולקים על אש קטנה", artist: "משינה", year: 1998, youtubeId: "FilQhY2Pjq0" },
  { title: "עטור מצחך", artist: "אריק איינשטיין", year: 1998, youtubeId: "WZM4iXT3-ic" },
  { title: "אין לי ארץ אחרת", artist: "גידי גוב", year: 1998, youtubeId: "MEJ5jgCaDhE" },
  { title: "אני מאמין", artist: "שלמה ארצי", year: 1997, youtubeId: "LsggvtqxQWA" },
  { title: "מחכים למשיח", artist: "שלום חנוך", year: 1997, youtubeId: "-0i3mev5EvQ" },
  { title: "רק בגלל הרוח", artist: "שלמה ארצי", year: 1997, youtubeId: "nli5tcVRjG4" },
  { title: "באה מאהבה", artist: "יהודית רביץ", year: 1997, youtubeId: "zUNPxTNxVoc" },
  { title: "שלח לי מלאך", artist: "משינה", year: 1995, youtubeId: "CYQ3WBi_n68" },
  { title: "ריקוד ירח", artist: "ריטה", year: 1994, youtubeId: "E26HGGPq0s8" },
  { title: "לילה בעיר", artist: "משינה", year: 1993, youtubeId: "Q1OWrVU3nTE" },
  { title: "אמא", artist: "שלמה ארצי", year: 1990, youtubeId: "xTTCD0U_HJg" },
  { title: "כמו שאתה", artist: "מרגלית צנעני", year: 1990, youtubeId: "bOasB1tl6i8" },
  { title: "דרך ארוכה", artist: "גידי גוב", year: 1989, youtubeId: "xVnwgIFOf2I" },
  { title: "בדרך אל הים", artist: "משינה", year: 1988, youtubeId: "pohW4WQ4H8M" },
  { title: "עוף גוזל", artist: "אריק איינשטיין", year: 1987, youtubeId: "mOd-hetRES0" },
  { title: "לתת", artist: "בועז שרעבי", year: 1987, youtubeId: "IG2waIDW7Cc" },
  { title: "אוהב להיות בבית", artist: "אריק איינשטיין", year: 1986, youtubeId: "yXll9VNF118" },
  { title: "מאיה", artist: "שלום חנוך", year: 1984, youtubeId: "urqQ3V76hXs" }
];
