// songs/ar.js — מאגר שירים בערבית (ללא youtubeId — ניגון בחיפוש אוטומטי).
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.ar = [
  { title: "إنت عمري", artist: "أم كلثوم", year: 1964 },
  { title: "الأطلال", artist: "أم كلثوم", year: 1966 },
  { title: "أغدا ألقاك", artist: "أم كلثوم", year: 1962 },
  { title: "فكروني", artist: "أم كلثوم", year: 1966 },
  { title: "سيرة الحب", artist: "أم كلثوم", year: 1964 },
  { title: "ألف ليلة وليلة", artist: "أم كلثوم", year: 1969 },
  { title: "يا مسهرني", artist: "فريد الأطرش", year: 1962 },
  { title: "حكاية غرامي", artist: "فريد الأطرش", year: 1957 },
  { title: "بساط الريح", artist: "فريد الأطرش", year: 1961 },
  { title: "علي بابا", artist: "فريد الأطرش", year: 1961 },
  { title: "زينة", artist: "عبد الحليم حافظ", year: 1970 },
  { title: "قارئة الفنجان", artist: "عبد الحليم حافظ", year: 1975 },
  { title: "أهواك", artist: "عبد الحليم حافظ", year: 1962 },
  { title: "موعود", artist: "عبد الحليم حافظ", year: 1966 },
  { title: "حبيبها", artist: "عبد الحليم حافظ", year: 1972 },
  { title: "سواح", artist: "عبد الحليم حافظ", year: 1972 },
  { title: "على قد الشوق", artist: "وردة الجزائرية", year: 1985 },
  { title: "بتونس بيك", artist: "وردة الجزائرية", year: 1977 },
  { title: "حبك نار", artist: "وردة الجزائرية", year: 1975 },
  { title: "خليك جنبي", artist: "شادية", year: 1970 },
  { title: "زحمة يا دنيا زحمة", artist: "شادية", year: 1970 },
  { title: "يا واد يا تقيل", artist: "شادية", year: 1972 },
  { title: "لا يا حبيبي", artist: "نجاة الصغيرة", year: 1968 },
  { title: "أنا قلبي إليك ميال", artist: "نجاة الصغيرة", year: 1966 },
  { title: "مسافة صمت", artist: "أصالة نصري", year: 1998 },
  { title: "بحبك وحشتني", artist: "أصالة نصري", year: 2005 },
  { title: "نسيان", artist: "أصالة نصري", year: 2010 },
  { title: "أنا هويت", artist: "فيروز", year: 1957 },
  { title: "سألوني الناس", artist: "فيروز", year: 1961 },
  { title: "كيفك إنت", artist: "فيروز", year: 1966 },
  { title: "شادي", artist: "فيروز", year: 1970 },
  { title: "نسم علينا الهوا", artist: "فيروز", year: 1957 },
  { title: "يا أنا يا أنا", artist: "فيروز", year: 1976 },
  { title: "حبيتك بالصيف", artist: "فيروز", year: 1966 },
  { title: "علي بالك", artist: "وائل كفوري", year: 2004 },
  { title: "حكم عليا قلبي", artist: "وائل كفوري", year: 2001 },
  { title: "أنا وليلي", artist: "عمرو دياب", year: 1996 },
  { title: "نور العين", artist: "عمرو دياب", year: 1996 },
  { title: "تملي معاك", artist: "عمرو دياب", year: 2013 },
  { title: "قمرين", artist: "عمرو دياب", year: 1996 },
  { title: "الليلة", artist: "عمرو دياب", year: 2004 },
  { title: "معدي الأيام", artist: "عمرو دياب", year: 1992 },
  { title: "أه لو لعبت يا زهر", artist: "عمرو دياب", year: 1990 },
  { title: "على رمش عيونها", artist: "عمرو دياب", year: 1990 },
  { title: "بحبك", artist: "كاظم الساهر", year: 1994 },
  { title: "أنا وليلة عمري", artist: "كاظم الساهر", year: 1997 },
  { title: "زيديني عشقاً", artist: "كاظم الساهر", year: 2000 },
  { title: "المحكمة", artist: "كاظم الساهر", year: 1998 },
  { title: "يا حلوة", artist: "كاظم الساهر", year: 1996 },
  { title: "قصائد", artist: "كاظم الساهر", year: 1993 },
  { title: "من غيرك", artist: "ماجدة الرومي", year: 1980 },
  { title: "كلمات", artist: "ماجدة الرومي", year: 1984 },
  { title: "بمزح جد", artist: "ماجدة الرومي", year: 1986 },
  { title: "حبيبي يا نور العين", artist: "عمرو دياب", year: 1996 },
  { title: "يا طيرة طيري", artist: "صباح فخري", year: 1970 },
  { title: "زوروني كل سنة مرة", artist: "صباح فخري", year: 1968 },
  { title: "خمرة الحان", artist: "صباح فخري", year: 1972 },
  { title: "بالأحضان", artist: "شيرين عبد الوهاب", year: 2005 },
  { title: "أنا مش كدة", artist: "شيرين عبد الوهاب", year: 2008 },
  { title: "أنساك", artist: "شيرين عبد الوهاب", year: 2010 },
  { title: "أوعى تكون فاكرني", artist: "شيرين عبد الوهاب", year: 2016 },
  { title: "بحبك اه", artist: "نانسي عجرم", year: 2004 },
  { title: "أه ونص", artist: "نانسي عجرم", year: 2003 },
  { title: "يا سلام", artist: "نانسي عجرم", year: 2003 },
  { title: "إجا الوقت", artist: "نانسي عجرم", year: 2007 },
  { title: "بتونس فيك", artist: "إليسا", year: 2002 },
  { title: "أعتذرلك", artist: "إليسا", year: 2005 },
  { title: "حالة حب", artist: "إليسا", year: 2007 },
  { title: "أنا هيك", artist: "إليسا", year: 2009 },
  { title: "طبعا احترق", artist: "ملحم زين", year: 2006 },
  { title: "من غير سلام", artist: "ملحم زين", year: 2005 },
  { title: "خلوني معاها", artist: "راغب علامة", year: 1988 },
  { title: "معقول", artist: "راغب علامة", year: 1998 },
  { title: "الحب الكبير", artist: "راغب علامة", year: 2001 },
  { title: "خدني معك", artist: "راشد الماجد", year: 2003 },
  { title: "أنا سؤال", artist: "راشد الماجد", year: 2010 },
  { title: "عيونها", artist: "محمد عبده", year: 1979 },
  { title: "أبعتلك", artist: "محمد عبده", year: 1985 },
  { title: "الشوق قتلني", artist: "طلال مداح", year: 1980 },
  { title: "زمان الصمت", artist: "طلال مداح", year: 1975 },
  { title: "أحبك موت", artist: "عبادي الجوهر", year: 2001 },
  { title: "يا مسافر وحدك", artist: "خالد عبد الرحمن", year: 1995 },
  { title: "علمني حبك", artist: "أنغام", year: 2003 },
  { title: "بحبك وحشني", artist: "أنغام", year: 2010 },
  { title: "قدك الميال", artist: "فارس كرم", year: 2002 },
  { title: "بدي دوب", artist: "فارس كرم", year: 2004 },
  { title: "يا الغالي", artist: "طارق العربي (شاب طارق)", year: 1998 },
  { title: "دي دي", artist: "شاب خالد", year: 1992 },
  { title: "عليا العتاب", artist: "شاب خالد", year: 1996 },
  { title: "عيشة", artist: "شاب خالد", year: 1996 },
  { title: "الوحدة", artist: "شاب مامي", year: 1998 },
  { title: "قالوا القلب", artist: "سعد المجرد", year: 2014 },
  { title: "غزالي", artist: "سعد المجرد", year: 2016 },
  { title: "علاش", artist: "سعد المجرد", year: 2017 },
];
