// songs/en.js — English-language song pack. No youtubeId (search fallback,
// per the schema in songs/he.js) — playback resolves via YouTube search on
// "artist title" at run time.
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.en = [
  { title: "Bohemian Rhapsody", artist: "Queen", year: 1975 },
  { title: "We Will Rock You", artist: "Queen", year: 1977 },
  { title: "Don't Stop Me Now", artist: "Queen", year: 1978 },
  { title: "Billie Jean", artist: "Michael Jackson", year: 1983 },
  { title: "Thriller", artist: "Michael Jackson", year: 1982 },
  { title: "Beat It", artist: "Michael Jackson", year: 1982 },
  { title: "Smooth Criminal", artist: "Michael Jackson", year: 1987 },
  { title: "Like a Prayer", artist: "Madonna", year: 1989 },
  { title: "Material Girl", artist: "Madonna", year: 1984 },
  { title: "Vogue", artist: "Madonna", year: 1990 },
  { title: "Jailhouse Rock", artist: "Elvis Presley", year: 1957 },
  { title: "Can't Help Falling in Love", artist: "Elvis Presley", year: 1961 },
  { title: "Hound Dog", artist: "Elvis Presley", year: 1956 },
  { title: "I Will Always Love You", artist: "Whitney Houston", year: 1992 },
  { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", year: 1987 },
  { title: "Rolling in the Deep", artist: "Adele", year: 2010 },
  { title: "Someone Like You", artist: "Adele", year: 2011 },
  { title: "Hello", artist: "Adele", year: 2015 },
  { title: "Shape of You", artist: "Ed Sheeran", year: 2017 },
  { title: "Perfect", artist: "Ed Sheeran", year: 2017 },
  { title: "Thinking Out Loud", artist: "Ed Sheeran", year: 2014 },
  { title: "Shake It Off", artist: "Taylor Swift", year: 2014 },
  { title: "Blank Space", artist: "Taylor Swift", year: 2014 },
  { title: "Love Story", artist: "Taylor Swift", year: 2008 },
  { title: "Anti-Hero", artist: "Taylor Swift", year: 2022 },
  { title: "Uptown Funk", artist: "Bruno Mars", year: 2014 },
  { title: "Just the Way You Are", artist: "Bruno Mars", year: 2010 },
  { title: "24K Magic", artist: "Bruno Mars", year: 2016 },
  { title: "Umbrella", artist: "Rihanna", year: 2007 },
  { title: "Diamonds", artist: "Rihanna", year: 2012 },
  { title: "Work", artist: "Rihanna", year: 2016 },
  { title: "Halo", artist: "Beyoncé", year: 2008 },
  { title: "Single Ladies (Put a Ring on It)", artist: "Beyoncé", year: 2008 },
  { title: "Crazy in Love", artist: "Beyoncé", year: 2003 },
  { title: "Lose Yourself", artist: "Eminem", year: 2002 },
  { title: "Not Afraid", artist: "Eminem", year: 2010 },
  { title: "Yellow", artist: "Coldplay", year: 2000 },
  { title: "Fix You", artist: "Coldplay", year: 2005 },
  { title: "Viva la Vida", artist: "Coldplay", year: 2008 },
  { title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986 },
  { title: "It's My Life", artist: "Bon Jovi", year: 2000 },
  { title: "Sweet Child o' Mine", artist: "Guns N' Roses", year: 1987 },
  { title: "November Rain", artist: "Guns N' Roses", year: 1991 },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
  { title: "Come as You Are", artist: "Nirvana", year: 1991 },
  { title: "With or Without You", artist: "U2", year: 1987 },
  { title: "Beautiful Day", artist: "U2", year: 2000 },
  { title: "Rocket Man", artist: "Elton John", year: 1972 },
  { title: "Your Song", artist: "Elton John", year: 1970 },
  { title: "Tiny Dancer", artist: "Elton John", year: 1971 },
  { title: "Superstition", artist: "Stevie Wonder", year: 1972 },
  { title: "Isn't She Lovely", artist: "Stevie Wonder", year: 1976 },
  { title: "Dreams", artist: "Fleetwood Mac", year: 1977 },
  { title: "Go Your Own Way", artist: "Fleetwood Mac", year: 1977 },
  { title: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", year: 1965 },
  { title: "Paint It Black", artist: "The Rolling Stones", year: 1966 },
  { title: "Stairway to Heaven", artist: "Led Zeppelin", year: 1971 },
  { title: "Whole Lotta Love", artist: "Led Zeppelin", year: 1969 },
  { title: "Heroes", artist: "David Bowie", year: 1977 },
  { title: "Let's Dance", artist: "David Bowie", year: 1983 },
  { title: "Space Oddity", artist: "David Bowie", year: 1969 },
  { title: "Purple Rain", artist: "Prince", year: 1984 },
  { title: "Kiss", artist: "Prince", year: 1986 },
  { title: "When Doves Cry", artist: "Prince", year: 1984 },
  { title: "Careless Whisper", artist: "George Michael", year: 1984 },
  { title: "Faith", artist: "George Michael", year: 1987 },
  { title: "Piano Man", artist: "Billy Joel", year: 1973 },
  { title: "Uptown Girl", artist: "Billy Joel", year: 1983 },
  { title: "Stayin' Alive", artist: "Bee Gees", year: 1977 },
  { title: "Night Fever", artist: "Bee Gees", year: 1977 },
  { title: "Hotel California", artist: "Eagles", year: 1976 },
  { title: "Don't Stop Believin'", artist: "Journey", year: 1981 },
  { title: "Dream On", artist: "Aerosmith", year: 1973 },
  { title: "I Don't Want to Miss a Thing", artist: "Aerosmith", year: 1998 },
  { title: "Back in Black", artist: "AC/DC", year: 1980 },
  { title: "Highway to Hell", artist: "AC/DC", year: 1979 },
  { title: "Enter Sandman", artist: "Metallica", year: 1991 },
  { title: "Nothing Else Matters", artist: "Metallica", year: 1991 },
  { title: "I Want It That Way", artist: "Backstreet Boys", year: 1999 },
  { title: "Bye Bye Bye", artist: "NSYNC", year: 2000 },
  { title: "...Baby One More Time", artist: "Britney Spears", year: 1998 },
  { title: "Toxic", artist: "Britney Spears", year: 2003 },
  { title: "Cry Me a River", artist: "Justin Timberlake", year: 2002 },
  { title: "Can't Stop the Feeling!", artist: "Justin Timberlake", year: 2016 },
  { title: "Baby", artist: "Justin Bieber", year: 2010 },
  { title: "Sorry", artist: "Justin Bieber", year: 2015 },
  { title: "Firework", artist: "Katy Perry", year: 2010 },
  { title: "Roar", artist: "Katy Perry", year: 2013 },
  { title: "Bad Romance", artist: "Lady Gaga", year: 2009 },
  { title: "Poker Face", artist: "Lady Gaga", year: 2008 },
  { title: "Shallow", artist: "Lady Gaga", year: 2018 },
  { title: "Sugar", artist: "Maroon 5", year: 2015 },
  { title: "Girls Like You", artist: "Maroon 5", year: 2018 },
  { title: "Counting Stars", artist: "OneRepublic", year: 2013 },
  { title: "Believer", artist: "Imagine Dragons", year: 2017 },
  { title: "Radioactive", artist: "Imagine Dragons", year: 2012 },
  { title: "Blinding Lights", artist: "The Weeknd", year: 2019 },
  { title: "Starboy", artist: "The Weeknd", year: 2016 },
  { title: "Levitating", artist: "Dua Lipa", year: 2020 },
  { title: "Don't Start Now", artist: "Dua Lipa", year: 2019 },
  { title: "Thank U, Next", artist: "Ariana Grande", year: 2018 },
  { title: "7 Rings", artist: "Ariana Grande", year: 2019 },
  { title: "Bad Guy", artist: "Billie Eilish", year: 2019 },
  { title: "Happier Than Ever", artist: "Billie Eilish", year: 2021 },
  { title: "Drivers License", artist: "Olivia Rodrigo", year: 2021 },
  { title: "As It Was", artist: "Harry Styles", year: 2022 },
  { title: "Stitches", artist: "Shawn Mendes", year: 2015 },
  { title: "Chandelier", artist: "Sia", year: 2014 },
  { title: "Stay With Me", artist: "Sam Smith", year: 2014 },
  { title: "Rehab", artist: "Amy Winehouse", year: 2006 },
  { title: "Back to Black", artist: "Amy Winehouse", year: 2006 },
  { title: "Creep", artist: "Radiohead", year: 1992 },
  { title: "Karma Police", artist: "Radiohead", year: 1997 },
  { title: "Mr. Brightside", artist: "The Killers", year: 2003 },
  { title: "Somebody Told Me", artist: "The Killers", year: 2004 },
  { title: "Do I Wanna Know?", artist: "Arctic Monkeys", year: 2013 },
  { title: "R U Mine?", artist: "Arctic Monkeys", year: 2013 },
  { title: "Wonderwall", artist: "Oasis", year: 1995 },
  { title: "Don't Look Back in Anger", artist: "Oasis", year: 1995 },
  { title: "Song 2", artist: "Blur", year: 1997 },
  { title: "Angels", artist: "Robbie Williams", year: 1997 },
  { title: "Wannabe", artist: "Spice Girls", year: 1996 },
  { title: "Say You'll Be There", artist: "Spice Girls", year: 1996 },
  { title: "Say My Name", artist: "Destiny's Child", year: 1999 },
  { title: "Survivor", artist: "Destiny's Child", year: 2001 },
  { title: "No Scrubs", artist: "TLC", year: 1999 },
  { title: "Waterfalls", artist: "TLC", year: 1994 },
  { title: "All I Want for Christmas Is You", artist: "Mariah Carey", year: 1994 },
  { title: "Fantasy", artist: "Mariah Carey", year: 1995 },
  { title: "My Heart Will Go On", artist: "Celine Dion", year: 1997 },
  { title: "The Power of Love", artist: "Celine Dion", year: 1993 },
  { title: "What's Love Got to Do with It", artist: "Tina Turner", year: 1984 },
  { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: 1983 },
  { title: "I Heard It Through the Grapevine", artist: "Marvin Gaye", year: 1968 },
  { title: "What's Going On", artist: "Marvin Gaye", year: 1971 },
  { title: "Respect", artist: "Aretha Franklin", year: 1967 },
  { title: "Fly Me to the Moon", artist: "Frank Sinatra", year: 1964 },
  { title: "My Way", artist: "Frank Sinatra", year: 1969 },
  { title: "New York, New York", artist: "Frank Sinatra", year: 1980 },
  { title: "Good Vibrations", artist: "The Beach Boys", year: 1966 },
  { title: "The Sound of Silence", artist: "Simon & Garfunkel", year: 1964 },
  { title: "Bridge Over Troubled Water", artist: "Simon & Garfunkel", year: 1970 },
  { title: "Like a Rolling Stone", artist: "Bob Dylan", year: 1965 },
  { title: "Knockin' on Heaven's Door", artist: "Bob Dylan", year: 1973 },
  { title: "25 or 6 to 4", artist: "Chicago", year: 1970 },
  { title: "Africa", artist: "Toto", year: 1982 },
  { title: "I Want to Know What Love Is", artist: "Foreigner", year: 1984 },
  { title: "Can't Fight This Feeling", artist: "REO Speedwagon", year: 1984 },
  { title: "Eye of the Tiger", artist: "Survivor", year: 1982 },
  { title: "Carry On Wayward Son", artist: "Kansas", year: 1976 },
  { title: "More Than a Feeling", artist: "Boston", year: 1976 },
  { title: "The Joker", artist: "Steve Miller Band", year: 1973 },
  { title: "Layla", artist: "Eric Clapton", year: 1970 },
  { title: "Wonderful Tonight", artist: "Eric Clapton", year: 1977 },
  { title: "Every Breath You Take", artist: "The Police", year: 1983 },
  { title: "Roxanne", artist: "The Police", year: 1978 },
  { title: "Fields of Gold", artist: "Sting", year: 1993 },
  { title: "In the Air Tonight", artist: "Phil Collins", year: 1981 },
  { title: "Another Day in Paradise", artist: "Phil Collins", year: 1989 },
  { title: "Sledgehammer", artist: "Peter Gabriel", year: 1986 },
  { title: "Sultans of Swing", artist: "Dire Straits", year: 1978 },
  { title: "Money for Nothing", artist: "Dire Straits", year: 1985 },
  { title: "Everybody Wants to Rule the World", artist: "Tears for Fears", year: 1985 },
  { title: "Girls on Film", artist: "Duran Duran", year: 1981 },
  { title: "Hungry Like the Wolf", artist: "Duran Duran", year: 1982 },
  { title: "Karma Chameleon", artist: "Culture Club", year: 1983 },
  { title: "Last Christmas", artist: "Wham!", year: 1984 },
  { title: "Take On Me", artist: "a-ha", year: 1985 },
  { title: "Enjoy the Silence", artist: "Depeche Mode", year: 1990 },
  { title: "Blue Monday", artist: "New Order", year: 1983 },
  { title: "Friday I'm in Love", artist: "The Cure", year: 1992 },
  { title: "Once in a Lifetime", artist: "Talking Heads", year: 1980 },
  { title: "Losing My Religion", artist: "R.E.M.", year: 1991 },
  { title: "Alive", artist: "Pearl Jam", year: 1991 },
  { title: "Black Hole Sun", artist: "Soundgarden", year: 1994 },
  { title: "Man in the Box", artist: "Alice in Chains", year: 1990 },
  { title: "Under the Bridge", artist: "Red Hot Chili Peppers", year: 1991 },
  { title: "Can't Stop", artist: "Red Hot Chili Peppers", year: 2002 },
  { title: "Everlong", artist: "Foo Fighters", year: 1997 },
  { title: "Learn to Fly", artist: "Foo Fighters", year: 1999 },
  { title: "Basket Case", artist: "Green Day", year: 1994 },
  { title: "Boulevard of Broken Dreams", artist: "Green Day", year: 2004 },
  { title: "All the Small Things", artist: "blink-182", year: 1999 },
  { title: "In the End", artist: "Linkin Park", year: 2000 },
  { title: "Numb", artist: "Linkin Park", year: 2003 },
  { title: "Chop Suey!", artist: "System of a Down", year: 2001 },
  { title: "Bring Me to Life", artist: "Evanescence", year: 2003 },
  { title: "Welcome to the Black Parade", artist: "My Chemical Romance", year: 2006 },
  { title: "I Write Sins Not Tragedies", artist: "Panic! at the Disco", year: 2005 },
  { title: "Sugar, We're Goin Down", artist: "Fall Out Boy", year: 2005 },
  { title: "Misery Business", artist: "Paramore", year: 2007 },
  { title: "Stressed Out", artist: "twenty one pilots", year: 2015 },
  { title: "Drive By", artist: "Train", year: 2012 },
  { title: "All of Me", artist: "John Legend", year: 2013 },
  { title: "No One", artist: "Alicia Keys", year: 2007 },
  { title: "Yeah!", artist: "Usher", year: 2004 },
  { title: "Forever", artist: "Chris Brown", year: 2008 },
  { title: "So Sick", artist: "Ne-Yo", year: 2005 },
  { title: "Smack That", artist: "Akon", year: 2006 },
  { title: "Low", artist: "Flo Rida", year: 2007 },
  { title: "Give Me Everything", artist: "Pitbull", year: 2011 },
  { title: "I Gotta Feeling", artist: "The Black Eyed Peas", year: 2009 },
  { title: "Empire State of Mind", artist: "Jay-Z", year: 2009 },
  { title: "Stronger", artist: "Kanye West", year: 2007 },
  { title: "God's Plan", artist: "Drake", year: 2018 },
  { title: "One Dance", artist: "Drake", year: 2016 },
  { title: "Circles", artist: "Post Malone", year: 2019 },
  { title: "Sicko Mode", artist: "Travis Scott", year: 2018 },
  { title: "Bodak Yellow", artist: "Cardi B", year: 2017 },
  { title: "Super Bass", artist: "Nicki Minaj", year: 2010 },
  { title: "Say So", artist: "Doja Cat", year: 2019 },

  // --- Motown / Soul ---
  { title: "You Can't Hurry Love", artist: "The Supremes", year: 1966 },
  { title: "Stop! In the Name of Love", artist: "The Supremes", year: 1965 },
  { title: "Baby Love", artist: "The Supremes", year: 1964 },
  { title: "My Girl", artist: "The Temptations", year: 1964 },
  { title: "Ain't Too Proud to Beg", artist: "The Temptations", year: 1966 },
  { title: "Papa Was a Rollin' Stone", artist: "The Temptations", year: 1972 },
  { title: "I Want You Back", artist: "The Jackson 5", year: 1969 },
  { title: "ABC", artist: "The Jackson 5", year: 1970 },
  { title: "I'll Be There", artist: "The Jackson 5", year: 1970 },
  { title: "A Change Is Gonna Come", artist: "Sam Cooke", year: 1964 },
  { title: "Twistin' the Night Away", artist: "Sam Cooke", year: 1962 },
  { title: "(Sittin' On) The Dock of the Bay", artist: "Otis Redding", year: 1968 },
  { title: "Try a Little Tenderness", artist: "Otis Redding", year: 1966 },
  { title: "Let's Stay Together", artist: "Al Green", year: 1971 },
  { title: "Tired of Being Alone", artist: "Al Green", year: 1971 },
  { title: "September", artist: "Earth, Wind & Fire", year: 1978 },
  { title: "Boogie Wonderland", artist: "Earth, Wind & Fire", year: 1979 },
  { title: "Celebration", artist: "Kool & The Gang", year: 1980 },
  { title: "Ladies Night", artist: "Kool & The Gang", year: 1979 },
  { title: "Get Ready", artist: "The Temptations", year: 1966 },
  { title: "Signed, Sealed, Delivered I'm Yours", artist: "Stevie Wonder", year: 1970 },
  { title: "Higher Ground", artist: "Stevie Wonder", year: 1973 },
  { title: "Sir Duke", artist: "Stevie Wonder", year: 1976 },

  // --- Classic Rock deep cuts ---
  { title: "Comfortably Numb", artist: "Pink Floyd", year: 1979 },
  { title: "Wish You Were Here", artist: "Pink Floyd", year: 1975 },
  { title: "Another Brick in the Wall", artist: "Pink Floyd", year: 1979 },
  { title: "Money", artist: "Pink Floyd", year: 1973 },
  { title: "Baba O'Riley", artist: "The Who", year: 1971 },
  { title: "My Generation", artist: "The Who", year: 1965 },
  { title: "Won't Get Fooled Again", artist: "The Who", year: 1971 },
  { title: "Smoke on the Water", artist: "Deep Purple", year: 1972 },
  { title: "Highway Star", artist: "Deep Purple", year: 1972 },
  { title: "Paranoid", artist: "Black Sabbath", year: 1970 },
  { title: "Iron Man", artist: "Black Sabbath", year: 1970 },
  { title: "Jump", artist: "Van Halen", year: 1984 },
  { title: "Panama", artist: "Van Halen", year: 1984 },
  { title: "La Grange", artist: "ZZ Top", year: 1973 },
  { title: "Sharp Dressed Man", artist: "ZZ Top", year: 1983 },
  { title: "Fortunate Son", artist: "Creedence Clearwater Revival", year: 1969 },
  { title: "Have You Ever Seen the Rain?", artist: "Creedence Clearwater Revival", year: 1970 },
  { title: "Bad Moon Rising", artist: "Creedence Clearwater Revival", year: 1969 },
  { title: "Light My Fire", artist: "The Doors", year: 1967 },
  { title: "Riders on the Storm", artist: "The Doors", year: 1971 },
  { title: "Born to Be Wild", artist: "Steppenwolf", year: 1968 },
  { title: "All Right Now", artist: "Free", year: 1970 },

  // --- Disco ---
  { title: "I Will Survive", artist: "Gloria Gaynor", year: 1978 },
  { title: "Hot Stuff", artist: "Donna Summer", year: 1979 },
  { title: "Last Dance", artist: "Donna Summer", year: 1978 },
  { title: "I Feel Love", artist: "Donna Summer", year: 1977 },
  { title: "That's the Way (I Like It)", artist: "KC and the Sunshine Band", year: 1975 },
  { title: "Y.M.C.A.", artist: "Village People", year: 1978 },
  { title: "Le Freak", artist: "Chic", year: 1978 },
  { title: "Good Times", artist: "Chic", year: 1979 },
  { title: "Boogie Oogie Oogie", artist: "A Taste of Honey", year: 1978 },
  { title: "Funkytown", artist: "Lipps Inc.", year: 1979 },
  { title: "Disco Inferno", artist: "The Trammps", year: 1976 },

  // --- Country ---
  { title: "Jolene", artist: "Dolly Parton", year: 1973 },
  { title: "9 to 5", artist: "Dolly Parton", year: 1980 },
  { title: "I Will Always Love You (original)", artist: "Dolly Parton", year: 1973 },
  { title: "Ring of Fire", artist: "Johnny Cash", year: 1963 },
  { title: "I Walk the Line", artist: "Johnny Cash", year: 1956 },
  { title: "Folsom Prison Blues", artist: "Johnny Cash", year: 1955 },
  { title: "The Gambler", artist: "Kenny Rogers", year: 1978 },
  { title: "Islands in the Stream", artist: "Kenny Rogers & Dolly Parton", year: 1983 },
  { title: "Man! I Feel Like a Woman!", artist: "Shania Twain", year: 1997 },
  { title: "You're Still the One", artist: "Shania Twain", year: 1997 },
  { title: "That Don't Impress Me Much", artist: "Shania Twain", year: 1998 },
  { title: "Before He Cheats", artist: "Carrie Underwood", year: 2006 },
  { title: "Jesus, Take the Wheel", artist: "Carrie Underwood", year: 2005 },
  { title: "Friends in Low Places", artist: "Garth Brooks", year: 1990 },
  { title: "The Dance", artist: "Garth Brooks", year: 1990 },
  { title: "On the Road Again", artist: "Willie Nelson", year: 1980 },
  { title: "Crazy", artist: "Patsy Cline", year: 1961 },
  { title: "Take Me Home, Country Roads", artist: "John Denver", year: 1971 },

  // --- 90s R&B / Hip-Hop ---
  { title: "End of the Road", artist: "Boyz II Men", year: 1992 },
  { title: "I'll Make Love to You", artist: "Boyz II Men", year: 1994 },
  { title: "Motownphilly", artist: "Boyz II Men", year: 1991 },
  { title: "My Lovin' (You're Never Gonna Get It)", artist: "En Vogue", year: 1992 },
  { title: "Don't Let Go (Love)", artist: "En Vogue", year: 1996 },
  { title: "Push It", artist: "Salt-N-Pepa", year: 1988 },
  { title: "Shoop", artist: "Salt-N-Pepa", year: 1993 },
  { title: "Juicy", artist: "The Notorious B.I.G.", year: 1994 },
  { title: "Hypnotize", artist: "The Notorious B.I.G.", year: 1997 },
  { title: "California Love", artist: "2Pac ft. Dr. Dre", year: 1995 },
  { title: "Changes", artist: "2Pac", year: 1998 },
  { title: "C.R.E.A.M.", artist: "Wu-Tang Clan", year: 1993 },
  { title: "Gangsta's Paradise", artist: "Coolio", year: 1995 },
  { title: "Thong Song", artist: "Sisqo", year: 2000 },
  { title: "No Diggity", artist: "Blackstreet", year: 1996 },
  { title: "Nuthin' But a 'G' Thang", artist: "Dr. Dre ft. Snoop Dogg", year: 1992 },
  { title: "Gin and Juice", artist: "Snoop Dogg", year: 1993 },
  { title: "It Was a Good Day", artist: "Ice Cube", year: 1992 },
  { title: "Ms. Jackson", artist: "OutKast", year: 2000 },
  { title: "Hey Ya!", artist: "OutKast", year: 2003 },
  { title: "Hot in Herre", artist: "Nelly", year: 2002 },
  { title: "Country Grammar", artist: "Nelly", year: 2000 },

  // --- 2000s Pop ---
  { title: "Genie in a Bottle", artist: "Christina Aguilera", year: 1999 },
  { title: "Beautiful", artist: "Christina Aguilera", year: 2002 },
  { title: "Fighter", artist: "Christina Aguilera", year: 2003 },
  { title: "Complicated", artist: "Avril Lavigne", year: 2002 },
  { title: "Sk8er Boi", artist: "Avril Lavigne", year: 2002 },
  { title: "Since U Been Gone", artist: "Kelly Clarkson", year: 2004 },
  { title: "Because of You", artist: "Kelly Clarkson", year: 2004 },
  { title: "So What", artist: "P!nk", year: 2008 },
  { title: "Just Like a Pill", artist: "P!nk", year: 2002 },
  { title: "Get the Party Started", artist: "P!nk", year: 2001 },
  { title: "Hollaback Girl", artist: "Gwen Stefani", year: 2004 },
  { title: "The Sweet Escape", artist: "Gwen Stefani", year: 2006 },
  { title: "Don't Speak", artist: "No Doubt", year: 1996 },
  { title: "It's My Life", artist: "No Doubt", year: 2003 },

  // --- 2010s / 2020s Pop & Indie ---
  { title: "Royals", artist: "Lorde", year: 2013 },
  { title: "Team", artist: "Lorde", year: 2013 },
  { title: "Without Me", artist: "Halsey", year: 2018 },
  { title: "Bad at Love", artist: "Halsey", year: 2017 },
  { title: "Havana", artist: "Camila Cabello", year: 2017 },
  { title: "Señorita", artist: "Shawn Mendes & Camila Cabello", year: 2019 },
  { title: "Attention", artist: "Charlie Puth", year: 2017 },
  { title: "We Don't Talk Anymore", artist: "Charlie Puth ft. Selena Gomez", year: 2016 },
  { title: "She Looks So Perfect", artist: "5 Seconds of Summer", year: 2014 },
  { title: "Youngblood", artist: "5 Seconds of Summer", year: 2018 },
  { title: "Pumped Up Kicks", artist: "Foster the People", year: 2010 },
  { title: "Ho Hey", artist: "The Lumineers", year: 2012 },
  { title: "Little Talks", artist: "Of Monsters and Men", year: 2011 },
  { title: "I Will Wait", artist: "Mumford & Sons", year: 2012 },
  { title: "Pompeii", artist: "Bastille", year: 2013 },
  { title: "Shut Up and Dance", artist: "Walk the Moon", year: 2014 },
  { title: "Dog Days Are Over", artist: "Florence + The Machine", year: 2008 },
  { title: "Shake It Out", artist: "Florence + The Machine", year: 2011 },
  { title: "Somebody That I Used to Know", artist: "Gotye ft. Kimbra", year: 2011 },
  { title: "Riptide", artist: "Vance Joy", year: 2013 },
  { title: "Take Me to Church", artist: "Hozier", year: 2013 },
  { title: "Budapest", artist: "George Ezra", year: 2014 },
  { title: "Sugar", artist: "Robin Schulz ft. Francesco Yates", year: 2015 },
  { title: "Cake by the Ocean", artist: "DNCE", year: 2015 },
  { title: "Cheap Thrills", artist: "Sia ft. Sean Paul", year: 2016 },
  { title: "Titanium", artist: "David Guetta ft. Sia", year: 2011 },
  { title: "Wake Me Up", artist: "Avicii", year: 2013 },
  { title: "Levels", artist: "Avicii", year: 2011 },
  { title: "Clarity", artist: "Zedd ft. Foxes", year: 2012 },
  { title: "Wide Awake", artist: "Katy Perry", year: 2012 },
  { title: "Dark Horse", artist: "Katy Perry ft. Juicy J", year: 2013 },
  { title: "California Gurls", artist: "Katy Perry ft. Snoop Dogg", year: 2010 },
  { title: "Teenage Dream", artist: "Katy Perry", year: 2010 },
  { title: "Faded", artist: "Alan Walker", year: 2015 },
  { title: "Closer", artist: "The Chainsmokers ft. Halsey", year: 2016 },
  { title: "Something Just Like This", artist: "The Chainsmokers & Coldplay", year: 2017 },
  { title: "Old Town Road", artist: "Lil Nas X", year: 2019 },
  { title: "Watermelon Sugar", artist: "Harry Styles", year: 2019 },
  { title: "Adore You", artist: "Harry Styles", year: 2019 },
  { title: "Good 4 U", artist: "Olivia Rodrigo", year: 2021 },
  { title: "New Rules", artist: "Dua Lipa", year: 2017 },
  { title: "Physical", artist: "Dua Lipa", year: 2020 },
  { title: "Peaches", artist: "Justin Bieber ft. Daniel Caesar, Giveon", year: 2021 },
  { title: "Stay", artist: "The Kid LAROI & Justin Bieber", year: 2021 },
  { title: "Save Your Tears", artist: "The Weeknd", year: 2020 },
  { title: "Heat Waves", artist: "Glass Animals", year: 2020 },
  { title: "Flowers", artist: "Miley Cyrus", year: 2023 },
  { title: "Wrecking Ball", artist: "Miley Cyrus", year: 2013 },
  { title: "Party in the U.S.A.", artist: "Miley Cyrus", year: 2009 },
  { title: "Vampire", artist: "Olivia Rodrigo", year: 2023 },
  { title: "Cruel Summer", artist: "Taylor Swift", year: 2019 },
  { title: "Cardigan", artist: "Taylor Swift", year: 2020 },
  { title: "Willow", artist: "Taylor Swift", year: 2020 },
  { title: "22", artist: "Taylor Swift", year: 2012 },
  { title: "You Belong With Me", artist: "Taylor Swift", year: 2008 },
  { title: "I Knew You Were Trouble", artist: "Taylor Swift", year: 2012 },

  // --- British Rock / Indie ---
  { title: "Waterloo Sunset", artist: "The Kinks", year: 1967 },
  { title: "You Really Got Me", artist: "The Kinks", year: 1964 },
  { title: "Time of the Season", artist: "The Zombies", year: 1968 },
  { title: "Itchycoo Park", artist: "Small Faces", year: 1967 },
  { title: "If You Tolerate This Your Children Will Be Next", artist: "Manic Street Preachers", year: 1998 },
  { title: "Starlight", artist: "Muse", year: 2006 },
  { title: "Uprising", artist: "Muse", year: 2009 },
  { title: "Supermassive Black Hole", artist: "Muse", year: 2006 },
  { title: "Chasing Cars", artist: "Snow Patrol", year: 2006 },
  { title: "Somewhere Only We Know", artist: "Keane", year: 2004 },
  { title: "Why Does It Always Rain on Me?", artist: "Travis", year: 1999 },
  { title: "A-Punk", artist: "Vampire Weekend", year: 2008 },
  { title: "The Man Who Sold the World", artist: "David Bowie", year: 1970 },
  { title: "Life on Mars?", artist: "David Bowie", year: 1971 },
  { title: "Ashes to Ashes", artist: "David Bowie", year: 1980 },
  { title: "Chocolate", artist: "The 1975", year: 2013 },
  { title: "Somebody Else", artist: "The 1975", year: 2016 },
  { title: "Breezeblocks", artist: "Alt-J", year: 2012 },
  { title: "What Do You Mean?", artist: "Two Door Cinema Club", year: 2010 },

  // --- Musicals & Disney ---
  { title: "Let It Go", artist: "Idina Menzel", year: 2013 },
  { title: "A Whole New World", artist: "Peabo Bryson & Regina Belle", year: 1992 },
  { title: "Circle of Life", artist: "Elton John", year: 1994 },
  { title: "Can You Feel the Love Tonight", artist: "Elton John", year: 1994 },
  { title: "Defying Gravity", artist: "Idina Menzel & Kristin Chenoweth", year: 2003 },
  { title: "Seasons of Love", artist: "Rent Cast", year: 1996 },
  { title: "Memory", artist: "Elaine Paige", year: 1981 },
  { title: "The Phantom of the Opera", artist: "Sarah Brightman & Michael Crawford", year: 1986 },
  { title: "Somewhere Over the Rainbow", artist: "Judy Garland", year: 1939 },
  { title: "Singin' in the Rain", artist: "Gene Kelly", year: 1952 },

  // --- Wedding / Standards ---
  { title: "At Last", artist: "Etta James", year: 1960 },
  { title: "Marry You", artist: "Bruno Mars", year: 2010 },
  { title: "L-O-V-E", artist: "Nat King Cole", year: 1965 },
  { title: "Unforgettable", artist: "Nat King Cole", year: 1951 },
  { title: "What a Wonderful World", artist: "Louis Armstrong", year: 1967 },
  { title: "The Way You Look Tonight", artist: "Frank Sinatra", year: 1964 },
  { title: "Just the Two of Us", artist: "Grover Washington Jr. ft. Bill Withers", year: 1980 },
  { title: "Lean on Me", artist: "Bill Withers", year: 1972 },
  { title: "Ain't No Sunshine", artist: "Bill Withers", year: 1971 },
  { title: "You Are the Sunshine of My Life", artist: "Stevie Wonder", year: 1973 },
  { title: "I Just Called to Say I Love You", artist: "Stevie Wonder", year: 1984 },
  { title: "Kiss From a Rose", artist: "Seal", year: 1994 },
  { title: "A Thousand Years", artist: "Christina Perri", year: 2011 },
  { title: "Make You Feel My Love", artist: "Adele", year: 2008 },
  { title: "Groovin'", artist: "The Young Rascals", year: 1967 },

  // --- More classics / one-hit wonders ---
  { title: "Tainted Love", artist: "Soft Cell", year: 1981 },
  { title: "Video Killed the Radio Star", artist: "The Buggles", year: 1979 },
  { title: "867-5309/Jenny", artist: "Tommy Tutone", year: 1981 },
  { title: "Come On Eileen", artist: "Dexys Midnight Runners", year: 1982 },
  { title: "I Ran (So Far Away)", artist: "A Flock of Seagulls", year: 1982 },
  { title: "Whip It", artist: "Devo", year: 1980 },
  { title: "Turning Japanese", artist: "The Vapors", year: 1980 },
  { title: "99 Red Balloons", artist: "Nena", year: 1984 },
  { title: "Mickey", artist: "Toni Basil", year: 1982 },
  { title: "Walking on Sunshine", artist: "Katrina and the Waves", year: 1985 },
  { title: "The Final Countdown", artist: "Europe", year: 1986 },
  { title: "Take My Breath Away", artist: "Berlin", year: 1986 },
  { title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987 },
  { title: "How Will I Know", artist: "Whitney Houston", year: 1985 },
  { title: "So Emotional", artist: "Whitney Houston", year: 1987 },
  { title: "Greatest Love of All", artist: "Whitney Houston", year: 1985 },
  { title: "Vision of Love", artist: "Mariah Carey", year: 1990 },
  { title: "Hero", artist: "Mariah Carey", year: 1993 },
  { title: "Without You", artist: "Mariah Carey", year: 1994 },
  { title: "Endless Love", artist: "Diana Ross & Lionel Richie", year: 1981 },
  { title: "Hello", artist: "Lionel Richie", year: 1984 },
  { title: "All Night Long", artist: "Lionel Richie", year: 1983 },
  { title: "Easy", artist: "Commodores", year: 1977 },
  { title: "Brick House", artist: "Commodores", year: 1977 },
  { title: "Ain't No Mountain High Enough", artist: "Marvin Gaye & Tammi Terrell", year: 1967 },
  { title: "You're All I Need to Get By", artist: "Marvin Gaye & Tammi Terrell", year: 1968 },
  { title: "Let's Get It On", artist: "Marvin Gaye", year: 1973 },
  { title: "Sexual Healing", artist: "Marvin Gaye", year: 1982 },
  { title: "Freedom! '90", artist: "George Michael", year: 1990 },
  { title: "Club Tropicana", artist: "Wham!", year: 1983 },
  { title: "Wake Me Up Before You Go-Go", artist: "Wham!", year: 1984 },

  // --- Reggae / Funk ---
  { title: "No Woman, No Cry", artist: "Bob Marley & The Wailers", year: 1974 },
  { title: "One Love", artist: "Bob Marley & The Wailers", year: 1977 },
  { title: "Three Little Birds", artist: "Bob Marley & The Wailers", year: 1977 },
  { title: "Redemption Song", artist: "Bob Marley & The Wailers", year: 1980 },
  { title: "Is This Love", artist: "Bob Marley & The Wailers", year: 1978 },
  { title: "Buffalo Soldier", artist: "Bob Marley & The Wailers", year: 1983 },
  { title: "The Israelites", artist: "Desmond Dekker", year: 1968 },
  { title: "Get Up (I Feel Like Being a) Sex Machine", artist: "James Brown", year: 1970 },
  { title: "I Got You (I Feel Good)", artist: "James Brown", year: 1965 },
  { title: "Papa's Got a Brand New Bag", artist: "James Brown", year: 1965 },
  { title: "Give Up the Funk (Tear the Roof off the Sucker)", artist: "Parliament", year: 1976 },
  { title: "Flash Light", artist: "Parliament", year: 1977 },
  { title: "Play That Funky Music", artist: "Wild Cherry", year: 1976 },
  { title: "Super Freak", artist: "Rick James", year: 1981 },

  // --- Jazz standards ---
  { title: "Summertime", artist: "Ella Fitzgerald & Louis Armstrong", year: 1957 },
  { title: "Take Five", artist: "The Dave Brubeck Quartet", year: 1959 },
  { title: "Feeling Good", artist: "Nina Simone", year: 1965 },
  { title: "Sinnerman", artist: "Nina Simone", year: 1965 },
  { title: "My Baby Just Cares for Me", artist: "Nina Simone", year: 1958 },
  { title: "Georgia on My Mind", artist: "Ray Charles", year: 1960 },
  { title: "Hit the Road Jack", artist: "Ray Charles", year: 1961 },
  { title: "I Got You Under My Skin", artist: "Frank Sinatra", year: 1956 },
  { title: "Come Fly with Me", artist: "Frank Sinatra", year: 1958 },

  // --- More recent (2020s) ---
  { title: "Unholy", artist: "Sam Smith & Kim Petras", year: 2022 },
  { title: "About Damn Time", artist: "Lizzo", year: 2022 },
  { title: "Truth Hurts", artist: "Lizzo", year: 2017 },
  { title: "Industry Baby", artist: "Lil Nas X & Jack Harlow", year: 2021 },
  { title: "Montero (Call Me by Your Name)", artist: "Lil Nas X", year: 2021 },
  { title: "Easy on Me", artist: "Adele", year: 2021 },
  { title: "Oh My God", artist: "Adele", year: 2021 },
  { title: "Late Night Talking", artist: "Harry Styles", year: 2022 },
  { title: "Golden", artist: "Harry Styles", year: 2020 },
  { title: "Sunflower", artist: "Post Malone & Swae Lee", year: 2018 },
  { title: "Rockstar", artist: "Post Malone ft. 21 Savage", year: 2017 },
  { title: "Congratulations", artist: "Post Malone ft. Quavo", year: 2016 },
  { title: "Location", artist: "Khalid", year: 2016 },
  { title: "Talk", artist: "Khalid", year: 2019 },
  { title: "Lovely", artist: "Billie Eilish & Khalid", year: 2018 },
  { title: "Ocean Eyes", artist: "Billie Eilish", year: 2016 },
  { title: "Therefore I Am", artist: "Billie Eilish", year: 2020 },
  { title: "Ghost", artist: "Justin Bieber", year: 2021 },
  { title: "Love Yourself", artist: "Justin Bieber", year: 2015 },
  { title: "What Do You Mean? (Bieber)", artist: "Justin Bieber", year: 2015 },
  { title: "Company", artist: "Justin Bieber", year: 2015 },
  { title: "In My Blood", artist: "Shawn Mendes", year: 2018 },
  { title: "There's Nothing Holdin' Me Back", artist: "Shawn Mendes", year: 2017 },
  { title: "Treat You Better", artist: "Shawn Mendes", year: 2016 },
];
