// songs/en.js — English-language song pack. No youtubeId (search fallback,
// per the schema in songs/he.js) — playback resolves via YouTube search on
// "artist title" at run time.
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.en = [
  { title: "Bohemian Rhapsody", artist: "Queen", year: 1975 },
  { title: "We Will Rock You", artist: "Queen", year: 1977 },
  { title: "Don't Stop Me Now", artist: "Queen", year: 1978 },
  { title: "Billie Jean", artist: "Michael Jackson", year: 1983 },
  { title: "Thriller", artist: "Michael Jackson", year: 1982 },
  { title: "Beat It", artist: "Michael Jackson", year: 1982 },
  { title: "Smooth Criminal", artist: "Michael Jackson", year: 1987 },
  { title: "Like a Prayer", artist: "Madonna", year: 1989 },
  { title: "Material Girl", artist: "Madonna", year: 1984 },
  { title: "Vogue", artist: "Madonna", year: 1990 },
  { title: "Jailhouse Rock", artist: "Elvis Presley", year: 1957 },
  { title: "Can't Help Falling in Love", artist: "Elvis Presley", year: 1961 },
  { title: "Hound Dog", artist: "Elvis Presley", year: 1956 },
  { title: "I Will Always Love You", artist: "Whitney Houston", year: 1992 },
  { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", year: 1987 },
  { title: "Rolling in the Deep", artist: "Adele", year: 2010 },
  { title: "Someone Like You", artist: "Adele", year: 2011 },
  { title: "Hello", artist: "Adele", year: 2015 },
  { title: "Shape of You", artist: "Ed Sheeran", year: 2017 },
  { title: "Perfect", artist: "Ed Sheeran", year: 2017 },
  { title: "Thinking Out Loud", artist: "Ed Sheeran", year: 2014 },
  { title: "Shake It Off", artist: "Taylor Swift", year: 2014 },
  { title: "Blank Space", artist: "Taylor Swift", year: 2014 },
  { title: "Love Story", artist: "Taylor Swift", year: 2008 },
  { title: "Anti-Hero", artist: "Taylor Swift", year: 2022 },
  { title: "Uptown Funk", artist: "Bruno Mars", year: 2014 },
  { title: "Just the Way You Are", artist: "Bruno Mars", year: 2010 },
  { title: "24K Magic", artist: "Bruno Mars", year: 2016 },
  { title: "Umbrella", artist: "Rihanna", year: 2007 },
  { title: "Diamonds", artist: "Rihanna", year: 2012 },
  { title: "Work", artist: "Rihanna", year: 2016 },
  { title: "Halo", artist: "Beyoncé", year: 2008 },
  { title: "Single Ladies (Put a Ring on It)", artist: "Beyoncé", year: 2008 },
  { title: "Crazy in Love", artist: "Beyoncé", year: 2003 },
  { title: "Lose Yourself", artist: "Eminem", year: 2002 },
  { title: "Not Afraid", artist: "Eminem", year: 2010 },
  { title: "Yellow", artist: "Coldplay", year: 2000 },
  { title: "Fix You", artist: "Coldplay", year: 2005 },
  { title: "Viva la Vida", artist: "Coldplay", year: 2008 },
  { title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986 },
  { title: "It's My Life", artist: "Bon Jovi", year: 2000 },
  { title: "Sweet Child o' Mine", artist: "Guns N' Roses", year: 1987 },
  { title: "November Rain", artist: "Guns N' Roses", year: 1991 },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
  { title: "Come as You Are", artist: "Nirvana", year: 1991 },
  { title: "With or Without You", artist: "U2", year: 1987 },
  { title: "Beautiful Day", artist: "U2", year: 2000 },
  { title: "Rocket Man", artist: "Elton John", year: 1972 },
  { title: "Your Song", artist: "Elton John", year: 1970 },
  { title: "Tiny Dancer", artist: "Elton John", year: 1971 },
  { title: "Superstition", artist: "Stevie Wonder", year: 1972 },
  { title: "Isn't She Lovely", artist: "Stevie Wonder", year: 1976 },
  { title: "Dreams", artist: "Fleetwood Mac", year: 1977 },
  { title: "Go Your Own Way", artist: "Fleetwood Mac", year: 1977 },
  { title: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", year: 1965 },
  { title: "Paint It Black", artist: "The Rolling Stones", year: 1966 },
  { title: "Stairway to Heaven", artist: "Led Zeppelin", year: 1971 },
  { title: "Whole Lotta Love", artist: "Led Zeppelin", year: 1969 },
  { title: "Heroes", artist: "David Bowie", year: 1977 },
  { title: "Let's Dance", artist: "David Bowie", year: 1983 },
  { title: "Space Oddity", artist: "David Bowie", year: 1969 },
  { title: "Purple Rain", artist: "Prince", year: 1984 },
  { title: "Kiss", artist: "Prince", year: 1986 },
  { title: "When Doves Cry", artist: "Prince", year: 1984 },
  { title: "Careless Whisper", artist: "George Michael", year: 1984 },
  { title: "Faith", artist: "George Michael", year: 1987 },
  { title: "Piano Man", artist: "Billy Joel", year: 1973 },
  { title: "Uptown Girl", artist: "Billy Joel", year: 1983 },
  { title: "Stayin' Alive", artist: "Bee Gees", year: 1977 },
  { title: "Night Fever", artist: "Bee Gees", year: 1977 },
  { title: "Hotel California", artist: "Eagles", year: 1976 },
  { title: "Don't Stop Believin'", artist: "Journey", year: 1981 },
  { title: "Dream On", artist: "Aerosmith", year: 1973 },
  { title: "I Don't Want to Miss a Thing", artist: "Aerosmith", year: 1998 },
  { title: "Back in Black", artist: "AC/DC", year: 1980 },
  { title: "Highway to Hell", artist: "AC/DC", year: 1979 },
  { title: "Enter Sandman", artist: "Metallica", year: 1991 },
  { title: "Nothing Else Matters", artist: "Metallica", year: 1991 },
  { title: "I Want It That Way", artist: "Backstreet Boys", year: 1999 },
  { title: "Bye Bye Bye", artist: "NSYNC", year: 2000 },
  { title: "...Baby One More Time", artist: "Britney Spears", year: 1998 },
  { title: "Toxic", artist: "Britney Spears", year: 2003 },
  { title: "Cry Me a River", artist: "Justin Timberlake", year: 2002 },
  { title: "Can't Stop the Feeling!", artist: "Justin Timberlake", year: 2016 },
  { title: "Baby", artist: "Justin Bieber", year: 2010 },
  { title: "Sorry", artist: "Justin Bieber", year: 2015 },
  { title: "Firework", artist: "Katy Perry", year: 2010 },
  { title: "Roar", artist: "Katy Perry", year: 2013 },
  { title: "Bad Romance", artist: "Lady Gaga", year: 2009 },
  { title: "Poker Face", artist: "Lady Gaga", year: 2008 },
  { title: "Shallow", artist: "Lady Gaga", year: 2018 },
  { title: "Sugar", artist: "Maroon 5", year: 2015 },
  { title: "Girls Like You", artist: "Maroon 5", year: 2018 },
  { title: "Counting Stars", artist: "OneRepublic", year: 2013 },
  { title: "Believer", artist: "Imagine Dragons", year: 2017 },
  { title: "Radioactive", artist: "Imagine Dragons", year: 2012 },
  { title: "Blinding Lights", artist: "The Weeknd", year: 2019 },
  { title: "Starboy", artist: "The Weeknd", year: 2016 },
  { title: "Levitating", artist: "Dua Lipa", year: 2020 },
  { title: "Don't Start Now", artist: "Dua Lipa", year: 2019 },
  { title: "Thank U, Next", artist: "Ariana Grande", year: 2018 },
  { title: "7 Rings", artist: "Ariana Grande", year: 2019 },
  { title: "Bad Guy", artist: "Billie Eilish", year: 2019 },
  { title: "Happier Than Ever", artist: "Billie Eilish", year: 2021 },
  { title: "Drivers License", artist: "Olivia Rodrigo", year: 2021 },
  { title: "As It Was", artist: "Harry Styles", year: 2022 },
  { title: "Stitches", artist: "Shawn Mendes", year: 2015 },
  { title: "Chandelier", artist: "Sia", year: 2014 },
  { title: "Stay With Me", artist: "Sam Smith", year: 2014 },
  { title: "Rehab", artist: "Amy Winehouse", year: 2006 },
  { title: "Back to Black", artist: "Amy Winehouse", year: 2006 },
  { title: "Creep", artist: "Radiohead", year: 1992 },
  { title: "Karma Police", artist: "Radiohead", year: 1997 },
  { title: "Mr. Brightside", artist: "The Killers", year: 2003 },
  { title: "Somebody Told Me", artist: "The Killers", year: 2004 },
  { title: "Do I Wanna Know?", artist: "Arctic Monkeys", year: 2013 },
  { title: "R U Mine?", artist: "Arctic Monkeys", year: 2013 },
  { title: "Wonderwall", artist: "Oasis", year: 1995 },
  { title: "Don't Look Back in Anger", artist: "Oasis", year: 1995 },
  { title: "Song 2", artist: "Blur", year: 1997 },
  { title: "Angels", artist: "Robbie Williams", year: 1997 },
  { title: "Wannabe", artist: "Spice Girls", year: 1996 },
  { title: "Say You'll Be There", artist: "Spice Girls", year: 1996 },
  { title: "Say My Name", artist: "Destiny's Child", year: 1999 },
  { title: "Survivor", artist: "Destiny's Child", year: 2001 },
  { title: "No Scrubs", artist: "TLC", year: 1999 },
  { title: "Waterfalls", artist: "TLC", year: 1994 },
  { title: "All I Want for Christmas Is You", artist: "Mariah Carey", year: 1994 },
  { title: "Fantasy", artist: "Mariah Carey", year: 1995 },
  { title: "My Heart Will Go On", artist: "Celine Dion", year: 1997 },
  { title: "The Power of Love", artist: "Celine Dion", year: 1993 },
  { title: "What's Love Got to Do with It", artist: "Tina Turner", year: 1984 },
  { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: 1983 },
  { title: "I Heard It Through the Grapevine", artist: "Marvin Gaye", year: 1968 },
  { title: "What's Going On", artist: "Marvin Gaye", year: 1971 },
  { title: "Respect", artist: "Aretha Franklin", year: 1967 },
  { title: "Fly Me to the Moon", artist: "Frank Sinatra", year: 1964 },
  { title: "My Way", artist: "Frank Sinatra", year: 1969 },
  { title: "New York, New York", artist: "Frank Sinatra", year: 1980 },
  { title: "Good Vibrations", artist: "The Beach Boys", year: 1966 },
  { title: "The Sound of Silence", artist: "Simon & Garfunkel", year: 1964 },
  { title: "Bridge Over Troubled Water", artist: "Simon & Garfunkel", year: 1970 },
  { title: "Like a Rolling Stone", artist: "Bob Dylan", year: 1965 },
  { title: "Knockin' on Heaven's Door", artist: "Bob Dylan", year: 1973 },
  { title: "25 or 6 to 4", artist: "Chicago", year: 1970 },
  { title: "Africa", artist: "Toto", year: 1982 },
  { title: "I Want to Know What Love Is", artist: "Foreigner", year: 1984 },
  { title: "Can't Fight This Feeling", artist: "REO Speedwagon", year: 1984 },
  { title: "Eye of the Tiger", artist: "Survivor", year: 1982 },
  { title: "Carry On Wayward Son", artist: "Kansas", year: 1976 },
  { title: "More Than a Feeling", artist: "Boston", year: 1976 },
  { title: "The Joker", artist: "Steve Miller Band", year: 1973 },
  { title: "Layla", artist: "Eric Clapton", year: 1970 },
  { title: "Wonderful Tonight", artist: "Eric Clapton", year: 1977 },
  { title: "Every Breath You Take", artist: "The Police", year: 1983 },
  { title: "Roxanne", artist: "The Police", year: 1978 },
  { title: "Fields of Gold", artist: "Sting", year: 1993 },
  { title: "In the Air Tonight", artist: "Phil Collins", year: 1981 },
  { title: "Another Day in Paradise", artist: "Phil Collins", year: 1989 },
  { title: "Sledgehammer", artist: "Peter Gabriel", year: 1986 },
  { title: "Sultans of Swing", artist: "Dire Straits", year: 1978 },
  { title: "Money for Nothing", artist: "Dire Straits", year: 1985 },
  { title: "Everybody Wants to Rule the World", artist: "Tears for Fears", year: 1985 },
  { title: "Girls on Film", artist: "Duran Duran", year: 1981 },
  { title: "Hungry Like the Wolf", artist: "Duran Duran", year: 1982 },
  { title: "Karma Chameleon", artist: "Culture Club", year: 1983 },
  { title: "Last Christmas", artist: "Wham!", year: 1984 },
  { title: "Take On Me", artist: "a-ha", year: 1985 },
  { title: "Enjoy the Silence", artist: "Depeche Mode", year: 1990 },
  { title: "Blue Monday", artist: "New Order", year: 1983 },
  { title: "Friday I'm in Love", artist: "The Cure", year: 1992 },
  { title: "Once in a Lifetime", artist: "Talking Heads", year: 1980 },
  { title: "Losing My Religion", artist: "R.E.M.", year: 1991 },
  { title: "Alive", artist: "Pearl Jam", year: 1991 },
  { title: "Black Hole Sun", artist: "Soundgarden", year: 1994 },
  { title: "Man in the Box", artist: "Alice in Chains", year: 1990 },
  { title: "Under the Bridge", artist: "Red Hot Chili Peppers", year: 1991 },
  { title: "Can't Stop", artist: "Red Hot Chili Peppers", year: 2002 },
  { title: "Everlong", artist: "Foo Fighters", year: 1997 },
  { title: "Learn to Fly", artist: "Foo Fighters", year: 1999 },
  { title: "Basket Case", artist: "Green Day", year: 1994 },
  { title: "Boulevard of Broken Dreams", artist: "Green Day", year: 2004 },
  { title: "All the Small Things", artist: "blink-182", year: 1999 },
  { title: "In the End", artist: "Linkin Park", year: 2000 },
  { title: "Numb", artist: "Linkin Park", year: 2003 },
  { title: "Chop Suey!", artist: "System of a Down", year: 2001 },
  { title: "Bring Me to Life", artist: "Evanescence", year: 2003 },
  { title: "Welcome to the Black Parade", artist: "My Chemical Romance", year: 2006 },
  { title: "I Write Sins Not Tragedies", artist: "Panic! at the Disco", year: 2005 },
  { title: "Sugar, We're Goin Down", artist: "Fall Out Boy", year: 2005 },
  { title: "Misery Business", artist: "Paramore", year: 2007 },
  { title: "Stressed Out", artist: "twenty one pilots", year: 2015 },
  { title: "Drive By", artist: "Train", year: 2012 },
  { title: "All of Me", artist: "John Legend", year: 2013 },
  { title: "No One", artist: "Alicia Keys", year: 2007 },
  { title: "Yeah!", artist: "Usher", year: 2004 },
  { title: "Forever", artist: "Chris Brown", year: 2008 },
  { title: "So Sick", artist: "Ne-Yo", year: 2005 },
  { title: "Smack That", artist: "Akon", year: 2006 },
  { title: "Low", artist: "Flo Rida", year: 2007 },
  { title: "Give Me Everything", artist: "Pitbull", year: 2011 },
  { title: "I Gotta Feeling", artist: "The Black Eyed Peas", year: 2009 },
  { title: "Empire State of Mind", artist: "Jay-Z", year: 2009 },
  { title: "Stronger", artist: "Kanye West", year: 2007 },
  { title: "God's Plan", artist: "Drake", year: 2018 },
  { title: "One Dance", artist: "Drake", year: 2016 },
  { title: "Circles", artist: "Post Malone", year: 2019 },
  { title: "Sicko Mode", artist: "Travis Scott", year: 2018 },
  { title: "Bodak Yellow", artist: "Cardi B", year: 2017 },
  { title: "Super Bass", artist: "Nicki Minaj", year: 2010 },
  { title: "Say So", artist: "Doja Cat", year: 2019 },
];
