// songs/es.js — מאגר שירים בספרדית (ללא youtubeId — ניגון בחיפוש אוטומטי).
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.es = [
  { title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", year: 2017 },
  { title: "Bailando", artist: "Enrique Iglesias", year: 2014 },
  { title: "Bailamos", artist: "Enrique Iglesias", year: 1999 },
  { title: "Hero", artist: "Enrique Iglesias", year: 2001 },
  { title: "Vivir Mi Vida", artist: "Marc Anthony", year: 2013 },
  { title: "Y Tú Te Vas", artist: "Chayanne", year: 2003 },
  { title: "Torero", artist: "Chayanne", year: 2002 },
  { title: "Waka Waka (Esto Es África)", artist: "Shakira", year: 2010 },
  { title: "Hips Don't Lie", artist: "Shakira", year: 2005 },
  { title: "Whenever, Wherever", artist: "Shakira", year: 2001 },
  { title: "La Tortura", artist: "Shakira ft. Alejandro Sanz", year: 2005 },
  { title: "Corazón Partío", artist: "Alejandro Sanz", year: 1997 },
  { title: "La Camisa Negra", artist: "Juanes", year: 2004 },
  { title: "A Dios le Pido", artist: "Juanes", year: 2002 },
  { title: "Provenza", artist: "Karol G", year: 2022 },
  { title: "Tusa", artist: "Karol G ft. Nicki Minaj", year: 2019 },
  { title: "Con Altura", artist: "Rosalía ft. J Balvin", year: 2019 },
  { title: "Malamente", artist: "Rosalía", year: 2018 },
  { title: "Mi Gente", artist: "J Balvin", year: 2017 },
  { title: "Ginza", artist: "J Balvin", year: 2015 },
  { title: "Danza Kuduro", artist: "Don Omar ft. Lucenzo", year: 2010 },
  { title: "Bailar", artist: "Deorro ft. Elvis Crespo", year: 2015 },
  { title: "Gasolina", artist: "Daddy Yankee", year: 2004 },
  { title: "Con Calma", artist: "Daddy Yankee ft. Snow", year: 2019 },
  { title: "Vivir Sin Aire", artist: "Maná", year: 1992 },
  { title: "Rayando el Sol", artist: "Maná", year: 1990 },
  { title: "Corazón Espinado", artist: "Santana ft. Maná", year: 1999 },
  { title: "Oye Como Va", artist: "Santana", year: 1970 },
  { title: "Smooth", artist: "Santana ft. Rob Thomas", year: 1999 },
  { title: "La Bamba", artist: "Ritchie Valens", year: 1958 },
  { title: "Livin' la Vida Loca", artist: "Ricky Martin", year: 1999 },
  { title: "La Copa de la Vida", artist: "Ricky Martin", year: 1998 },
  { title: "María", artist: "Ricky Martin", year: 1995 },
  { title: "Amor Prohibido", artist: "Selena", year: 1994 },
  { title: "Como la Flor", artist: "Selena", year: 1992 },
  { title: "Bidi Bidi Bom Bom", artist: "Selena", year: 1994 },
  { title: "Volare", artist: "Gipsy Kings", year: 1989 },
  { title: "Bamboléo", artist: "Gipsy Kings", year: 1987 },
  { title: "Macarena", artist: "Los del Río", year: 1993 },
  { title: "Suavemente", artist: "Elvis Crespo", year: 1998 },
  { title: "Obsesión", artist: "Aventura", year: 2002 },
  { title: "Propuesta Indecente", artist: "Romeo Santos", year: 2013 },
  { title: "Odio", artist: "Romeo Santos ft. Drake", year: 2019 },
  { title: "Loba", artist: "Shakira", year: 2009 },
  { title: "Chantaje", artist: "Shakira ft. Maluma", year: 2016 },
  { title: "Felices los 4", artist: "Maluma", year: 2017 },
  { title: "Hawái", artist: "Maluma", year: 2020 },
  { title: "Vente Pa' Ca", artist: "Ricky Martin ft. Maluma", year: 2016 },
  { title: "Despacito (remix)", artist: "Luis Fonsi ft. Justin Bieber", year: 2017 },
  { title: "El Perdón", artist: "Nicky Jam & Enrique Iglesias", year: 2015 },
  { title: "Ay Vamos", artist: "J Balvin", year: 2014 },
  { title: "Tu Foto", artist: "Ozuna", year: 2017 },
  { title: "Taki Taki", artist: "DJ Snake ft. Ozuna, Cardi B, Selena Gomez", year: 2018 },
  { title: "Dákiti", artist: "Bad Bunny ft. Jhay Cortez", year: 2020 },
  { title: "Yo Perreo Sola", artist: "Bad Bunny", year: 2020 },
  { title: "Titi Me Preguntó", artist: "Bad Bunny", year: 2022 },
  { title: "Me Porto Bonito", artist: "Bad Bunny ft. Chencho Corleone", year: 2022 },
  { title: "China", artist: "Anuel AA, Daddy Yankee, Karol G, Ozuna, J Balvin", year: 2019 },
  { title: "Échame la Culpa", artist: "Luis Fonsi & Demi Lovato", year: 2017 },
  { title: "Duele el Corazón", artist: "Enrique Iglesias ft. Wisin", year: 2016 },
  { title: "Súbeme la Radio", artist: "Enrique Iglesias ft. Descemer Bueno", year: 2017 },
  { title: "Amorfoda", artist: "Bad Bunny", year: 2017 },
  { title: "La Bicicleta", artist: "Carlos Vives & Shakira", year: 2016 },
  { title: "La Bilirrubina", artist: "Juan Luis Guerra", year: 1990 },
  { title: "Ojalá Que Llueva Café", artist: "Juan Luis Guerra", year: 1989 },
  { title: "Burbujas de Amor", artist: "Juan Luis Guerra", year: 1990 },
  { title: "Color Esperanza", artist: "Diego Torres", year: 2001 },
  { title: "Tal Vez", artist: "Ricky Martin", year: 2003 },
  { title: "Bella", artist: "Ricardo Arjona", year: 1996 },
  { title: "Historia de Taxi", artist: "Ricardo Arjona", year: 1994 },
  { title: "Volver a Empezar", artist: "Alejandro Sanz", year: 2019 },
  { title: "Amiga Mía", artist: "Alejandro Sanz", year: 1997 },
  { title: "El Triste", artist: "José José", year: 1970 },
  { title: "Resistiré", artist: "Dúo Dinámico", year: 1988 },
  { title: "Pedro Navaja", artist: "Rubén Blades", year: 1978 },
  { title: "Aguanile", artist: "Héctor Lavoe", year: 1978 },
  { title: "El Cantante", artist: "Héctor Lavoe", year: 1978 },
  { title: "Idilio", artist: "Willie Colón & Héctor Lavoe", year: 1976 },
  { title: "Vivir Mi Vida (salsa)", artist: "Marc Anthony", year: 2013 },
  { title: "Preciosa", artist: "Marc Anthony", year: 1999 },
  { title: "Valió la Pena", artist: "Marc Anthony", year: 2004 },
  { title: "Bachata Rosa", artist: "Juan Luis Guerra", year: 1990 },
  { title: "El Wanabí", artist: "Chimbala", year: 2017 },
  { title: "Baila Esta Cumbia", artist: "Selena", year: 1990 },
  { title: "Cielito Lindo", artist: "Trío Los Panchos", year: 1950 },
  { title: "Bésame Mucho", artist: "Consuelo Velázquez", year: 1940 },
  { title: "Guantanamera", artist: "Celia Cruz", year: 1966 },
  { title: "La Vida Es Un Carnaval", artist: "Celia Cruz", year: 1998 },
  { title: "Quimbara", artist: "Celia Cruz", year: 1974 },
  { title: "La Negra Tiene Tumbao", artist: "Celia Cruz", year: 2001 },
  { title: "Rayito de Luna", artist: "Los Panchos", year: 1948 },
  { title: "Amor Eterno", artist: "Juan Gabriel", year: 1984 },
  { title: "Querida", artist: "Juan Gabriel", year: 1984 },
  { title: "El Noa Noa", artist: "Juan Gabriel", year: 1976 },
  { title: "Cielo Rojo", artist: "Los Ángeles Negros", year: 1969 },
  { title: "Y Nos Dieron las Diez", artist: "Joaquín Sabina", year: 1994 },
  { title: "19 Días y 500 Noches", artist: "Joaquín Sabina", year: 1999 },
  { title: "Contigo Aprendí", artist: "Armando Manzanero", year: 1967 },
  { title: "No Culpes a la Noche", artist: "Armando Manzanero", year: 1970 },
  { title: "Clavado en un Bar", artist: "Maná", year: 1995 },
  { title: "Oye Mi Amor", artist: "Maná", year: 1995 },
  { title: "En El Muelle de San Blas", artist: "Maná", year: 1997 },
  { title: "Labios Compartidos", artist: "Maná", year: 2006 },
  { title: "De Música Ligera", artist: "Soda Stereo", year: 1990 },
  { title: "Persiana Americana", artist: "Soda Stereo", year: 1986 },
  { title: "Prófugos", artist: "Soda Stereo", year: 1987 },
  { title: "Cuando Pase el Temblor", artist: "Soda Stereo", year: 1985 },
  { title: "Matador", artist: "Los Fabulosos Cadillacs", year: 1993 },
  { title: "Mal Bicho", artist: "Los Fabulosos Cadillacs", year: 1989 },
  { title: "Un Beso y Una Flor", artist: "Nino Bravo", year: 1972 },
  { title: "Libre", artist: "Nino Bravo", year: 1972 },
  { title: "América", artist: "Nino Bravo", year: 1971 },
  { title: "Y Como Es Él", artist: "José Luis Perales", year: 1982 },
  { title: "Ella", artist: "José José", year: 1990 },
  { title: "Amar y Vivir", artist: "Vicente Fernández", year: 1990 },
  { title: "El Rey", artist: "Vicente Fernández", year: 1971 },
  { title: "Volver, Volver", artist: "Vicente Fernández", year: 1972 },
  { title: "Cielito Lindo (mariachi)", artist: "Pedro Infante", year: 1953 },
  { title: "Amorcito Corazón", artist: "Pedro Infante", year: 1948 },
  { title: "Cucurrucucú Paloma", artist: "Lola Beltrán", year: 1954 },

  // --- Rock latino / Argentina ---
  { title: "Un Ángel para tu Soledad", artist: "Fito Páez", year: 1994 },
  { title: "11 y 6", artist: "Fito Páez", year: 1985 },
  { title: "Ya Nada Volverá a Ser Igual", artist: "Fito Páez", year: 2011 },
  { title: "Rezo por Vos", artist: "Charly García & Luis Alberto Spinetta", year: 1985 },
  { title: "Los Dinosaurios", artist: "Charly García", year: 1983 },
  { title: "Demoliendo Hoteles", artist: "Charly García", year: 1984 },
  { title: "Muchacha (Ojos de Papel)", artist: "Luis Alberto Spinetta", year: 1969 },
  { title: "Bajan", artist: "Divididos", year: 1993 },
  { title: "El Arriero", artist: "Divididos", year: 1993 },
  { title: "Se Viene", artist: "Bersuit Vergarabat", year: 2000 },
  { title: "Sr. Cobranza", artist: "Bersuit Vergarabat", year: 1998 },
  { title: "Irresponsables", artist: "Babasónicos", year: 2001 },
  { title: "Deléctrico", artist: "Babasónicos", year: 2001 },
  { title: "Ji Ji Ji", artist: "Los Fabulosos Cadillacs", year: 1997 },
  { title: "El Genio del Dub", artist: "Los Fabulosos Cadillacs", year: 1992 },
  { title: "Sobredosis de TV", artist: "Soda Stereo", year: 1986 },
  { title: "En la Ciudad de la Furia", artist: "Soda Stereo", year: 1988 },
  { title: "Té para Tres", artist: "Soda Stereo", year: 1985 },
  { title: "Zona de Promesas", artist: "Soda Stereo", year: 1990 },
  { title: "Adiós", artist: "Gustavo Cerati", year: 2006 },
  { title: "Puente", artist: "Gustavo Cerati", year: 1999 },
  { title: "Crimen", artist: "Gustavo Cerati", year: 2002 },
  { title: "Verano del '92", artist: "Guasones", year: 1997 },
  { title: "Ella Vino", artist: "Los Enanitos Verdes", year: 1994 },
  { title: "Lady Blue", artist: "Los Enanitos Verdes", year: 1994 },
  { title: "Tu Cárcel", artist: "Los Enanitos Verdes", year: 1994 },
  { title: "Rock del Gato", artist: "Fito Páez", year: 1984 },
  { title: "Un Buen Día", artist: "La Vela Puerca", year: 2003 },
  { title: "A Redoblar", artist: "La Vela Puerca", year: 2004 },
  { title: "Es Por Vos", artist: "Turf", year: 2000 },
  { title: "Que Sea Rock", artist: "Turf", year: 2001 },
  { title: "Ella Es Así", artist: "Attaque 77", year: 1996 },
  { title: "Hacelo por Mí", artist: "Attaque 77", year: 1993 },

  // --- Chile ---
  { title: "El Duelo", artist: "La Ley", year: 1995 },
  { title: "Mentira", artist: "La Ley", year: 1998 },
  { title: "Tren al Sur", artist: "Los Prisioneros", year: 1990 },
  { title: "El Baile de los Que Sobran", artist: "Los Prisioneros", year: 1986 },
  { title: "Muevete", artist: "Los Prisioneros", year: 1986 },
  { title: "Latinoamérica", artist: "Calle 13", year: 2010 },
  { title: "Atrévete-te-te", artist: "Calle 13", year: 2005 },
  { title: "Pa'l Norte", artist: "Calle 13 ft. Orishas", year: 2007 },

  // --- Colombia ---
  { title: "Te Mando Flores", artist: "Fonseca ft. Andrés Cepeda", year: 2013 },
  { title: "Eres Mi Sueño", artist: "Fonseca", year: 2005 },
  { title: "Sentir", artist: "Fonseca", year: 2007 },
  { title: "Voy a Extrañarte", artist: "Andrés Cepeda", year: 2005 },
  { title: "Lo Que Somos", artist: "Andrés Cepeda", year: 2007 },
  { title: "Fruta Fresca", artist: "Carlos Vives", year: 1995 },
  { title: "La Gota Fría", artist: "Carlos Vives", year: 1993 },
  { title: "Pa' Mayte", artist: "Carlos Vives", year: 1994 },
  { title: "Volví a Nacer", artist: "Carlos Vives", year: 2010 },

  // --- Reggaeton / Latin pop contemporáneo ---
  { title: "Rakata", artist: "Wisin y Yandel", year: 2005 },
  { title: "Pam Pam", artist: "Wisin y Yandel ft. Los Vaqueros", year: 2011 },
  { title: "Sexy Movimiento", artist: "Wisin y Yandel", year: 2007 },
  { title: "Loba (feat.)", artist: "Wisin y Yandel", year: 2009 },
  { title: "Loco", artist: "Tego Calderón", year: 2003 },
  { title: "Pa' Que Retozen", artist: "Tego Calderón", year: 2002 },
  { title: "Guaya Guaya", artist: "Don Omar", year: 2003 },
  { title: "Reggaetón Latino", artist: "Don Omar", year: 2004 },
  { title: "Pobre Diabla", artist: "Don Omar", year: 2003 },
  { title: "El Amante", artist: "Nicky Jam", year: 2017 },
  { title: "Travesuras", artist: "Nicky Jam", year: 2014 },
  { title: "Hasta el Amanecer", artist: "Nicky Jam", year: 2016 },
  { title: "X (Equis)", artist: "Nicky Jam & J Balvin", year: 2018 },
  { title: "Pepas", artist: "Farruko", year: 2021 },
  { title: "Krippy Kush", artist: "Farruko", year: 2017 },
  { title: "Obsesionado", artist: "Farruko", year: 2018 },
  { title: "Adictiva", artist: "Daddy Yankee ft. Anuel AA", year: 2019 },
  { title: "Shaky Shaky", artist: "Daddy Yankee", year: 2016 },
  { title: "Limbo", artist: "Daddy Yankee", year: 2011 },
  { title: "Rompe", artist: "Daddy Yankee", year: 2004 },
  { title: "El Amante", artist: "Anuel AA", year: 2018 },
  { title: "Ella Quiere Beber", artist: "Anuel AA", year: 2016 },
  { title: "Secreto", artist: "Anuel AA & Karol G", year: 2019 },
  { title: "Bichota", artist: "Karol G", year: 2020 },
  { title: "Mi Cama", artist: "Karol G", year: 2017 },
  { title: "Ahora Me Llama", artist: "Karol G & Bad Bunny", year: 2017 },
  { title: "199 Millas", artist: "Karol G", year: 2021 },
  { title: "Culpables", artist: "Karol G & Anuel AA", year: 2018 },
  { title: "Otro Trago", artist: "Sech ft. Darell", year: 2020 },
  { title: "Relación", artist: "Sech", year: 2019 },
  { title: "Baila Baila Baila", artist: "Ozuna", year: 2019 },
  { title: "Se Preparó", artist: "Ozuna", year: 2018 },
  { title: "Criminal", artist: "Ozuna ft. Natti Natasha", year: 2018 },
  { title: "Vaina Loca", artist: "Ozuna & Manuel Turizo", year: 2018 },
  { title: "Sin Pijama", artist: "Becky G & Natti Natasha", year: 2018 },
  { title: "Mayores", artist: "Becky G ft. Bad Bunny", year: 2017 },
  { title: "Sola", artist: "Anuel AA, Daddy Yankee, Wisin, Ozuna, J Balvin", year: 2019 },
  { title: "No Es Justo", artist: "J Balvin & Zion & Lennox", year: 2016 },
  { title: "6 AM", artist: "J Balvin ft. Farruko", year: 2015 },
  { title: "Machika", artist: "J Balvin, Jeon, Anitta", year: 2018 },
  { title: "Rojo", artist: "J Balvin", year: 2019 },
  { title: "Reggaetón", artist: "J Balvin", year: 2020 },
  { title: "Safaera", artist: "Bad Bunny, Jowell y Randy, Ñengo Flow", year: 2020 },
  { title: "Callaita", artist: "Bad Bunny", year: 2019 },
  { title: "Vete", artist: "Bad Bunny", year: 2019 },
  { title: "La Difícil", artist: "Bad Bunny", year: 2020 },
  { title: "Booker T", artist: "Bad Bunny", year: 2020 },
  { title: "Un Verano Sin Ti", artist: "Bad Bunny", year: 2022 },
  { title: "Tití Me Preguntó (single ver.)", artist: "Bad Bunny", year: 2022 },
  { title: "Ojitos Lindos", artist: "Bad Bunny ft. Bomba Estéreo", year: 2022 },
  { title: "Moscow Mule", artist: "Bad Bunny", year: 2022 },

  // --- Pop latino contemporáneo ---
  { title: "Amigos No Más", artist: "Sebastián Yatra", year: 2018 },
  { title: "Traicionera", artist: "Sebastián Yatra", year: 2017 },
  { title: "Robarte un Beso", artist: "Carlos Vives & Sebastián Yatra", year: 2017 },
  { title: "No Bailes Sola", artist: "Sebastián Yatra ft. Danny Ocean & Manuel Turizo", year: 2018 },
  { title: "Reggaetón Lento (Bailemos)", artist: "CNCO", year: 2016 },
  { title: "Se Vuelve Loca", artist: "CNCO", year: 2017 },
  { title: "Quisiera", artist: "CNCO", year: 2016 },
  { title: "Yo Te Esperaré", artist: "Morat", year: 2016 },
  { title: "Cómo Te Atreves", artist: "Morat", year: 2016 },
  { title: "Besos en Guerra", artist: "Morat & Juanes", year: 2018 },
  { title: "600 Noches", artist: "Morat", year: 2018 },
  { title: "Sabes", artist: "Morat", year: 2017 },
  { title: "TQ", artist: "Danna Paola", year: 2019 },
  { title: "Sodio", artist: "Danna Paola", year: 2020 },
  { title: "Mala Fama", artist: "Danna Paola", year: 2019 },
  { title: "Contigo", artist: "Kany García", year: 2021 },
  { title: "Alguien", artist: "Kany García", year: 2010 },
  { title: "Para Siempre", artist: "Vicente Fernández", year: 2003 },
  { title: "Estos Celos", artist: "Vicente Fernández", year: 1998 },
  { title: "Aunque Me Duela el Alma", artist: "Vicente Fernández", year: 1994 },
  { title: "Hermoso Cariño", artist: "Vicente Fernández", year: 1980 },
  { title: "Un Millón de Primaveras", artist: "Vicente Fernández", year: 2005 },
  { title: "Volcán", artist: "José José", year: 1978 },
  { title: "Gavilán o Paloma", artist: "José José", year: 1972 },
  { title: "El Príncipe", artist: "José José", year: 1985 },
  { title: "Amnesia", artist: "José José", year: 1996 },
  { title: "No Basta", artist: "José José", year: 1985 },

  // --- Bachata / Merengue extra ---
  { title: "El Farsante", artist: "Ozuna & Romeo Santos", year: 2018 },
  { title: "Yo También", artist: "Romeo Santos ft. Marc Anthony", year: 2011 },
  { title: "Que Se Muera Sola", artist: "Romeo Santos", year: 2014 },
  { title: "Inocente", artist: "Romeo Santos", year: 2011 },
  { title: "Eres Mía", artist: "Romeo Santos", year: 2014 },
  { title: "Suerte", artist: "Shakira", year: 2001 },
  { title: "Antología", artist: "Shakira", year: 1998 },
  { title: "Ojos Así", artist: "Shakira", year: 1998 },
  { title: "Ciega, Sordomuda", artist: "Shakira", year: 1998 },
  { title: "Estoy Aquí", artist: "Shakira", year: 1996 },
  { title: "Pies Descalzos, Sueños Blancos", artist: "Shakira", year: 1995 },
  { title: "Te Aviso, Te Anuncio (Tango)", artist: "Shakira", year: 1998 },
  { title: "Inevitable", artist: "Shakira", year: 1998 },
  { title: "No Creo", artist: "Shakira ft. Ozuna", year: 2019 },
  { title: "Me Enamoré", artist: "Shakira", year: 2017 },
  { title: "Perro Fiel", artist: "Shakira ft. Nicky Jam", year: 2017 },
  { title: "Girl Like Me", artist: "Shakira & Black Eyed Peas", year: 2020 },

  // --- Salsa clásica extra ---
  { title: "Anacaona", artist: "Cheo Feliciano", year: 1971 },
  { title: "El Ratón", artist: "Cheo Feliciano", year: 1975 },
  { title: "Que Se Sepa", artist: "Gilberto Santa Rosa", year: 1993 },
  { title: "Perdóname", artist: "Gilberto Santa Rosa", year: 1998 },
  { title: "Conciencia", artist: "Gilberto Santa Rosa", year: 1997 },
  { title: "Vivir Lo Nuestro", artist: "Marc Anthony & La India", year: 1997 },
  { title: "Se Me Sigue Olvidando", artist: "La India", year: 1997 },
  { title: "Ese Hombre", artist: "La India", year: 1994 },
  { title: "Llorarás", artist: "Oscar D'León", year: 1975 },
  { title: "Detalles", artist: "Oscar D'León", year: 1976 },
  { title: "Periódico de Ayer", artist: "Héctor Lavoe", year: 1976 },
  { title: "Todo Tiene Su Final", artist: "Héctor Lavoe", year: 1975 },
  { title: "Mi Gente", artist: "Héctor Lavoe", year: 1975 },
  { title: "Rebelión", artist: "Joe Arroyo", year: 1986 },
  { title: "En Barranquilla Me Quedo", artist: "Joe Arroyo", year: 1993 },
  { title: "Mi Libertad", artist: "Joe Arroyo", year: 1998 },

  // --- Flamenco / España pop extra ---
  { title: "Entre Dos Aguas", artist: "Paco de Lucía", year: 1976 },
  { title: "Camarón", artist: "Camarón de la Isla", year: 1979 },
  { title: "Volando Voy", artist: "Camarón de la Isla", year: 1979 },
  { title: "Como el Agua", artist: "Camarón de la Isla", year: 1981 },
  { title: "La Leyenda del Tiempo", artist: "Camarón de la Isla", year: 1979 },
  { title: "Rosas", artist: "La Oreja de Van Gogh", year: 2003 },
  { title: "Puedes Contar Conmigo", artist: "La Oreja de Van Gogh", year: 2003 },
  { title: "20 de Enero", artist: "La Oreja de Van Gogh", year: 1998 },
  { title: "Cuídate", artist: "La Oreja de Van Gogh", year: 2003 },
  { title: "No Es Lo Mismo", artist: "Alejandro Sanz", year: 2003 },
  { title: "Mi Soledad y Yo", artist: "Alejandro Sanz", year: 2003 },
  { title: "Y Solo Se Me Ocurre Amarte", artist: "Alejandro Sanz & Shakira", year: 2005 },
  { title: "Looking for Paradise", artist: "Alejandro Sanz ft. Alicia Keys", year: 2012 },
  { title: "El Trato", artist: "Alejandro Sanz", year: 2019 },
  { title: "Lo Que Fui Es Lo Que Soy", artist: "Alejandro Sanz", year: 2015 },
  { title: "Pongamos que Hablo de Madrid", artist: "Joaquín Sabina", year: 1994 },
  { title: "Princesa", artist: "Joaquín Sabina", year: 1992 },
  { title: "Contigo", artist: "Ana Belén & Víctor Manuel", year: 1988 },
  { title: "Solo le Pido a Dios", artist: "Ana Belén", year: 1979 },
  { title: "La Puerta de Alcalá", artist: "Ana Belén, Víctor Manuel, Miguel Ríos", year: 1986 },
  { title: "Bienvenidos", artist: "Miguel Ríos", year: 1982 },
  { title: "El Rock de la Cárcel", artist: "Miguel Ríos", year: 1966 },
  { title: "Escríbeme", artist: "David Bisbal", year: 2002 },
  { title: "Bulería", artist: "David Bisbal", year: 2002 },
  { title: "Ave María", artist: "David Bisbal", year: 2005 },
  { title: "Digale", artist: "David Bisbal", year: 2004 },
  { title: "Corazón Sin Cara", artist: "Prince Royce", year: 2010 },
  { title: "Stand by Me (Spanish ver.)", artist: "Prince Royce", year: 2010 },
  { title: "Darte un Beso", artist: "Prince Royce", year: 2013 },
  { title: "Culpa al Corazón", artist: "Prince Royce", year: 2013 },
  { title: "El Amor Que Perdimos", artist: "Prince Royce", year: 2012 },
];
