// songs/es.js — מאגר שירים בספרדית (ללא youtubeId — ניגון בחיפוש אוטומטי).
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.es = [
  { title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", year: 2017 },
  { title: "Bailando", artist: "Enrique Iglesias", year: 2014 },
  { title: "Bailamos", artist: "Enrique Iglesias", year: 1999 },
  { title: "Hero", artist: "Enrique Iglesias", year: 2001 },
  { title: "Vivir Mi Vida", artist: "Marc Anthony", year: 2013 },
  { title: "Y Tú Te Vas", artist: "Chayanne", year: 2003 },
  { title: "Torero", artist: "Chayanne", year: 2002 },
  { title: "Waka Waka (Esto Es África)", artist: "Shakira", year: 2010 },
  { title: "Hips Don't Lie", artist: "Shakira", year: 2005 },
  { title: "Whenever, Wherever", artist: "Shakira", year: 2001 },
  { title: "La Tortura", artist: "Shakira ft. Alejandro Sanz", year: 2005 },
  { title: "Corazón Partío", artist: "Alejandro Sanz", year: 1997 },
  { title: "La Camisa Negra", artist: "Juanes", year: 2004 },
  { title: "A Dios le Pido", artist: "Juanes", year: 2002 },
  { title: "Provenza", artist: "Karol G", year: 2022 },
  { title: "Tusa", artist: "Karol G ft. Nicki Minaj", year: 2019 },
  { title: "Con Altura", artist: "Rosalía ft. J Balvin", year: 2019 },
  { title: "Malamente", artist: "Rosalía", year: 2018 },
  { title: "Mi Gente", artist: "J Balvin", year: 2017 },
  { title: "Ginza", artist: "J Balvin", year: 2015 },
  { title: "Danza Kuduro", artist: "Don Omar ft. Lucenzo", year: 2010 },
  { title: "Bailar", artist: "Deorro ft. Elvis Crespo", year: 2015 },
  { title: "Gasolina", artist: "Daddy Yankee", year: 2004 },
  { title: "Con Calma", artist: "Daddy Yankee ft. Snow", year: 2019 },
  { title: "Vivir Sin Aire", artist: "Maná", year: 1992 },
  { title: "Rayando el Sol", artist: "Maná", year: 1990 },
  { title: "Corazón Espinado", artist: "Santana ft. Maná", year: 1999 },
  { title: "Oye Como Va", artist: "Santana", year: 1970 },
  { title: "Smooth", artist: "Santana ft. Rob Thomas", year: 1999 },
  { title: "La Bamba", artist: "Ritchie Valens", year: 1958 },
  { title: "Livin' la Vida Loca", artist: "Ricky Martin", year: 1999 },
  { title: "La Copa de la Vida", artist: "Ricky Martin", year: 1998 },
  { title: "María", artist: "Ricky Martin", year: 1995 },
  { title: "Amor Prohibido", artist: "Selena", year: 1994 },
  { title: "Como la Flor", artist: "Selena", year: 1992 },
  { title: "Bidi Bidi Bom Bom", artist: "Selena", year: 1994 },
  { title: "Volare", artist: "Gipsy Kings", year: 1989 },
  { title: "Bamboléo", artist: "Gipsy Kings", year: 1987 },
  { title: "Macarena", artist: "Los del Río", year: 1993 },
  { title: "Suavemente", artist: "Elvis Crespo", year: 1998 },
  { title: "Obsesión", artist: "Aventura", year: 2002 },
  { title: "Propuesta Indecente", artist: "Romeo Santos", year: 2013 },
  { title: "Odio", artist: "Romeo Santos ft. Drake", year: 2019 },
  { title: "Loba", artist: "Shakira", year: 2009 },
  { title: "Chantaje", artist: "Shakira ft. Maluma", year: 2016 },
  { title: "Felices los 4", artist: "Maluma", year: 2017 },
  { title: "Hawái", artist: "Maluma", year: 2020 },
  { title: "Vente Pa' Ca", artist: "Ricky Martin ft. Maluma", year: 2016 },
  { title: "Despacito (remix)", artist: "Luis Fonsi ft. Justin Bieber", year: 2017 },
  { title: "El Perdón", artist: "Nicky Jam & Enrique Iglesias", year: 2015 },
  { title: "Ay Vamos", artist: "J Balvin", year: 2014 },
  { title: "Tu Foto", artist: "Ozuna", year: 2017 },
  { title: "Taki Taki", artist: "DJ Snake ft. Ozuna, Cardi B, Selena Gomez", year: 2018 },
  { title: "Dákiti", artist: "Bad Bunny ft. Jhay Cortez", year: 2020 },
  { title: "Yo Perreo Sola", artist: "Bad Bunny", year: 2020 },
  { title: "Titi Me Preguntó", artist: "Bad Bunny", year: 2022 },
  { title: "Me Porto Bonito", artist: "Bad Bunny ft. Chencho Corleone", year: 2022 },
  { title: "China", artist: "Anuel AA, Daddy Yankee, Karol G, Ozuna, J Balvin", year: 2019 },
  { title: "Échame la Culpa", artist: "Luis Fonsi & Demi Lovato", year: 2017 },
  { title: "Duele el Corazón", artist: "Enrique Iglesias ft. Wisin", year: 2016 },
  { title: "Súbeme la Radio", artist: "Enrique Iglesias ft. Descemer Bueno", year: 2017 },
  { title: "Amorfoda", artist: "Bad Bunny", year: 2017 },
  { title: "La Bicicleta", artist: "Carlos Vives & Shakira", year: 2016 },
  { title: "La Bilirrubina", artist: "Juan Luis Guerra", year: 1990 },
  { title: "Ojalá Que Llueva Café", artist: "Juan Luis Guerra", year: 1989 },
  { title: "Burbujas de Amor", artist: "Juan Luis Guerra", year: 1990 },
  { title: "Color Esperanza", artist: "Diego Torres", year: 2001 },
  { title: "Tal Vez", artist: "Ricky Martin", year: 2003 },
  { title: "Bella", artist: "Ricardo Arjona", year: 1996 },
  { title: "Historia de Taxi", artist: "Ricardo Arjona", year: 1994 },
  { title: "Volver a Empezar", artist: "Alejandro Sanz", year: 2019 },
  { title: "Amiga Mía", artist: "Alejandro Sanz", year: 1997 },
  { title: "El Triste", artist: "José José", year: 1970 },
  { title: "Resistiré", artist: "Dúo Dinámico", year: 1988 },
  { title: "Pedro Navaja", artist: "Rubén Blades", year: 1978 },
  { title: "Aguanile", artist: "Héctor Lavoe", year: 1978 },
  { title: "El Cantante", artist: "Héctor Lavoe", year: 1978 },
  { title: "Idilio", artist: "Willie Colón & Héctor Lavoe", year: 1976 },
  { title: "Vivir Mi Vida (salsa)", artist: "Marc Anthony", year: 2013 },
  { title: "Preciosa", artist: "Marc Anthony", year: 1999 },
  { title: "Valió la Pena", artist: "Marc Anthony", year: 2004 },
  { title: "Bachata Rosa", artist: "Juan Luis Guerra", year: 1990 },
  { title: "El Wanabí", artist: "Chimbala", year: 2017 },
  { title: "Baila Esta Cumbia", artist: "Selena", year: 1990 },
  { title: "Cielito Lindo", artist: "Trío Los Panchos", year: 1950 },
  { title: "Bésame Mucho", artist: "Consuelo Velázquez", year: 1940 },
  { title: "Guantanamera", artist: "Celia Cruz", year: 1966 },
  { title: "La Vida Es Un Carnaval", artist: "Celia Cruz", year: 1998 },
  { title: "Quimbara", artist: "Celia Cruz", year: 1974 },
  { title: "Vivir Mi Vida es de Celia Cruz Original", artist: "Celia Cruz", year: 1998 },
  { title: "Rayito de Luna", artist: "Los Panchos", year: 1948 },
  { title: "Amor Eterno", artist: "Juan Gabriel", year: 1984 },
  { title: "Querida", artist: "Juan Gabriel", year: 1984 },
  { title: "El Noa Noa", artist: "Juan Gabriel", year: 1976 },
  { title: "Cielo Rojo", artist: "Los Ángeles Negros", year: 1969 },
  { title: "Y Nos Dieron las Diez", artist: "Joaquín Sabina", year: 1994 },
  { title: "19 Días y 500 Noches", artist: "Joaquín Sabina", year: 1999 },
  { title: "Contigo Aprendí", artist: "Armando Manzanero", year: 1967 },
  { title: "No Culpes a la Noche", artist: "Armando Manzanero", year: 1970 },
  { title: "Clavado en un Bar", artist: "Maná", year: 1995 },
  { title: "Oye Mi Amor", artist: "Maná", year: 1995 },
  { title: "En El Muelle de San Blas", artist: "Maná", year: 1997 },
  { title: "Labios Compartidos", artist: "Maná", year: 2006 },
  { title: "De Música Ligera", artist: "Soda Stereo", year: 1990 },
  { title: "Persiana Americana", artist: "Soda Stereo", year: 1986 },
  { title: "Prófugos", artist: "Soda Stereo", year: 1987 },
  { title: "Cuando Pase el Temblor", artist: "Soda Stereo", year: 1985 },
  { title: "Matador", artist: "Los Fabulosos Cadillacs", year: 1993 },
  { title: "Mal Bicho", artist: "Los Fabulosos Cadillacs", year: 1989 },
  { title: "Un Beso y Una Flor", artist: "Nino Bravo", year: 1972 },
  { title: "Libre", artist: "Nino Bravo", year: 1972 },
  { title: "América", artist: "Nino Bravo", year: 1971 },
  { title: "Y Como Es Él", artist: "José Luis Perales", year: 1982 },
  { title: "Ella", artist: "José José", year: 1990 },
  { title: "Amar y Vivir", artist: "Vicente Fernández", year: 1990 },
  { title: "El Rey", artist: "Vicente Fernández", year: 1971 },
  { title: "Volver, Volver", artist: "Vicente Fernández", year: 1972 },
  { title: "Cielito Lindo (mariachi)", artist: "Pedro Infante", year: 1953 },
  { title: "Amorcito Corazón", artist: "Pedro Infante", year: 1948 },
  { title: "Cucurrucucú Paloma", artist: "Lola Beltrán", year: 1954 },
];
