// songs/fr.js — מאגר שירים בצרפתית (ללא youtubeId — ניגון בחיפוש אוטומטי).
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.fr = [
  { title: "Non, je ne regrette rien", artist: "Édith Piaf", year: 1960 },
  { title: "La Vie en Rose", artist: "Édith Piaf", year: 1946 },
  { title: "Milord", artist: "Édith Piaf", year: 1959 },
  { title: "L'Hymne à l'Amour", artist: "Édith Piaf", year: 1949 },
  { title: "Ne Me Quitte Pas", artist: "Jacques Brel", year: 1959 },
  { title: "Quand On N'a Que L'Amour", artist: "Jacques Brel", year: 1957 },
  { title: "La Bohème", artist: "Charles Aznavour", year: 1965 },
  { title: "Emmenez-moi", artist: "Charles Aznavour", year: 1967 },
  { title: "Comme d'habitude", artist: "Claude François", year: 1967 },
  { title: "Alexandrie Alexandra", artist: "Claude François", year: 1978 },
  { title: "Aline", artist: "Christophe", year: 1965 },
  { title: "Les Champs-Élysées", artist: "Joe Dassin", year: 1969 },
  { title: "L'Été indien", artist: "Joe Dassin", year: 1975 },
  { title: "Salut les amoureux", artist: "Joe Dassin", year: 1973 },
  { title: "Je m'appelle Hélène", artist: "Hélène Rollès", year: 1993 },
  { title: "Formidable", artist: "Stromae", year: 2013 },
  { title: "Alors on danse", artist: "Stromae", year: 2009 },
  { title: "Papaoutai", artist: "Stromae", year: 2013 },
  { title: "Tous les mêmes", artist: "Stromae", year: 2013 },
  { title: "Je veux", artist: "Zaz", year: 2010 },
  { title: "On ira", artist: "Zaz", year: 2010 },
  { title: "Dernière Danse", artist: "Indila", year: 2014 },
  { title: "Tourner dans le vide", artist: "Indila", year: 2015 },
  { title: "Djadja", artist: "Aya Nakamura", year: 2018 },
  { title: "Pookie", artist: "Aya Nakamura", year: 2019 },
  { title: "Copines", artist: "Aya Nakamura", year: 2018 },
  { title: "Dernier Domicile Connu", artist: "IAM", year: 1997 },
  { title: "Je Danse le Mia", artist: "IAM", year: 1993 },
  { title: "La Boulette", artist: "Diam's", year: 2006 },
  { title: "Suzy", artist: "Diam's", year: 2003 },
  { title: "Aicha", artist: "Khaled", year: 1996 },
  { title: "Didi", artist: "Khaled", year: 1992 },
  { title: "Joe le Taxi", artist: "Vanessa Paradis", year: 1987 },
  { title: "Tandem", artist: "Vanessa Paradis", year: 1990 },
  { title: "Désenchantée", artist: "Mylène Farmer", year: 1991 },
  { title: "Sans Contrefaçon", artist: "Mylène Farmer", year: 1987 },
  { title: "Libertine", artist: "Mylène Farmer", year: 1986 },
  { title: "Ella, elle l'a", artist: "France Gall", year: 1987 },
  { title: "Résiste", artist: "France Gall", year: 1981 },
  { title: "Poupée de cire, poupée de son", artist: "France Gall", year: 1965 },
  { title: "Comme toi", artist: "Jean-Jacques Goldman", year: 1982 },
  { title: "Envole-moi", artist: "Jean-Jacques Goldman", year: 1984 },
  { title: "Il changeait la vie", artist: "Jean-Jacques Goldman", year: 1987 },
  { title: "Star's", artist: "Jean-Jacques Goldman", year: 1987 },
  { title: "L'Aziza", artist: "Daniel Balavoine", year: 1985 },
  { title: "Je ne suis pas un héros", artist: "Daniel Balavoine", year: 1980 },
  { title: "Foule Sentimentale", artist: "Alain Souchon", year: 1993 },
  { title: "Sous le vent", artist: "Garou & Céline Dion", year: 2001 },
  { title: "Belle", artist: "Garou, Daniel Lavoie, Patrick Fiori", year: 1998 },
  { title: "L'Amour est Bleu", artist: "Vicky Leandros", year: 1967 },
  { title: "Je t'aime... moi non plus", artist: "Serge Gainsbourg", year: 1969 },
  { title: "Le Poinçonneur des Lilas", artist: "Serge Gainsbourg", year: 1958 },
  { title: "La Javanaise", artist: "Serge Gainsbourg", year: 1963 },
  { title: "Harley Davidson", artist: "Serge Gainsbourg & Brigitte Bardot", year: 1968 },
  { title: "Chandelier de Cristal", artist: "Michel Sardou", year: 1976 },
  { title: "La Maladie d'Amour", artist: "Michel Sardou", year: 1973 },
  { title: "Les Lacs du Connemara", artist: "Michel Sardou", year: 1981 },
  { title: "Vivre", artist: "Michel Sardou", year: 1974 },
  { title: "Toute la musique que j'aime", artist: "Johnny Hallyday", year: 1985 },
  { title: "Que je t'aime", artist: "Johnny Hallyday", year: 1969 },
  { title: "Allumer le feu", artist: "Johnny Hallyday", year: 1998 },
  { title: "Requiem pour un fou", artist: "Johnny Hallyday", year: 1977 },
  { title: "L'Envie d'Aimer", artist: "Daniel Lévi", year: 1998 },
  { title: "Le Temps des Cathédrales", artist: "Bruno Pelletier", year: 1998 },
  { title: "Vivo Per Lei (version FR: Je Vis Pour Elle)", artist: "Hélène Ségara", year: 1998 },
  { title: "On Ecrit Sur Les Murs", artist: "Kids United", year: 2015 },
  { title: "Little Big Man", artist: "Kids United", year: 2016 },
  { title: "Manhattan-Kaboul", artist: "Renaud & Axelle Red", year: 2002 },
  { title: "Mistral Gagnant", artist: "Renaud", year: 1985 },
  { title: "Dès que le vent soufflera", artist: "Renaud", year: 1983 },
  { title: "Sensualité", artist: "Axelle Red", year: 1993 },
  { title: "Voilà", artist: "Barbara Pravi", year: 2021 },
  { title: "J'ai Cherché", artist: "Amir", year: 2016 },
  { title: "On Va S'Aimer", artist: "Kendji Girac", year: 2014 },
  { title: "Andalouse", artist: "Kendji Girac", year: 2014 },
  { title: "Color Gitano", artist: "Kendji Girac", year: 2015 },
  { title: "Freed From Desire (Marina)", artist: "Marina", year: 2016 },
  { title: "Dommage", artist: "Bigflo & Oli", year: 2017 },
  { title: "Alors on Change", artist: "Bigflo & Oli", year: 2015 },
  { title: "La Grenade", artist: "Clara Luciani", year: 2018 },
  { title: "Respire Encore", artist: "Clara Luciani", year: 2021 },
  { title: "Balance ton quoi", artist: "Angèle", year: 2018 },
  { title: "Tout Oublier", artist: "Angèle ft. Roméo Elvis", year: 2018 },
  { title: "Ta Reine", artist: "Angèle", year: 2019 },
  { title: "Bella Ciao (version française)", artist: "Maître Gims, Vitaa, Slimane, Dadju, Naestro", year: 2018 },
  { title: "Sapés Comme Jamais", artist: "Maître Gims ft. Niska", year: 2015 },
  { title: "Bella", artist: "Maître Gims", year: 2013 },
  { title: "J'me Tire", artist: "Maître Gims", year: 2013 },
  { title: "On Sait", artist: "Naps", year: 2019 },
  { title: "Elle Me Dit", artist: "Mika", year: 2012 },
  { title: "Grace Kelly", artist: "Mika", year: 2007 },
  { title: "Que Reste-t-il de Nos Amours ?", artist: "Charles Trenet", year: 1942 },
  { title: "La Mer", artist: "Charles Trenet", year: 1946 },
  { title: "Douce France", artist: "Charles Trenet", year: 1947 },
  { title: "Les Feuilles Mortes", artist: "Yves Montand", year: 1946 },
  { title: "C'est Si Bon", artist: "Yves Montand", year: 1950 },
  { title: "À Bicyclette", artist: "Yves Montand", year: 1968 },

  // --- Variété française classique ---
  { title: "Ma Préférence", artist: "Julien Clerc", year: 1978 },
  { title: "Femmes... Je Vous Aime", artist: "Julien Clerc", year: 1982 },
  { title: "Ce N'est Rien", artist: "Julien Clerc", year: 1972 },
  { title: "Cœur de Rocker", artist: "Julien Clerc", year: 1983 },
  { title: "Le Sud", artist: "Nino Ferrer", year: 1975 },
  { title: "Mirza", artist: "Nino Ferrer", year: 1965 },
  { title: "La Maison Près de la Fontaine", artist: "Nino Ferrer", year: 1969 },
  { title: "Les Mots Bleus", artist: "Christophe", year: 1974 },
  { title: "Les Paradis Perdus", artist: "Christophe", year: 1973 },
  { title: "Manureva", artist: "Alain Chamfort", year: 1979 },
  { title: "Bambou", artist: "Alain Chamfort", year: 1978 },
  { title: "Il Est Cinq Heures, Paris S'éveille", artist: "Jacques Dutronc", year: 1968 },
  { title: "Et Moi, Et Moi, Et Moi", artist: "Jacques Dutronc", year: 1966 },
  { title: "Les Cactus", artist: "Jacques Dutronc", year: 1966 },
  { title: "L'Opportuniste", artist: "Jacques Dutronc", year: 1968 },
  { title: "Comment Te Dire Adieu", artist: "Françoise Hardy", year: 1968 },
  { title: "Tous les Garçons et les Filles", artist: "Françoise Hardy", year: 1962 },
  { title: "Le Temps de l'Amour", artist: "Françoise Hardy", year: 1962 },
  { title: "Message Personnel", artist: "Françoise Hardy", year: 1973 },
  { title: "Laisse Tomber les Filles", artist: "France Gall", year: 1964 },
  { title: "Sacré Charlemagne", artist: "France Gall", year: 1964 },
  { title: "Musique", artist: "France Gall", year: 1988 },
  { title: "Diego, Libre dans sa Tête", artist: "France Gall", year: 1980 },
  { title: "Chanson pour Elle", artist: "Yves Duteil", year: 1985 },
  { title: "La Langue de Chez Nous", artist: "Yves Duteil", year: 1985 },
  { title: "Prendre un Enfant", artist: "Yves Duteil", year: 1977 },
  { title: "Fais-Moi une Place", artist: "Julien Clerc", year: 1990 },
  { title: "Le Chanteur", artist: "Daniel Balavoine", year: 1978 },
  { title: "Sauver l'Amour", artist: "Daniel Balavoine", year: 1985 },
  { title: "Mon Fils, Ma Bataille", artist: "Daniel Balavoine", year: 1980 },
  { title: "Vivre ou Survivre", artist: "Daniel Balavoine", year: 1979 },
  { title: "La Chanson des Vieux Amants", artist: "Jacques Brel", year: 1967 },
  { title: "Amsterdam", artist: "Jacques Brel", year: 1964 },
  { title: "Le Plat Pays", artist: "Jacques Brel", year: 1962 },
  { title: "Vesoul", artist: "Jacques Brel", year: 1968 },
  { title: "Ces Gens-Là", artist: "Jacques Brel", year: 1966 },
  { title: "Le Moribond", artist: "Jacques Brel", year: 1961 },
  { title: "Rosa", artist: "Jacques Brel", year: 1962 },
  { title: "For Me Formidable", artist: "Charles Aznavour", year: 1963 },
  { title: "Les Comédiens", artist: "Charles Aznavour", year: 1962 },
  { title: "Que C'est Triste Venise", artist: "Charles Aznavour", year: 1964 },
  { title: "Tu Te Laisses Aller", artist: "Charles Aznavour", year: 1960 },
  { title: "Hier Encore", artist: "Charles Aznavour", year: 1964 },
  { title: "Mon Amant de Saint-Jean", artist: "Patrick Bruel", year: 1993 },
  { title: "Casser la Voix", artist: "Patrick Bruel", year: 1989 },
  { title: "Alors Regarde", artist: "Patrick Bruel", year: 1989 },
  { title: "Qui a le Droit", artist: "Patrick Bruel", year: 1990 },
  { title: "Pour la Vie", artist: "Patrick Bruel", year: 1999 },
  { title: "Marcher au Soleil", artist: "Patrick Bruel", year: 1995 },

  // --- Rap / R&B français ---
  { title: "Nique la Police", artist: "NTM", year: 1993 },
  { title: "Laisse Pas Traîner Ton Fils", artist: "NTM", year: 1998 },
  { title: "Ma Benz", artist: "NTM", year: 1998 },
  { title: "Tonton du Bled", artist: "113", year: 1999 },
  { title: "Les Princes de la Ville", artist: "113", year: 1999 },
  { title: "Marly-Gomont", artist: "Kamini", year: 2006 },
  { title: "Ma Direction", artist: "Sinik", year: 2006 },
  { title: "Fais Pas l'Autiste", artist: "Sniper", year: 2003 },
  { title: "Gamin de Paris", artist: "Sniper", year: 2004 },
  { title: "Petite Sœur", artist: "Youssoupha", year: 2012 },
  { title: "Dreamin'", artist: "Booba", year: 2002 },
  { title: "Boulbi", artist: "Booba", year: 2006 },
  { title: "OKLM", artist: "Booba", year: 2016 },
  { title: "Validé", artist: "Booba", year: 2019 },
  { title: "DKR", artist: "Booba", year: 2015 },
  { title: "Peur de Rien", artist: "Kaaris", year: 2013 },
  { title: "Zoo", artist: "Kaaris", year: 2013 },
  { title: "J'suis Qu'une Sale Pute", artist: "Diam's", year: 2003 },
  { title: "Ma France à Moi", artist: "Diam's", year: 2006 },
  { title: "Confessions Nocturnes", artist: "Diam's", year: 2006 },
  { title: "Jeune Demoiselle", artist: "Diam's", year: 2006 },
  { title: "Bavarder", artist: "SDM", year: 2020 },
  { title: "Freeze Corleone 667", artist: "Freeze Corleone", year: 2019 },
  { title: "Rentre chez Toi", artist: "PNL", year: 2015 },
  { title: "Au DD", artist: "PNL", year: 2016 },
  { title: "Onizuka", artist: "PNL", year: 2016 },
  { title: "Naha", artist: "PNL", year: 2019 },
  { title: "Bené", artist: "PNL", year: 2019 },
  { title: "J'aurais Aimé", artist: "Damso", year: 2016 },
  { title: "Macarena", artist: "Damso", year: 2017 },
  { title: "Silence", artist: "Damso", year: 2016 },
  { title: "Ipséité", artist: "Damso", year: 2017 },
  { title: "La Puissance", artist: "Damso", year: 2020 },
  { title: "Bad", artist: "Niska", year: 2018 },
  { title: "Réseaux", artist: "Niska", year: 2016 },
  { title: "Elle Me Contrôle", artist: "Franglish", year: 2016 },
  { title: "Comme Ci Comme Ça", artist: "Franglish ft. Dadju", year: 2017 },
  { title: "Reine", artist: "Dadju", year: 2018 },
  { title: "Jaloux", artist: "Dadju", year: 2018 },
  { title: "Mafuzzy Style", artist: "Dadju", year: 2016 },
  { title: "Petrouchka", artist: "Dadju ft. MHD", year: 2018 },
  { title: "AFRO TRAP Part.3", artist: "MHD", year: 2016 },
  { title: "Bon Anniversaire", artist: "MHD", year: 2018 },
  { title: "Fais le Mouv'", artist: "MHD", year: 2016 },
  { title: "Petit Frère", artist: "Ninho", year: 2019 },
  { title: "Lettre à une Femme", artist: "Ninho", year: 2018 },
  { title: "Jefe", artist: "Ninho ft. Niska", year: 2018 },

  // --- Pop / électro français contemporain ---
  { title: "One More Time", artist: "Daft Punk", year: 2000 },
  { title: "Get Lucky", artist: "Daft Punk ft. Pharrell Williams", year: 2013 },
  { title: "Harder, Better, Faster, Stronger", artist: "Daft Punk", year: 2001 },
  { title: "Around the World", artist: "Daft Punk", year: 1997 },
  { title: "Instant Crush", artist: "Daft Punk ft. Julian Casablancas", year: 2013 },
  { title: "Music Sounds Better with You", artist: "Stardust", year: 1998 },
  { title: "Sexy Boy", artist: "Air", year: 1998 },
  { title: "La Femme d'Argent", artist: "Air", year: 1998 },
  { title: "Cléopâtre", artist: "Indochine", year: 1981 },
  { title: "L'Aventurier", artist: "Indochine", year: 1982 },
  { title: "3ème Sexe", artist: "Indochine", year: 1985 },
  { title: "J'ai Demandé à la Lune", artist: "Indochine", year: 2002 },
  { title: "Le Grand Secret", artist: "Indochine", year: 2005 },
  { title: "Un Jour Dans Notre Vie", artist: "Indochine", year: 2013 },
  { title: "Vertige de l'Amour", artist: "Alain Bashung", year: 1980 },
  { title: "Gaby Oh Gaby", artist: "Alain Bashung", year: 1980 },
  { title: "Osez Joséphine", artist: "Alain Bashung", year: 1991 },
  { title: "La Nuit Je Mens", artist: "Alain Bashung", year: 1998 },
  { title: "Ma Petite Entreprise", artist: "Alain Bashung", year: 1998 },
  { title: "Sur la Route", artist: "Marc Lavoine", year: 2002 },
  { title: "Elle a les Yeux Revolver", artist: "Marc Lavoine", year: 1985 },
  { title: "Le Parking des Anges", artist: "Marc Lavoine", year: 2011 },
  { title: "Paris", artist: "Marc Lavoine ft. Zaho", year: 2010 },

  // --- Pop / Nouvelle Génération ---
  { title: "Fever", artist: "Angèle & Dua Lipa", year: 2019 },
  { title: "Flou", artist: "Angèle", year: 2019 },
  { title: "Solo", artist: "Clara Luciani", year: 2017 },
  { title: "Ne Rien Dire", artist: "Clara Luciani", year: 2018 },
  { title: "Bon Anniversaire (Clara)", artist: "Clara Luciani", year: 2021 },
  { title: "L'Antidote", artist: "Vitaa", year: 2006 },
  { title: "Dis-moi Que Tu M'aimes", artist: "Vitaa", year: 2006 },
  { title: "À Fleur de Toi", artist: "Vitaa & Slimane", year: 2019 },
  { title: "Ça Va, Ça Vient", artist: "Vitaa & Slimane", year: 2019 },
  { title: "Rien Qu'une Fois", artist: "Slimane", year: 2016 },
  { title: "Paname", artist: "Slimane", year: 2016 },
  { title: "Viens On S'aime", artist: "Slimane", year: 2018 },
  { title: "Mon Amour", artist: "Slimane", year: 2019 },
  { title: "Elle Danse Seule", artist: "Julien Doré", year: 2013 },
  { title: "Paris-Seychelles", artist: "Julien Doré", year: 2008 },
  { title: "La Fille aux Bas Nylon", artist: "Julien Doré", year: 2011 },
  { title: "Coco Câline", artist: "Julien Doré", year: 2013 },
  { title: "Nu", artist: "Julien Doré", year: 2016 },
  { title: "L'Amour en Solitaire", artist: "Jeanne Added", year: 2015 },
  { title: "Carmen", artist: "Stromae", year: 2015 },
  { title: "Ta Fête", artist: "Stromae", year: 2013 },
  { title: "L'Enfer", artist: "Stromae", year: 2022 },
  { title: "Santé", artist: "Stromae", year: 2022 },

  // --- Chanson française classique ---
  { title: "Les Copains d'Abord", artist: "Georges Brassens", year: 1964 },
  { title: "La Mauvaise Réputation", artist: "Georges Brassens", year: 1952 },
  { title: "Le Gorille", artist: "Georges Brassens", year: 1952 },
  { title: "Chanson pour l'Auvergnat", artist: "Georges Brassens", year: 1954 },
  { title: "Les Sabots d'Hélène", artist: "Georges Brassens", year: 1954 },
  { title: "Supplique pour Être Enterré à la Plage de Sète", artist: "Georges Brassens", year: 1966 },
  { title: "Avec le Temps", artist: "Léo Ferré", year: 1971 },
  { title: "C'est Extra", artist: "Léo Ferré", year: 1969 },
  { title: "Paris Canaille", artist: "Léo Ferré", year: 1954 },
  { title: "L'Aigle Noir", artist: "Barbara", year: 1970 },
  { title: "Dis, Quand Reviendras-tu?", artist: "Barbara", year: 1964 },
  { title: "Göttingen", artist: "Barbara", year: 1964 },
  { title: "Nantes", artist: "Barbara", year: 1964 },
  { title: "Ma Plus Belle Histoire d'Amour", artist: "Barbara", year: 1967 },
  { title: "Le Petit Vin Blanc", artist: "Lina Margy", year: 1943 },
  { title: "Toi le Venin", artist: "Serge Reggiani", year: 1971 },
  { title: "Le Petit Garçon", artist: "Serge Reggiani", year: 1971 },
  { title: "Ma Fille", artist: "Serge Reggiani", year: 1971 },
  { title: "L'Italien", artist: "Serge Reggiani", year: 1968 },
  { title: "Fais-Moi une Fleur", artist: "Michel Delpech", year: 1972 },
  { title: "Wight Is Wight", artist: "Michel Delpech", year: 1969 },
  { title: "Le Loir-et-Cher", artist: "Michel Delpech", year: 1973 },
  { title: "Pour un Flirt", artist: "Michel Delpech", year: 1971 },
  { title: "Les Divorcés", artist: "Michel Delpech", year: 1973 },
  { title: "Qu'est-ce Qu'on Attend Pour Être Heureux", artist: "Michel Delpech", year: 1971 },

  // --- Yé-yé / années 60-70 ---
  { title: "La Plus Belle Pour Aller Danser", artist: "Sylvie Vartan", year: 1964 },
  { title: "Comme un Garçon", artist: "Sylvie Vartan", year: 1967 },
  { title: "Nicolas", artist: "Sylvie Vartan", year: 1965 },
  { title: "Bang Bang", artist: "Sheila", year: 1966 },
  { title: "L'École Est Finie", artist: "Sheila", year: 1963 },
  { title: "Petite Fille de Français Moyen", artist: "Sheila", year: 1975 },
  { title: "Les Elucubrations d'Antoine", artist: "Antoine", year: 1966 },
  { title: "Am Stram Gram", artist: "Antoine", year: 1968 },
  { title: "La Poupée qui Fait Non", artist: "Michel Polnareff", year: 1966 },
  { title: "Love Me, Please Love Me", artist: "Michel Polnareff", year: 1966 },
  { title: "On Ira Tous au Paradis", artist: "Michel Polnareff", year: 1972 },
  { title: "Je Suis un Homme", artist: "Michel Polnareff", year: 1981 },
  { title: "Bambino", artist: "Dalida", year: 1956 },
  { title: "Il Venait d'Avoir 18 Ans", artist: "Dalida", year: 1973 },
  { title: "Gigi l'Amoroso", artist: "Dalida", year: 1974 },
  { title: "Paroles, Paroles", artist: "Dalida & Alain Delon", year: 1973 },
  { title: "Salma Ya Salama", artist: "Dalida", year: 1977 },
  { title: "J'attendrai", artist: "Dalida", year: 1975 },
  { title: "Génération", artist: "Étienne Daho", year: 1994 },
  { title: "Duel au Soleil", artist: "Étienne Daho", year: 1986 },
  { title: "Week-end à Rome", artist: "Étienne Daho", year: 1986 },
  { title: "Tombé pour la France", artist: "Étienne Daho", year: 1981 },

  // --- Pop contemporaine française ---
  { title: "On S'Attache", artist: "Christophe Maé", year: 2007 },
  { title: "Il Est où le Bonheur", artist: "Christophe Maé", year: 2010 },
  { title: "Belle Demoiselle", artist: "Christophe Maé", year: 2013 },
  { title: "Dingue, Dingue, Dingue", artist: "Christophe Maé", year: 2007 },
  { title: "L'Éternité", artist: "Christophe Maé", year: 2018 },
  { title: "On Se Ressemble Trop", artist: "Christophe Maé", year: 2010 },
  { title: "Je Te Le Donne", artist: "Vianney", year: 2014 },
  { title: "Pas Là", artist: "Vianney", year: 2015 },
  { title: "Idées Blanches", artist: "Vianney", year: 2018 },
  { title: "Beau Bizarre", artist: "Vianney ft. Gaëtan Roussel", year: 2021 },
  { title: "Le Portrait", artist: "Vianney", year: 2014 },
  { title: "Riez, Riez", artist: "Louane", year: 2015 },
  { title: "Jour 1", artist: "Louane", year: 2015 },
  { title: "Avenir", artist: "Louane", year: 2015 },
  { title: "On Était Beau", artist: "Louane", year: 2018 },
  { title: "Emmenez-moi Danser", artist: "Louane", year: 2019 },
  { title: "Derrière les Fagots", artist: "Grand Corps Malade", year: 2006 },
  { title: "Roméo Kiffe Juliette", artist: "Grand Corps Malade", year: 2010 },
  { title: "Midi 20", artist: "Grand Corps Malade", year: 2006 },
  { title: "Mesdames", artist: "Grand Corps Malade", year: 2008 },
  { title: "Enfant de la Ville", artist: "Grand Corps Malade & Camille Lellouche", year: 2020 },
  { title: "As-tu Déjà Aimé", artist: "Soprano", year: 2018 },
  { title: "Fresh Prince", artist: "Soprano", year: 2018 },
  { title: "Cosmo", artist: "Soprano", year: 2013 },
  { title: "Roule", artist: "Soprano", year: 2018 },
  { title: "Célestine", artist: "Soprano", year: 2018 },
  { title: "Victoire", artist: "Soprano", year: 2016 },
  { title: "Millionnaire", artist: "Soprano ft. Leto", year: 2018 },
  { title: "Africa Sarab", artist: "Soprano", year: 2010 },

  // --- Électro / dance français ---
  { title: "D.A.N.C.E.", artist: "Justice", year: 2007 },
  { title: "Genesis", artist: "Justice", year: 2007 },
  { title: "We Are Your Friends", artist: "Justice vs. Simian", year: 2006 },
  { title: "Love Generation", artist: "Bob Sinclar", year: 2005 },
  { title: "World, Hold On", artist: "Bob Sinclar", year: 2006 },
  { title: "Rock This Party", artist: "Bob Sinclar", year: 2006 },
  { title: "Flowers", artist: "Bob Sinclar", year: 2004 },
  { title: "Sound of Freedom", artist: "Bob Sinclar", year: 2012 },
  { title: "Alive", artist: "David Guetta ft. Kelly Rowland", year: 2007 },
  { title: "Love Is Gone", artist: "David Guetta & Chris Willis", year: 2007 },
  { title: "When Love Takes Over", artist: "David Guetta ft. Kelly Rowland", year: 2009 },
  { title: "Sexy Bitch", artist: "David Guetta ft. Akon", year: 2009 },
  { title: "Memories", artist: "David Guetta ft. Kid Cudi", year: 2010 },
  { title: "Turn Me On", artist: "David Guetta ft. Nicki Minaj", year: 2012 },
  { title: "Waiting for Love", artist: "Avicii", year: 2015 },

  // --- Rap français contemporain ---
  { title: "Basique", artist: "Orelsan", year: 2017 },
  { title: "La Terre Est Ronde", artist: "Orelsan", year: 2017 },
  { title: "Défaite de Fauve", artist: "Orelsan", year: 2011 },
  { title: "Suicide Social", artist: "Orelsan", year: 2009 },
  { title: "Ils Sont Cools", artist: "Orelsan", year: 2021 },
  { title: "L'Odeur de l'Essence", artist: "Orelsan", year: 2021 },
  { title: "On Verra", artist: "Nekfeu", year: 2015 },
  { title: "Egérie", artist: "Nekfeu", year: 2015 },
  { title: "Tempo", artist: "Nekfeu", year: 2016 },
  { title: "Le Bruit de la Ville", artist: "Georgio", year: 2015 },
  { title: "Coup de Vieux", artist: "Georgio", year: 2015 },
  { title: "1000°C", artist: "Lomepal", year: 2017 },
  { title: "Trop Beau", artist: "Lomepal", year: 2017 },
  { title: "Yeux Disent", artist: "Lomepal", year: 2020 },
  { title: "Flip", artist: "Lomepal", year: 2020 },
  { title: "Wesh Alors", artist: "Lomepal", year: 2017 },
  { title: "La Fête Est Finie", artist: "Lomepal", year: 2020 },
  { title: "Rentrer chez Moi", artist: "Camélia Jordana", year: 2013 },
  { title: "Non Non Non", artist: "Camélia Jordana", year: 2010 },

  // --- Eurovision / variété récente ---
  { title: "L'Oiseau et l'Enfant", artist: "Marie Myriam", year: 1977 },
  { title: "Un Premier Amour", artist: "Sandrine François", year: 2002 },
  { title: "À Chaque Pas", artist: "Sébastien Tellier", year: 2008 },
  { title: "Divine Idylle", artist: "Sébastien Tellier", year: 2004 },
  { title: "N'oubliez Jamais", artist: "Amaury Vassili", year: 2011 },
  { title: "Mon Alliée", artist: "Alma", year: 2017 },
  { title: "Requiem", artist: "Alma", year: 2017 },
  { title: "Fresh", artist: "Barbara Pravi", year: 2022 },

  // --- Enfance / fêtes ---
  { title: "Petit Papa Noël", artist: "Tino Rossi", year: 1946 },
  { title: "Vive le Vent", artist: "Traditionnel", year: 1956 },
  { title: "Au Clair de la Lune", artist: "Traditionnel", year: 1780 },
  { title: "Sur le Pont d'Avignon", artist: "Traditionnel", year: 1503 },
  { title: "Frère Jacques", artist: "Traditionnel", year: 1780 },
  { title: "Il Court, Il Court, le Furet", artist: "Traditionnel", year: 1826 },

  // --- Chanteurs et groupes additionnels ---
  { title: "Le Chat", artist: "Zazie", year: 1993 },
  { title: "Homme Sweet Homme", artist: "Zazie", year: 1998 },
  { title: "Je Suis un Homme", artist: "Zazie", year: 1998 },
  { title: "Tout le Monde", artist: "Zazie", year: 2001 },
  { title: "Rue de la Paix", artist: "Zazie", year: 2004 },
  { title: "Chanteur", artist: "Marc Lavoine ft. Zazie", year: 1998 },
  { title: "Fous à Lier", artist: "Renaud & Axelle Red", year: 2002 },
  { title: "Marche à l'Ombre", artist: "Renaud", year: 1980 },
  { title: "Hexagone", artist: "Renaud", year: 1975 },
  { title: "Laisse Béton", artist: "Renaud", year: 1977 },
  { title: "Morgane de Toi", artist: "Renaud", year: 1983 },
  { title: "Miss Maggie", artist: "Renaud", year: 1985 },
  { title: "Ma Gonzesse", artist: "Renaud", year: 1979 },
  { title: "Chanson pour Pierrot", artist: "Renaud", year: 1980 },
  { title: "Manu", artist: "Renaud", year: 1985 },
  { title: "En Cloque", artist: "Renaud", year: 1988 },
  { title: "P'tite Conne", artist: "Renaud", year: 1980 },
  { title: "Bienvenue chez Moi", artist: "Roch Voisine", year: 1992 },
  { title: "Hélène", artist: "Roch Voisine", year: 1989 },
  { title: "Pays d'Plaine", artist: "Roch Voisine", year: 1993 },
  { title: "La Rivière Artificielle", artist: "Roch Voisine", year: 1994 },
  { title: "Belle Île en Mer, Marie-Galante", artist: "Laurent Voulzy", year: 1985 },
  { title: "Rockollection", artist: "Laurent Voulzy", year: 1977 },
  { title: "Le Cœur Grenadine", artist: "Laurent Voulzy", year: 1979 },
  { title: "Bubble Star", artist: "Laurent Voulzy", year: 1987 },
  { title: "Désir, Désir", artist: "Laurent Voulzy", year: 1984 },
  { title: "Chanson sur une Drôle de Vie", artist: "William Sheller", year: 1975 },
  { title: "Un Homme Heureux", artist: "William Sheller", year: 1975 },
  { title: "Rock'n Dollars", artist: "William Sheller", year: 1979 },
  { title: "Photos de Vacances", artist: "William Sheller", year: 1979 },
  { title: "Il Jouait du Piano Debout", artist: "France Gall", year: 1980 },
  { title: "Évidemment", artist: "France Gall", year: 1988 },
  { title: "Débranche", artist: "France Gall", year: 1984 },
  { title: "Cézanne Peint", artist: "France Gall", year: 1987 },
  { title: "Pense à Moi", artist: "Julien Clerc", year: 1993 },
  { title: "Utile", artist: "Julien Clerc", year: 2004 },
  { title: "Melissa", artist: "Julien Clerc", year: 1984 },
  { title: "Si On Chantait", artist: "Julien Clerc", year: 1976 },
  { title: "La Cavalerie", artist: "Julien Clerc", year: 1971 },
  { title: "Femmes des Années 80", artist: "Jean Schultheis", year: 1982 },
  { title: "Confidence pour Confidence", artist: "Jean Schultheis", year: 1982 },
  { title: "Il Est 5 Heures, Rome S'Éveille", artist: "Étienne Daho", year: 1986 },
  { title: "Le Grand Sommeil", artist: "Étienne Daho", year: 1984 },
  { title: "Kiss Me", artist: "C. Jérôme", year: 1975 },
  { title: "Poupée de Cire, Poupée de Chiffon", artist: "Nino Ferrer", year: 1965 },
  { title: "Le Téléfon", artist: "Nino Ferrer", year: 1968 },
  { title: "Complainte des Filles de Joie", artist: "Georges Brassens", year: 1961 },
  { title: "Il N'y a Pas d'Amour Heureux", artist: "Georges Brassens", year: 1953 },
  { title: "Les Amoureux des Bancs Publics", artist: "Georges Brassens", year: 1954 },
  { title: "Le Parapluie", artist: "Georges Brassens", year: 1953 },
  { title: "Auprès de Mon Arbre", artist: "Georges Brassens", year: 1957 },
  { title: "Brave Margot", artist: "Georges Brassens", year: 1953 },
  { title: "Le Petit Cheval", artist: "Georges Brassens", year: 1952 },
  { title: "La Non-Demande en Mariage", artist: "Georges Brassens", year: 1966 },
  { title: "Chez Laurette", artist: "Michel Delpech", year: 1973 },
  { title: "Le Chasseur", artist: "Michel Delpech", year: 1974 },
  { title: "Que Marianne Était Jolie", artist: "Michel Delpech", year: 1975 },
  { title: "Le Facteur", artist: "Michel Delpech", year: 1969 },
  { title: "Rendez-vous au Restaurant", artist: "Michel Fugain", year: 1976 },
  { title: "Une Belle Histoire", artist: "Michel Fugain", year: 1972 },
  { title: "Fais Comme l'Oiseau", artist: "Michel Fugain", year: 1974 },
  { title: "Bravo, Tu As Gagné", artist: "Michel Fugain", year: 1976 },
  { title: "Attention Mesdames et Messieurs", artist: "Michel Fugain", year: 1972 },
  { title: "Chante-la Ta Peine", artist: "Michel Fugain", year: 1979 },
  { title: "Souvenirs, Souvenirs (Halliday)", artist: "Johnny Hallyday", year: 1960 },
  { title: "Retiens la Nuit", artist: "Johnny Hallyday", year: 1962 },
  { title: "L'Envie", artist: "Johnny Hallyday", year: 1993 },
  { title: "Sang pour Sang", artist: "Johnny Hallyday", year: 1999 },
  { title: "Ma Gueule", artist: "Johnny Hallyday", year: 1979 },
  { title: "Le Pénitencier", artist: "Johnny Hallyday", year: 1964 },
  { title: "Noir C'est Noir", artist: "Johnny Hallyday", year: 1966 },
  { title: "Cheveux Longs et Idées Courtes", artist: "Johnny Hallyday", year: 1966 },
  { title: "Gabrielle", artist: "Johnny Hallyday", year: 1976 },
  { title: "Vivre pour le Meilleur", artist: "Johnny Hallyday", year: 1994 },
  { title: "L'Idole des Jeunes", artist: "Johnny Hallyday", year: 1962 },
  { title: "Marie", artist: "Johnny Hallyday", year: 1970 },
  { title: "Pour Me Comprendre", artist: "Johnny Hallyday", year: 1971 },

  // --- Rap / R&B additionnel ---
  { title: "Petite Sœur, Grand Frère", artist: "Youssoupha", year: 2015 },
  { title: "On the Corner", artist: "Youssoupha", year: 2015 },
  { title: "Négritude", artist: "Youssoupha ft. Ayna Shox", year: 2015 },
  { title: "La Puissance (Vald)", artist: "Vald", year: 2015 },
  { title: "Xanax", artist: "Vald", year: 2018 },
  { title: "Coma Idyllique", artist: "Vald", year: 2019 },
  { title: "Deux Frères", artist: "PNL", year: 2019 },
  { title: "Blanka", artist: "PNL", year: 2019 },
  { title: "Que la Famille", artist: "PNL", year: 2019 },
  { title: "Autobahn", artist: "Kaaris", year: 2016 },
  { title: "Or Noir", artist: "Kaaris", year: 2013 },
  { title: "Tchoin", artist: "Jul & DJ Yaniss", year: 2016 },
  { title: "Wesh Alors (Jul)", artist: "Jul", year: 2015 },
  { title: "Bande Organisée", artist: "Jul, SCH, Kofs & others", year: 2020 },
  { title: "Je Ne Me Casse Pas", artist: "Jul", year: 2015 },
  { title: "La Zone", artist: "Jul", year: 2019 },
  { title: "Le Blanc", artist: "SCH", year: 2019 },
  { title: "Otto", artist: "SCH", year: 2017 },
  { title: "Fusil", artist: "SCH", year: 2016 },
  { title: "Champs-Élysées (SCH)", artist: "SCH", year: 2019 },
  { title: "Autobahn (Gazo)", artist: "Gazo", year: 2021 },
  { title: "Belek", artist: "Gazo", year: 2022 },
  { title: "Drill FR", artist: "Gazo", year: 2021 },
  { title: "Freeze Corleone Interlude", artist: "Freeze Corleone", year: 2020 },
  { title: "NGRD", artist: "Freeze Corleone", year: 2020 },
  { title: "Euros en Cash", artist: "Freeze Corleone", year: 2020 },
  { title: "3 Sœurs", artist: "Alonzo", year: 2016 },
  { title: "Bandana", artist: "Alonzo", year: 2017 },
  { title: "Meilleure Ennemie", artist: "Alonzo ft. Tayc", year: 2020 },
  { title: "Petite Sirène", artist: "Alonzo", year: 2018 },
];
