// songs/fr.js — מאגר שירים בצרפתית (ללא youtubeId — ניגון בחיפוש אוטומטי).
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.fr = [
  { title: "Non, je ne regrette rien", artist: "Édith Piaf", year: 1960 },
  { title: "La Vie en Rose", artist: "Édith Piaf", year: 1946 },
  { title: "Milord", artist: "Édith Piaf", year: 1959 },
  { title: "L'Hymne à l'Amour", artist: "Édith Piaf", year: 1949 },
  { title: "Ne Me Quitte Pas", artist: "Jacques Brel", year: 1959 },
  { title: "Quand On N'a Que L'Amour", artist: "Jacques Brel", year: 1957 },
  { title: "La Bohème", artist: "Charles Aznavour", year: 1965 },
  { title: "Emmenez-moi", artist: "Charles Aznavour", year: 1967 },
  { title: "Comme d'habitude", artist: "Claude François", year: 1967 },
  { title: "Alexandrie Alexandra", artist: "Claude François", year: 1978 },
  { title: "Aline", artist: "Christophe", year: 1965 },
  { title: "Les Champs-Élysées", artist: "Joe Dassin", year: 1969 },
  { title: "L'Été indien", artist: "Joe Dassin", year: 1975 },
  { title: "Salut les amoureux", artist: "Joe Dassin", year: 1973 },
  { title: "Je m'appelle Hélène", artist: "Hélène Rollès", year: 1993 },
  { title: "Formidable", artist: "Stromae", year: 2013 },
  { title: "Alors on danse", artist: "Stromae", year: 2009 },
  { title: "Papaoutai", artist: "Stromae", year: 2013 },
  { title: "Tous les mêmes", artist: "Stromae", year: 2013 },
  { title: "Je veux", artist: "Zaz", year: 2010 },
  { title: "On ira", artist: "Zaz", year: 2010 },
  { title: "Dernière Danse", artist: "Indila", year: 2014 },
  { title: "Tourner dans le vide", artist: "Indila", year: 2015 },
  { title: "Djadja", artist: "Aya Nakamura", year: 2018 },
  { title: "Pookie", artist: "Aya Nakamura", year: 2019 },
  { title: "Copines", artist: "Aya Nakamura", year: 2018 },
  { title: "Dernier Domicile Connu", artist: "IAM", year: 1997 },
  { title: "Je Danse le Mia", artist: "IAM", year: 1993 },
  { title: "La Boulette", artist: "Diam's", year: 2006 },
  { title: "Suzy", artist: "Diam's", year: 2003 },
  { title: "Aicha", artist: "Khaled", year: 1996 },
  { title: "Didi", artist: "Khaled", year: 1992 },
  { title: "Joe le Taxi", artist: "Vanessa Paradis", year: 1987 },
  { title: "Tandem", artist: "Vanessa Paradis", year: 1990 },
  { title: "Désenchantée", artist: "Mylène Farmer", year: 1991 },
  { title: "Sans Contrefaçon", artist: "Mylène Farmer", year: 1987 },
  { title: "Libertine", artist: "Mylène Farmer", year: 1986 },
  { title: "Ella, elle l'a", artist: "France Gall", year: 1987 },
  { title: "Résiste", artist: "France Gall", year: 1981 },
  { title: "Poupée de cire, poupée de son", artist: "France Gall", year: 1965 },
  { title: "Comme toi", artist: "Jean-Jacques Goldman", year: 1982 },
  { title: "Envole-moi", artist: "Jean-Jacques Goldman", year: 1984 },
  { title: "Il changeait la vie", artist: "Jean-Jacques Goldman", year: 1987 },
  { title: "Star's", artist: "Jean-Jacques Goldman", year: 1987 },
  { title: "L'Aziza", artist: "Daniel Balavoine", year: 1985 },
  { title: "Je ne suis pas un héros", artist: "Daniel Balavoine", year: 1980 },
  { title: "Foule Sentimentale", artist: "Alain Souchon", year: 1993 },
  { title: "Sous le vent", artist: "Garou & Céline Dion", year: 2001 },
  { title: "Belle", artist: "Garou, Daniel Lavoie, Patrick Fiori", year: 1998 },
  { title: "L'Amour est Bleu", artist: "Vicky Leandros", year: 1967 },
  { title: "Je t'aime... moi non plus", artist: "Serge Gainsbourg", year: 1969 },
  { title: "Le Poinçonneur des Lilas", artist: "Serge Gainsbourg", year: 1958 },
  { title: "La Javanaise", artist: "Serge Gainsbourg", year: 1963 },
  { title: "Harley Davidson", artist: "Serge Gainsbourg & Brigitte Bardot", year: 1968 },
  { title: "Chandelier de Cristal", artist: "Michel Sardou", year: 1976 },
  { title: "La Maladie d'Amour", artist: "Michel Sardou", year: 1973 },
  { title: "Les Lacs du Connemara", artist: "Michel Sardou", year: 1981 },
  { title: "Vivre", artist: "Michel Sardou", year: 1974 },
  { title: "Toute la musique que j'aime", artist: "Johnny Hallyday", year: 1985 },
  { title: "Que je t'aime", artist: "Johnny Hallyday", year: 1969 },
  { title: "Allumer le feu", artist: "Johnny Hallyday", year: 1998 },
  { title: "Requiem pour un fou", artist: "Johnny Hallyday", year: 1977 },
  { title: "L'Envie d'Aimer", artist: "Daniel Lévi", year: 1998 },
  { title: "Le Temps des Cathédrales", artist: "Bruno Pelletier", year: 1998 },
  { title: "Vivo Per Lei (version FR: Je Vis Pour Elle)", artist: "Hélène Ségara", year: 1998 },
  { title: "On Ecrit Sur Les Murs", artist: "Kids United", year: 2015 },
  { title: "Little Big Man", artist: "Kids United", year: 2016 },
  { title: "Manhattan-Kaboul", artist: "Renaud & Axelle Red", year: 2002 },
  { title: "Mistral Gagnant", artist: "Renaud", year: 1985 },
  { title: "Dès que le vent soufflera", artist: "Renaud", year: 1983 },
  { title: "Sensualité", artist: "Axelle Red", year: 1993 },
  { title: "Voilà", artist: "Barbara Pravi", year: 2021 },
  { title: "J'ai Cherché", artist: "Amir", year: 2016 },
  { title: "On Va S'Aimer", artist: "Kendji Girac", year: 2014 },
  { title: "Andalouse", artist: "Kendji Girac", year: 2014 },
  { title: "Color Gitano", artist: "Kendji Girac", year: 2015 },
  { title: "Freed From Desire (Marina)", artist: "Marina", year: 2016 },
  { title: "Dommage", artist: "Bigflo & Oli", year: 2017 },
  { title: "Alors on Change", artist: "Bigflo & Oli", year: 2015 },
  { title: "La Grenade", artist: "Clara Luciani", year: 2018 },
  { title: "Respire Encore", artist: "Clara Luciani", year: 2021 },
  { title: "Balance ton quoi", artist: "Angèle", year: 2018 },
  { title: "Tout Oublier", artist: "Angèle ft. Roméo Elvis", year: 2018 },
  { title: "Ta Reine", artist: "Angèle", year: 2019 },
  { title: "Bella Ciao (version française)", artist: "Maître Gims, Vitaa, Slimane, Dadju, Naestro", year: 2018 },
  { title: "Sapés Comme Jamais", artist: "Maître Gims ft. Niska", year: 2015 },
  { title: "Bella", artist: "Maître Gims", year: 2013 },
  { title: "J'me Tire", artist: "Maître Gims", year: 2013 },
  { title: "On Sait", artist: "Naps", year: 2019 },
  { title: "Elle Me Dit", artist: "Mika", year: 2012 },
  { title: "Grace Kelly", artist: "Mika", year: 2007 },
  { title: "Que Reste-t-il de Nos Amours ?", artist: "Charles Trenet", year: 1942 },
  { title: "La Mer", artist: "Charles Trenet", year: 1946 },
  { title: "Douce France", artist: "Charles Trenet", year: 1947 },
  { title: "Les Feuilles Mortes", artist: "Yves Montand", year: 1946 },
  { title: "C'est Si Bon", artist: "Yves Montand", year: 1950 },
  { title: "À Bicyclette", artist: "Yves Montand", year: 1968 },

  // --- Variété française classique ---
  { title: "Ma Préférence", artist: "Julien Clerc", year: 1978 },
  { title: "Femmes... Je Vous Aime", artist: "Julien Clerc", year: 1982 },
  { title: "Ce N'est Rien", artist: "Julien Clerc", year: 1972 },
  { title: "Cœur de Rocker", artist: "Julien Clerc", year: 1983 },
  { title: "Le Sud", artist: "Nino Ferrer", year: 1975 },
  { title: "Mirza", artist: "Nino Ferrer", year: 1965 },
  { title: "La Maison Près de la Fontaine", artist: "Nino Ferrer", year: 1969 },
  { title: "Les Mots Bleus", artist: "Christophe", year: 1974 },
  { title: "Les Paradis Perdus", artist: "Christophe", year: 1973 },
  { title: "Manureva", artist: "Alain Chamfort", year: 1979 },
  { title: "Bambou", artist: "Alain Chamfort", year: 1978 },
  { title: "Il Est Cinq Heures, Paris S'éveille", artist: "Jacques Dutronc", year: 1968 },
  { title: "Et Moi, Et Moi, Et Moi", artist: "Jacques Dutronc", year: 1966 },
  { title: "Les Cactus", artist: "Jacques Dutronc", year: 1966 },
  { title: "L'Opportuniste", artist: "Jacques Dutronc", year: 1968 },
  { title: "Comment Te Dire Adieu", artist: "Françoise Hardy", year: 1968 },
  { title: "Tous les Garçons et les Filles", artist: "Françoise Hardy", year: 1962 },
  { title: "Le Temps de l'Amour", artist: "Françoise Hardy", year: 1962 },
  { title: "Message Personnel", artist: "Françoise Hardy", year: 1973 },
  { title: "Laisse Tomber les Filles", artist: "France Gall", year: 1964 },
  { title: "Sacré Charlemagne", artist: "France Gall", year: 1964 },
  { title: "Musique", artist: "France Gall", year: 1988 },
  { title: "Diego, Libre dans sa Tête", artist: "France Gall", year: 1980 },
  { title: "Chanson pour Elle", artist: "Yves Duteil", year: 1985 },
  { title: "La Langue de Chez Nous", artist: "Yves Duteil", year: 1985 },
  { title: "Prendre un Enfant", artist: "Yves Duteil", year: 1977 },
  { title: "Fais-Moi une Place", artist: "Julien Clerc", year: 1990 },
  { title: "Le Chanteur", artist: "Daniel Balavoine", year: 1978 },
  { title: "Sauver l'Amour", artist: "Daniel Balavoine", year: 1985 },
  { title: "Mon Fils, Ma Bataille", artist: "Daniel Balavoine", year: 1980 },
  { title: "Vivre ou Survivre", artist: "Daniel Balavoine", year: 1979 },
  { title: "La Chanson des Vieux Amants", artist: "Jacques Brel", year: 1967 },
  { title: "Amsterdam", artist: "Jacques Brel", year: 1964 },
  { title: "Le Plat Pays", artist: "Jacques Brel", year: 1962 },
  { title: "Vesoul", artist: "Jacques Brel", year: 1968 },
  { title: "Ces Gens-Là", artist: "Jacques Brel", year: 1966 },
  { title: "Le Moribond", artist: "Jacques Brel", year: 1961 },
  { title: "Rosa", artist: "Jacques Brel", year: 1962 },
  { title: "For Me Formidable", artist: "Charles Aznavour", year: 1963 },
  { title: "Les Comédiens", artist: "Charles Aznavour", year: 1962 },
  { title: "Que C'est Triste Venise", artist: "Charles Aznavour", year: 1964 },
  { title: "Tu Te Laisses Aller", artist: "Charles Aznavour", year: 1960 },
  { title: "Hier Encore", artist: "Charles Aznavour", year: 1964 },
  { title: "Mon Amant de Saint-Jean", artist: "Patrick Bruel", year: 1993 },
  { title: "Casser la Voix", artist: "Patrick Bruel", year: 1989 },
  { title: "Alors Regarde", artist: "Patrick Bruel", year: 1989 },
  { title: "Qui a le Droit", artist: "Patrick Bruel", year: 1990 },
  { title: "Pour la Vie", artist: "Patrick Bruel", year: 1999 },
  { title: "Marcher au Soleil", artist: "Patrick Bruel", year: 1995 },

  // --- Rap / R&B français ---
  { title: "Nique la Police", artist: "NTM", year: 1993 },
  { title: "Laisse Pas Traîner Ton Fils", artist: "NTM", year: 1998 },
  { title: "Ma Benz", artist: "NTM", year: 1998 },
  { title: "Tonton du Bled", artist: "113", year: 1999 },
  { title: "Les Princes de la Ville", artist: "113", year: 1999 },
  { title: "Marly-Gomont", artist: "Kamini", year: 2006 },
  { title: "Ma Direction", artist: "Sinik", year: 2006 },
  { title: "Fais Pas l'Autiste", artist: "Sniper", year: 2003 },
  { title: "Gamin de Paris", artist: "Sniper", year: 2004 },
  { title: "Petite Sœur", artist: "Youssoupha", year: 2012 },
  { title: "Dreamin'", artist: "Booba", year: 2002 },
  { title: "Boulbi", artist: "Booba", year: 2006 },
  { title: "OKLM", artist: "Booba", year: 2016 },
  { title: "Validé", artist: "Booba", year: 2019 },
  { title: "DKR", artist: "Booba", year: 2015 },
  { title: "Peur de Rien", artist: "Kaaris", year: 2013 },
  { title: "Zoo", artist: "Kaaris", year: 2013 },
  { title: "J'suis Qu'une Sale Pute", artist: "Diam's", year: 2003 },
  { title: "Ma France à Moi", artist: "Diam's", year: 2006 },
  { title: "Confessions Nocturnes", artist: "Diam's", year: 2006 },
  { title: "Jeune Demoiselle", artist: "Diam's", year: 2006 },
  { title: "Bavarder", artist: "SDM", year: 2020 },
  { title: "Freeze Corleone 667", artist: "Freeze Corleone", year: 2019 },
  { title: "Rentre chez Toi", artist: "PNL", year: 2015 },
  { title: "Au DD", artist: "PNL", year: 2016 },
  { title: "Onizuka", artist: "PNL", year: 2016 },
  { title: "Naha", artist: "PNL", year: 2019 },
  { title: "Bené", artist: "PNL", year: 2019 },
  { title: "J'aurais Aimé", artist: "Damso", year: 2016 },
  { title: "Macarena", artist: "Damso", year: 2017 },
  { title: "Silence", artist: "Damso", year: 2016 },
  { title: "Ipséité", artist: "Damso", year: 2017 },
  { title: "La Puissance", artist: "Damso", year: 2020 },
  { title: "Bad", artist: "Niska", year: 2018 },
  { title: "Réseaux", artist: "Niska", year: 2016 },
  { title: "Elle Me Contrôle", artist: "Franglish", year: 2016 },
  { title: "Comme Ci Comme Ça", artist: "Franglish ft. Dadju", year: 2017 },
  { title: "Reine", artist: "Dadju", year: 2018 },
  { title: "Jaloux", artist: "Dadju", year: 2018 },
  { title: "Mafuzzy Style", artist: "Dadju", year: 2016 },
  { title: "Petrouchka", artist: "Dadju ft. MHD", year: 2018 },
  { title: "AFRO TRAP Part.3", artist: "MHD", year: 2016 },
  { title: "Bon Anniversaire", artist: "MHD", year: 2018 },
  { title: "Fais le Mouv'", artist: "MHD", year: 2016 },
  { title: "Petit Frère", artist: "Ninho", year: 2019 },
  { title: "Lettre à une Femme", artist: "Ninho", year: 2018 },
  { title: "Jefe", artist: "Ninho ft. Niska", year: 2018 },

  // --- Pop / électro français contemporain ---
  { title: "One More Time", artist: "Daft Punk", year: 2000 },
  { title: "Get Lucky", artist: "Daft Punk ft. Pharrell Williams", year: 2013 },
  { title: "Harder, Better, Faster, Stronger", artist: "Daft Punk", year: 2001 },
  { title: "Around the World", artist: "Daft Punk", year: 1997 },
  { title: "Instant Crush", artist: "Daft Punk ft. Julian Casablancas", year: 2013 },
  { title: "Music Sounds Better with You", artist: "Stardust", year: 1998 },
  { title: "Sexy Boy", artist: "Air", year: 1998 },
  { title: "La Femme d'Argent", artist: "Air", year: 1998 },
  { title: "Cléopâtre", artist: "Indochine", year: 1981 },
  { title: "L'Aventurier", artist: "Indochine", year: 1982 },
  { title: "3ème Sexe", artist: "Indochine", year: 1985 },
  { title: "J'ai Demandé à la Lune", artist: "Indochine", year: 2002 },
  { title: "Le Grand Secret", artist: "Indochine", year: 2005 },
  { title: "Un Jour Dans Notre Vie", artist: "Indochine", year: 2013 },
  { title: "Vertige de l'Amour", artist: "Alain Bashung", year: 1980 },
  { title: "Gaby Oh Gaby", artist: "Alain Bashung", year: 1980 },
  { title: "Osez Joséphine", artist: "Alain Bashung", year: 1991 },
  { title: "La Nuit Je Mens", artist: "Alain Bashung", year: 1998 },
  { title: "Ma Petite Entreprise", artist: "Alain Bashung", year: 1998 },
  { title: "Sur la Route", artist: "Marc Lavoine", year: 2002 },
  { title: "Elle a les Yeux Revolver", artist: "Marc Lavoine", year: 1985 },
  { title: "Le Parking des Anges", artist: "Marc Lavoine", year: 2011 },
  { title: "Paris", artist: "Marc Lavoine ft. Zaho", year: 2010 },

  // --- Pop / Nouvelle Génération ---
  { title: "Fever", artist: "Angèle & Dua Lipa", year: 2019 },
  { title: "Flou", artist: "Angèle", year: 2019 },
  { title: "Solo", artist: "Clara Luciani", year: 2017 },
  { title: "Ne Rien Dire", artist: "Clara Luciani", year: 2018 },
  { title: "Bon Anniversaire (Clara)", artist: "Clara Luciani", year: 2021 },
  { title: "L'Antidote", artist: "Vitaa", year: 2006 },
  { title: "Dis-moi Que Tu M'aimes", artist: "Vitaa", year: 2006 },
  { title: "À Fleur de Toi", artist: "Vitaa & Slimane", year: 2019 },
  { title: "Ça Va, Ça Vient", artist: "Vitaa & Slimane", year: 2019 },
  { title: "Rien Qu'une Fois", artist: "Slimane", year: 2016 },
  { title: "Paname", artist: "Slimane", year: 2016 },
  { title: "Viens On S'aime", artist: "Slimane", year: 2018 },
  { title: "Mon Amour", artist: "Slimane", year: 2019 },
  { title: "Elle Danse Seule", artist: "Julien Doré", year: 2013 },
  { title: "Paris-Seychelles", artist: "Julien Doré", year: 2008 },
  { title: "La Fille aux Bas Nylon", artist: "Julien Doré", year: 2011 },
  { title: "Coco Câline", artist: "Julien Doré", year: 2013 },
  { title: "Nu", artist: "Julien Doré", year: 2016 },
  { title: "L'Amour en Solitaire", artist: "Jeanne Added", year: 2015 },
  { title: "Carmen", artist: "Stromae", year: 2015 },
  { title: "Ta Fête", artist: "Stromae", year: 2013 },
  { title: "L'Enfer", artist: "Stromae", year: 2022 },
  { title: "Santé", artist: "Stromae", year: 2022 },
];
