// songs/fr.js — מאגר שירים בצרפתית (ללא youtubeId — ניגון בחיפוש אוטומטי).
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.fr = [
  { title: "Non, je ne regrette rien", artist: "Édith Piaf", year: 1960 },
  { title: "La Vie en Rose", artist: "Édith Piaf", year: 1946 },
  { title: "Milord", artist: "Édith Piaf", year: 1959 },
  { title: "L'Hymne à l'Amour", artist: "Édith Piaf", year: 1949 },
  { title: "Ne Me Quitte Pas", artist: "Jacques Brel", year: 1959 },
  { title: "Quand On N'a Que L'Amour", artist: "Jacques Brel", year: 1957 },
  { title: "La Bohème", artist: "Charles Aznavour", year: 1965 },
  { title: "Emmenez-moi", artist: "Charles Aznavour", year: 1967 },
  { title: "Comme d'habitude", artist: "Claude François", year: 1967 },
  { title: "Alexandrie Alexandra", artist: "Claude François", year: 1978 },
  { title: "Aline", artist: "Christophe", year: 1965 },
  { title: "Les Champs-Élysées", artist: "Joe Dassin", year: 1969 },
  { title: "L'Été indien", artist: "Joe Dassin", year: 1975 },
  { title: "Salut les amoureux", artist: "Joe Dassin", year: 1973 },
  { title: "Je m'appelle Hélène", artist: "Hélène Rollès", year: 1993 },
  { title: "Formidable", artist: "Stromae", year: 2013 },
  { title: "Alors on danse", artist: "Stromae", year: 2009 },
  { title: "Papaoutai", artist: "Stromae", year: 2013 },
  { title: "Tous les mêmes", artist: "Stromae", year: 2013 },
  { title: "Je veux", artist: "Zaz", year: 2010 },
  { title: "On ira", artist: "Zaz", year: 2010 },
  { title: "Dernière Danse", artist: "Indila", year: 2014 },
  { title: "Tourner dans le vide", artist: "Indila", year: 2015 },
  { title: "Djadja", artist: "Aya Nakamura", year: 2018 },
  { title: "Pookie", artist: "Aya Nakamura", year: 2019 },
  { title: "Copines", artist: "Aya Nakamura", year: 2018 },
  { title: "Dernier Domicile Connu", artist: "IAM", year: 1997 },
  { title: "Je Danse le Mia", artist: "IAM", year: 1993 },
  { title: "La Boulette", artist: "Diam's", year: 2006 },
  { title: "Suzy", artist: "Diam's", year: 2003 },
  { title: "Aicha", artist: "Khaled", year: 1996 },
  { title: "Didi", artist: "Khaled", year: 1992 },
  { title: "Joe le Taxi", artist: "Vanessa Paradis", year: 1987 },
  { title: "Tandem", artist: "Vanessa Paradis", year: 1990 },
  { title: "Désenchantée", artist: "Mylène Farmer", year: 1991 },
  { title: "Sans Contrefaçon", artist: "Mylène Farmer", year: 1987 },
  { title: "Libertine", artist: "Mylène Farmer", year: 1986 },
  { title: "Ella, elle l'a", artist: "France Gall", year: 1987 },
  { title: "Résiste", artist: "France Gall", year: 1981 },
  { title: "Poupée de cire, poupée de son", artist: "France Gall", year: 1965 },
  { title: "Comme toi", artist: "Jean-Jacques Goldman", year: 1982 },
  { title: "Envole-moi", artist: "Jean-Jacques Goldman", year: 1984 },
  { title: "Il changeait la vie", artist: "Jean-Jacques Goldman", year: 1987 },
  { title: "Star's", artist: "Jean-Jacques Goldman", year: 1987 },
  { title: "L'Aziza", artist: "Daniel Balavoine", year: 1985 },
  { title: "Je ne suis pas un héros", artist: "Daniel Balavoine", year: 1980 },
  { title: "Foule Sentimentale", artist: "Alain Souchon", year: 1993 },
  { title: "Sous le vent", artist: "Garou & Céline Dion", year: 2001 },
  { title: "Belle", artist: "Garou, Daniel Lavoie, Patrick Fiori", year: 1998 },
  { title: "L'Amour est Bleu", artist: "Vicky Leandros", year: 1967 },
  { title: "Je t'aime... moi non plus", artist: "Serge Gainsbourg", year: 1969 },
  { title: "Le Poinçonneur des Lilas", artist: "Serge Gainsbourg", year: 1958 },
  { title: "La Javanaise", artist: "Serge Gainsbourg", year: 1963 },
  { title: "Harley Davidson", artist: "Serge Gainsbourg & Brigitte Bardot", year: 1968 },
  { title: "Chandelier de Cristal", artist: "Michel Sardou", year: 1976 },
  { title: "La Maladie d'Amour", artist: "Michel Sardou", year: 1973 },
  { title: "Les Lacs du Connemara", artist: "Michel Sardou", year: 1981 },
  { title: "Vivre", artist: "Michel Sardou", year: 1974 },
  { title: "Toute la musique que j'aime", artist: "Johnny Hallyday", year: 1985 },
  { title: "Que je t'aime", artist: "Johnny Hallyday", year: 1969 },
  { title: "Allumer le feu", artist: "Johnny Hallyday", year: 1998 },
  { title: "Requiem pour un fou", artist: "Johnny Hallyday", year: 1977 },
  { title: "L'Envie d'Aimer", artist: "Daniel Lévi", year: 1998 },
  { title: "Le Temps des Cathédrales", artist: "Bruno Pelletier", year: 1998 },
  { title: "Vivo Per Lei (version FR: Je Vis Pour Elle)", artist: "Hélène Ségara", year: 1998 },
  { title: "On Ecrit Sur Les Murs", artist: "Kids United", year: 2015 },
  { title: "Little Big Man", artist: "Kids United", year: 2016 },
  { title: "Manhattan-Kaboul", artist: "Renaud & Axelle Red", year: 2002 },
  { title: "Mistral Gagnant", artist: "Renaud", year: 1985 },
  { title: "Dès que le vent soufflera", artist: "Renaud", year: 1983 },
  { title: "Sensualité", artist: "Axelle Red", year: 1993 },
  { title: "Voilà", artist: "Barbara Pravi", year: 2021 },
  { title: "J'ai Cherché", artist: "Amir", year: 2016 },
  { title: "On Va S'Aimer", artist: "Kendji Girac", year: 2014 },
  { title: "Andalouse", artist: "Kendji Girac", year: 2014 },
  { title: "Color Gitano", artist: "Kendji Girac", year: 2015 },
  { title: "Freed From Desire (Marina)", artist: "Marina", year: 2016 },
  { title: "Dommage", artist: "Bigflo & Oli", year: 2017 },
  { title: "Alors on Change", artist: "Bigflo & Oli", year: 2015 },
  { title: "La Grenade", artist: "Clara Luciani", year: 2018 },
  { title: "Respire Encore", artist: "Clara Luciani", year: 2021 },
  { title: "Balance ton quoi", artist: "Angèle", year: 2018 },
  { title: "Tout Oublier", artist: "Angèle ft. Roméo Elvis", year: 2018 },
  { title: "Ta Reine", artist: "Angèle", year: 2019 },
  { title: "Bella Ciao (version française)", artist: "Maître Gims, Vitaa, Slimane, Dadju, Naestro", year: 2018 },
  { title: "Sapés Comme Jamais", artist: "Maître Gims ft. Niska", year: 2015 },
  { title: "Bella", artist: "Maître Gims", year: 2013 },
  { title: "J'me Tire", artist: "Maître Gims", year: 2013 },
  { title: "On Sait", artist: "Naps", year: 2019 },
  { title: "Dernière Danse (Indila cover context)", artist: "Indila", year: 2014 },
  { title: "Elle Me Dit", artist: "Mika", year: 2012 },
  { title: "Grace Kelly", artist: "Mika", year: 2007 },
  { title: "Que Reste-t-il de Nos Amours ?", artist: "Charles Trenet", year: 1942 },
  { title: "La Mer", artist: "Charles Trenet", year: 1946 },
  { title: "Douce France", artist: "Charles Trenet", year: 1947 },
  { title: "Les Feuilles Mortes", artist: "Yves Montand", year: 1946 },
  { title: "C'est Si Bon", artist: "Yves Montand", year: 1950 },
  { title: "À Bicyclette", artist: "Yves Montand", year: 1968 },
];
