// songs/he.js — מאגר השירים בעברית (שירים ייחודיים, ללא כפילויות).
//
// סכימה לכל שיר:
//   title      — שם השיר (חובה)
//   artist     — שם האומן/הלהקה (חובה)
//   year       — שנת יציאה (חובה, מספר)
//   youtubeId  — מזהה סרטון YouTube מדויק (אופציונלי). קיים → מנגן בדיוק אותו סרטון.
//                חסר/ריק ("") → האתר נופל לחיפוש אוטומטי לפי "אומן שם-שיר".
//
// הערה: הרשימה המקורית (500 שורות) הכילה כפילויות — אותו שיר שהופיע בכמה
// שנים כי נשאר פופולרי לאורך זמן. הן סוננו, נשאר מופע ראשון של כל צירוף
// שיר+אומן (השנה שנשמרה היא זו של המופע המוקדם ביותר ברשימה המקורית).

window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.he = [
  { title: "איך שהיא רוקדת", artist: "עדן חסון, אופק אדנק, אגם בוחבוט", year: 2026, youtubeId: "eaqW5eQXTdM" },
  { title: "כולם גנבים", artist: "אושר כהן", year: 2026, youtubeId: "INKpPFwOQLY" },
  { title: "אבי הטחול", artist: "רואי אדם", year: 2026, youtubeId: "yrlyruDX5vI" },
  { title: "עשר רמות מעליו", artist: "אודיה", year: 2026, youtubeId: "VFH6mJHFILc" },
  { title: "06", artist: "איתי לוי", year: 2026, youtubeId: "O4zEeaMtmHI" },
  { title: "יוצאת מן הכלל", artist: "ליעד מאיר ואופק אדנק", year: 2026, youtubeId: "1ZlX-M3l7R8" },
  { title: "בשעות הבודדות", artist: "איתי לוי", year: 2026, youtubeId: "TGv3akMUreA" },
  { title: "בן 32", artist: "עומר אדם", year: 2026, youtubeId: "7PE611GuMAk" },
  { title: "או לה פופה", artist: "נועה קירל", year: 2026, youtubeId: "aQfI0WP-fcE" },
  { title: "MICHELLE", artist: "נועם בתן", year: 2026, youtubeId: "xWCnWSoG8nI" },
  { title: "בית ביפו", artist: "דודו טסה", year: 2026, youtubeId: "zXwkMXMyYJc" },
  { title: "הלוואי", artist: "חנן בן ארי, פאר טסי", year: 2026, youtubeId: "4DbqBFPv1aE" },
  { title: "המזרח הרחוק", artist: "שרית חדד", year: 2026, youtubeId: "foy3MEZTP50" },
  { title: "ילדה מטורפת", artist: "בר צברי", year: 2026, youtubeId: "53Y37uuuvOM" },
  { title: "תמיד אוהב אותי", artist: "ששון איפרם שאולוב", year: 2025, youtubeId: "" },
  { title: "מלכת הדור", artist: "עומר אדם", year: 2025, youtubeId: "fVMihvd4Xzs" },
  { title: "סופרמן", artist: "עידן עמדי", year: 2025, youtubeId: "zv7l6nRI--M" },
  { title: "אם את כבר הולכת", artist: "נדב חנציס", year: 2025, youtubeId: "Ki94rmDMoPk" },
  { title: "היא לא יודעת למה", artist: "פאר טסי", year: 2025, youtubeId: "Dl4RKBYRUxQ" },
  { title: "כל עכבה לטובה", artist: "בן צור", year: 2025, youtubeId: "1u8-tOmOVyU" },
  { title: "אהובתי כבר לא רואה אותי", artist: "עומר אדם", year: 2025, youtubeId: "QzDpV_8HVXk" },
  { title: "את לא יודעת כמה שאני אוהב אותך", artist: "אודיה", year: 2025, youtubeId: "J-q28gVKEcA" },
  { title: "פרפרים", artist: "אודיה", year: 2025, youtubeId: "GmagbJ_bGZI" },
  { title: "רשימת קניות", artist: "נס, סטילה, אודיה", year: 2025, youtubeId: "kYntjh4XEto" },
  { title: "פאפי", artist: "אודיה", year: 2025, youtubeId: "zgcBg0ofc0c" },
  { title: "אליס", artist: "אודיה", year: 2025, youtubeId: "N-eAGk1uySY" },
  { title: "אם הייתי", artist: "איתי לוי", year: 2025, youtubeId: "" },
  { title: "טוב לי", artist: "אושר כהן", year: 2025, youtubeId: "SlE5Dh9GkpQ" },
  { title: "מה יהיה מחר", artist: "פאר טסי", year: 2025, youtubeId: "Iay1xdXljb4" },
  { title: "אהבה חולה", artist: "פאר טסי", year: 2024, youtubeId: "SNRBruxYezA" },
  { title: "אין אותי", artist: "פאר טסי", year: 2024, youtubeId: "" },
  { title: "מגבות", artist: "אושר כהן", year: 2024, youtubeId: "" },
  { title: "נאדי באדי", artist: "סטטיק", year: 2024, youtubeId: "" },
  { title: "חרבו דרבו", artist: "נס וסטילה", year: 2024, youtubeId: "1rk3n9V-aQs" },
  { title: "עם ישראל חי", artist: "אייל גולן", year: 2024, youtubeId: "1HgKB4-kQdA" },
  { title: "לצאת מדיכאון", artist: "יגל אושרי", year: 2024, youtubeId: "9XIZ_T_vg_E" },
  { title: "פחד אלוהים", artist: "כפיר צפריר", year: 2024, youtubeId: "kBLdR1J8Je4" },
  { title: "מנגן ושר", artist: "אושר כהן", year: 2024, youtubeId: "AZMuSrWcsEg" },
  { title: "צמוד צמוד", artist: "סטטיק ובן אל", year: 2024, youtubeId: "" },
  { title: "הלוואי", artist: "חנן בן ארי", year: 2024, youtubeId: "4DbqBFPv1aE" },
  { title: "אולי", artist: "אודיה", year: 2024, youtubeId: "" },
  { title: "יהלומים", artist: "נועה קירל", year: 2023, youtubeId: "X7iLyas7Oi4" },
  { title: "מיליון דולר", artist: "נועה קירל", year: 2023, youtubeId: "oQbh5Kvet04" },
  { title: "אהבה ממבט ראשון", artist: "אושר כהן", year: 2023, youtubeId: "" },
  { title: "סוף העולם", artist: "אודיה", year: 2023, youtubeId: "" },
  { title: "פנתרה", artist: "נועה קירל", year: 2023, youtubeId: "ZOf7aMbzQAM" },
  { title: "אוהב אותך", artist: "אושר כהן", year: 2023, youtubeId: "p1z6MInHFrM" },
  { title: "תיק קטן", artist: "נטע ברזילי", year: 2023, youtubeId: "" },
  { title: "אורות", artist: "אודיה", year: 2023, youtubeId: "" },
  { title: "אין לי מקום אחר", artist: "איתי לוי", year: 2023, youtubeId: "RAsTZqalx-g" },
  { title: "רק שיישאר", artist: "אודיה", year: 2023, youtubeId: "yhOc8kIsCsc" },
  { title: "הלב שלי", artist: "ישי ריבו", year: 2023, youtubeId: "6U_5KhaH6IM" },
  { title: "סיבת הסיבות", artist: "ישי ריבו", year: 2022, youtubeId: "T5Wf3gmF6Do" },
  { title: "מועבט", artist: "עדן בן זקן", year: 2022, youtubeId: "yoIeg9B8EEg" },
  { title: "סופרסטאר", artist: "סטטיק", year: 2022, youtubeId: "" },
  { title: "בא לי אותך", artist: "אושר כהן", year: 2022, youtubeId: "" },
  { title: "אני", artist: "נועה קירל", year: 2022, youtubeId: "jmSuPQu7xNA" },
  { title: "קפה וסיגריה", artist: "רביד פלוטניק", year: 2022, youtubeId: "dmUGuJf-cgg" },
  { title: "תוך כדי תנועה", artist: "קרן פלס", year: 2022, youtubeId: "" },
  { title: "אהבה שלי", artist: "אודיה", year: 2022, youtubeId: "roop3ndu_BY" },
  { title: "אין לי", artist: "איתי לוי", year: 2022, youtubeId: "RAsTZqalx-g" },
  { title: "אם הייתי", artist: "אודיה", year: 2022, youtubeId: "cSkTzkGoot0" },
  { title: "מכתוב", artist: "סטטיק", year: 2022, youtubeId: "" },
  { title: "שיר אהבה", artist: "עדן חסון", year: 2022, youtubeId: "" },
  { title: "שבט אחים ואחיות", artist: "עידן רייכל", year: 2021, youtubeId: "" },
  { title: "לייק דיס", artist: "סטטיק", year: 2021, youtubeId: "" },
  { title: "ככה וככה", artist: "אושר כהן", year: 2021, youtubeId: "KmuH00cOKno" },
  { title: "תישארי", artist: "יובל דיין", year: 2021, youtubeId: "3qmvZ_tjU7Y" },
  { title: "אין יותר טוב מזה", artist: "עדן חסון", year: 2021, youtubeId: "hySvIlHhCgA" },
  { title: "אוהב אותך", artist: "אייל גולן", year: 2021, youtubeId: "gz3_IZc5NSk" },
  { title: "CEO", artist: "נטע ברזילי", year: 2021, youtubeId: "CuI9hg7tuhI" },
  { title: "בום", artist: "רביד פלוטניק", year: 2021, youtubeId: "x8gw0WcESFE" },
  { title: "אני זכיתי", artist: "סטטיק", year: 2021, youtubeId: "" },
  { title: "שאריות של החיים", artist: "עידן רייכל", year: 2021, youtubeId: "xYYYctLmnt4" },
  { title: "שדות של אירוסים", artist: "שלמה ארצי", year: 2021, youtubeId: "L3uG2knMb4s" },
  { title: "הולך לי טוב", artist: "עומר אדם", year: 2021, youtubeId: "" },
  { title: "רק שלך", artist: "עומר אדם", year: 2020, youtubeId: "Jw02uPan7RU" },
  { title: "שקיעות אדומות", artist: "עדן חסון", year: 2020, youtubeId: "VTbqsoJYAZA" },
  { title: "ננה בננה", artist: "נטע ברזילי", year: 2020, youtubeId: "kSLtroWy4O0" },
  { title: "נחכה לך", artist: "ישי ריבו", year: 2020, youtubeId: "ryTO71_eMO4" },
  { title: "שלוש בלילה", artist: "רביד פלוטניק", year: 2020, youtubeId: "" },
  { title: "טרילילי טרללה", artist: "נועה קירל", year: 2020, youtubeId: "QB8NuvDML2I" },
  { title: "אבינו מלכנו", artist: "שלומי שבת", year: 2020, youtubeId: "" },
  { title: "לב קבור", artist: "דודו אהרון", year: 2020, youtubeId: "b_7kijmY4Ng" },
  { title: "אור גדול", artist: "מירי מסיקה", year: 2020, youtubeId: "" },
  { title: "תן לי רגע", artist: "הראל סקעת", year: 2020, youtubeId: "" },
  { title: "זאת האהבה שלנו", artist: "עברי לידר", year: 2020, youtubeId: "XJrVizZpMIA" },
  { title: "בין המילים", artist: "רוני דלומי", year: 2020, youtubeId: "" },
  { title: "אולי", artist: "דנה ברגר", year: 2020, youtubeId: "0WFaz60f_4E" },
  { title: "אהבה", artist: "אושר כהן", year: 2020, youtubeId: "K1nQX_hdop0" },
  { title: "לאלף את הסוסים", artist: "ריטה", year: 2020, youtubeId: "" },
  { title: "פולארויד", artist: "עומר אדם", year: 2019, youtubeId: "" },
  { title: "פאוץ'", artist: "נועה קירל", year: 2019, youtubeId: "5TUN30--lUw" },
  { title: "קילר", artist: "נועה קירל", year: 2019, youtubeId: "_pGjSmrxZ7s" },
  { title: "מתפוצץ לי הראש", artist: "עדן חסון", year: 2019, youtubeId: "a4Sd7aazEw4" },
  { title: "תן לי את האור", artist: "רביד פלוטניק", year: 2019, youtubeId: "" },
  { title: "נתראה בגלגול הבא", artist: "רביד פלוטניק", year: 2019, youtubeId: "Maf6BaEhCzY" },
  { title: "באסה סבבה", artist: "נטע ברזילי", year: 2019, youtubeId: "jV1sjm9Lz_Q" },
  { title: "אפס מאמץ", artist: "סטטיק ובן אל", year: 2019, youtubeId: "NpDAFKqeUDw" },
  { title: "לשון הרע לא מדבר אליי", artist: "ישי ריבו", year: 2019, youtubeId: "yX7AniVDw0w" },
  { title: "ואם תבואי אליי", artist: "עידן רייכל", year: 2019, youtubeId: "nI8n20UpaBY" },
  { title: "אני בא", artist: "שלמה ארצי", year: 2019, youtubeId: "yzk3t81glZE" },
  { title: "כל הכוכבים", artist: "פאר טסי", year: 2019, youtubeId: "" },
  { title: "תשמח", artist: "אייל גולן", year: 2019, youtubeId: "" },
  { title: "לא הצלחתי", artist: "אריק ברמן", year: 2019, youtubeId: "Hacg4KrJlSE" },
  { title: "הוזה אותך מולי", artist: "אייל גולן", year: 2018, youtubeId: "iWodhfNtdFY" },
  { title: "זה אני", artist: "אייל גולן", year: 2018, youtubeId: "WvaTAan0OFA" },
  { title: "שני משוגעים", artist: "עומר אדם", year: 2018, youtubeId: "WLMmX17D2uw" },
  { title: "מלכת השושנים", artist: "עדן בן זקן", year: 2018, youtubeId: "nwpLIXdrHS0" },
  { title: "אין אותי", artist: "נועה קירל", year: 2018, youtubeId: "h3iqvIWAfck" },
  { title: "טודו בום", artist: "סטטיק ובן אל", year: 2018, youtubeId: "Y_OLslE3bX8" },
  { title: "זהב", artist: "סטטיק ובן אל", year: 2018, youtubeId: "cRGrIn2VHTE" },
  { title: "גומיגם", artist: "סטטיק ובן אל", year: 2018, youtubeId: "9aFz_aLuFhI" },
  { title: "ימים יגידו", artist: "הראל סקעת", year: 2018, youtubeId: "" },
  { title: "מלך", artist: "מירי מסיקה", year: 2018, youtubeId: "E6uKhiJgziM" },
  { title: "גלים", artist: "אמיר דדון", year: 2018, youtubeId: "N2TRnC7g6Jo" },
  { title: "מחמל נפשי", artist: "שלמה ארצי", year: 2018, youtubeId: "IE2jnIvCxn4" },
  { title: "היא לא יודעת", artist: "איתי לוי", year: 2018, youtubeId: "" },
  { title: "מעבר לנהר", artist: "קרן פלס", year: 2018, youtubeId: "E6fgnGEsocE" },
  { title: "מסיבה בחיפה", artist: "עדן בן זקן", year: 2017, youtubeId: "" },
  { title: "כביש החוף", artist: "סטטיק ובן אל", year: 2017, youtubeId: "t2fakms1QWo" },
  { title: "לשוב הביתה", artist: "ישי ריבו", year: 2017, youtubeId: "Y30pfWIQfoo" },
  { title: "סדר העבודה", artist: "ישי ריבו", year: 2017, youtubeId: "ECy3CMxShIQ" },
  { title: "תל אביב בלילה", artist: "עדן חסון", year: 2017, youtubeId: "KuCPWqK46aY" },
  { title: "חצי", artist: "אמיר דדון", year: 2017, youtubeId: "kCl_yVJKsiw" },
  { title: "מעגלים", artist: "עידן רייכל", year: 2017, youtubeId: "5gemebkLaYY" },
  { title: "סוף שבוע", artist: "רביד פלוטניק", year: 2017, youtubeId: "DHPrIoolu9g" },
  { title: "אוהבת אותי אמיתי", artist: "עומר אדם", year: 2017, youtubeId: "31DIsGbFVgY" },
  { title: "רוז", artist: "פאר טסי", year: 2017, youtubeId: "6EvjmgtR2rI" },
  { title: "בואי ניפגש", artist: "איתי לוי", year: 2017, youtubeId: "" },
  { title: "תלתלים", artist: "רוני דלומי", year: 2017, youtubeId: "" },
  { title: "פעם בחיים", artist: "עומר אדם", year: 2016, youtubeId: "Iwv-aggzNbk" },
  { title: "תזיזו", artist: "עדן בן זקן", year: 2016, youtubeId: "ryHLrr4J1M4" },
  { title: "ברבי", artist: "סטטיק ובן אל", year: 2016, youtubeId: "YJsi8g_Hsvo" },
  { title: "משקה יקר", artist: "פאר טסי", year: 2016, youtubeId: "VhQFyNWN2uc" },
  { title: "תן", artist: "רוני דלומי", year: 2016, youtubeId: "spCQCjDPMvE" },
  { title: "עוד יגיע היום", artist: "הראל סקעת", year: 2016, youtubeId: "" },
  { title: "שיר תקווה", artist: "מירי מסיקה", year: 2016, youtubeId: "Lh9PEh0sIYQ" },
  { title: "אמא", artist: "דודו אהרון", year: 2016, youtubeId: "2f8BdHwPGgM" },
  { title: "תבואי היום", artist: "אייל גולן", year: 2016, youtubeId: "3VT3VIRQPKA" },
  { title: "מנגינה", artist: "עדן בן זקן", year: 2016, youtubeId: "fMyhIe_bV_s" },
  { title: "שקופים", artist: "קרן פלס", year: 2016, youtubeId: "4g9mJjJ9WU0" },
  { title: "מחכה", artist: "עברי לידר", year: 2016, youtubeId: "" },
  { title: "מהפכה של שמחה", artist: "עומר אדם", year: 2015, youtubeId: "tbNURvMcAiE" },
  { title: "מודה אני", artist: "עומר אדם", year: 2015, youtubeId: "YQ5f1OMFFL0" },
  { title: "דרך השלום", artist: "פאר טסי", year: 2015, youtubeId: "VD9F_7N_MbI" },
  { title: "שרק תחייך", artist: "יובל דיין", year: 2015, youtubeId: "nzT5YPAIGZA" },
  { title: "לבחור נכון", artist: "אמיר דדון", year: 2015, youtubeId: "yjJcnqZqciU" },
  { title: "שותפים", artist: "הדג נחש", year: 2015, youtubeId: "i1FITLtNA0g" },
  { title: "אם אלה החיים", artist: "קרן פלס", year: 2015, youtubeId: "RlxmsqMRmR8" },
  { title: "הלב", artist: "שלומי שבת", year: 2015, youtubeId: "Jr7lGLkx3iI" },
  { title: "רק תבואי", artist: "עברי לידר", year: 2015, youtubeId: "" },
  { title: "בין קירות ביתי", artist: "עידן רייכל", year: 2015, youtubeId: "9RYwXYtzru0" },
  { title: "אולי", artist: "איתי לוי", year: 2015, youtubeId: "" },
  { title: "מילים יפות מאלה", artist: "עידן רייכל", year: 2015, youtubeId: "j_oajsiBiQA" },
  { title: "שיר השירים", artist: "הדג נחש", year: 2015, youtubeId: "" },
  { title: "אישתי", artist: "רוני דלומי", year: 2015, youtubeId: "" },
  { title: "מתאימה לי", artist: "עומר אדם", year: 2014, youtubeId: "" },
  { title: "יפה שלי", artist: "עומר אדם", year: 2014, youtubeId: "" },
  { title: "ימים יגידו", artist: "אייל גולן", year: 2014, youtubeId: "maTcKfZ4eqo" },
  { title: "אין כמו אהבה", artist: "דודו אהרון", year: 2014, youtubeId: "JeWbelR1k4I" },
  { title: "אף אחת", artist: "מירי מסיקה", year: 2014, youtubeId: "SGIYmCdtbzg" },
  { title: "כמו כולם", artist: "הראל סקעת", year: 2014, youtubeId: "og5dskyoEb8" },
  { title: "שמות", artist: "אריק ברמן", year: 2014, youtubeId: "df7xKFTm7Is" },
  { title: "פנים אל מול פנים", artist: "יהודה פוליקר", year: 2014, youtubeId: "" },
  { title: "הכל עובר", artist: "קרן פלס", year: 2014, youtubeId: "" },
  { title: "בדיוק כמו הירח", artist: "יובל דיין", year: 2014, youtubeId: "V4qsi4V-NFY" },
  { title: "בואי", artist: "ריטה", year: 2014, youtubeId: "" },
  { title: "כמו ציפור", artist: "אמיר דדון", year: 2014, youtubeId: "" },
  { title: "כמו כולם", artist: "דנה ברגר", year: 2014, youtubeId: "" },
  { title: "אהבה ראשונה", artist: "דודו אהרון", year: 2014, youtubeId: "nI2k_LzUyug" },
  { title: "תישארי", artist: "עברי לידר", year: 2014, youtubeId: "" },
  { title: "קאקדילה", artist: "עומר אדם", year: 2013, youtubeId: "fXFLjct5agw" },
  { title: "בוקר טוב", artist: "עומר אדם", year: 2013, youtubeId: "JRE-30sKXqs" },
  { title: "לבדי", artist: "אייל גולן", year: 2013, youtubeId: "nPc-ahsDqas" },
  { title: "השיר של איתי", artist: "יובל דיין", year: 2013, youtubeId: "" },
  { title: "רוב השעות", artist: "עידן רייכל", year: 2013, youtubeId: "qD4mkJiQPKY" },
  { title: "הכל זה מלמעלה", artist: "דודו אהרון", year: 2013, youtubeId: "Y1pK0woqv58" },
  { title: "חלל", artist: "אמיר דדון", year: 2013, youtubeId: "5YqlqjAzm5Q" },
  { title: "תן לי מנגינה", artist: "הדג נחש", year: 2013, youtubeId: "nGPF-HYF7SY" },
  { title: "מילים", artist: "הראל סקעת", year: 2013, youtubeId: "" },
  { title: "רגע פרטי", artist: "ריטה", year: 2013, youtubeId: "LY3baJOd9To" },
  { title: "בואי נדבר", artist: "דנה ברגר", year: 2013, youtubeId: "" },
  { title: "תודה", artist: "שלומי שבת", year: 2013, youtubeId: "eQZn3j3LFuo" },
  { title: "אהבה כמו שלנו", artist: "קרן פלס", year: 2013, youtubeId: "" },
  { title: "מלאת אהבה", artist: "עומר אדם", year: 2013, youtubeId: "" },
  { title: "בואי אליי", artist: "עידן רייכל", year: 2013, youtubeId: "_uJLsc05ZE4" },
  { title: "תל אביב", artist: "עומר אדם", year: 2012, youtubeId: "nMQw29nfzpg" },
  { title: "תשאל את המים", artist: "יובל דיין", year: 2012, youtubeId: "aPmOiRA5WrY" },
  { title: "ארץ חדשה", artist: "שלמה ארצי", year: 2012, youtubeId: "" },
  { title: "יש לך אותך", artist: "מירי מסיקה", year: 2012, youtubeId: "UzlVFA9eu7Y" },
  { title: "אדוני", artist: "עברי לידר", year: 2012, youtubeId: "" },
  { title: "חולם אותך", artist: "יהודה פוליקר", year: 2012, youtubeId: "xTpOhPzCphQ" },
  { title: "דרך לחיים", artist: "אייל גולן", year: 2011, youtubeId: "IT_mMBfeOBg" },
  { title: "כשאת איתו", artist: "אייל גולן", year: 2011, youtubeId: "g4t2GDIoquE" },
  { title: "קלרה", artist: "עומר אדם", year: 2011, youtubeId: "" },
  { title: "עוד אח אחד", artist: "הדג נחש", year: 2011, youtubeId: "Rz-xsKZYnPw" },
  { title: "ואת", artist: "קרן פלס", year: 2011, youtubeId: "" },
  { title: "הרי את מקודשת לי", artist: "שלומי שבת", year: 2011, youtubeId: "cuvsBPOanQA" },
  { title: "באה אליכם", artist: "מירי מסיקה", year: 2011, youtubeId: "7IaJXfVY5Pk" },
  { title: "נאחז באוויר", artist: "גידי גוב", year: 2011, youtubeId: "l-tRKBTJVE0" },
  { title: "מלטף ומשקר", artist: "עברי לידר", year: 2011, youtubeId: "ebJKjN6xdFI" },
  { title: "עוד", artist: "אמיר דדון", year: 2011, youtubeId: "" },
  { title: "מחוזקים לעולם", artist: "אמיר דדון", year: 2010, youtubeId: "" },
  { title: "אור גדול", artist: "אמיר דדון", year: 2010, youtubeId: "jeU9Sbq0D0A" },
  { title: "מלכת היופי שלי", artist: "אייל גולן", year: 2010, youtubeId: "KIjKR3LxoWM" },
  { title: "נולדת בשבילי", artist: "אייל גולן", year: 2010, youtubeId: "0DXZzKDabSI" },
  { title: "כמו אז", artist: "שלמה ארצי", year: 2010, youtubeId: "PBMg6yvjOHU" },
  { title: "אחרי הכול את שיר", artist: "שלמה ארצי", year: 2010, youtubeId: "P4KnqxpoKkM" },
  { title: "לא מספיק", artist: "הדג נחש", year: 2010, youtubeId: "cpyPi8_RQs0" },
  { title: "כמו ציפור", artist: "ריטה", year: 2010, youtubeId: "" },
  { title: "רק אלוהים ישפוט אותי", artist: "קרן פלס", year: 2010, youtubeId: "r4qTj8ZiGyQ" },
  { title: "בית משוגעים", artist: "רוני דלומי", year: 2010, youtubeId: "" },
  { title: "תגידי לי", artist: "דודו אהרון", year: 2010, youtubeId: "" },
  { title: "בואי נדבר", artist: "ארקדי דוכין", year: 2010, youtubeId: "" },
  { title: "רכבת", artist: "דנה ברגר", year: 2010, youtubeId: "" },
  { title: "מי שמאמין", artist: "אייל גולן", year: 2009, youtubeId: "-CZqRKYznrM" },
  { title: "היא לא יודעת מה עובר עליי", artist: "אייל גולן", year: 2009, youtubeId: "" },
  { title: "מכל האהבות", artist: "דודו אהרון", year: 2009, youtubeId: "" },
  { title: "הנני כאן", artist: "הראל סקעת", year: 2009, youtubeId: "867VJMEXQ3M" },
  { title: "בגלל הרוח", artist: "שלומי שבת", year: 2009, youtubeId: "nli5tcVRjG4" },
  { title: "האם אתה מאושר", artist: "ריטה", year: 2009, youtubeId: "GgX8WpSYJVE" },
  { title: "אני מאמין", artist: "הדג נחש", year: 2009, youtubeId: "HTkmOPkuIpo" },
  { title: "אהבה ממבט ראשון", artist: "אריק ברמן", year: 2009, youtubeId: "" },
  { title: "בוקר טוב", artist: "עברי לידר", year: 2009, youtubeId: "" },
  { title: "שוב", artist: "ארקדי דוכין", year: 2009, youtubeId: "" },
  { title: "לא דומה", artist: "דודו אהרון", year: 2009, youtubeId: "yI4kTq2OKlA" },
  { title: "נובמבר", artist: "מירי מסיקה", year: 2008, youtubeId: "yS_tA7WNghM" },
  { title: "תמיד אהבה", artist: "עברי לידר", year: 2008, youtubeId: "eWieCfG6634" },
  { title: "בואי ניפרד", artist: "גידי גוב", year: 2008, youtubeId: "" },
  { title: "עיניים שלי", artist: "יהודה פוליקר", year: 2008, youtubeId: "fpEc_7kXlQM" },
  { title: "המתוקות האחרונות", artist: "אריק ברמן", year: 2008, youtubeId: "0SlAGZMPmVA" },
  { title: "כמו פעם", artist: "ארקדי דוכין", year: 2008, youtubeId: "" },
  { title: "משבר אמון", artist: "ריטה", year: 2008, youtubeId: "" },
  { title: "מילים יפות", artist: "עידן רייכל", year: 2008, youtubeId: "j_oajsiBiQA" },
  { title: "כמו ציפור", artist: "יובל דיין", year: 2008, youtubeId: "V4qsi4V-NFY" },
  { title: "אם יש גן עדן", artist: "אייל גולן", year: 2007, youtubeId: "nLLS924fGUU" },
  { title: "תתארו לכם", artist: "שלמה ארצי", year: 2007, youtubeId: "Y0KxZz5k-RE" },
  { title: "איסלנד", artist: "שלמה ארצי", year: 2007, youtubeId: "zaZUNFPmFB0" },
  { title: "הנה אני בא", artist: "הדג נחש", year: 2007, youtubeId: "JNwJFLkoX80" },
  { title: "יום חדש נפלא", artist: "אריק ברמן", year: 2007, youtubeId: "TFFAjojBe1k" },
  { title: "שביל הבריחה", artist: "עברי לידר", year: 2007, youtubeId: "" },
  { title: "ממעמקים", artist: "עידן רייכל", year: 2007, youtubeId: "kmW2yAYhMmM" },
  { title: "לשם", artist: "מירי מסיקה", year: 2007, youtubeId: "iQoxiA4K72w" },
  { title: "בוא", artist: "עברי לידר", year: 2007, youtubeId: "F_BxJvYPtpk" },
  { title: "אל תלכי לי", artist: "אייל גולן", year: 2006, youtubeId: "8RrMom7EonE" },
  { title: "אתה ואני", artist: "הראל סקעת", year: 2006, youtubeId: "ApjfPKgDdMc" },
  { title: "ואת", artist: "הראל סקעת", year: 2006, youtubeId: "AcpgsbFvnbM" },
  { title: "השקט שנשאר", artist: "שירי מימון", year: 2006, youtubeId: "_xsI9tgyj1A" },
  { title: "אור", artist: "שירי מימון", year: 2006, youtubeId: "" },
  { title: "מפחד עלייך", artist: "מירי מסיקה", year: 2006, youtubeId: "Fr8gix_aqO8" },
  { title: "אני שוב מתאהב", artist: "גידי גוב", year: 2006, youtubeId: "qoGurrdtz6Q" },
  { title: "לומדת לעוף", artist: "דנה ברגר", year: 2006, youtubeId: "Wtup9AJmP3c" },
  { title: "ממעמקים", artist: "הפרויקט של עידן רייכל", year: 2006, youtubeId: "kmW2yAYhMmM" },
  { title: "זכיתי לאהוב", artist: "עברי לידר", year: 2006, youtubeId: "nUJro16dpbs" },
  { title: "יש בי אהבה", artist: "אריק איינשטיין", year: 2006, youtubeId: "5WEggKymynE" },
  { title: "מחכה", artist: "ריטה", year: 2006, youtubeId: "hAX2ku9ifEs" },
  { title: "מצטער", artist: "אייל גולן", year: 2005, youtubeId: "VSQ5haTLKB8" },
  { title: "הנך יפה", artist: "הפרויקט של עידן רייכל", year: 2005, youtubeId: "-qxrnxoHl6A" },
  { title: "מדברים בשקט", artist: "הפרויקט של עידן רייכל", year: 2005, youtubeId: "J_g6c6IZ6VY" },
  { title: "אם זאת אהבה", artist: "מירי מסיקה", year: 2005, youtubeId: "FgoGB0cSg60" },
  { title: "ניסים", artist: "עברי לידר", year: 2005, youtubeId: "-SubcIwy0Vs" },
  { title: "שלל שרב", artist: "גידי גוב", year: 2005, youtubeId: "ojBKxaVL5Fw" },
  { title: "איך קוראים לאהבה שלי", artist: "יהודה פוליקר", year: 2005, youtubeId: "sFzVHbvnEnk" },
  { title: "בואי", artist: "עברי לידר", year: 2004, youtubeId: "" },
  { title: "כשתבוא", artist: "הדג נחש", year: 2004, youtubeId: "" },
  { title: "שירת הסטיקר", artist: "הדג נחש", year: 2004, youtubeId: "QflL6R2-k-8" },
  { title: "גבי ודבי", artist: "הדג נחש", year: 2004, youtubeId: "70i9PvrsvJ0" },
  { title: "מי אוהב אותך יותר ממני", artist: "ארקדי דוכין", year: 2004, youtubeId: "l0WYMRSs9C4" },
  { title: "בחוף של טרפטוני", artist: "שלומי שבת", year: 2004, youtubeId: "KGk2BOsVpno" },
  { title: "כשתגדל", artist: "יהודה פוליקר", year: 2004, youtubeId: "CZYtx-JIu3g" },
  { title: "האהבה הישנה", artist: "שלמה ארצי", year: 2004, youtubeId: "02uV8M6XSto" },
  { title: "אתה בכל זאת", artist: "ריטה", year: 2004, youtubeId: "r1YHVXL74IY" },
  { title: "מישהו פעם", artist: "עברי לידר", year: 2004, youtubeId: "3kJiCtRlVTo" },
  { title: "יותר טוב כלום מכמעט", artist: "עברי לידר", year: 2004, youtubeId: "TmqmH0n7EXY" },
  { title: "לזוז", artist: "הדג נחש", year: 2004, youtubeId: "JC_s0yRDUoE" },
  { title: "אומרים ישנה ארץ", artist: "שלמה ארצי", year: 2003, youtubeId: "SKMdUcDV0CA" },
  { title: "אף פעם לא תדעי", artist: "שלמה ארצי", year: 2003, youtubeId: "8GmoiZ9j2YM" },
  { title: "דברים שרציתי לומר", artist: "יהודה פוליקר", year: 2003, youtubeId: "vWFKdqvdLO4" },
  { title: "שביל הבריחה", artist: "ריטה", year: 2003, youtubeId: "thcsC9PpHvM" },
  { title: "בוא", artist: "ריטה", year: 2003, youtubeId: "RrYmegnmRXo" },
  { title: "אם תלך", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "CtpCGfRRToo" },
  { title: "בואי", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "_uJLsc05ZE4" },
  { title: "שושנים", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "egtOB8arAN0" },
  { title: "תודה", artist: "הפרויקט של עידן רייכל", year: 2002, youtubeId: "" },
  { title: "מכל האהבות", artist: "עידן רייכל", year: 2002, youtubeId: "Wa0Nmruih_A" },
  { title: "פחות אבל כואב", artist: "יהודה פוליקר", year: 2002, youtubeId: "wlYpgESy6UY" },
  { title: "עד הקצה", artist: "דנה ברגר", year: 2002, youtubeId: "fEAB2iDVw-w" },
  { title: "אמא", artist: "שלומי שבת", year: 2001, youtubeId: "KMISUbgXhCY" },
  { title: "אני ואתה", artist: "אריק איינשטיין", year: 2001, youtubeId: "gP6PS-poyMg" },
  { title: "ירח", artist: "שלמה ארצי", year: 2001, youtubeId: "hGiNUsSHkr0" },
  { title: "לא פראיירים", artist: "הדג נחש", year: 2000, youtubeId: "qHM3uTxvPRg" },
  { title: "אתה לי ארץ", artist: "שלמה ארצי", year: 2000, youtubeId: "" },
  { title: "גוליית", artist: "גידי גוב", year: 2000, youtubeId: "" },
  { title: "היא", artist: "דנה ברגר", year: 2000, youtubeId: "" },
  { title: "יש בי אהבה", artist: "ארקדי דוכין", year: 2000, youtubeId: "XIgkTSmWQO0" },
  { title: "מיליארד טועים", artist: "אביב גפן", year: 1999, youtubeId: "_ChMp1XsH90" },
  { title: "האם להיות בך מאוהב", artist: "אביב גפן", year: 1999, youtubeId: "_u8wImTMh3k" },
  { title: "שיר תקווה", artist: "אביב גפן", year: 1999, youtubeId: "csOuqrL9NvQ" },
  { title: "רכבת לילה לקהיר", artist: "משינה", year: 1999, youtubeId: "0y0gaLiyiak" },
  { title: "אהובתי", artist: "משינה", year: 1999, youtubeId: "Hd9ubTcJc7E" },
  { title: "אני חיה לי מיום ליום", artist: "ריטה", year: 1999, youtubeId: "M8qfRZ5w2qY" },
  { title: "כשהלב הוא חופשי", artist: "ריטה", year: 1999, youtubeId: "" },
  { title: "אין מקום אחר", artist: "משינה", year: 1999, youtubeId: "PVAD3KWgQrQ" },
  { title: "שיר לשירה", artist: "קורין אלאל", year: 1998, youtubeId: "5Dnu2RvttBw" },
  { title: "זה מה שנשאר", artist: "שלמה ארצי", year: 1998, youtubeId: "2zk_cTSeLUk" },
  { title: "אור הירח", artist: "אביב גפן", year: 1998, youtubeId: "TeJQz1Bco84" },
  { title: "עונות", artist: "אביב גפן", year: 1998, youtubeId: "SzGr282fgAM" },
  { title: "גשם כבד", artist: "אביב גפן", year: 1998, youtubeId: "P9u_svtR3Sg" },
  { title: "לבכות לך", artist: "אביב גפן", year: 1998, youtubeId: "XjVUzfb_oBo" },
  { title: "הכוכבים דולקים על אש קטנה", artist: "משינה", year: 1998, youtubeId: "FilQhY2Pjq0" },
  { title: "עטור מצחך", artist: "אריק איינשטיין", year: 1998, youtubeId: "WZM4iXT3-ic" },
  { title: "אין לי ארץ אחרת", artist: "גידי גוב", year: 1998, youtubeId: "" },
  { title: "אני מאמין", artist: "שלמה ארצי", year: 1997, youtubeId: "" },
  { title: "מחכים למשיח", artist: "שלום חנוך", year: 1997, youtubeId: "-0i3mev5EvQ" },
  { title: "רק בגלל הרוח", artist: "שלמה ארצי", year: 1997, youtubeId: "" },
  { title: "באה מאהבה", artist: "יהודית רביץ", year: 1997, youtubeId: "zUNPxTNxVoc" },
  { title: "שלח לי מלאך", artist: "משינה", year: 1995, youtubeId: "CYQ3WBi_n68" },
  { title: "ריקוד ירח", artist: "ריטה", year: 1994, youtubeId: "E26HGGPq0s8" },
  { title: "לילה בעיר", artist: "משינה", year: 1993, youtubeId: "Q1OWrVU3nTE" },
  { title: "אמא", artist: "שלמה ארצי", year: 1990, youtubeId: "" },
  { title: "כמו שאתה", artist: "מרגלית צנעני", year: 1990, youtubeId: "bOasB1tl6i8" },
  { title: "דרך ארוכה", artist: "גידי גוב", year: 1989, youtubeId: "xVnwgIFOf2I" },
  { title: "בדרך אל הים", artist: "משינה", year: 1988, youtubeId: "pohW4WQ4H8M" },
  { title: "עוף גוזל", artist: "אריק איינשטיין", year: 1987, youtubeId: "mOd-hetRES0" },
  { title: "לתת", artist: "בועז שרעבי", year: 1987, youtubeId: "IG2waIDW7Cc" },
  { title: "אוהב להיות בבית", artist: "אריק איינשטיין", year: 1986, youtubeId: "yXll9VNF118" },
  { title: "מאיה", artist: "שלום חנוך", year: 1984, youtubeId: "urqQ3V76hXs" },
  { title: "מאושרת", artist: "עומר אדם", year: 2011, youtubeId: "" },
  { title: "אל תחפשי", artist: "עומר אדם", year: 2012, youtubeId: "" },
  { title: "בניתי עלייך", artist: "עומר אדם", year: 2012, youtubeId: "" },
  { title: "נועצת מבט", artist: "עומר אדם", year: 2014, youtubeId: "" },
  { title: "בוקרשט", artist: "עומר אדם", year: 2015, youtubeId: "" },
  { title: "אחרי כל השנים", artist: "עומר אדם", year: 2016, youtubeId: "" },
  { title: "שדות של תירוצים", artist: "עומר אדם", year: 2017, youtubeId: "" },
  { title: "מביט מהצד", artist: "עומר אדם", year: 2017, youtubeId: "" },
  { title: "מזל", artist: "עומר אדם", year: 2017, youtubeId: "" },
  { title: "פרדייז", artist: "עומר אדם", year: 2017, youtubeId: "" },
  { title: "בסוף הכל חולף", artist: "עומר אדם", year: 2017, youtubeId: "" },
  { title: "ככה זה מרגיש להתאהב", artist: "עומר אדם", year: 2017, youtubeId: "" },
  { title: "לא הפסקתי לחפש אותך", artist: "עומר אדם", year: 2017, youtubeId: "" },
  { title: "חברות שלך", artist: "עומר אדם", year: 2018, youtubeId: "" },
  { title: "בחורים טובים", artist: "עומר אדם", year: 2018, youtubeId: "" },
  { title: "טמפרטורה", artist: "עומר אדם", year: 2019, youtubeId: "" },
  { title: "יום השישי", artist: "עומר אדם", year: 2019, youtubeId: "" },
  { title: "בא לי", artist: "שרית חדד", year: 2011, youtubeId: "" },
  { title: "מה שלומך יקירי", artist: "שרית חדד", year: 2011, youtubeId: "" },
  { title: "יפה יפה", artist: "שרית חדד", year: 2012, youtubeId: "" },
  { title: "הוא לא ידע את שמה", artist: "שרית חדד", year: 2012, youtubeId: "" },
  { title: "כמה כמה", artist: "שרית חדד", year: 2012, youtubeId: "" },
  { title: "חיכיתי לו", artist: "שרית חדד", year: 2015, youtubeId: "" },
  { title: "קופנגן", artist: "שרית חדד", year: 2015, youtubeId: "" },
  { title: "ישמח חתני", artist: "שרית חדד", year: 2016, youtubeId: "" },
  { title: "למה לי", artist: "שרית חדד", year: 2016, youtubeId: "" },
  { title: "שרה שרה", artist: "שרית חדד", year: 2016, youtubeId: "" },
  { title: "חלק ממני", artist: "שרית חדד", year: 2017, youtubeId: "" },
  { title: "אמן", artist: "שרית חדד", year: 2018, youtubeId: "" },
  { title: "נתתי לה חיי", artist: "שרית חדד", year: 2018, youtubeId: "" },
  { title: "בן אדם", artist: "שרית חדד", year: 2019, youtubeId: "" },
  { title: "אמאל'ה ואבאל'ה", artist: "שרית חדד", year: 2019, youtubeId: "" },
  { title: "מישהו יחבק אותי", artist: "שרית חדד", year: 2019, youtubeId: "" },
  { title: "קחי אותי אלייך", artist: "משה פרץ", year: 2011, youtubeId: "" },
  { title: "כמו מלך", artist: "משה פרץ", year: 2011, youtubeId: "" },
  { title: "רחוק ממך", artist: "משה פרץ", year: 2011, youtubeId: "" },
  { title: "אלף פעמים", artist: "משה פרץ", year: 2011, youtubeId: "" },
  { title: "אולי הלילה", artist: "משה פרץ", year: 2012, youtubeId: "" },
  { title: "הראשונה", artist: "משה פרץ", year: 2012, youtubeId: "" },
  { title: "הטעם הישן", artist: "משה פרץ", year: 2013, youtubeId: "" },
  { title: "חלמתי", artist: "משה פרץ", year: 2013, youtubeId: "" },
  { title: "ילדה קטנה", artist: "משה פרץ", year: 2013, youtubeId: "" },
  { title: "זיכרונות", artist: "משה פרץ", year: 2013, youtubeId: "" },
  { title: "אם זאת מלחמה", artist: "משה פרץ", year: 2014, youtubeId: "" },
  { title: "תהיה מאושר", artist: "משה פרץ", year: 2014, youtubeId: "" },
  { title: "ברצלונה", artist: "משה פרץ", year: 2015, youtubeId: "" },
  { title: "אח שלי", artist: "משה פרץ", year: 2015, youtubeId: "" },
  { title: "כוס של יין", artist: "משה פרץ", year: 2016, youtubeId: "" },
  { title: "היינו שניים", artist: "משה פרץ", year: 2018, youtubeId: "" },
  { title: "הולכים להשתגע", artist: "משה פרץ", year: 2018, youtubeId: "" },
  { title: "אם תרצי", artist: "ליאור נרקיס", year: 2012, youtubeId: "" },
  { title: "מיליון כוכבים", artist: "ליאור נרקיס", year: 2012, youtubeId: "" },
  { title: "לב שאוהב", artist: "ליאור נרקיס", year: 2012, youtubeId: "" },
  { title: "איך קרה", artist: "ליאור נרקיס", year: 2012, youtubeId: "" },
  { title: "יהלום", artist: "ליאור נרקיס", year: 2014, youtubeId: "" },
  { title: "נדירה", artist: "ליאור נרקיס", year: 2014, youtubeId: "" },
  { title: "ענני", artist: "ליאור נרקיס", year: 2015, youtubeId: "" },
  { title: "יום שעובר", artist: "ליאור נרקיס", year: 2015, youtubeId: "" },
  { title: "ריחות של אלכוהול", artist: "ליאור נרקיס", year: 2015, youtubeId: "" },
  { title: "צביקה", artist: "ליאור נרקיס", year: 2016, youtubeId: "" },
  { title: "6000 מייל", artist: "ליאור נרקיס", year: 2016, youtubeId: "" },
  { title: "גנבים", artist: "ליאור נרקיס", year: 2016, youtubeId: "" },
  { title: "עכשיו", artist: "ליאור נרקיס", year: 2017, youtubeId: "" },
  { title: "ביוטי", artist: "ליאור נרקיס", year: 2017, youtubeId: "" },
  { title: "מהרסת", artist: "ליאור נרקיס", year: 2018, youtubeId: "" },
  { title: "עולם יפה וחדש", artist: "ליאור נרקיס", year: 2019, youtubeId: "" },
  { title: "היינו עושים אהבה", artist: "ליאור נרקיס", year: 2019, youtubeId: "" },
  { title: "בובות", artist: "אביב גפן", year: 2011, youtubeId: "" },
  { title: "נוסטלגיה", artist: "אביב גפן", year: 2011, youtubeId: "" },
  { title: "יש שמים מעלי", artist: "אביב גפן", year: 2012, youtubeId: "" },
  { title: "עולם חדש", artist: "אביב גפן", year: 2014, youtubeId: "" },
  { title: "מי אני היום", artist: "אביב גפן", year: 2017, youtubeId: "" },
  { title: "הללויה", artist: "אביב גפן", year: 2017, youtubeId: "" },
  { title: "קצר פה כל כך האביב", artist: "יהודה פוליקר", year: 2011, youtubeId: "" },
  { title: "גברים קשוחים", artist: "יהודה פוליקר", year: 2011, youtubeId: "" },
  { title: "כל דבר מזכיר לי", artist: "יהודה פוליקר", year: 2011, youtubeId: "" },
  { title: "אושר", artist: "יהודה פוליקר", year: 2011, youtubeId: "" },
  { title: "מקום אחר", artist: "יהודה פוליקר", year: 2017, youtubeId: "" },
  { title: "זמן להתעורר", artist: "הדג נחש", year: 2013, youtubeId: "" },
  { title: "מבסוט", artist: "הדג נחש", year: 2013, youtubeId: "" },
  { title: "שמש", artist: "הדג נחש", year: 2016, youtubeId: "" },
  { title: "עכשיו קרוב", artist: "עידן רייכל", year: 2013, youtubeId: "" },
  { title: "בלילה", artist: "עידן רייכל", year: 2013, youtubeId: "" },
  { title: "עד שאין יותר לאן", artist: "עידן רייכל", year: 2013, youtubeId: "" },
  { title: "יורד הערב", artist: "עידן רייכל", year: 2013, youtubeId: "" },
  { title: "הרוח הזו", artist: "עידן רייכל", year: 2013, youtubeId: "" },
  { title: "עולם שלם", artist: "עידן רייכל", year: 2013, youtubeId: "" },
  { title: "לפני שייגמר", artist: "עידן רייכל", year: 2015, youtubeId: "" },
  { title: "גלגל מסתובב", artist: "עידן רייכל", year: 2017, youtubeId: "" },
  { title: "אהבה כזו", artist: "עידן רייכל", year: 2017, youtubeId: "" },
  { title: "בראשית", artist: "עידן רייכל", year: 2018, youtubeId: "" },
  { title: "עכשיו נשארנו שנינו", artist: "עידן רייכל", year: 2019, youtubeId: "" },
  { title: "כתוב מלמעלה", artist: "עידן רייכל", year: 2019, youtubeId: "" },
  { title: "אם רק תסכימי", artist: "עידן רייכל", year: 2019, youtubeId: "" },
  { title: "כבתחילה", artist: "ישי ריבו", year: 2012, youtubeId: "" },
  { title: "השבעתי", artist: "ישי ריבו", year: 2014, youtubeId: "" },
  { title: "מקשה אחת זהב", artist: "ישי ריבו", year: 2015, youtubeId: "" },
  { title: "הנה ימים באים", artist: "ישי ריבו", year: 2018, youtubeId: "" },
  { title: "אחת ולתמיד", artist: "ישי ריבו", year: 2018, youtubeId: "" },
  { title: "לבחור נכון", artist: "ישי ריבו", year: 2018, youtubeId: "" },
  { title: "ניצחת איתי הכל", artist: "ישי ריבו", year: 2018, youtubeId: "" },
  { title: "ממך עד אליי", artist: "חנן בן ארי", year: 2014, youtubeId: "" },
  { title: "החיים שלנו תותים", artist: "חנן בן ארי", year: 2016, youtubeId: "" },
  { title: "ויקיפדיה", artist: "חנן בן ארי", year: 2017, youtubeId: "" },
  { title: "לא לבד", artist: "חנן בן ארי", year: 2017, youtubeId: "" },
  { title: "תודה שאת", artist: "חנן בן ארי", year: 2017, youtubeId: "" },
  { title: "מה אתה רוצה ממני", artist: "חנן בן ארי", year: 2018, youtubeId: "" },
  { title: "בשורות טובות", artist: "חנן בן ארי", year: 2018, youtubeId: "" },
  { title: "אלוף העולם", artist: "חנן בן ארי", year: 2019, youtubeId: "" },
  { title: "דור", artist: "חנן בן ארי", year: 2019, youtubeId: "" },
  { title: "את אשתי", artist: "דודו אהרון", year: 2011, youtubeId: "" },
  { title: "אמא יקרה", artist: "דודו אהרון", year: 2011, youtubeId: "" },
  { title: "כמה אושר", artist: "דודו אהרון", year: 2011, youtubeId: "" },
  { title: "הנה היא נכנסת", artist: "דודו אהרון", year: 2012, youtubeId: "" },
  { title: "הלב", artist: "דודו אהרון", year: 2013, youtubeId: "" },
  { title: "כמוך לא אמצא", artist: "דודו אהרון", year: 2013, youtubeId: "" },
  { title: "ימים טובים", artist: "דודו אהרון", year: 2013, youtubeId: "" },
  { title: "נתתי לך ללכת", artist: "דודו אהרון", year: 2015, youtubeId: "" },
  { title: "משהו קורה פה", artist: "דודו אהרון", year: 2015, youtubeId: "" },
  { title: "שם טבעת עליה", artist: "דודו אהרון", year: 2016, youtubeId: "" },
  { title: "ירוק ודבש", artist: "דודו אהרון", year: 2016, youtubeId: "" },
  { title: "השיר שלך", artist: "דודו אהרון", year: 2017, youtubeId: "" },
  { title: "כל הבנות", artist: "דודו אהרון", year: 2017, youtubeId: "" },
  { title: "חושב עליה", artist: "דודו אהרון", year: 2017, youtubeId: "" },
  { title: "שיכורים מאהבה", artist: "עדן בן זקן", year: 2015, youtubeId: "" },
  { title: "פיסה מזכרוני", artist: "עדן בן זקן", year: 2015, youtubeId: "" },
  { title: "אלבינה", artist: "עדן בן זקן", year: 2015, youtubeId: "" },
  { title: "תאמין לי", artist: "עדן בן זקן", year: 2016, youtubeId: "" },
  { title: "אף אחד", artist: "עדן בן זקן", year: 2016, youtubeId: "" },
  { title: "אין לי אותך", artist: "עדן בן זקן", year: 2016, youtubeId: "" },
  { title: "לזאת שניצחה", artist: "עדן בן זקן", year: 2017, youtubeId: "" },
  { title: "רציתי", artist: "עדן בן זקן", year: 2017, youtubeId: "" },
  { title: "כולם באילת", artist: "עדן בן זקן", year: 2017, youtubeId: "" },
  { title: "צועקת", artist: "עדן בן זקן", year: 2017, youtubeId: "" },
  { title: "חיים שלי", artist: "עדן בן זקן", year: 2018, youtubeId: "" },
  { title: "מקסיקו", artist: "עדן בן זקן", year: 2018, youtubeId: "" },
  { title: "מילה של גבר", artist: "עדן בן זקן", year: 2018, youtubeId: "" },
  { title: "חצי מדינה", artist: "עדן בן זקן", year: 2019, youtubeId: "" },
  { title: "אגרוף", artist: "עדן בן זקן", year: 2019, youtubeId: "" },
  { title: "יש בי אהבה", artist: "נועה קירל", year: 2015, youtubeId: "" },
  { title: "רק אתה", artist: "נועה קירל", year: 2016, youtubeId: "" },
  { title: "חצי משוגע", artist: "נועה קירל", year: 2016, youtubeId: "" },
  { title: "תן לי סימן", artist: "נועה קירל", year: 2016, youtubeId: "" },
  { title: "מקום לשינוי", artist: "נועה קירל", year: 2017, youtubeId: "" },
  { title: "לרקוד", artist: "נועה קירל", year: 2017, youtubeId: "" },
  { title: "כמעט מפורסמת", artist: "נועה קירל", year: 2017, youtubeId: "" },
  { title: "בא לי אותך", artist: "נועה קירל", year: 2018, youtubeId: "" },
  { title: "סינדרלה", artist: "נועה קירל", year: 2018, youtubeId: "" },
  { title: "אמא שלי", artist: "נועה קירל", year: 2019, youtubeId: "" },
  { title: "חצוף", artist: "נועה קירל", year: 2019, youtubeId: "" },
  { title: "תן למוזיקה לדבר", artist: "סאבלימינל", year: 2018, youtubeId: "" },
  { title: "הדור הזה שלנו", artist: "התקווה 6", year: 2012, youtubeId: "" },
  { title: "עוד פעם פעם", artist: "התקווה 6", year: 2014, youtubeId: "" },
  { title: "הכי ישראלי", artist: "התקווה 6", year: 2014, youtubeId: "" },
  { title: "קופנגן", artist: "התקווה 6", year: 2016, youtubeId: "" },
  { title: "שים עין עלינו", artist: "התקווה 6", year: 2016, youtubeId: "" },
  { title: "הכל עוד לפניי", artist: "התקווה 6", year: 2017, youtubeId: "" },
  { title: "העברית החדשה", artist: "התקווה 6", year: 2019, youtubeId: "" },
  { title: "אבן ספיר", artist: "אהוד בנאי", year: 2011, youtubeId: "" },
  { title: "זמן של מספרים", artist: "ברי סחרוף", year: 2011, youtubeId: "" },
  { title: "אדם", artist: "ברי סחרוף", year: 2015, youtubeId: "" },
  { title: "סלסולים", artist: "סטטיק ובן אל", year: 2016, youtubeId: "" },
  { title: "סתם", artist: "סטטיק ובן אל", year: 2016, youtubeId: "" },
  { title: "הכל לטובה", artist: "סטטיק ובן אל", year: 2017, youtubeId: "" },
  { title: "נמסטה", artist: "סטטיק ובן אל", year: 2018, youtubeId: "" },
  { title: "בננות", artist: "סטטיק ובן אל", year: 2019, youtubeId: "" },
  { title: "סליחה", artist: "פאר טסי", year: 2012, youtubeId: "" },
  { title: "תחזרי", artist: "פאר טסי", year: 2013, youtubeId: "" },
  { title: "כמו שיכור", artist: "פאר טסי", year: 2013, youtubeId: "" },
  { title: "דפיקות הלב", artist: "פאר טסי", year: 2013, youtubeId: "" },
  { title: "בלי לומר שלום", artist: "פאר טסי", year: 2013, youtubeId: "" },
  { title: "רוקד עם הכאב", artist: "פאר טסי", year: 2014, youtubeId: "" },
  { title: "אל תהיי עצובה", artist: "פאר טסי", year: 2014, youtubeId: "" },
  { title: "בואי ניפגש", artist: "פאר טסי", year: 2014, youtubeId: "" },
  { title: "היי מאמא", artist: "פאר טסי", year: 2015, youtubeId: "" },
  { title: "אם תחכי לי", artist: "פאר טסי", year: 2015, youtubeId: "" },
  { title: "כמה דמעות", artist: "פאר טסי", year: 2016, youtubeId: "" },
  { title: "כמה טוב", artist: "פאר טסי", year: 2016, youtubeId: "" },
  { title: "רוקדת", artist: "פאר טסי", year: 2019, youtubeId: "" },
  { title: "שלוש בלילה", artist: "פאר טסי", year: 2019, youtubeId: "" },
  { title: "מי אני", artist: "פאר טסי", year: 2019, youtubeId: "" },
  { title: "הולך ומתרחק", artist: "פאר טסי", year: 2019, youtubeId: "" },
  { title: "חורף בחלון", artist: "פאר טסי", year: 2019, youtubeId: "" },
  { title: "ברגעים שאת הולכת", artist: "אושר כהן", year: 2018, youtubeId: "" },
  { title: "מה הוא יודע", artist: "אושר כהן", year: 2019, youtubeId: "" },
  { title: "מה את עושה לי", artist: "אושר כהן", year: 2019, youtubeId: "" },
  { title: "אני שונא אותך", artist: "אושר כהן", year: 2019, youtubeId: "" },
  { title: "ציפרלקס", artist: "אושר כהן", year: 2019, youtubeId: "" },
  { title: "למחוק את הזמן", artist: "מרגלית צנעני", year: 2011, youtubeId: "" },
  { title: "רחוק מכאן", artist: "מרגלית צנעני", year: 2016, youtubeId: "" },
  { title: "יאמה", artist: "מרגלית צנעני", year: 2018, youtubeId: "" },
  { title: "גרביטציה", artist: "אריק ברמן", year: 2013, youtubeId: "" },
  { title: "התמונה הגדולה", artist: "אריק ברמן", year: 2015, youtubeId: "" },
  { title: "את לא מספיק יפה", artist: "אריק ברמן", year: 2017, youtubeId: "" },
  { title: "מסונוורת", artist: "יובל דיין", year: 2012, youtubeId: "" },
  { title: "לאסוף", artist: "יובל דיין", year: 2013, youtubeId: "" },
  { title: "פעם אחת", artist: "יובל דיין", year: 2013, youtubeId: "" },
  { title: "צבעים", artist: "יובל דיין", year: 2014, youtubeId: "" },
  { title: "בשעה טובה", artist: "יובל דיין", year: 2015, youtubeId: "" },
  { title: "ליבי ער", artist: "יובל דיין", year: 2016, youtubeId: "" },
  { title: "לילותיי", artist: "יובל דיין", year: 2016, youtubeId: "" },
  { title: "הסוף הטוב הזה", artist: "יובל דיין", year: 2018, youtubeId: "" },
  { title: "דמעות שקופות", artist: "יובל דיין", year: 2018, youtubeId: "" },
  { title: "לפתוח את הלב", artist: "יובל דיין", year: 2019, youtubeId: "" },
  { title: "תהיה לי אהבה", artist: "הראל סקעת", year: 2011, youtubeId: "" },
  { title: "המאה ה-21", artist: "הראל סקעת", year: 2012, youtubeId: "" },
  { title: "עכשיו", artist: "הראל סקעת", year: 2013, youtubeId: "" },
  { title: "שיבואו עלינו", artist: "הראל סקעת", year: 2014, youtubeId: "" },
  { title: "צמרמורת", artist: "הראל סקעת", year: 2015, youtubeId: "" },
  { title: "את לי הכל", artist: "הראל סקעת", year: 2016, youtubeId: "" },
  { title: "אהבה מסובבת הכל", artist: "הראל סקעת", year: 2017, youtubeId: "" },
  { title: "בין השמיכות", artist: "הראל סקעת", year: 2017, youtubeId: "" },
  { title: "מקום ליותר", artist: "עברי לידר", year: 2015, youtubeId: "" },
  { title: "הכל בוער", artist: "עברי לידר", year: 2015, youtubeId: "" },
  { title: "מוגזם", artist: "עברי לידר", year: 2017, youtubeId: "" },
  { title: "נסיכה שלי", artist: "עברי לידר", year: 2018, youtubeId: "" },
  { title: "בננה", artist: "ארקדי דוכין", year: 2015, youtubeId: "" },
  { title: "שיר לאמיר", artist: "ארקדי דוכין", year: 2017, youtubeId: "" },
  { title: "בסה סבבה", artist: "נטע ברזילי", year: 2019, youtubeId: "" },
  { title: "נגד הרוח", artist: "אמיר דדון", year: 2011, youtubeId: "" },
  { title: "לא סתם", artist: "אמיר דדון", year: 2013, youtubeId: "" },
  { title: "רק לא לאחר", artist: "אמיר דדון", year: 2013, youtubeId: "" },
  { title: "יש אין סוף", artist: "אמיר דדון", year: 2013, youtubeId: "" },
  { title: "בגלגול אחר", artist: "אמיר דדון", year: 2013, youtubeId: "" },
  { title: "חיים פשוטים", artist: "אמיר דדון", year: 2013, youtubeId: "" },
  { title: "כל יום כמו נס", artist: "אמיר דדון", year: 2015, youtubeId: "" },
  { title: "אם הייתי מוכן", artist: "אמיר דדון", year: 2016, youtubeId: "" },
  { title: "גבעה אחת", artist: "אמיר דדון", year: 2016, youtubeId: "" },
  { title: "כשאהוד שר", artist: "אמיר דדון", year: 2017, youtubeId: "" },
  { title: "בואי נדבר בינינו", artist: "אמיר דדון", year: 2017, youtubeId: "" },
  { title: "בנאדם", artist: "אמיר דדון", year: 2018, youtubeId: "" },
  { title: "עדיין ילד", artist: "אמיר דדון", year: 2019, youtubeId: "" },
  { title: "בין קודש לחול", artist: "אמיר דדון", year: 2019, youtubeId: "" },
  { title: "רוצי קטנה", artist: "רמי קליינשטיין", year: 2012, youtubeId: "" },
  { title: "מתנות קטנות", artist: "רמי קליינשטיין", year: 2014, youtubeId: "" },
  { title: "תמר ואני", artist: "רמי קליינשטיין", year: 2014, youtubeId: "" },
  { title: "אנשים טובים", artist: "רמי קליינשטיין", year: 2015, youtubeId: "" },
  { title: "בסוף כולם חוזרים הביתה", artist: "רמי קליינשטיין", year: 2017, youtubeId: "" },
  { title: "לאהבה בסוף נשוב", artist: "רמי קליינשטיין", year: 2018, youtubeId: "" },
  { title: "לב חופשי", artist: "דודו טסה", year: 2013, youtubeId: "" },
  { title: "גרמניה", artist: "דודו טסה", year: 2013, youtubeId: "" },
  { title: "גיבור", artist: "דודו טסה", year: 2018, youtubeId: "" },
  { title: "חלק מחיי", artist: "אייל גולן", year: 2011, youtubeId: "" },
  { title: "ללכת או להישאר", artist: "אייל גולן", year: 2011, youtubeId: "" },
  { title: "בואי נברח", artist: "אייל גולן", year: 2011, youtubeId: "" },
  { title: "רציתי להגיד לך", artist: "אייל גולן", year: 2011, youtubeId: "" },
  { title: "תמונה שבורה", artist: "אייל גולן", year: 2011, youtubeId: "" },
  { title: "מנגינה", artist: "אייל גולן", year: 2012, youtubeId: "" },
  { title: "נגעת לי בלב", artist: "אייל גולן", year: 2012, youtubeId: "" },
  { title: "קל כל כך", artist: "אייל גולן", year: 2013, youtubeId: "" },
  { title: "מבעד לדמעה", artist: "אייל גולן", year: 2013, youtubeId: "" },
  { title: "מתפלל", artist: "אייל גולן", year: 2013, youtubeId: "" },
  { title: "את", artist: "אייל גולן", year: 2013, youtubeId: "" },
  { title: "סטטוס מאוהב", artist: "אייל גולן", year: 2013, youtubeId: "" },
  { title: "כל החלומות", artist: "אייל גולן", year: 2013, youtubeId: "" },
  { title: "היא לא את", artist: "אייל גולן", year: 2013, youtubeId: "" },
  { title: "הלילה תרקדי", artist: "אייל גולן", year: 2014, youtubeId: "" },
  { title: "צללים של דמותה", artist: "אייל גולן", year: 2014, youtubeId: "" },
  { title: "שמור עליו", artist: "אייל גולן", year: 2014, youtubeId: "" },
  { title: "שוב לאהוב", artist: "אייל גולן", year: 2014, youtubeId: "" },
  { title: "טוב לך איתו", artist: "אייל גולן", year: 2016, youtubeId: "" },
  { title: "בלי להתכוון", artist: "אייל גולן", year: 2017, youtubeId: "" },
  { title: "יפה לך להיות מאושרת", artist: "אייל גולן", year: 2017, youtubeId: "" },
  { title: "כמו בספרים ההם", artist: "אייל גולן", year: 2018, youtubeId: "" },
  { title: "נכון להיום", artist: "אייל גולן", year: 2018, youtubeId: "" },
  { title: "עוד דקה את נעלמת", artist: "אייל גולן", year: 2018, youtubeId: "" },
  { title: "אסתדר לבד", artist: "אייל גולן", year: 2018, youtubeId: "" },
  { title: "אהיה בכל מקום", artist: "אייל גולן", year: 2018, youtubeId: "" },
  { title: "לא מבינה עברית", artist: "אייל גולן", year: 2018, youtubeId: "" },
  { title: "אהבה ראשונה", artist: "אייל גולן", year: 2019, youtubeId: "" },
  { title: "הפוך מהיקום", artist: "אייל גולן", year: 2019, youtubeId: "" },
  { title: "אם היה לי", artist: "דנה ברגר", year: 2011, youtubeId: "" },
  { title: "דלתות נפתחות", artist: "דנה ברגר", year: 2011, youtubeId: "" },
  { title: "כולם צודקים", artist: "דנה ברגר", year: 2012, youtubeId: "" },
  { title: "מתנות של זמן", artist: "דנה ברגר", year: 2014, youtubeId: "" },
  { title: "לבנות ולהרוס", artist: "דנה ברגר", year: 2014, youtubeId: "" },
  { title: "הקירות שלי", artist: "דנה ברגר", year: 2014, youtubeId: "" },
  { title: "תראה אותך", artist: "דנה ברגר", year: 2014, youtubeId: "" },
  { title: "לא ליפול", artist: "דנה ברגר", year: 2015, youtubeId: "" },
  { title: "נגן", artist: "דנה ברגר", year: 2017, youtubeId: "" },
  { title: "ימים צפופים", artist: "דנה ברגר", year: 2017, youtubeId: "" },
  { title: "אתה לא בבית", artist: "דנה ברגר", year: 2017, youtubeId: "" },
  { title: "מהפכה", artist: "דנה ברגר", year: 2017, youtubeId: "" },
  { title: "בן חייל", artist: "דנה ברגר", year: 2018, youtubeId: "" },
  { title: "מגנטים", artist: "דנה ברגר", year: 2019, youtubeId: "" },
  { title: "את בנשמה", artist: "שלומי שבת", year: 2011, youtubeId: "" },
  { title: "כשאתה", artist: "שלומי שבת", year: 2012, youtubeId: "" },
  { title: "מתאהב בך", artist: "שלומי שבת", year: 2012, youtubeId: "" },
  { title: "גשם אהבה", artist: "שלומי שבת", year: 2012, youtubeId: "" },
  { title: "אין לי שקט", artist: "שלומי שבת", year: 2015, youtubeId: "" },
  { title: "רפסודה", artist: "שלומי שבת", year: 2015, youtubeId: "" },
  { title: "איתך", artist: "שלומי שבת", year: 2019, youtubeId: "" },
  { title: "כל מה שיש לי", artist: "נתן גושן", year: 2011, youtubeId: "" },
  { title: "אם את הולכת", artist: "אברהם טל", year: 2011, youtubeId: "" },
  { title: "יש לך", artist: "שלומי שבת", year: 2012, youtubeId: "" },
  { title: "זיקוקים", artist: "משה פרץ", year: 2012, youtubeId: "" },
  { title: "אלוהיי", artist: "שלמה ארצי ואברהם טל", year: 2012, youtubeId: "" },
  { title: "נגמר", artist: "עידן רייכל", year: 2013, youtubeId: "" },
  { title: "עוד", artist: "נתן גושן", year: 2013, youtubeId: "" },
  { title: "אני לא מפסיק להתרגש ממך", artist: "דני רובס", year: 2013, youtubeId: "" },
  { title: "כל מה שצריך", artist: "כפיר צפריר", year: 2018, youtubeId: "" },
  { title: "מונה ליזה", artist: "כפיר צפריר", year: 2019, youtubeId: "" },
  { title: "דפוקות", artist: "כפיר צפריר", year: 2019, youtubeId: "" },
  { title: "יהיה בסדר", artist: "רביד פלוטניק", year: 2014, youtubeId: "" },
  { title: "חסידה צחורה", artist: "רביד פלוטניק", year: 2015, youtubeId: "" },
  { title: "אני כאן לשבור", artist: "רביד פלוטניק", year: 2016, youtubeId: "" },
  { title: "כל הזמן הזה", artist: "רביד פלוטניק", year: 2017, youtubeId: "" },
  { title: "ניפגש בשמחות", artist: "עומר אדם", year: 2020, youtubeId: "" },
  { title: "כתבתי עלייך שיר", artist: "עומר אדם", year: 2020, youtubeId: "" },
  { title: "יש דברים שלא עושים", artist: "עומר אדם", year: 2020, youtubeId: "" },
  { title: "השתגע העולם", artist: "עומר אדם", year: 2020, youtubeId: "" },
  { title: "פרצופים", artist: "עומר אדם", year: 2021, youtubeId: "" },
  { title: "ירושלים", artist: "עומר אדם", year: 2021, youtubeId: "" },
  { title: "סטלות", artist: "עומר אדם", year: 2023, youtubeId: "" },
  { title: "לא לבד", artist: "עומר אדם", year: 2023, youtubeId: "" },
  { title: "ראיתי עולם", artist: "עומר אדם", year: 2024, youtubeId: "" },
  { title: "עברנו הכל", artist: "עומר אדם", year: 2024, youtubeId: "" },
  { title: "חי", artist: "עומר אדם", year: 2025, youtubeId: "" },
  { title: "כשהכל יגמר", artist: "שרית חדד", year: 2020, youtubeId: "" },
  { title: "אהבה כמו שלנו", artist: "שרית חדד", year: 2021, youtubeId: "" },
  { title: "חוף מבטחים", artist: "שרית חדד", year: 2022, youtubeId: "" },
  { title: "אוהבת אותך", artist: "שרית חדד", year: 2022, youtubeId: "" },
  { title: "אתה אני ואלוקים", artist: "שרית חדד", year: 2023, youtubeId: "" },
  { title: "איפה היית", artist: "שרית חדד", year: 2023, youtubeId: "" },
  { title: "לא בבית", artist: "שרית חדד", year: 2024, youtubeId: "" },
  { title: "מה נשאר", artist: "משה פרץ", year: 2022, youtubeId: "" },
  { title: "דון חוליו", artist: "משה פרץ", year: 2022, youtubeId: "" },
  { title: "קרובים", artist: "משה פרץ", year: 2023, youtubeId: "" },
  { title: "געגוע", artist: "משה פרץ", year: 2023, youtubeId: "" },
  { title: "לזוז", artist: "משה פרץ", year: 2023, youtubeId: "" },
  { title: "הללויה", artist: "משה פרץ", year: 2024, youtubeId: "" },
  { title: "רק אהבה", artist: "קובי פרץ", year: 2024, youtubeId: "" },
  { title: "פרחים וכינורות", artist: "קובי פרץ", year: 2024, youtubeId: "" },
  { title: "תודה עלייך", artist: "קובי פרץ", year: 2024, youtubeId: "" },
  { title: "הלב לא שוכח", artist: "קובי פרץ", year: 2026, youtubeId: "" },
  { title: "אהבה זה דמעות", artist: "ליאור נרקיס", year: 2020, youtubeId: "" },
  { title: "חלקת אלוהים", artist: "ליאור נרקיס", year: 2021, youtubeId: "" },
  { title: "חיבוק", artist: "ליאור נרקיס", year: 2021, youtubeId: "" },
  { title: "עד סוף העולם שלי", artist: "ליאור נרקיס", year: 2021, youtubeId: "" },
  { title: "הוויסקי והיין", artist: "ליאור נרקיס", year: 2023, youtubeId: "" },
  { title: "פרחים ודמעות", artist: "ליאור נרקיס", year: 2023, youtubeId: "" },
  { title: "וואלק מי", artist: "ליאור נרקיס", year: 2023, youtubeId: "" },
  { title: "מאמי", artist: "ליאור נרקיס", year: 2023, youtubeId: "" },
  { title: "יש כאן טוב", artist: "ליאור נרקיס", year: 2024, youtubeId: "" },
  { title: "נגמר", artist: "ליאור נרקיס", year: 2024, youtubeId: "" },
  { title: "אלף סליחות", artist: "ליאור נרקיס", year: 2024, youtubeId: "" },
  { title: "בא לי", artist: "זהבה בן", year: 2020, youtubeId: "" },
  { title: "אולי בעולם אחר", artist: "זהבה בן", year: 2021, youtubeId: "" },
  { title: "בצורת", artist: "אביב גפן", year: 2020, youtubeId: "" },
  { title: "מבולבל", artist: "יהודה פוליקר", year: 2023, youtubeId: "" },
  { title: "בומבה", artist: "הדג נחש", year: 2020, youtubeId: "" },
  { title: "אנה אנחנו", artist: "הדג נחש", year: 2020, youtubeId: "" },
  { title: "אי אפשר לשקר את הלב", artist: "הדג נחש", year: 2023, youtubeId: "" },
  { title: "למה ככה עצובה", artist: "עידן רייכל", year: 2020, youtubeId: "" },
  { title: "מכל הכוכבים בלילה", artist: "עידן רייכל", year: 2020, youtubeId: "" },
  { title: "ככה מיום ליום", artist: "עידן רייכל", year: 2021, youtubeId: "" },
  { title: "אבן על אבן", artist: "עידן רייכל", year: 2021, youtubeId: "" },
  { title: "כמה שרחוק", artist: "עידן רייכל", year: 2022, youtubeId: "" },
  { title: "ציפור בלי שמיים", artist: "עידן רייכל", year: 2023, youtubeId: "" },
  { title: "ארץ", artist: "עידן רייכל", year: 2025, youtubeId: "" },
  { title: "כתר מלוכה", artist: "ישי ריבו", year: 2020, youtubeId: "" },
  { title: "תכף יפתח", artist: "ישי ריבו", year: 2022, youtubeId: "" },
  { title: "אני שייך לעם", artist: "ישי ריבו", year: 2023, youtubeId: "" },
  { title: "פורחים לשובם", artist: "ישי ריבו", year: 2024, youtubeId: "" },
  { title: "אין לי מלבדך", artist: "ישי ריבו", year: 2024, youtubeId: "" },
  { title: "ארץ ישראל", artist: "ישי ריבו", year: 2024, youtubeId: "" },
  { title: "עוד ישמע", artist: "ישי ריבו", year: 2025, youtubeId: "" },
  { title: "אמן על הילדים", artist: "חנן בן ארי", year: 2020, youtubeId: "" },
  { title: "חולם כמו יוסף", artist: "חנן בן ארי", year: 2021, youtubeId: "" },
  { title: "מקום", artist: "חנן בן ארי", year: 2021, youtubeId: "" },
  { title: "בסוף זה הלחן", artist: "חנן בן ארי", year: 2022, youtubeId: "" },
  { title: "חנניה", artist: "חנן בן ארי", year: 2022, youtubeId: "" },
  { title: "עטלף עיוור", artist: "חנן בן ארי", year: 2023, youtubeId: "" },
  { title: "מולדת", artist: "חנן בן ארי", year: 2023, youtubeId: "" },
  { title: "היום קמתי שמח", artist: "חנן בן ארי", year: 2025, youtubeId: "" },
  { title: "אחי", artist: "חנן בן ארי", year: 2025, youtubeId: "" },
  { title: "מבול", artist: "דודו אהרון", year: 2020, youtubeId: "" },
  { title: "לגעת בשמיים", artist: "דודו אהרון", year: 2023, youtubeId: "" },
  { title: "דובדבן", artist: "דודו אהרון", year: 2025, youtubeId: "" },
  { title: "ברחובות של תל אביב", artist: "עדן בן זקן", year: 2021, youtubeId: "" },
  { title: "ממתק", artist: "עדן בן זקן", year: 2021, youtubeId: "" },
  { title: "מה קרה", artist: "עדן בן זקן", year: 2022, youtubeId: "" },
  { title: "כינורות", artist: "עדן בן זקן", year: 2022, youtubeId: "" },
  { title: "ריגוש זמני", artist: "עדן בן זקן", year: 2023, youtubeId: "" },
  { title: "דם שלי", artist: "עדן בן זקן", year: 2024, youtubeId: "" },
  { title: "אם אתה גבר", artist: "נועה קירל", year: 2020, youtubeId: "" },
  { title: "בנות כמוני לא בוכות", artist: "נועה קירל", year: 2024, youtubeId: "" },
  { title: "שיהיה לך טוב", artist: "נועה קירל", year: 2024, youtubeId: "" },
  { title: "חושב שאתה מסי", artist: "נועה קירל", year: 2025, youtubeId: "" },
  { title: "חי על הירח", artist: "התקווה 6", year: 2020, youtubeId: "" },
  { title: "המנון הלוחם", artist: "התקווה 6", year: 2021, youtubeId: "" },
  { title: "ילדים של החיים", artist: "התקווה 6", year: 2022, youtubeId: "" },
  { title: "החיים זה עכשיו", artist: "התקווה 6", year: 2023, youtubeId: "" },
  { title: "איש הצל", artist: "אהוד בנאי", year: 2023, youtubeId: "" },
  { title: "אמאלה", artist: "סטטיק ובן אל", year: 2020, youtubeId: "" },
  { title: "קוביות", artist: "סטטיק ובן אל", year: 2020, youtubeId: "" },
  { title: "קקטוס", artist: "סטטיק ובן אל", year: 2021, youtubeId: "" },
  { title: "כוסות ריקות", artist: "סטטיק ובן אל", year: 2021, youtubeId: "" },
  { title: "קרנבל", artist: "סטטיק ובן אל", year: 2022, youtubeId: "" },
  { title: "לא תירא", artist: "פאר טסי", year: 2023, youtubeId: "" },
  { title: "38", artist: "פאר טסי", year: 2023, youtubeId: "" },
  { title: "פרפר", artist: "פאר טסי", year: 2025, youtubeId: "" },
  { title: "עוף מוזר", artist: "פאר טסי", year: 2025, youtubeId: "" },
  { title: "כל הזמן אומרת", artist: "אושר כהן", year: 2020, youtubeId: "" },
  { title: "הריני מקשר", artist: "אושר כהן", year: 2020, youtubeId: "" },
  { title: "מי עוד יחבק", artist: "אושר כהן", year: 2020, youtubeId: "" },
  { title: "תחזרי מהר", artist: "אושר כהן", year: 2020, youtubeId: "" },
  { title: "אני אוהב אותך", artist: "אושר כהן", year: 2021, youtubeId: "" },
  { title: "זוגות כאלה", artist: "אושר כהן", year: 2021, youtubeId: "" },
  { title: "מקבל על עצמי", artist: "אושר כהן", year: 2022, youtubeId: "" },
  { title: "חמישי שישי", artist: "אושר כהן", year: 2022, youtubeId: "" },
  { title: "אהובי לב אדום", artist: "אושר כהן", year: 2022, youtubeId: "" },
  { title: "תרקדי", artist: "אושר כהן", year: 2023, youtubeId: "" },
  { title: "קווים לדמותו", artist: "אושר כהן", year: 2023, youtubeId: "" },
  { title: "איך שאת אוהבת", artist: "אושר כהן", year: 2023, youtubeId: "" },
  { title: "אין כמו בבית", artist: "אושר כהן", year: 2024, youtubeId: "" },
  { title: "לופ", artist: "אושר כהן", year: 2024, youtubeId: "" },
  { title: "אתה בכולם", artist: "יובל דיין", year: 2021, youtubeId: "" },
  { title: "קרוב בינינו", artist: "יובל דיין", year: 2021, youtubeId: "" },
  { title: "תישארי את", artist: "יובל דיין", year: 2023, youtubeId: "" },
  { title: "תפילה לעני", artist: "יובל דיין", year: 2024, youtubeId: "" },
  { title: "החיים רצים קדימה", artist: "הראל סקעת", year: 2022, youtubeId: "" },
  { title: "הרגע הריק", artist: "עברי לידר", year: 2021, youtubeId: "" },
  { title: "אבא", artist: "אמיר דדון", year: 2020, youtubeId: "" },
  { title: "הרוח הטובה", artist: "אמיר דדון", year: 2021, youtubeId: "" },
  { title: "מעגל החיים", artist: "אמיר דדון", year: 2023, youtubeId: "" },
  { title: "ילדה קטנה כותבת מכתב", artist: "אמיר דדון", year: 2024, youtubeId: "" },
  { title: "ואפילו בהסתרה", artist: "אמיר דדון", year: 2025, youtubeId: "" },
  { title: "עפיפונים", artist: "אמיר דדון", year: 2025, youtubeId: "" },
  { title: "אין אותנו יותר", artist: "אבי אבורומי ומור", year: 2023, youtubeId: "" },
  { title: "רונדלים", artist: "סטטיק", year: 2023, youtubeId: "" },
  { title: "משוגעת", artist: "גל אדם ונורוז", year: 2023, youtubeId: "" },
  { title: "עיר נמל", artist: "אייל גולן", year: 2023, youtubeId: "" },
  { title: "מתי את חוזרת", artist: "אייל גולן", year: 2023, youtubeId: "" },
  { title: "מי את היום בלעדיי", artist: "יונתן קלימי", year: 2023, youtubeId: "" },
  { title: "טרנטולה", artist: "סטטיק ואגם בוחבוט", year: 2023, youtubeId: "" },
  { title: "ברולטה", artist: "ערן יוסף, עידו בי ושגב", year: 2023, youtubeId: "" },
  { title: "אינטלקטוערסית", artist: "אודיה", year: 2023, youtubeId: "" },
  { title: "קומה 58", artist: "עומר אדם", year: 2023, youtubeId: "" },
  { title: "יצאה שבת", artist: "עומר אדם", year: 2023, youtubeId: "" },
  { title: "סיגליות", artist: "עומר אדם ודיויד ברוזה", year: 2023, youtubeId: "" },
  { title: "התעוררתי עם נמר", artist: "עומר אדם ואיזי", year: 2023, youtubeId: "" },
  { title: "גושפנקא", artist: "איזי ונועה קירל", year: 2023, youtubeId: "" },
  { title: "משהו אמיתי בעיניים", artist: "ששון איפרם שאולוב", year: 2024, youtubeId: "" },
  { title: "אם אתה שלי", artist: "אודיה", year: 2024, youtubeId: "" },
  { title: "ואיך שלא", artist: "עומר אדם", year: 2024, youtubeId: "" },
  { title: "בואי נדבר", artist: "ששון איפרם שאולוב", year: 2024, youtubeId: "" },
  { title: "צוחקת ובוכה", artist: "עדן חסון", year: 2024, youtubeId: "" },
  { title: "לילות וקללות", artist: "עומר אדם", year: 2024, youtubeId: "" },
  { title: "מערב ראשון", artist: "איתי לוי", year: 2024, youtubeId: "" },
  { title: "יהיה טוב ומים שקופים", artist: "יסמין מועלם ועומר אדם", year: 2024, youtubeId: "" },
  { title: "38 וחוץ מכדורגל", artist: "פאר טסי וחנן בן ארי", year: 2024, youtubeId: "" },
  { title: "אקדח", artist: "עומר אדם", year: 2024, youtubeId: "" },
  { title: "כוכבים", artist: "שילה בן סעדון", year: 2024, youtubeId: "" },
  { title: "שלום אהובתי", artist: "אייל גולן", year: 2024, youtubeId: "" },
  { title: "אין אותי", artist: "אושר כהן ונועה קירל", year: 2024, youtubeId: "" },
  { title: "באמפרים", artist: "נס וסטילה", year: 2024, youtubeId: "" },
  { title: "איפה אתה", artist: "אושר כהן", year: 2024, youtubeId: "" },
  { title: "עזבת ת'בית", artist: "פלד ונסטיה רוד", year: 2024, youtubeId: "" },
  { title: "גן עדן של משוגעים", artist: "ששון איפרם שאולוב", year: 2024, youtubeId: "" },
  { title: "כסף או דמעות", artist: "עומר אדם", year: 2024, youtubeId: "" },
  { title: "שכחתי מזמן", artist: "אייל גולן", year: 2024, youtubeId: "" },
  { title: "פזמון אחר", artist: "אייל גולן", year: 2024, youtubeId: "" },
  { title: "ג'וני", artist: "בר צברי", year: 2021, youtubeId: "" },
  { title: "בין קודש לחול", artist: "אמיר דדון ושולי רנד", year: 2020, youtubeId: "" },
  { title: "נראתה לאחרונה", artist: "אייל גולן", year: 2020, youtubeId: "" },
  { title: "רכבת הרים", artist: "אייל גולן", year: 2020, youtubeId: "" },
  { title: "וי כחול", artist: "אייל גולן", year: 2021, youtubeId: "" },
  { title: "ארמון בחול", artist: "אייל גולן", year: 2021, youtubeId: "" },
  { title: "תמיד נשארת", artist: "אייל גולן", year: 2021, youtubeId: "" },
  { title: "מילה טובה", artist: "אייל גולן", year: 2021, youtubeId: "" },
  { title: "סוף של כל סיפור", artist: "אייל גולן", year: 2022, youtubeId: "" },
  { title: "החדר מסתובב", artist: "אייל גולן", year: 2025, youtubeId: "" },
  { title: "טק טק", artist: "אייל גולן", year: 2025, youtubeId: "" },
  { title: "עטופה ומוגנת", artist: "דנה ברגר", year: 2024, youtubeId: "" },
  { title: "בוא הביתה", artist: "שלומי שבת", year: 2021, youtubeId: "" },
  { title: "גם אם טעיתי", artist: "שלומי שבת", year: 2021, youtubeId: "" },
  { title: "כמה את יפה לי היום", artist: "שלומי שבת", year: 2022, youtubeId: "" },
  { title: "רגעים", artist: "שלומי שבת", year: 2022, youtubeId: "" },
  { title: "חלום ישן", artist: "שלומי שבת", year: 2023, youtubeId: "" },
  { title: "כמו הרוחות", artist: "שלומי שבת", year: 2023, youtubeId: "" },
  { title: "מכתב מיוסי", artist: "שלומי שבת", year: 2024, youtubeId: "" },
  { title: "בואי אמא", artist: "שלומי שבת", year: 2024, youtubeId: "" },
  { title: "מגדלים", artist: "נס וסטילה", year: 2024, youtubeId: "" },
  { title: "מי כמוני", artist: "נס וסטילה", year: 2026, youtubeId: "" },
  { title: "מונולוג", artist: "נס וסטילה", year: 2026, youtubeId: "" },
  { title: "מתגעגעת", artist: "כפיר צפריר", year: 2020, youtubeId: "" },
  { title: "כוכב אחר", artist: "כפיר צפריר", year: 2020, youtubeId: "" },
  { title: "גבוה", artist: "כפיר צפריר", year: 2020, youtubeId: "" },
  { title: "חרקות", artist: "כפיר צפריר", year: 2021, youtubeId: "" },
  { title: "סרט פשע", artist: "כפיר צפריר", year: 2022, youtubeId: "" },
  { title: "ירוק בדם", artist: "כפיר צפריר", year: 2023, youtubeId: "" },
  { title: "פסנתר", artist: "יגל אושרי", year: 2020, youtubeId: "" },
  { title: "בר-אל", artist: "יגל אושרי", year: 2021, youtubeId: "" },
  { title: "סיני וגיטרה", artist: "יגל אושרי", year: 2021, youtubeId: "" },
  { title: "למה לך לטוס", artist: "יגל אושרי", year: 2021, youtubeId: "" },
  { title: "אף אחד לא מושלם", artist: "יגל אושרי", year: 2022, youtubeId: "" },
  { title: "מזל טוב", artist: "יגל אושרי", year: 2022, youtubeId: "" },
  { title: "אופניים", artist: "יגל אושרי", year: 2022, youtubeId: "" },
  { title: "סוף העולם", artist: "יגל אושרי", year: 2022, youtubeId: "" },
  { title: "לא תמיד צודקת", artist: "יגל אושרי", year: 2023, youtubeId: "" },
  { title: "חברים", artist: "יגל אושרי", year: 2024, youtubeId: "" },
  { title: "תפילה", artist: "יגל אושרי", year: 2024, youtubeId: "" },
  { title: "להאמין", artist: "יגל אושרי", year: 2024, youtubeId: "" },
  { title: "נמשך אלייך", artist: "יגל אושרי", year: 2024, youtubeId: "" },
  { title: "אני אשמור עלייך", artist: "יגל אושרי", year: 2024, youtubeId: "" },
  { title: "סימן שאנחנו מגזימים", artist: "אנה זק", year: 2020, youtubeId: "" },
  { title: "שמור על העולם", artist: "אנה זק", year: 2021, youtubeId: "" },
  { title: "לך לישון", artist: "אנה זק", year: 2022, youtubeId: "" },
  { title: "מי זאת", artist: "אנה זק", year: 2022, youtubeId: "" },
  { title: "כולם מזיזים", artist: "אנה זק", year: 2023, youtubeId: "" },
  { title: "הבו לנו זמר", artist: "נעמי שמר", year: 1957, youtubeId: "" },
  { title: "אהבתי ילדה", artist: "יגאל בשן", year: 1969, youtubeId: "" },
  { title: "ירושלים של זהב", artist: "נעמי שמר", year: 1967, youtubeId: "" },
  { title: "רוח רוח", artist: "שלום חנוך", year: 1968, youtubeId: "" },
  { title: "להשתחרר", artist: "יגאל בשן", year: 1972, youtubeId: "" },
  { title: "מה נשתנה", artist: "יגאל בשן", year: 1972, youtubeId: "" },
  { title: "יש לי ציפור קטנה בלב", artist: "יגאל בשן", year: 1974, youtubeId: "" },
  { title: "מכת שמש", artist: "יגאל בשן", year: 1978, youtubeId: "" },
  { title: "כל יום שעובר", artist: "זוהר ארגוב", year: 1977, youtubeId: "" },
  { title: "רציתי שתדע", artist: "עוזי חיטמן", year: 1977, youtubeId: "" },
  { title: "נולדתי לשלום", artist: "עוזי חיטמן", year: 1979, youtubeId: "" },
  { title: "לו יהי", artist: "נעמי שמר", year: 1973, youtubeId: "" },
  { title: "אצלנו בחצר", artist: "נעמי שמר", year: 1979, youtubeId: "" },
  { title: "החגיגה נגמרת", artist: "נעמי שמר", year: 1976, youtubeId: "" },
  { title: "ישאו הרים שלום", artist: "עופרה חזה", year: 1979, youtubeId: "" },
  { title: "קח לך אישה", artist: "שלום חנוך", year: 1970, youtubeId: "" },
  { title: "לך לפסיכיאטר", artist: "שלום חנוך", year: 1973, youtubeId: "" },
  { title: "שיר אהבה בדואי", artist: "דויד ברוזה", year: 1978, youtubeId: "" },
  { title: "טיפת מזל", artist: "זהבה בן", year: 1989, youtubeId: "" },
  { title: "יא חביבי", artist: "זהבה בן", year: 1989, youtubeId: "" },
  { title: "אפר ואבק", artist: "יהודה פוליקר", year: 1988, youtubeId: "" },
  { title: "בת יענה", artist: "יהודה פוליקר", year: 1989, youtubeId: "" },
  { title: "סיוון", artist: "יגאל בשן", year: 1980, youtubeId: "" },
  { title: "כוכבים בלילה", artist: "יגאל בשן", year: 1981, youtubeId: "" },
  { title: "עדה", artist: "יגאל בשן", year: 1984, youtubeId: "" },
  { title: "איזה לילה", artist: "יגאל בשן", year: 1985, youtubeId: "" },
  { title: "מטדור", artist: "חיים משה", year: 1981, youtubeId: "" },
  { title: "אמא", artist: "חיים משה", year: 1983, youtubeId: "" },
  { title: "תן לזמן ללכת", artist: "חיים משה", year: 1984, youtubeId: "" },
  { title: "תודה", artist: "חיים משה", year: 1986, youtubeId: "" },
  { title: "כל נדריי", artist: "חיים משה", year: 1987, youtubeId: "" },
  { title: "חי לאהבה", artist: "חיים משה", year: 1989, youtubeId: "" },
  { title: "שיר אהבה בלב", artist: "זוהר ארגוב", year: 1981, youtubeId: "" },
  { title: "הפרח בגני", artist: "זוהר ארגוב", year: 1982, youtubeId: "" },
  { title: "נכון להיום", artist: "זוהר ארגוב", year: 1982, youtubeId: "" },
  { title: "סיימתי מילואים", artist: "זוהר ארגוב", year: 1983, youtubeId: "" },
  { title: "יסמין", artist: "זוהר ארגוב", year: 1984, youtubeId: "" },
  { title: "להיות אדם", artist: "זוהר ארגוב", year: 1986, youtubeId: "" },
  { title: "בארץ הזאת", artist: "עוזי חיטמן", year: 1989, youtubeId: "" },
  { title: "תלבשי לבן", artist: "נעמי שמר", year: 1985, youtubeId: "" },
  { title: "אין לי רגע דל", artist: "נעמי שמר", year: 1980, youtubeId: "" },
  { title: "כמו ציפור", artist: "עופרה חזה", year: 1980, youtubeId: "" },
  { title: "סופרסטאר", artist: "עופרה חזה", year: 1983, youtubeId: "" },
  { title: "עזה כמוות", artist: "עופרה חזה", year: 1988, youtubeId: "" },
  { title: "עגל הזהב", artist: "אהוד בנאי", year: 1986, youtubeId: "" },
  { title: "כולם יודעים", artist: "אהוד בנאי", year: 1989, youtubeId: "" },
  { title: "שמור אותי", artist: "מרגלית צנעני", year: 1987, youtubeId: "" },
  { title: "אהבה אבודה", artist: "מרגלית צנעני", year: 1988, youtubeId: "" },
  { title: "אנטוניו", artist: "מרגלית צנעני", year: 1988, youtubeId: "" },
  { title: "ילד רע תל אביב", artist: "מרגלית צנעני", year: 1989, youtubeId: "" },
  { title: "בלדה לסוכן כפול", artist: "משינה", year: 1985, youtubeId: "" },
  { title: "רני בפריז", artist: "משינה", year: 1988, youtubeId: "" },
  { title: "לפעמים", artist: "ארקדי דוכין", year: 1988, youtubeId: "" },
  { title: "ארץ ישראל שלי", artist: "דתיה בן דור", year: 1980, youtubeId: "" },
  { title: "אני נקי", artist: "דתיה בן דור", year: 1980, youtubeId: "" },
  { title: "איך יודעים שבא אביב", artist: "דתיה בן דור", year: 1980, youtubeId: "" },
  { title: "עוד לא תמו כל פלאייך", artist: "רמי קליינשטיין", year: 1985, youtubeId: "" },
  { title: "את שרה ברדיו", artist: "רמי קליינשטיין", year: 1986, youtubeId: "" },
  { title: "אף פעם", artist: "רמי קליינשטיין", year: 1989, youtubeId: "" },
  { title: "מה קרה לחלום", artist: "רמי קליינשטיין", year: 1989, youtubeId: "" },
  { title: "עצים", artist: "שלום חנוך", year: 1980, youtubeId: "" },
  { title: "ירוק על ירוק", artist: "שלום חנוך", year: 1983, youtubeId: "" },
  { title: "אלה", artist: "שלום חנוך", year: 1986, youtubeId: "" },
  { title: "אוהבת אותך עוזבת אותך", artist: "שלום חנוך", year: 1986, youtubeId: "" },
  { title: "חיפה", artist: "דויד ברוזה", year: 1982, youtubeId: "" },
  { title: "האשה שאיתי", artist: "דויד ברוזה", year: 1983, youtubeId: "" },
  { title: "שלום חבר", artist: "שרית חדד", year: 1995, youtubeId: "" },
  { title: "הכל סגור", artist: "שרית חדד", year: 1998, youtubeId: "" },
  { title: "ירח שחור", artist: "שרית חדד", year: 1998, youtubeId: "" },
  { title: "כמו סינדרלה", artist: "שרית חדד", year: 1999, youtubeId: "" },
  { title: "כשאני איתך אני כמו דג", artist: "שרית חדד", year: 1999, youtubeId: "" },
  { title: "פטה מורגנה", artist: "דנה אינטרנשיונל", year: 1993, youtubeId: "" },
  { title: "ישנן בנות", artist: "דנה אינטרנשיונל", year: 1994, youtubeId: "" },
  { title: "נוסעת לפטרה", artist: "דנה אינטרנשיונל", year: 1994, youtubeId: "" },
  { title: "בתולה", artist: "דנה אינטרנשיונל", year: 1994, youtubeId: "" },
  { title: "אני רוצה לחיות", artist: "דנה אינטרנשיונל", year: 1995, youtubeId: "" },
  { title: "דיווה", artist: "דנה אינטרנשיונל", year: 1997, youtubeId: "" },
  { title: "עד סוף הזמן", artist: "דנה אינטרנשיונל", year: 1999, youtubeId: "" },
  { title: "כמו פרפר", artist: "ליאור נרקיס", year: 1994, youtubeId: "" },
  { title: "העולם כמו גלגל", artist: "ליאור נרקיס", year: 1995, youtubeId: "" },
  { title: "נשבע לא משקר", artist: "ליאור נרקיס", year: 1995, youtubeId: "" },
  { title: "לא מנסה", artist: "ליאור נרקיס", year: 1998, youtubeId: "" },
  { title: "טלפון האהבה", artist: "זהבה בן", year: 1990, youtubeId: "" },
  { title: "דף חדש", artist: "זהבה בן", year: 1992, youtubeId: "" },
  { title: "לחמניות", artist: "זהבה בן", year: 1999, youtubeId: "" },
  { title: "אמש", artist: "אביב גפן", year: 1991, youtubeId: "" },
  { title: "עכשיו מעונן", artist: "אביב גפן", year: 1993, youtubeId: "" },
  { title: "בוכה על הקבר", artist: "אביב גפן", year: 1993, youtubeId: "" },
  { title: "שומקום", artist: "אביב גפן", year: 1995, youtubeId: "" },
  { title: "יש לך אותי", artist: "אביב גפן", year: 1996, youtubeId: "" },
  { title: "המכתב", artist: "אביב גפן", year: 1996, youtubeId: "" },
  { title: "בוקר טוב איראן", artist: "אביב גפן", year: 1998, youtubeId: "" },
  { title: "רומיאו ויוליה", artist: "אביב גפן", year: 1999, youtubeId: "" },
  { title: "שושנים של פחם", artist: "יהודה פוליקר", year: 1992, youtubeId: "" },
  { title: "קין", artist: "יהודה פוליקר", year: 1995, youtubeId: "" },
  { title: "כמו גנב באפלה", artist: "יהודה פוליקר", year: 1995, youtubeId: "" },
  { title: "אלוהים", artist: "יגאל בשן", year: 1990, youtubeId: "" },
  { title: "הביתה", artist: "חיים משה", year: 1990, youtubeId: "" },
  { title: "איזו מין אישה", artist: "חיים משה", year: 1992, youtubeId: "" },
  { title: "אתמול", artist: "חיים משה", year: 1995, youtubeId: "" },
  { title: "סניוריטה", artist: "חיים משה", year: 1998, youtubeId: "" },
  { title: "כאן", artist: "עוזי חיטמן", year: 1991, youtubeId: "" },
  { title: "לתת", artist: "עופרה חזה", year: 1998, youtubeId: "" },
  { title: "מהרי נא", artist: "אהוד בנאי", year: 1996, youtubeId: "" },
  { title: "אמונה עיוורת", artist: "ברי סחרוף", year: 1991, youtubeId: "" },
  { title: "הזיות", artist: "ברי סחרוף", year: 1993, youtubeId: "" },
  { title: "עיר של קיץ", artist: "ברי סחרוף", year: 1998, youtubeId: "" },
  { title: "גן עדן", artist: "מרגלית צנעני", year: 1990, youtubeId: "" },
  { title: "במעגל", artist: "מרגלית צנעני", year: 1991, youtubeId: "" },
  { title: "התחנה המרכזית", artist: "מרגלית צנעני", year: 1992, youtubeId: "" },
  { title: "כתונת פסים", artist: "מרגלית צנעני", year: 1995, youtubeId: "" },
  { title: "בתי את בוכה או צוחקת", artist: "מרגלית צנעני", year: 1999, youtubeId: "" },
  { title: "איזה איש", artist: "משינה", year: 1992, youtubeId: "" },
  { title: "בנות הים", artist: "משינה", year: 1992, youtubeId: "" },
  { title: "דני", artist: "משינה", year: 1993, youtubeId: "" },
  { title: "לאונרדו", artist: "עברי לידר", year: 1997, youtubeId: "" },
  { title: "כמה כוכב", artist: "עברי לידר", year: 1997, youtubeId: "" },
  { title: "הכוס הכחולה", artist: "עברי לידר", year: 1999, youtubeId: "" },
  { title: "חדר משלי", artist: "ארקדי דוכין", year: 1995, youtubeId: "" },
  { title: "עניין של זמן", artist: "רמי קליינשטיין", year: 1992, youtubeId: "" },
  { title: "תשארי עוד קצת", artist: "רמי קליינשטיין", year: 1997, youtubeId: "" },
  { title: "הים כבר לא", artist: "רמי קליינשטיין", year: 1997, youtubeId: "" },
  { title: "בדיוק כמוך", artist: "שלום חנוך", year: 1991, youtubeId: "" },
  { title: "לאט לאט", artist: "שלום חנוך", year: 1994, youtubeId: "" },
  { title: "שלום חבר", artist: "שלום חנוך", year: 1997, youtubeId: "" },
  { title: "בצהרי יום", artist: "דויד ברוזה", year: 1991, youtubeId: "" },
  { title: "נטשה", artist: "דויד ברוזה", year: 1994, youtubeId: "" },
  { title: "מכאן", artist: "שלומי שבת", year: 1991, youtubeId: "" },
  { title: "להיאבד ברוח", artist: "עומר אדם", year: 2009, youtubeId: "" },
  { title: "אל תבכי", artist: "עומר אדם", year: 2009, youtubeId: "" },
  { title: "קצת משוגעת", artist: "שרית חדד", year: 2003, youtubeId: "" },
  { title: "בחום של תל אביב", artist: "שרית חדד", year: 2004, youtubeId: "" },
  { title: "בושם צרפתי", artist: "שרית חדד", year: 2005, youtubeId: "" },
  { title: "חופשייה", artist: "שרית חדד", year: 2007, youtubeId: "" },
  { title: "אהבה בתוכי", artist: "שרית חדד", year: 2009, youtubeId: "" },
  { title: "מביט אל המרומים", artist: "משה פרץ", year: 2005, youtubeId: "" },
  { title: "שחורת עיניים", artist: "משה פרץ", year: 2005, youtubeId: "" },
  { title: "האישה שלי", artist: "משה פרץ", year: 2005, youtubeId: "" },
  { title: "אש", artist: "משה פרץ", year: 2006, youtubeId: "" },
  { title: "כמו השקט", artist: "משה פרץ", year: 2007, youtubeId: "" },
  { title: "יש רגעים", artist: "משה פרץ", year: 2007, youtubeId: "" },
  { title: "אלייך", artist: "משה פרץ", year: 2008, youtubeId: "" },
  { title: "נשבע לך", artist: "משה פרץ", year: 2008, youtubeId: "" },
  { title: "אישה", artist: "משה פרץ", year: 2008, youtubeId: "" },
  { title: "מהשמיים", artist: "משה פרץ", year: 2009, youtubeId: "" },
  { title: "בלבלי אותו", artist: "קובי פרץ", year: 2003, youtubeId: "" },
  { title: "ניצחתי", artist: "דנה אינטרנשיונל", year: 2001, youtubeId: "" },
  { title: "תגידי", artist: "ליאור נרקיס", year: 2001, youtubeId: "" },
  { title: "החיים כמו סרט", artist: "ליאור נרקיס", year: 2002, youtubeId: "" },
  { title: "תגלי לי", artist: "ליאור נרקיס", year: 2005, youtubeId: "" },
  { title: "המלכה שלי", artist: "ליאור נרקיס", year: 2008, youtubeId: "" },
  { title: "העיניים שלי", artist: "ליאור נרקיס", year: 2009, youtubeId: "" },
  { title: "שפוי בשבילך", artist: "ליאור נרקיס", year: 2009, youtubeId: "" },
  { title: "ללכת עם האור", artist: "זהבה בן", year: 2006, youtubeId: "" },
  { title: "שישי לפני הערב", artist: "זהבה בן", year: 2008, youtubeId: "" },
  { title: "פרחים בצבע זית", artist: "זהבה בן", year: 2009, youtubeId: "" },
  { title: "יומן מסע", artist: "אביב גפן", year: 2000, youtubeId: "" },
  { title: "שיר עצוב", artist: "אביב גפן", year: 2002, youtubeId: "" },
  { title: "הולך קדימה", artist: "אביב גפן", year: 2002, youtubeId: "" },
  { title: "עם הזמן", artist: "אביב גפן", year: 2006, youtubeId: "" },
  { title: "גג העולם", artist: "יהודה פוליקר", year: 2003, youtubeId: "" },
  { title: "אף אחד", artist: "הדג נחש", year: 2000, youtubeId: "" },
  { title: "מספרים", artist: "הדג נחש", year: 2003, youtubeId: "" },
  { title: "רק פה", artist: "הדג נחש", year: 2004, youtubeId: "" },
  { title: "יש בי עוד כוח", artist: "עידן רייכל", year: 2005, youtubeId: "" },
  { title: "עלה נישא ברוח", artist: "עידן רייכל", year: 2005, youtubeId: "" },
  { title: "מנעי קולך מבכי", artist: "עידן רייכל", year: 2008, youtubeId: "" },
  { title: "מי נהר", artist: "עידן רייכל", year: 2008, youtubeId: "" },
  { title: "היחידה שלי", artist: "דודו אהרון", year: 2007, youtubeId: "" },
  { title: "מרגיש כמו מלך", artist: "דודו אהרון", year: 2007, youtubeId: "" },
  { title: "יותר מחבר", artist: "סאבלימינל", year: 2000, youtubeId: "" },
  { title: "הסוד", artist: "סאבלימינל", year: 2004, youtubeId: "" },
  { title: "לנצח", artist: "סאבלימינל", year: 2004, youtubeId: "" },
  { title: "טורו", artist: "סאבלימינל", year: 2006, youtubeId: "" },
  { title: "לילה לבן", artist: "התקווה 6", year: 2007, youtubeId: "" },
  { title: "מונסון", artist: "ברי סחרוף", year: 2001, youtubeId: "" },
  { title: "אז מה", artist: "מרגלית צנעני", year: 2005, youtubeId: "" },
  { title: "אל תישברי", artist: "מרגלית צנעני", year: 2008, youtubeId: "" },
  { title: "שער שש", artist: "אריק ברמן", year: 2007, youtubeId: "" },
  { title: "הסיגריה האחרונה", artist: "אריק ברמן", year: 2009, youtubeId: "" },
  { title: "ילד מדהים", artist: "אריק ברמן", year: 2009, youtubeId: "" },
  { title: "כל הציפורים", artist: "הראל סקעת", year: 2006, youtubeId: "" },
  { title: "סוף", artist: "הראל סקעת", year: 2009, youtubeId: "" },
  { title: "על קו המים", artist: "עברי לידר", year: 2002, youtubeId: "" },
  { title: "גשם אחרון", artist: "עברי לידר", year: 2002, youtubeId: "" },
  { title: "הפעם", artist: "עברי לידר", year: 2008, youtubeId: "" },
  { title: "השדות האדומים", artist: "עברי לידר", year: 2008, youtubeId: "" },
  { title: "מתעורר", artist: "עברי לידר", year: 2008, youtubeId: "" },
  { title: "אוהבת לא אוהבת", artist: "ארקדי דוכין", year: 2001, youtubeId: "" },
  { title: "בודד בודד", artist: "ארקדי דוכין", year: 2001, youtubeId: "" },
  { title: "כשאני רוקד איתך", artist: "רמי קליינשטיין", year: 2000, youtubeId: "" },
  { title: "רוחות מלחמה", artist: "רמי קליינשטיין", year: 2004, youtubeId: "" },
  { title: "אלוהי הדברים הקטנים", artist: "רמי קליינשטיין", year: 2009, youtubeId: "" },
  { title: "זה הכל או כלום", artist: "דויד ברוזה", year: 2002, youtubeId: "" },
  { title: "אני רץ", artist: "דודו טסה", year: 2003, youtubeId: "" },
  { title: "הלילה לא", artist: "דודו טסה", year: 2004, youtubeId: "" },
  { title: "לולה", artist: "דודו טסה", year: 2006, youtubeId: "" },
  { title: "בומביי", artist: "דנה ברגר", year: 2000, youtubeId: "" },
  { title: "צבעי הערב", artist: "דנה ברגר", year: 2004, youtubeId: "" },
  { title: "תנו לגדול בשקט", artist: "שלומי שבת", year: 2002, youtubeId: "" },
  { title: "זמן אהבה", artist: "שלומי שבת", year: 2003, youtubeId: "" },
  { title: "תרצי בי", artist: "שלומי שבת", year: 2008, youtubeId: "" },
  { title: "את בליבי", artist: "עומר אדם", year: 2010, youtubeId: "" },
  { title: "נמס ממך", artist: "עומר אדם", year: 2010, youtubeId: "" },
  { title: "הופה", artist: "עומר אדם", year: 2010, youtubeId: "" },
  { title: "איך שאת יפה", artist: "משה פרץ", year: 2010, youtubeId: "" },
  { title: "אין כמוך", artist: "משה פרץ", year: 2010, youtubeId: "" },
  { title: "קפה או סרט", artist: "ליאור נרקיס", year: 2010, youtubeId: "" },
  { title: "שלושה ימים", artist: "יהודה פוליקר", year: 2010, youtubeId: "" },
  { title: "מה נעשה", artist: "הדג נחש", year: 2010, youtubeId: "" },
  { title: "תגידו לה", artist: "דודו אהרון", year: 2010, youtubeId: "" },
  { title: "כסף ואלכוהול", artist: "דודו אהרון", year: 2010, youtubeId: "" },
  { title: "כל יום מחדש", artist: "התקווה 6", year: 2010, youtubeId: "" },
  { title: "הלילה", artist: "מרגלית צנעני", year: 2010, youtubeId: "" },
  { title: "יהלומים בשמיים", artist: "משינה", year: 2010, youtubeId: "" },
  { title: "מלך העולם", artist: "אמיר דדון", year: 2010, youtubeId: "" },
  { title: "לילה לא שקט", artist: "אמיר דדון", year: 2010, youtubeId: "" },
  { title: "הישראלי האחרון", artist: "רמי קליינשטיין", year: 2010, youtubeId: "" },
  { title: "שתדעי", artist: "שלומי שבת", year: 2010, youtubeId: "" },
];
