// songs/hi.js — हिन्दी गीत सूची (कोई youtubeId नहीं — "कलाकार गीत" से खोजकर बजाया जाता है)।
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.hi = [
  { title: "Tere Bina Zindagi Se", artist: "Lata Mangeshkar & Kishore Kumar", year: 1975 },
  { title: "Lag Jaa Gale", artist: "Lata Mangeshkar", year: 1964 },
  { title: "Ajeeb Dastan Hai Yeh", artist: "Lata Mangeshkar", year: 1960 },
  { title: "Pyar Kiya To Darna Kya", artist: "Lata Mangeshkar", year: 1960 },
  { title: "Lagu Toh Chalu", artist: "Lata Mangeshkar", year: 1958 },
  { title: "Aap Ki Nazron Ne Samjha", artist: "Lata Mangeshkar", year: 1962 },
  { title: "Roop Tera Mastana", artist: "Kishore Kumar", year: 1969 },
  { title: "Mere Sapno Ki Rani", artist: "Kishore Kumar", year: 1969 },
  { title: "Yeh Shaam Mastani", artist: "Kishore Kumar", year: 1971 },
  { title: "Zindagi Ek Safar Hai Suhana", artist: "Kishore Kumar", year: 1971 },
  { title: "Pal Pal Dil Ke Paas", artist: "Kishore Kumar", year: 1973 },
  { title: "Chura Liya Hai Tumne", artist: "Asha Bhosle & Mohammed Rafi", year: 1973 },
  { title: "Dum Maro Dum", artist: "Asha Bhosle", year: 1971 },
  { title: "Piya Tu Ab To Aaja", artist: "Asha Bhosle", year: 1971 },
  { title: "Chaudhvin Ka Chand", artist: "Mohammed Rafi", year: 1960 },
  { title: "Chahunga Main Tujhe", artist: "Mohammed Rafi", year: 1966 },
  { title: "Baharon Phool Barsao", artist: "Mohammed Rafi", year: 1966 },
  { title: "Kya Hua Tera Wada", artist: "Mohammed Rafi", year: 1977 },
  { title: "Mere Mehboob Qayamat Hogi", artist: "Kishore Kumar", year: 1980 },
  { title: "Tujhe Dekha To", artist: "Lata Mangeshkar & Kumar Sanu", year: 1995 },
  { title: "Tum Hi Ho", artist: "Arijit Singh", year: 2013 },
  { title: "Channa Mereya", artist: "Arijit Singh", year: 2016 },
  { title: "Kesariya", artist: "Arijit Singh", year: 2022 },
  { title: "Ae Dil Hai Mushkil", artist: "Arijit Singh", year: 2016 },
  { title: "Raabta", artist: "Arijit Singh", year: 2012 },
  { title: "Tera Yaar Hoon Main", artist: "Arijit Singh", year: 2018 },
  { title: "Agar Tum Saath Ho", artist: "Alka Yagnik & Arijit Singh", year: 2015 },
  { title: "Kal Ho Naa Ho", artist: "Sonu Nigam", year: 2003 },
  { title: "Abhi Mujh Mein Kahin", artist: "Sonu Nigam", year: 2010 },
  { title: "Sandese Aate Hain", artist: "Sonu Nigam & Roop Kumar Rathod", year: 1999 },
  { title: "Suraj Hua Maddham", artist: "Sonu Nigam & Alka Yagnik", year: 2001 },
  { title: "Kabhi Khushi Kabhie Gham", artist: "Sonu Nigam & Alka Yagnik", year: 2001 },
  { title: "Tujhe Yaad Na Meri Aayi", artist: "Udit Narayan", year: 1998 },
  { title: "Pardesi Pardesi", artist: "Udit Narayan & Alka Yagnik", year: 1997 },
  { title: "Mera Dil Bhi Kitna Pagal Hai", artist: "Udit Narayan & Alka Yagnik", year: 1995 },
  { title: "Ho Gaya Hai Tujhko Toh Pyar", artist: "Udit Narayan & Alka Yagnik", year: 1998 },
  { title: "Kuch Kuch Hota Hai", artist: "Udit Narayan & Alka Yagnik", year: 1998 },
  { title: "Chaiyya Chaiyya", artist: "Sukhwinder Singh & Sapna Awasthi", year: 1998 },
  { title: "Jai Ho", artist: "A. R. Rahman", year: 2008 },
  { title: "Roobaroo", artist: "A. R. Rahman", year: 2006 },
  { title: "Dil Se Re", artist: "A. R. Rahman", year: 1998 },
  { title: "Tere Bina", artist: "A. R. Rahman", year: 2007 },
  { title: "Kun Faya Kun", artist: "A. R. Rahman", year: 2011 },
  { title: "Tum Se Hi", artist: "Mohit Chauhan", year: 2007 },
  { title: "Tum Hi Ho Bandhu", artist: "Amitabh Bhattacharya & Mohit Chauhan", year: 2013 },
  { title: "Masakali", artist: "Mohit Chauhan", year: 2009 },
  { title: "Kabira", artist: "Tochi Raina & Rekha Bhardwaj", year: 2013 },
  { title: "Bulleya", artist: "Amit Mishra & Shilpa Rao", year: 2016 },
  { title: "Gerua", artist: "Arijit Singh & Antara Mitra", year: 2015 },
  { title: "Janam Janam", artist: "Arijit Singh & Antara Mitra", year: 2015 },
  { title: "Ilahi", artist: "Arijit Singh", year: 2013 },
  { title: "Zinda", artist: "Siddharth Mahadevan", year: 2009 },
  { title: "Namo Namo", artist: "Amit Trivedi", year: 2016 },
  { title: "Iktara", artist: "Kavita Seth & Amitabh Bhattacharya", year: 2009 },
  { title: "Kabhi Kabhi Aditi", artist: "Rashid Ali", year: 2009 },
  { title: "Senorita", artist: "Farhan Akhtar, Hrithik Roshan, Abhay Deol", year: 2011 },
  { title: "Dil Dhadakne Do", artist: "Priyanka Chopra & others", year: 2015 },
  { title: "London Thumakda", artist: "Labh Janjua", year: 2014 },
  { title: "Kala Chashma", artist: "Neha Kakkar & Badshah", year: 2016 },
  { title: "Dilbar", artist: "Neha Kakkar & Dhvani Bhanushali", year: 2018 },
  { title: "Aankh Marey", artist: "Neha Kakkar & Mika Singh", year: 2019 },
  { title: "Manike Mage Hithe (Hindi mix)", artist: "Yohani & Jubin Nautiyal", year: 2021 },
  { title: "Ghungroo", artist: "Arijit Singh & Shilpa Rao", year: 2019 },
  { title: "Tera Ban Jaunga", artist: "Akhil Sachdeva & Tulsi Kumar", year: 2019 },
  { title: "Ve Maahi", artist: "Arijit Singh & Asees Kaur", year: 2019 },
  { title: "Bekhayali", artist: "Sachet Tandon", year: 2019 },
  { title: "Tum Hi Aana", artist: "Jubin Nautiyal", year: 2019 },
  { title: "Kaun Tujhe", artist: "Palak Muchhal", year: 2016 },
  { title: "Pee Loon", artist: "Mohit Chauhan", year: 2010 },
  { title: "Jeene Laga Hoon", artist: "Atif Aslam & Shreya Ghoshal", year: 2014 },
  { title: "Tera Hone Laga Hoon", artist: "Atif Aslam & Alisha Chinai", year: 2008 },
  { title: "Pehli Nazar Mein", artist: "Atif Aslam", year: 2007 },
  { title: "Doorie", artist: "Atif Aslam", year: 2006 },
  { title: "Deewani Mastani", artist: "Shreya Ghoshal", year: 2015 },
  { title: "Teri Ore", artist: "Shreya Ghoshal & Rahat Fateh Ali Khan", year: 2008 },
  { title: "Barso Re", artist: "Shreya Ghoshal", year: 2007 },
  { title: "Sun Raha Hai Na Tu", artist: "Shreya Ghoshal", year: 2013 },
];
