// songs/it.js — מאגר שירים באיטלקית (ללא youtubeId — ניגון בחיפוש אוטומטי).
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.it = [
  { title: "Volare (Nel Blu Dipinto Di Blu)", artist: "Domenico Modugno", year: 1958 },
  { title: "Azzurro", artist: "Adriano Celentano", year: 1968 },
  { title: "Il Ragazzo della Via Gluck", artist: "Adriano Celentano", year: 1966 },
  { title: "Susanna", artist: "Adriano Celentano", year: 1979 },
  { title: "Prisencolinensinainciusol", artist: "Adriano Celentano", year: 1972 },
  { title: "L'Italiano", artist: "Toto Cutugno", year: 1983 },
  { title: "Solo Noi", artist: "Toto Cutugno", year: 1990 },
  { title: "Con Te Partirò", artist: "Andrea Bocelli", year: 1995 },
  { title: "Time to Say Goodbye", artist: "Andrea Bocelli & Sarah Brightman", year: 1996 },
  { title: "Vivo Per Lei", artist: "Andrea Bocelli", year: 1995 },
  { title: "Caruso", artist: "Lucio Dalla", year: 1986 },
  { title: "4/3/1943", artist: "Lucio Dalla", year: 1971 },
  { title: "Attenti al Lupo", artist: "Lucio Dalla", year: 1990 },
  { title: "Piazza Grande", artist: "Lucio Dalla", year: 1972 },
  { title: "La Cura", artist: "Franco Battiato", year: 1996 },
  { title: "Centro di Gravità Permanente", artist: "Franco Battiato", year: 1981 },
  { title: "Voglio Vederti Danzare", artist: "Franco Battiato", year: 1982 },
  { title: "Bella Ciao", artist: "Traditional", year: 1943 },
  { title: "Romagna Mia", artist: "Secondo Casadei", year: 1954 },
  { title: "La Donna Cannone", artist: "Francesco De Gregori", year: 1983 },
  { title: "Generale", artist: "Francesco De Gregori", year: 1978 },
  { title: "Rimmel", artist: "Francesco De Gregori", year: 1975 },
  { title: "Buonanotte Fiorellino", artist: "Francesco De Gregori", year: 1976 },
  { title: "La Cura del Tempo", artist: "Ivano Fossati", year: 1997 },
  { title: "Una Storia Sbagliata", artist: "Fabrizio De André", year: 1980 },
  { title: "Il Pescatore", artist: "Fabrizio De André", year: 1970 },
  { title: "La Canzone di Marinella", artist: "Fabrizio De André", year: 1964 },
  { title: "Bocca di Rosa", artist: "Fabrizio De André", year: 1967 },
  { title: "Ti Amo", artist: "Umberto Tozzi", year: 1977 },
  { title: "Gloria", artist: "Umberto Tozzi", year: 1979 },
  { title: "Tu", artist: "Umberto Tozzi", year: 1978 },
  { title: "Notte Prima degli Esami", artist: "Antonello Venditti", year: 1984 },
  { title: "Sara", artist: "Antonello Venditti", year: 1979 },
  { title: "Grazie Roma", artist: "Antonello Venditti", year: 1983 },
  { title: "Bella d'Estate", artist: "Nomadi", year: 1971 },
  { title: "Io Vagabondo", artist: "Nomadi", year: 1972 },
  { title: "Perdere l'Amore", artist: "Massimo Ranieri", year: 1988 },
  { title: "Rose Rosse", artist: "Massimo Ranieri", year: 1969 },
  { title: "Se Bruciasse la Città", artist: "Fabio Concato", year: 1985 },
  { title: "Domenica Bestiale", artist: "Fabio Concato", year: 1985 },
  { title: "L'Emozione Non Ha Voce", artist: "Adriano Celentano", year: 1990 },
  { title: "Una Storia Disonesta", artist: "Adriano Celentano", year: 1979 },
  { title: "Storie di Tutti i Giorni", artist: "Riccardo Fogli", year: 1976 },
  { title: "Io Che Non Vivo (Senza Te)", artist: "Pino Donaggio", year: 1965 },
  { title: "Grande Grande Grande", artist: "Mina", year: 1972 },
  { title: "Parole Parole", artist: "Mina & Alberto Lupo", year: 1972 },
  { title: "Se Telefonando", artist: "Mina", year: 1966 },
  { title: "Un Anno d'Amore", artist: "Mina", year: 1965 },
  { title: "Insieme a Te Non Ci Sto Più", artist: "Caterina Caselli", year: 1968 },
  { title: "Nessuno Mi Può Giudicare", artist: "Caterina Caselli", year: 1966 },
  { title: "Non Ho L'Età", artist: "Gigliola Cinquetti", year: 1964 },
  { title: "Zingara", artist: "Bobby Solo", year: 1969 },
  { title: "Una Lacrima Sul Viso", artist: "Bobby Solo", year: 1964 },
  { title: "29 Settembre", artist: "Il Volo (Batisti orig.)", year: 1975 },
  { title: "Grande Amore", artist: "Il Volo", year: 2015 },
  { title: "Il Mondo", artist: "Jimmy Fontana", year: 1965 },
  { title: "Sapore di Sale", artist: "Gino Paoli", year: 1963 },
  { title: "Il Cielo in Una Stanza", artist: "Gino Paoli", year: 1960 },
  { title: "La Gatta", artist: "Gino Paoli", year: 1960 },
  { title: "Ancora Ancora Ancora", artist: "Mina", year: 1984 },
  { title: "Felicità", artist: "Al Bano & Romina Power", year: 1982 },
  { title: "Nostalgia Canaglia", artist: "Al Bano & Romina Power", year: 1984 },
  { title: "Ci Sarà", artist: "Al Bano & Romina Power", year: 1984 },
  { title: "Sharazan", artist: "Al Bano", year: 1983 },
  { title: "Lady Marmalade (versione IT non esiste, sostituita)", artist: "Riccardo Fogli", year: 1976 },
  { title: "Splendido Splendente", artist: "Raf", year: 1990 },
  { title: "Self Control", artist: "Raf", year: 1984 },
  { title: "Cosa Resterà Degli Anni '80", artist: "Raf", year: 1989 },
  { title: "Sei Nell'Anima", artist: "Gianna Nannini", year: 1980 },
  { title: "Bello e Impossibile", artist: "Gianna Nannini", year: 1986 },
  { title: "America", artist: "Gianna Nannini", year: 1979 },
  { title: "Un'Emozione da Poco", artist: "Anna Oxa", year: 1978 },
  { title: "Quando Nasce un Amore", artist: "Anna Oxa & Fausto Leali", year: 1989 },
  { title: "Vita", artist: "Alberto Fortis", year: 1980 },
  { title: "Sarà Perché Ti Amo", artist: "Ricchi e Poveri", year: 1981 },
  { title: "Mamma Maria", artist: "Ricchi e Poveri", year: 1982 },
  { title: "Che Sarà", artist: "Ricchi e Poveri (José Feliciano orig.)", year: 1971 },
  { title: "Se Piangi, Se Ridi", artist: "Ricchi e Poveri", year: 1978 },
  { title: "Un Uomo Come Me", artist: "Zucchero", year: 1985 },
  { title: "Diamante", artist: "Zucchero", year: 1989 },
  { title: "Il Volo", artist: "Zucchero", year: 2013 },
  { title: "Baila Morena", artist: "Zucchero", year: 1995 },
  { title: "Rispetto", artist: "Zucchero", year: 2001 },
  { title: "Vorrei Incontrarti Tra Cent'Anni", artist: "Zucchero & Andrea Bocelli", year: 1996 },
  { title: "Salirò", artist: "Daniele Silvestri", year: 2002 },
  { title: "L'Uomo Nero", artist: "Daniele Silvestri", year: 1999 },
  { title: "Il Mio Canto Libero", artist: "Lucio Battisti", year: 1972 },
  { title: "Emozioni", artist: "Lucio Battisti", year: 1970 },
  { title: "Ancora Tu", artist: "Lucio Battisti", year: 1976 },
  { title: "I Giardini di Marzo", artist: "Lucio Battisti", year: 1972 },
  { title: "La Canzone del Sole", artist: "Lucio Battisti", year: 1971 },
];
