// songs/ja.js — 日本語の曲リスト（youtubeId なし — 「アーティスト 曲名」で自動検索して再生）。
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.ja = [
  { title: "上を向いて歩こう", artist: "坂本九", year: 1961 },
  { title: "津軽海峡・冬景色", artist: "石川さゆり", year: 1977 },
  { title: "川の流れのように", artist: "美空ひばり", year: 1989 },
  { title: "お祭りマンボ", artist: "美空ひばり", year: 1952 },
  { title: "少年時代", artist: "井上陽水", year: 1990 },
  { title: "夢の中へ", artist: "井上陽水", year: 1973 },
  { title: "傘がない", artist: "井上陽水", year: 1972 },
  { title: "襟裳岬", artist: "森進一", year: 1974 },
  { title: "北の宿から", artist: "都はるみ", year: 1975 },
  { title: "365歩のマーチ", artist: "水前寺清子", year: 1968 },
  { title: "またあいましょう", artist: "尾崎紀世彦", year: 1971 },
  { title: "喝采", artist: "ちあきなおみ", year: 1972 },
  { title: "圭子の夢は夜ひらく", artist: "藤圭子", year: 1970 },
  { title: "神田川", artist: "かぐや姫", year: 1973 },
  { title: "22才の別れ", artist: "風", year: 1975 },
  { title: "なごり雪", artist: "イルカ", year: 1975 },
  { title: "木綿のハンカチーフ", artist: "太田裕美", year: 1975 },
  { title: "ルビーの指環", artist: "寺尾聰", year: 1981 },
  { title: "異邦人", artist: "久保田早紀", year: 1979 },
  { title: "UFO", artist: "ピンク・レディー", year: 1977 },
  { title: "サウスポー", artist: "ピンク・レディー", year: 1978 },
  { title: "ペッパー警部", artist: "ピンク・レディー", year: 1976 },
  { title: "勝手にしやがれ", artist: "沢田研二", year: 1977 },
  { title: "TOKIO", artist: "沢田研二", year: 1980 },
  { title: "時の流れに身をまかせ", artist: "テレサ・テン", year: 1986 },
  { title: "つぐない", artist: "テレサ・テン", year: 1984 },
  { title: "見上げてごらん夜の星を", artist: "坂本九", year: 1963 },
  { title: "First Love", artist: "宇多田ヒカル", year: 1999 },
  { title: "Automatic", artist: "宇多田ヒカル", year: 1998 },
  { title: "traveling", artist: "宇多田ヒカル", year: 2001 },
  { title: "Flavor Of Life", artist: "宇多田ヒカル", year: 2007 },
  { title: "涙そうそう", artist: "夏川りみ", year: 2001 },
  { title: "島唄", artist: "THE BOOM", year: 1992 },
  { title: "TSUNAMI", artist: "サザンオールスターズ", year: 2000 },
  { title: "いとしのエリー", artist: "サザンオールスターズ", year: 1979 },
  { title: "勝手にシンドバッド", artist: "サザンオールスターズ", year: 1978 },
  { title: "楽園", artist: "サザンオールスターズ", year: 1996 },
  { title: "睡蓮花", artist: "サザンオールスターズ", year: 2000 },
  { title: "世界に一つだけの花", artist: "SMAP", year: 2003 },
  { title: "夜空ノムコウ", artist: "SMAP", year: 1998 },
  { title: "らいおんハート", artist: "SMAP", year: 2000 },
  { title: "SHAKE", artist: "SMAP", year: 1996 },
  { title: "白いパラソル", artist: "松田聖子", year: 1981 },
  { title: "青い珊瑚礁", artist: "松田聖子", year: 1980 },
  { title: "赤いスイートピー", artist: "松田聖子", year: 1982 },
  { title: "ワインレッドの心", artist: "安全地帯", year: 1983 },
  { title: "恋の予感", artist: "安全地帯", year: 1985 },
  { title: "M", artist: "プリンセス プリンセス", year: 1989 },
  { title: "Diamonds", artist: "プリンセス プリンセス", year: 1989 },
  { title: "世界が終るまでは...", artist: "WANDS", year: 1994 },
  { title: "会いたかった", artist: "AKB48", year: 2006 },
  { title: "恋するフォーチュンクッキー", artist: "AKB48", year: 2013 },
  { title: "ヘビーローテーション", artist: "AKB48", year: 2010 },
  { title: "Everyday、カチューシャ", artist: "AKB48", year: 2011 },
  { title: "紅蓮華", artist: "LiSA", year: 2019 },
  { title: "炎", artist: "LiSA", year: 2020 },
  { title: "again", artist: "YUI", year: 2005 },
  { title: "Rolling star", artist: "YUI", year: 2006 },
  { title: "Lifetime Respect", artist: "YUI", year: 2004 },
  { title: "花束", artist: "back number", year: 2013 },
  { title: "高嶺の花子さん", artist: "back number", year: 2013 },
  { title: "クリスマスソング", artist: "back number", year: 2012 },
  { title: "前前前世", artist: "RADWIMPS", year: 2016 },
  { title: "なんでもないや", artist: "RADWIMPS", year: 2016 },
  { title: "Lemon", artist: "米津玄師", year: 2018 },
  { title: "馬と鹿", artist: "米津玄師", year: 2019 },
  { title: "パプリカ", artist: "Foorin (米津玄師 作)", year: 2018 },
  { title: "打上花火", artist: "DAOKO × 米津玄師", year: 2017 },
  { title: "白日", artist: "King Gnu", year: 2019 },
  { title: "小さな恋のうた", artist: "MONGOL800", year: 2001 },
  { title: "さくら", artist: "森山直太朗", year: 2003 },
  { title: "空も飛べるはず", artist: "スピッツ", year: 1994 },
  { title: "チェリー", artist: "スピッツ", year: 1996 },
  { title: "Only Human", artist: "福山雅治", year: 2014 },
  { title: "桜坂", artist: "福山雅治", year: 2000 },
  { title: "HELLO", artist: "福山雅治", year: 2001 },
  { title: "negai", artist: "MISIA", year: 1999 },
  { title: "Everything", artist: "MISIA", year: 2000 },
  { title: "つつみ込むように…", artist: "MISIA", year: 1999 },
];
