// songs/ko.js — 한국어 노래 목록 (youtubeId 없음 — "아티스트 곡명"으로 자동 검색 재생).
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.ko = [
  { title: "돌아와요 부산항에", artist: "조용필", year: 1976 },
  { title: "창밖의 여자", artist: "조용필", year: 1980 },
  { title: "단발머리", artist: "조용필", year: 1980 },
  { title: "허공", artist: "조용필", year: 1985 },
  { title: "friend", artist: "조용필", year: 2003 },
  { title: "동백아가씨", artist: "이미자", year: 1964 },
  { title: "섬마을 선생님", artist: "이미자", year: 1967 },
  { title: "찔레꽃", artist: "백난아", year: 1942 },
  { title: "낭만에 대하여", artist: "최백호", year: 1995 },
  { title: "입영전야", artist: "김광석", year: 1994 },
  { title: "서른 즈음에", artist: "김광석", year: 1994 },
  { title: "이등병의 편지", artist: "김광석", year: 1993 },
  { title: "먼지가 되어", artist: "김광석", year: 1994 },
  { title: "사랑했지만", artist: "김광석", year: 1995 },
  { title: "붉은 노을", artist: "이문세", year: 1988 },
  { title: "광화문 연가", artist: "이문세", year: 1988 },
  { title: "그녀의 웃음소리뿐", artist: "이문세", year: 1987 },
  { title: "사랑이란 게 다 그런거지", artist: "변진섭", year: 1989 },
  { title: "희망사항", artist: "변진섭", year: 1989 },
  { title: "숙녀에게", artist: "변진섭", year: 1988 },
  { title: "너에게로 또 다시", artist: "015B", year: 1994 },
  { title: "이젠 안녕", artist: "015B", year: 1990 },
  { title: "난 알아요", artist: "서태지와 아이들", year: 1992 },
  { title: "come back home", artist: "서태지와 아이들", year: 1995 },
  { title: "환상 속의 그대", artist: "서태지와 아이들", year: 1992 },
  { title: "캔디", artist: "H.O.T.", year: 1996 },
  { title: "행복", artist: "H.O.T.", year: 1998 },
  { title: "바람 불어 좋은 날", artist: "젝스키스", year: 1997 },
  { title: "커플", artist: "젝스키스", year: 1998 },
  { title: "고백", artist: "핑클", year: 1998 },
  { title: "내 남자친구에게", artist: "핑클", year: 1998 },
  { title: "I", artist: "S.E.S.", year: 1997 },
  { title: "Dreams Come True", artist: "S.E.S.", year: 1998 },
  { title: "나 있잖아 애인 있었으면 좋겠어", artist: "SG워너비", year: 2004 },
  { title: "죄와 벌", artist: "SG워너비", year: 2005 },
  { title: "timeless", artist: "SG워너비", year: 2004 },
  { title: "인형", artist: "SG워너비", year: 2007 },
  { title: "그 남자 그 여자", artist: "SG워너비", year: 2006 },
  { title: "closer", artist: "이승철", year: 1990 },
  { title: "제발", artist: "이승철", year: 1990 },
  { title: "그런 사람 또 없습니다", artist: "이승철", year: 2014 },
  { title: "다시 사랑한다면", artist: "부활 & 이승철", year: 1997 },
  { title: "그대 내 품에", artist: "유재하", year: 1987 },
  { title: "사랑하기 때문에", artist: "유재하", year: 1987 },
  { title: "가을 우체국 앞에서", artist: "윤도현", year: 2000 },
  { title: "나는 나비", artist: "윤도현밴드", year: 2003 },
  { title: "사랑Two", artist: "윤도현밴드", year: 2002 },
  { title: "거짓말", artist: "빅뱅", year: 2007 },
  { title: "마지막 인사", artist: "빅뱅", year: 2007 },
  { title: "haru haru", artist: "빅뱅", year: 2008 },
  { title: "뱅뱅뱅", artist: "빅뱅", year: 2015 },
  { title: "fantastic baby", artist: "빅뱅", year: 2012 },
  { title: "gee", artist: "소녀시대", year: 2009 },
  { title: "run devil run", artist: "소녀시대", year: 2010 },
  { title: "into the new world", artist: "소녀시대", year: 2007 },
  { title: "nobody", artist: "원더걸스", year: 2008 },
  { title: "tell me", artist: "원더걸스", year: 2007 },
  { title: "so hot", artist: "원더걸스", year: 2008 },
  { title: "abracadabra", artist: "브라운아이드걸스", year: 2009 },
  { title: "sign", artist: "브라운아이드걸스", year: 2009 },
  { title: "미스터", artist: "카라", year: 2009 },
  { title: "빙글빙글", artist: "카라", year: 2010 },
  { title: "그리워하다", artist: "씨스타", year: 2013 },
  { title: "나혼자", artist: "씨스타", year: 2014 },
  { title: "growl", artist: "엑소", year: 2013 },
  { title: "love shot", artist: "엑소", year: 2018 },
  { title: "boy with luv", artist: "방탄소년단", year: 2019 },
  { title: "dynamite", artist: "방탄소년단", year: 2020 },
  { title: "spring day", artist: "방탄소년단", year: 2017 },
  { title: "fake love", artist: "방탄소년단", year: 2018 },
  { title: "dna", artist: "방탄소년단", year: 2017 },
  { title: "idol", artist: "방탄소년단", year: 2018 },
  { title: "butter", artist: "방탄소년단", year: 2021 },
  { title: "kill this love", artist: "블랙핑크", year: 2019 },
  { title: "ddu-du ddu-du", artist: "블랙핑크", year: 2018 },
  { title: "how you like that", artist: "블랙핑크", year: 2020 },
  { title: "gangnam style", artist: "싸이", year: 2012 },
  { title: "gentleman", artist: "싸이", year: 2013 },
  { title: "너를 만나", artist: "폴킴", year: 2018 },
  { title: "밤편지", artist: "아이유", year: 2017 },
  { title: "좋은 날", artist: "아이유", year: 2010 },
  { title: "palette", artist: "아이유 ft. G-DRAGON", year: 2017 },
  { title: "eight", artist: "아이유 ft. 수기", year: 2020 },
];
