// songs/pt.js — מאגר שירים בפורטוגזית (ללא youtubeId — ניגון בחיפוש אוטומטי).
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.pt = [
  { title: "Garota de Ipanema", artist: "Tom Jobim & Vinícius de Moraes", year: 1962 },
  { title: "Águas de Março", artist: "Tom Jobim", year: 1972 },
  { title: "Chega de Saudade", artist: "João Gilberto", year: 1958 },
  { title: "Desafinado", artist: "João Gilberto", year: 1959 },
  { title: "Aquarela do Brasil", artist: "Ary Barroso", year: 1939 },
  { title: "Mas Que Nada", artist: "Jorge Ben Jor", year: 1963 },
  { title: "País Tropical", artist: "Jorge Ben Jor", year: 1969 },
  { title: "Taj Mahal", artist: "Jorge Ben Jor", year: 1972 },
  { title: "Aquele Abraço", artist: "Gilberto Gil", year: 1969 },
  { title: "Andar Com Fé", artist: "Gilberto Gil", year: 1982 },
  { title: "Toda Menina Baiana", artist: "Gilberto Gil", year: 1980 },
  { title: "Você Não Me Ensinou a Te Esquecer", artist: "Caetano Veloso", year: 1993 },
  { title: "Sozinho", artist: "Caetano Veloso", year: 1993 },
  { title: "Alegria, Alegria", artist: "Caetano Veloso", year: 1967 },
  { title: "Como Nossos Pais", artist: "Elis Regina", year: 1976 },
  { title: "Águas de Março (Elis version)", artist: "Elis Regina", year: 1974 },
  { title: "O Bêbado e a Equilibrista", artist: "Elis Regina", year: 1979 },
  { title: "Anunciação", artist: "Alceu Valença", year: 1979 },
  { title: "Morena Tropicana", artist: "Alceu Valença", year: 1978 },
  { title: "Evidências", artist: "Chitãozinho & Xororó", year: 1990 },
  { title: "Fio de Cabelo", artist: "Chitãozinho & Xororó", year: 1990 },
  { title: "Ai Se Eu Te Pego", artist: "Michel Teló", year: 2011 },
  { title: "Fugidinha", artist: "Michel Teló", year: 2012 },
  { title: "Como É Grande o Meu Amor Por Você", artist: "Roberto Carlos", year: 1967 },
  { title: "Detalhes", artist: "Roberto Carlos", year: 1971 },
  { title: "Emoções", artist: "Roberto Carlos", year: 1981 },
  { title: "Amada Amante", artist: "Roberto Carlos", year: 1975 },
  { title: "Além do Horizonte", artist: "Roberto Carlos", year: 1963 },
  { title: "É Preciso Saber Viver", artist: "Roberto Carlos & Erasmo Carlos", year: 1968 },
  { title: "Mulher de Fases", artist: "Zeca Pagodinho", year: 1997 },
  { title: "Deixa a Vida Me Levar", artist: "Zeca Pagodinho", year: 1997 },
  { title: "Verdade", artist: "Zeca Pagodinho", year: 2001 },
  { title: "O Show Tem Que Continuar", artist: "Zeca Pagodinho", year: 1999 },
  { title: "Apesar de Você", artist: "Chico Buarque", year: 1970 },
  { title: "Construção", artist: "Chico Buarque", year: 1971 },
  { title: "A Banda", artist: "Chico Buarque", year: 1966 },
  { title: "Roda Viva", artist: "Chico Buarque", year: 1968 },
  { title: "Cálice", artist: "Chico Buarque & Gilberto Gil", year: 1973 },
  { title: "Xote das Meninas", artist: "Luiz Gonzaga", year: 1953 },
  { title: "Asa Branca", artist: "Luiz Gonzaga", year: 1947 },
  { title: "Qui Nem Jiló", artist: "Luiz Gonzaga", year: 1951 },
  { title: "Ai Ai Ai De Mim", artist: "Roupa Nova", year: 1985 },
  { title: "Whisky a Go Go", artist: "Roupa Nova", year: 1982 },
  { title: "Dona", artist: "Roupa Nova", year: 1988 },
  { title: "Anna Júlia", artist: "Los Hermanos", year: 1999 },
  { title: "O Vencedor", artist: "Los Hermanos", year: 1999 },
  { title: "Sofrência", artist: "Marília Mendonça", year: 2018 },
  { title: "Infiel", artist: "Marília Mendonça", year: 2016 },
  { title: "Todo Mundo Vai Sofrer", artist: "Marília Mendonça", year: 2016 },
  { title: "Fala Mal de Mim", artist: "Marília Mendonça", year: 2021 },
  { title: "Batendo Estrela", artist: "Jorge & Mateus", year: 2011 },
  { title: "Pé na Areia", artist: "Jorge & Mateus", year: 2013 },
  { title: "Os Anjos Cantam", artist: "Jorge & Mateus", year: 2013 },
  { title: "Amor de Chocolate", artist: "Jorge & Mateus", year: 2009 },
  { title: "Trem-Bala", artist: "Ana Vilela", year: 2017 },
  { title: "Bandida", artist: "Anitta", year: 2013 },
  { title: "Show das Poderosas", artist: "Anitta", year: 2013 },
  { title: "Vai Malandra", artist: "Anitta", year: 2017 },
  { title: "Envolver", artist: "Anitta", year: 2021 },
  { title: "Paradinha", artist: "Anitta", year: 2017 },
  { title: "Deixa Isso Pra Lá", artist: "Legião Urbana", year: 1985 },
  { title: "Tempo Perdido", artist: "Legião Urbana", year: 1986 },
  { title: "Eduardo e Mônica", artist: "Legião Urbana", year: 1986 },
  { title: "Faroeste Caboclo", artist: "Legião Urbana", year: 1987 },
  { title: "Pais e Filhos", artist: "Legião Urbana", year: 1989 },
  { title: "Metamorfose Ambulante", artist: "Raul Seixas", year: 1973 },
  { title: "Ouro de Tolo", artist: "Raul Seixas", year: 1973 },
  { title: "Maluco Beleza", artist: "Raul Seixas", year: 1977 },
  { title: "Como Uma Onda", artist: "Lulu Santos", year: 1983 },
  { title: "Assum Preto", artist: "Lulu Santos", year: 1984 },
  { title: "Tempos Modernos", artist: "Lulu Santos", year: 1982 },
  { title: "Aquele 99", artist: "Skank", year: 1998 },
  { title: "É Uma Partida de Futebol", artist: "Skank", year: 1996 },
  { title: "Garota Nacional", artist: "Skank", year: 2000 },
  { title: "A Sua", artist: "Skank", year: 2003 },
  { title: "Vira-Lata", artist: "Titãs", year: 1986 },
  { title: "Comida", artist: "Titãs", year: 1987 },
  { title: "Epitáfio", artist: "Titãs", year: 1989 },
  { title: "Sonífera Ilha", artist: "Titãs", year: 1986 },
  { title: "Amor Não Correspondido", artist: "Charlie Brown Jr.", year: 1999 },
  { title: "Só os Loucos Sabem", artist: "Charlie Brown Jr.", year: 1997 },
  { title: "Zoio de Lula", artist: "Charlie Brown Jr.", year: 1997 },
  { title: "Não Deixe o Samba Morrer", artist: "Alcione", year: 1981 },
  { title: "Ilariê", artist: "Rita Lee", year: 1978 },
  { title: "Mania de Você", artist: "Rita Lee", year: 1979 },
  { title: "Lança Perfume", artist: "Rita Lee", year: 1980 },
  { title: "Balada Boa", artist: "Gusttavo Lima", year: 2011 },
  { title: "Apelido Carinhoso", artist: "Gusttavo Lima", year: 2013 },
  { title: "Diz Pra Mim", artist: "Gusttavo Lima", year: 2012 },
  { title: "Chora Me Liga", artist: "Wesley Safadão", year: 2017 },
  { title: "Camarote", artist: "Wesley Safadão", year: 2015 },

  // --- Fado (Portugal) ---
  { title: "Uma Casa Portuguesa", artist: "Amália Rodrigues", year: 1953 },
  { title: "Estranha Forma de Vida", artist: "Amália Rodrigues", year: 1962 },
  { title: "Povo Que Lavas No Rio", artist: "Amália Rodrigues", year: 1945 },
  { title: "Barco Negro", artist: "Amália Rodrigues", year: 1955 },
  { title: "Gaivota", artist: "Amália Rodrigues", year: 1963 },
  { title: "Meu Fado Meu", artist: "Mariza", year: 2001 },
  { title: "Ó Gente da Minha Terra", artist: "Mariza", year: 2001 },
  { title: "Barco Negro (Mariza)", artist: "Mariza", year: 2005 },
  { title: "Chuva", artist: "Mariza", year: 2010 },
  { title: "Cavaleiro Monge", artist: "Carlos do Carmo", year: 1977 },
  { title: "Lisboa Menina e Moça", artist: "Carlos do Carmo", year: 1984 },
  { title: "Os Putos", artist: "Carlos do Carmo", year: 1982 },

  // --- Rock/Pop português ---
  { title: "A Minha Casinha", artist: "Xutos & Pontapés", year: 1993 },
  { title: "Os Emigrantes", artist: "Xutos & Pontapés", year: 1989 },
  { title: "Circo de Feras", artist: "Xutos & Pontapés", year: 1996 },
  { title: "Contentores de Nós", artist: "Xutos & Pontapés", year: 2000 },
  { title: "Photograph", artist: "GNR", year: 1988 },
  { title: "Independência", artist: "GNR", year: 1982 },
  { title: "Sei Lá Navegar", artist: "Rui Veloso", year: 1980 },
  { title: "Chico Fininho", artist: "Rui Veloso", year: 1980 },
  { title: "Porto Cancão", artist: "Rui Veloso", year: 1980 },
  { title: "Amanhã Depois do Almoço", artist: "Da Weasel", year: 2004 },
  { title: "Toda a Gente Sabe", artist: "Da Weasel", year: 2007 },
  { title: "Mensagem Automática", artist: "Da Weasel", year: 2002 },
  { title: "Chamamos-lhe Amor", artist: "Da Weasel", year: 2011 },
  { title: "Toy", artist: "Salvador Sobral", year: 2017 },
  { title: "Amar Pelos Dois", artist: "Salvador Sobral", year: 2017 },

  // --- MPB ---
  { title: "Travessia", artist: "Milton Nascimento", year: 1967 },
  { title: "Cais", artist: "Milton Nascimento", year: 1978 },
  { title: "Bola de Meia, Bola de Gude", artist: "Milton Nascimento", year: 1972 },
  { title: "Nada Será Como Antes", artist: "Milton Nascimento", year: 1972 },
  { title: "Flor de Lis", artist: "Djavan", year: 1976 },
  { title: "Oceano", artist: "Djavan", year: 1989 },
  { title: "Samurai", artist: "Djavan", year: 1988 },
  { title: "Açaí", artist: "Djavan", year: 1981 },
  { title: "É Preciso Perdoar", artist: "Maria Bethânia", year: 1972 },
  { title: "Explode Coração", artist: "Maria Bethânia", year: 1988 },
  { title: "Ternura Antiga", artist: "Maria Bethânia", year: 1980 },
  { title: "Baby", artist: "Gal Costa", year: 1969 },
  { title: "Vapor Barato", artist: "Gal Costa", year: 1972 },
  { title: "Meu Nome É Gal", artist: "Gal Costa", year: 1969 },
  { title: "Festa do Interior", artist: "Gal Costa", year: 1977 },
  { title: "Modinha", artist: "Gal Costa", year: 1988 },
  { title: "Upa Neguinho", artist: "Elis Regina", year: 1967 },
  { title: "Madalena", artist: "Elis Regina", year: 1970 },
  { title: "Loucas Ilusões", artist: "Nara Leão", year: 1971 },
  { title: "Berimbau", artist: "Baden Powell", year: 1963 },
  { title: "Consolação", artist: "Baden Powell & Vinícius de Moraes", year: 1966 },
  { title: "Domingo No Parque", artist: "Gilberto Gil", year: 1967 },
  { title: "Expresso 2222", artist: "Gilberto Gil", year: 1972 },
  { title: "Palco", artist: "Gilberto Gil", year: 1977 },
  { title: "Filhos de Gandhi", artist: "Gilberto Gil", year: 1977 },
  { title: "Cucurrucucu Paloma (versão)", artist: "Caetano Veloso", year: 1984 },
  { title: "Cajuína", artist: "Caetano Veloso", year: 1971 },
  { title: "Odara", artist: "Caetano Veloso", year: 1977 },
  { title: "Terra", artist: "Caetano Veloso", year: 1978 },
  { title: "London London", artist: "Caetano Veloso", year: 1971 },
  { title: "Como 2 e 2", artist: "Marisa Monte", year: 1998 },
  { title: "Ainda Bem", artist: "Marisa Monte", year: 2006 },
  { title: "Bem Que Se Quis", artist: "Marisa Monte", year: 1994 },
  { title: "Diminuta", artist: "Marisa Monte", year: 2011 },
  { title: "Amor I Love You", artist: "Marisa Monte", year: 2006 },

  // --- Samba / Pagode / Axé ---
  { title: "Ela Só Pensa Em Beijar", artist: "Exaltasamba", year: 1999 },
  { title: "Espelho D'Água", artist: "Exaltasamba", year: 2000 },
  { title: "Errei Aceitar", artist: "Turma do Pagode", year: 2015 },
  { title: "Não Sei Se Choro ou Se Bebo", artist: "Turma do Pagode", year: 2014 },
  { title: "Deixa Acontecer", artist: "Thiaguinho", year: 2011 },
  { title: "Muleque Vacilão", artist: "Thiaguinho", year: 2011 },
  { title: "Ousadia e Alegria", artist: "Ivete Sangalo", year: 2000 },
  { title: "Sorte Grande", artist: "Ivete Sangalo", year: 1999 },
  { title: "Careless Whisper (Coração de Estudante remix)", artist: "Ivete Sangalo", year: 2007 },
  { title: "Se Eu Não Te Amasse Tanto Assim", artist: "Ivete Sangalo", year: 2000 },
  { title: "Swing e Simpatia", artist: "Chiclete com Banana", year: 1994 },
  { title: "Meu Erro", artist: "Chiclete com Banana", year: 1996 },
  { title: "Swing", artist: "Daniela Mercury", year: 1995 },
  { title: "O Canto da Cidade", artist: "Daniela Mercury", year: 1992 },
  { title: "Rapunzel", artist: "Daniela Mercury", year: 1993 },
  { title: "Preta", artist: "Daniela Mercury", year: 1997 },

  // --- Rock brasileiro ---
  { title: "Fátima", artist: "Capital Inicial", year: 1989 },
  { title: "Filhos da Pátria", artist: "Capital Inicial", year: 1990 },
  { title: "Música Urbana", artist: "Capital Inicial", year: 1988 },
  { title: "Independência ou Morte", artist: "Engenheiros do Hawaii", year: 1990 },
  { title: "Toda Forma de Poder", artist: "Engenheiros do Hawaii", year: 1990 },
  { title: "Infinita Highway", artist: "Engenheiros do Hawaii", year: 1990 },
  { title: "Bete Balanço", artist: "Barão Vermelho", year: 1984 },
  { title: "Maldito Serás", artist: "Barão Vermelho", year: 1982 },
  { title: "Songo do Vento", artist: "Barão Vermelho", year: 1990 },
  { title: "Menino do Rio", artist: "Baby Consuelo & Pepeu Gomes", year: 1980 },
  { title: "Metrô Linha 743", artist: "Metrô", year: 1984 },
  { title: "Não Existe Amor em SP", artist: "Rita Lee", year: 2002 },
  { title: "Ovelha Negra", artist: "Rita Lee", year: 1975 },
  { title: "Alô Alô Marciano", artist: "Rita Lee", year: 1982 },
  { title: "Chega Mais", artist: "Renato Russo & Cássia Eller", year: 2001 },
  { title: "Pelo Amor de Deus", artist: "Cássia Eller", year: 1994 },
  { title: "Malandragem", artist: "Cássia Eller", year: 1990 },
  { title: "Palavras ao Vento", artist: "Cássia Eller", year: 1994 },

  // --- MPB, Bossa Nova e clássicos (adições) ---
  { title: "Carinhoso", artist: "Pixinguinha", year: 1928 },
  { title: "Trem das Onze", artist: "Demônios da Garoa", year: 1964 },
  { title: "Panis et Circencis", artist: "Os Mutantes", year: 1968 },
  { title: "As Rosas Não Falam", artist: "Cartola", year: 1976 },
  { title: "O Mundo é um Moinho", artist: "Cartola", year: 1976 },
  { title: "Sinal Fechado", artist: "Chico Buarque", year: 1974 },
  { title: "Quero Que Vá Tudo pro Inferno", artist: "Roberto Carlos", year: 1965 },
  { title: "Preta Pretinha", artist: "Novos Baianos", year: 1972 },
  { title: "Tropicália", artist: "Caetano Veloso", year: 1968 },
  { title: "Da Lama ao Caos", artist: "Chico Science & Nação Zumbi", year: 1994 },
  { title: "Inútil", artist: "Ultraje a Rigor", year: 1985 },
  { title: "Eu Sei Que Vou Te Amar", artist: "Vinicius de Moraes", year: 1970 },
  { title: "País Tropical", artist: "Wilson Simonal", year: 1969 },
  { title: "Pra Não Dizer Que Não Falei das Flores", artist: "Geraldo Vandré", year: 1968 },
  { title: "Coisa Nº 5 - Nanã", artist: "Moacir Santos", year: 1965 },
  { title: "Pérola Negra", artist: "Luiz Melodia", year: 1973 },
  { title: "Brasil Pandeiro", artist: "Novos Baianos", year: 1972 },
  { title: "O Trem Azul", artist: "Lô Borges", year: 1972 },
  { title: "Eu Quero é Botar Meu Bloco na Rua", artist: "Sérgio Sampaio", year: 1972 },
  { title: "Sangue Latino", artist: "Secos & Molhados", year: 1973 },
  { title: "Manhã de Carnaval", artist: "Luiz Bonfá", year: 1959 },
  { title: "Sampa", artist: "Caetano Veloso", year: 1978 },
  { title: "Azul da Cor do Mar", artist: "Tim Maia", year: 1970 },
  { title: "Carcará", artist: "Maria Bethânia", year: 1965 },
  { title: "Ponteio", artist: "Edu Lobo e Marília Medalha", year: 1967 },
  { title: "Me Chama", artist: "Lobão e Os Ronaldos", year: 1984 },
  { title: "Maracatu Atômico", artist: "Chico Science & Nação Zumbi", year: 1996 },
  { title: "Os Alquimistas Estão Chegando", artist: "Jorge Ben Jor", year: 1974 },
  { title: "Ando Meio Desligado", artist: "Os Mutantes", year: 1970 },
  { title: "Disparada", artist: "Jair Rodrigues", year: 1966 },
  { title: "Diário de um Detento", artist: "Racionais MC's", year: 1997 },
  { title: "Brasileirinho", artist: "Waldir Azevedo", year: 1949 },
  { title: "Sabiá", artist: "Cynara e Cybele", year: 1968 },
  { title: "Balada do Louco", artist: "Os Mutantes", year: 1972 },
  { title: "A Lua e Eu", artist: "Cassiano", year: 1976 },
  { title: "Conversa de Botequim", artist: "Noel Rosa", year: 1935 },
  { title: "Minha Namorada", artist: "Carlos Lyra", year: 1971 },
  { title: "Na Rua, na Chuva, na Fazenda", artist: "Hyldon", year: 1975 },
  { title: "Chão de Estrelas", artist: "Sílvio Caldas", year: 1937 },
  { title: "Luar do Sertão", artist: "Luiz Gonzaga e Milton Nascimento", year: 1981 },
  { title: "Alagados", artist: "Os Paralamas do Sucesso", year: 1986 },
  { title: "As Curvas da Estrada de Santos", artist: "Roberto Carlos", year: 1969 },
  { title: "BR-3", artist: "Toni Tornado", year: 1970 },
  { title: "Clube da Esquina Nº 2", artist: "Milton Nascimento", year: 1972 },
  { title: "A Banda", artist: "Nara Leão", year: 1966 },
  { title: "Rosa de Hiroshima", artist: "Secos & Molhados", year: 1973 },
  { title: "Ronda", artist: "Inezita Barroso", year: 1953 },
  { title: "Gîtâ", artist: "Raul Seixas", year: 1974 },
  { title: "Wave", artist: "Tom Jobim", year: 1967 },
  { title: "Sentado à Beira do Caminho", artist: "Erasmo Carlos", year: 1969 },
  { title: "Foi um Rio Que Passou em Minha Vida", artist: "Paulinho da Viola", year: 1970 },
  { title: "Samba de Verão", artist: "Marcos Valle", year: 1964 },
  { title: "Insensatez", artist: "Tom Jobim", year: 1961 },
  { title: "Maria Fumaça", artist: "Banda Black Rio", year: 1977 },
  { title: "Que País é Este", artist: "Legião Urbana", year: 1987 },
  { title: "Sossego", artist: "Tim Maia", year: 1978 },
  { title: "Ideologia", artist: "Cazuza", year: 1988 },
  { title: "Rosa", artist: "Orlando Silva", year: 1937 },
  { title: "O Barquinho", artist: "Maysa", year: 1961 },
  { title: "Nervos de Aço", artist: "Paulinho da Viola", year: 1973 },
  { title: "Meu Mundo e Nada Mais", artist: "Guilherme Arantes", year: 1976 },
  { title: "Sá Marina", artist: "Wilson Simonal", year: 1968 },
  { title: "A Flor e o Espinho", artist: "Nelson Cavaquinho", year: 1973 },
  { title: "2001", artist: "Os Mutantes", year: 1969 },
  { title: "Felicidade", artist: "Caetano Veloso", year: 1974 },
  { title: "Tico-Tico no Fubá", artist: "Ademilde Fonseca", year: 1942 },
  { title: "Casa no Campo", artist: "Elis Regina", year: 1972 },
  { title: "O Mar", artist: "Dorival Caymmi", year: 1954 },
  { title: "Último Desejo", artist: "Aracy de Almeida", year: 1938 },
  { title: "Disritmia", artist: "Martinho da Vila", year: 1974 },
  { title: "Você Não Soube Me Amar", artist: "Blitz", year: 1982 },
  { title: "A Noite do Meu Bem", artist: "Dolores Duran", year: 1959 },
  { title: "Rua Augusta", artist: "Ronnie Cord", year: 1963 },
  { title: "Canto de Ossanha", artist: "Baden Powell e Vinicius de Moraes", year: 1966 },

  // --- Portugal — fado, rock e pop (adições) ---
  { title: "Grândola, Vila Morena", artist: "Zeca Afonso", year: 1971 },
  { title: "Canção do Mar", artist: "Dulce Pontes", year: 1993 },
  { title: "E Depois do Adeus", artist: "Paulo de Carvalho", year: 1974 },
  { title: "Desfado", artist: "Ana Moura", year: 2012 },
  { title: "O Erro Mais Bonito", artist: "Ana Bacalhau e Diogo Piçarra", year: 2019 },
  { title: "NÓS2", artist: "Bispo e Deezy", year: 2018 },
  { title: "Essa Saia", artist: "Bispo e Ivandro", year: 2019 },
  { title: "Cerco", artist: "Xutos & Pontapés", year: 1985 },
  { title: "Por Quem Não Esqueci", artist: "Sétima Legião", year: 1989 },
  { title: "Glória", artist: "Sétima Legião", year: 1983 },

  // --- Rock brasileiro anos 80 (adições) ---
  { title: "Exagerado", artist: "Cazuza", year: 1985 },
  { title: "Codinome Beija-Flor", artist: "Cazuza", year: 1985 },
  { title: "Pro Dia Nascer Feliz", artist: "Cazuza", year: 1988 },
  { title: "Lanterna dos Afogados", artist: "Os Paralamas do Sucesso", year: 1986 },
  { title: "Meu Erro", artist: "Os Paralamas do Sucesso", year: 1985 },
  { title: "Jubiabá", artist: "Os Paralamas do Sucesso", year: 1986 },
  { title: "Revoluções Por Minuto", artist: "RPM", year: 1985 },
  { title: "Rádio Pirata", artist: "RPM", year: 1986 },
  { title: "Pintura Íntima", artist: "Kid Abelha", year: 1984 },
  { title: "Fixação", artist: "Kid Abelha", year: 1984 },
  { title: "Como Eu Quero", artist: "Kid Abelha", year: 1983 },

  // --- Nordeste — Zé Ramalho, Elba Ramalho, Geraldo Azevedo, Gonzaguinha ---
  { title: "Vila do Sossego", artist: "Zé Ramalho", year: 1978 },
  { title: "Chão de Giz", artist: "Zé Ramalho", year: 1978 },
  { title: "Bicho de Sete Cabeças", artist: "Zé Ramalho", year: 1978 },
  { title: "Admirável Gado Novo", artist: "Zé Ramalho", year: 1979 },
  { title: "Frevo Mulher", artist: "Zé Ramalho", year: 1979 },
  { title: "Banho de Cheiro", artist: "Elba Ramalho", year: 1996 },
  { title: "Táxi Lunar", artist: "Geraldo Azevedo", year: 1996 },
  { title: "Sangrando", artist: "Gonzaguinha", year: 1982 },

  // --- Samba clássico (adições) ---
  { title: "Saudosa Maloca", artist: "Adoniran Barbosa", year: 1951 },
  { title: "Andança", artist: "Beth Carvalho", year: 1968 },
  { title: "Conto de Areia", artist: "Clara Nunes", year: 1974 },
  { title: "Canto das Três Raças", artist: "Clara Nunes", year: 1976 },

  // --- Mamonas Assassinas ---
  { title: "Pelados em Santos", artist: "Mamonas Assassinas", year: 1995 },
  { title: "Robocop Gay", artist: "Mamonas Assassinas", year: 1995 },
  { title: "Vira-Vira", artist: "Mamonas Assassinas", year: 1995 },

  // --- Reggae, rock alternativo e pagode 2000 (adições) ---
  { title: "Pescador de Ilusões", artist: "O Rappa", year: 1996 },
  { title: "A Sombra da Maldade", artist: "Cidade Negra", year: 1994 },
  { title: "Onde Você Mora", artist: "Cidade Negra", year: 1994 },
  { title: "Firmamento", artist: "Cidade Negra", year: 1996 },
  { title: "Girassol", artist: "Cidade Negra", year: 1998 },
  { title: "Liberdade pra Dentro da Cabeça", artist: "Natiruts", year: 1998 },
  { title: "Tá Escrito", artist: "Grupo Revelação", year: 2002 },

  // --- Axé anos 90 (adições) ---
  { title: "Segura o Tchan", artist: "É o Tchan", year: 1995 },
  { title: "Dança da Manivela", artist: "Asa de Águia", year: 1994 },
  { title: "Liberar Geral", artist: "Terra Samba", year: 1997 },
  { title: "Bate Lata", artist: "Banda Beijo", year: 1994 },

  // --- Funk carioca ---
  { title: "Rap da Felicidade", artist: "Cidinho e Doca", year: 1994 },
  { title: "Só Love", artist: "Claudinho e Buchecha", year: 1998 },
  { title: "Cerol na Mão", artist: "Bonde do Tigrão", year: 2001 },
  { title: "Glamurosa", artist: "MC Marcinho", year: 2003 },
  { title: "Eguinha Pocotó", artist: "MC Serginho", year: 2003 },

  // --- Sertanejo — raiz a universitário (adições) ---
  { title: "É o Amor", artist: "Zezé Di Camargo e Luciano", year: 1991 },
  { title: "Desculpe, Mas Eu Vou Chorar", artist: "Leandro & Leonardo", year: 1990 },
  { title: "Não Aprendi a Dizer Adeus", artist: "Leandro & Leonardo", year: 1991 },
  { title: "Um Sonhador", artist: "Leandro & Leonardo", year: 1992 },
  { title: "Liberdade Provisória", artist: "Henrique e Juliano", year: 2020 },
  { title: "Cuida Bem Dela", artist: "Henrique e Juliano", year: 2018 },
  { title: "Como É Que a Gente Fica", artist: "Henrique e Juliano", year: 2019 },
  { title: "Céu Particular", artist: "Henrique e Juliano", year: 2021 },
  { title: "10%", artist: "Maiara e Maraisa", year: 2015 },
  { title: "Medo Bobo", artist: "Maiara e Maraisa", year: 2018 },
  { title: "A Culpa É Dele", artist: "Maiara e Maraisa", year: 2019 },
  { title: "Largado às Traças", artist: "Zé Neto e Cristiano", year: 2018 },
  { title: "Braba", artist: "Luísa Sonza", year: 2019 },
  { title: "Combatchy", artist: "Luísa Sonza, Anitta e Papatinho", year: 2019 },
  { title: "Modo Turbo", artist: "Luísa Sonza, Pabllo Vittar e Anitta", year: 2020 },
  { title: "Flores", artist: "Luísa Sonza e Vitão", year: 2021 },
  { title: "Café da Manhã", artist: "Ludmilla e Luísa Sonza", year: 2022 },
  { title: "Ai Que Calor", artist: "Pabllo Vittar e Duda Beat", year: 2019 },
  { title: "Procurando Tu", artist: "Trio Nordestino", year: 1970 },
  { title: "Eu Só Quero Um Xodó", artist: "Dominguinhos", year: 1973 },

  // --- Anitta ---
  { title: "Meiga e Abusada", artist: "Anitta", year: 2012 },
  { title: "Blá Blá Blá", artist: "Anitta", year: 2014 },
  { title: "Na Batida", artist: "Anitta", year: 2014 },
  { title: "Downtown", artist: "Anitta e J Balvin", year: 2017 },
  { title: "Girl From Rio", artist: "Anitta", year: 2021 },
  { title: "Essa Mina É Louca", artist: "Anitta", year: 2013 },
  { title: "Deixa Ele Sofrer", artist: "Anitta", year: 2015 },

  // --- Rock brasileiro — Legião Urbana, Titãs, Barão Vermelho, Biquini Cavadão ---
  { title: "Será", artist: "Legião Urbana", year: 1985 },
  { title: "Geração Coca-Cola", artist: "Legião Urbana", year: 1985 },
  { title: "Ainda É Cedo", artist: "Legião Urbana", year: 1985 },
  { title: "Índios", artist: "Legião Urbana", year: 1986 },
  { title: "Eu Sei", artist: "Legião Urbana", year: 1987 },
  { title: "Há Tempos", artist: "Legião Urbana", year: 1989 },
  { title: "Quando o Sol Bater na Janela do Seu Quarto", artist: "Legião Urbana", year: 1989 },
  { title: "Meninos e Meninas", artist: "Legião Urbana", year: 1989 },
  { title: "Cabeça Dinossauro", artist: "Titãs", year: 1986 },
  { title: "Desordem", artist: "Titãs", year: 1986 },
  { title: "Família", artist: "Titãs", year: 1986 },
  { title: "Flores", artist: "Titãs", year: 1989 },
  { title: "Homem Primata", artist: "Titãs", year: 1986 },
  { title: "Marvin", artist: "Titãs", year: 1986 },
  { title: "Não Vou Me Adaptar", artist: "Titãs", year: 1986 },
  { title: "Querem Meu Sangue", artist: "Titãs", year: 1991 },
  { title: "Carente Profissional", artist: "Barão Vermelho", year: 1984 },
  { title: "Maior Abandonado", artist: "Barão Vermelho", year: 1982 },
  { title: "Pense e Dance", artist: "Barão Vermelho", year: 1982 },
  { title: "Todo Amor Que Houver Nessa Vida", artist: "Barão Vermelho", year: 1986 },
  { title: "Vento Ventania", artist: "Biquini Cavadão", year: 1986 },
  { title: "Tédio", artist: "Biquini Cavadão", year: 1990 },
  { title: "Zé Ninguém", artist: "Biquini Cavadão", year: 1996 },
  { title: "Timidez", artist: "Biquini Cavadão", year: 1988 },

  // --- Sertanejo universitário, gospel e pagode romântico ---
  { title: "Meteoro da Paixão", artist: "Luan Santana", year: 2009 },
  { title: "Te Esperando", artist: "Luan Santana", year: 2013 },
  { title: "Sinais", artist: "Luan Santana", year: 2014 },
  { title: "Amar Não É Pecado", artist: "Luan Santana", year: 2012 },
  { title: "Balada", artist: "Gusttavo Lima", year: 2011 },
  { title: "Bloqueado", artist: "Gusttavo Lima", year: 2016 },
  { title: "Homem de Família", artist: "Gusttavo Lima", year: 2018 },
  { title: "Magia e Mistério", artist: "João Bosco e Vinicius", year: 2003 },
  { title: "Chora, Me Liga", artist: "João Bosco e Vinicius", year: 2009 },
  { title: "Fogueira", artist: "Jorge & Mateus", year: 2007 },
  { title: "Grandes Coisas", artist: "Fernandinho", year: 2013 },
  { title: "Galileu", artist: "Fernandinho", year: 2011 },
  { title: "Casa do Pai", artist: "Aline Barros", year: 1999 },
  { title: "Lugar Secreto", artist: "Gabriela Rocha", year: 2019 },
  { title: "Que se Chama Amor", artist: "Só Pra Contrariar", year: 1993 },
  { title: "A Barata", artist: "Só Pra Contrariar", year: 1993 },
  { title: "Depois do Prazer", artist: "Só Pra Contrariar", year: 1997 },

  // --- Axé, MPB e rock anos 2000 (adições) ---
  { title: "Milla", artist: "Netinho", year: 1996 },
  { title: "Beleza Rara", artist: "Banda Eva", year: 1997 },
  { title: "Pequena Eva", artist: "Banda Eva", year: 1998 },
  { title: "Coração", artist: "Diogo Piçarra", year: 2019 },
  { title: "Anjos", artist: "Diogo Piçarra e Carolina Deslandes", year: 2019 },
  { title: "Vilarejo", artist: "Marisa Monte", year: 2011 },
  { title: "Arrastão", artist: "Elis Regina", year: 1965 },
  { title: "Razões e Emoções", artist: "NX Zero", year: 2005 },
  { title: "Cedo ou Tarde", artist: "NX Zero", year: 2007 },
  { title: "Dias Atrás", artist: "CPM 22", year: 2005 },
  { title: "Outro Lugar", artist: "Detonautas", year: 2002 },
  { title: "Admirável Chip Novo", artist: "Pitty", year: 2003 },

  // --- Forró, axé e pop recente (adições) ---
  { title: "Xote dos Milagres", artist: "Falamansa", year: 2000 },
  { title: "Um Dia Perfeito", artist: "Falamansa", year: 2000 },
  { title: "Rindo à Toa", artist: "Falamansa", year: 2000 },
  { title: "Destrava", artist: "Claudia Leitte", year: 2011 },
  { title: "Festa", artist: "Ivete Sangalo", year: 2007 },
  { title: "Aquele 1%", artist: "Wesley Safadão e Marcos & Belutti", year: 2015 },
  { title: "À Vontade", artist: "Wesley Safadão", year: 2017 },
  { title: "Amor Falso", artist: "Wesley Safadão", year: 2018 },
  { title: "Loka", artist: "Simone & Simaria e Anitta", year: 2017 },
  { title: "Paga de Solteiro Feliz", artist: "Simone & Simaria e Alok", year: 2018 },
  { title: "O Sol", artist: "Vitor Kley", year: 2016 },
  { title: "Morena", artist: "Vitor Kley", year: 2019 },
  { title: "Garoto Errado", artist: "Manu Gavassi", year: 2013 },
  { title: "Meu Abrigo", artist: "Melim", year: 2017 },
  { title: "Você Tem", artist: "Vitão e Carol Biazin", year: 2020 },

  // --- Portugal — Rui Veloso, pop e Festival da Canção (adições) ---
  { title: "Porto Sentido", artist: "Rui Veloso", year: 1986 },
  { title: "Porto Côvo", artist: "Rui Veloso", year: 1986 },
  { title: "Cavaleiro Andante", artist: "Rui Veloso", year: 1986 },
  { title: "A Gente Não Lê", artist: "Rui Veloso", year: 1983 },
  { title: "Máquina Zero", artist: "Rui Veloso", year: 1984 },
  { title: "Antes Dela Dizer Que Sim", artist: "Bárbara Tinoco", year: 2019 },
  { title: "Sei Lá", artist: "Bárbara Tinoco", year: 2021 },
  { title: "Outras Línguas", artist: "Bárbara Tinoco", year: 2021 },
  { title: "Oração", artist: "António Calvário", year: 1964 },
  { title: "Foi Magia", artist: "Sofia Vitória", year: 2004 },
  { title: "Amor", artist: "Heróis do Mar", year: 1982 },
  { title: "Paixão", artist: "Heróis do Mar", year: 1983 },
  { title: "Ai Destino", artist: "Tony Carreira", year: 1995 },
  { title: "Depois de Ti Mais Nada", artist: "Tony Carreira", year: 1999 },

  // --- MPB e funk 150 BPM (adições) ---
  { title: "Cotidiano", artist: "Chico Buarque", year: 1971 },
  { title: "Tatuagem", artist: "Chico Buarque", year: 1972 },
  { title: "Olha Maria", artist: "Chico Buarque", year: 1971 },
  { title: "Maria, Maria", artist: "Milton Nascimento", year: 1978 },
  { title: "Encontros e Despedidas", artist: "Milton Nascimento", year: 1985 },
  { title: "Nos Bailes da Vida", artist: "Milton Nascimento", year: 1981 },
  { title: "Olha a Explosão", artist: "MC Kevinho", year: 2016 },
  { title: "Elas Gostam", artist: "MC Kevinho", year: 2016 },
  { title: "Terremoto", artist: "MC Kevinho e Anitta", year: 2017 },
  { title: "Bem Querer", artist: "MC Livinho", year: 2016 },
  { title: "Dentro do Carro", artist: "Kevin O Chris", year: 2018 },

  // --- Pagode, agronejo e Djavan (adições) ---
  { title: "Vai Vadiar", artist: "Zeca Pagodinho", year: 1998 },
  { title: "Judia de Mim", artist: "Zeca Pagodinho", year: 1986 },
  { title: "Pipoco", artist: "Ana Castela, Melody e DJ Chris No Beat", year: 2022 },
  { title: "Bombonzinho", artist: "Ana Castela e Israel & Rodolffo", year: 2022 },
  { title: "Faltando um Pedaço", artist: "Djavan", year: 1981 },
  { title: "Eu Te Devoro", artist: "Djavan", year: 1998 },
  { title: "Lilás", artist: "Djavan", year: 1989 },

  // --- Roberto Carlos, MPB e Portugal (adições) ---
  { title: "Jesus Cristo", artist: "Roberto Carlos", year: 1970 },
  { title: "Cavalgada", artist: "Roberto Carlos", year: 1977 },
  { title: "O Portão", artist: "Roberto Carlos", year: 1980 },
  { title: "Proposta", artist: "Roberto Carlos", year: 1978 },
  { title: "Outra Vez", artist: "Roberto Carlos", year: 1976 },
  { title: "Como Vai Você", artist: "Roberto Carlos", year: 1979 },
  { title: "Um Índio", artist: "Caetano Veloso", year: 1977 },
  { title: "Agora Só Falta Você", artist: "Rita Lee", year: 1979 },
  { title: "Já Sei Namorar", artist: "Tribalistas", year: 2002 },
  { title: "Velha Infância", artist: "Tribalistas", year: 2002 },
  { title: "Carnavália", artist: "Tribalistas", year: 2002 },
  { title: "O Pastor", artist: "Madredeus", year: 1990 },
  { title: "Ainda", artist: "Madredeus", year: 1995 },
  { title: "Haja o Que Houver", artist: "Madredeus", year: 1994 },

  // --- Sertanejo, axé e Portugal recentes ---
  { title: "Propaganda", artist: "Jorge & Mateus", year: 2018 },
  { title: "Lençol Dobrado", artist: "João Gustavo & Murilo", year: 2019 },
  { title: "Batom de Cereja", artist: "Israel & Rodolffo", year: 2021 },
  { title: "Leão", artist: "Marília Mendonça", year: 2023 },
  { title: "Se Acaso Você Chegasse", artist: "Elza Soares", year: 1959 },
  { title: "Telemóveis", artist: "Conan Osiris", year: 2019 },
  { title: "Noite Inteira", artist: "Iolanda", year: 2024 },

  // --- Axé, MPB, rock e pop (adições) ---
  { title: "Magalenha", artist: "Carlinhos Brown", year: 1996 },
  { title: "Poema", artist: "Ney Matogrosso", year: 1976 },
  { title: "Jackie Tequila", artist: "Skank", year: 1994 },
  { title: "O Samba Poconé", artist: "Skank", year: 1996 },
  { title: "Saideira", artist: "Skank", year: 1998 },
  { title: "Encontrar Alguém", artist: "Jota Quest", year: 1998 },
  { title: "Fácil", artist: "Jota Quest", year: 1998 },
  { title: "Dias Melhores", artist: "Jota Quest", year: 2000 },
  { title: "Open Bar", artist: "Pabllo Vittar", year: 2015 },
  { title: "Sua Cara", artist: "Major Lazer, Pabllo Vittar e Anitta", year: 2017 },
  { title: "Vai Passar Mal", artist: "Pabllo Vittar", year: 2017 },
  { title: "Proibidona", artist: "Gloria Groove, Anitta e Valesca Popozuda", year: 2023 },
  { title: "Sonho Meu", artist: "Elba Ramalho", year: 1979 },
  { title: "Ciranda da Rosa Vermelha", artist: "Elba Ramalho", year: 1978 },
  { title: "Nuvem de Lágrimas", artist: "Chitãozinho & Xororó", year: 1989 },
  { title: "Saudade da Minha Terra", artist: "Chitãozinho & Xororó e João Paulo e Daniel", year: 1996 },
  { title: "Cheia de Manias", artist: "Raça Negra", year: 1996 },
  { title: "Cigana", artist: "Raça Negra", year: 1993 },
  { title: "Doce Paixão", artist: "Raça Negra", year: 1994 },
  { title: "Dig-Dig-Joy", artist: "Sandy & Júnior", year: 1996 },
  { title: "Vou de Táxi", artist: "Angélica", year: 1988 },
  { title: "Bombom", artist: "Xuxa", year: 1990 },

  // --- Infantil, sertanejo feminino e clássicos adicionais ---
  { title: "He-Man", artist: "Trem da Alegria", year: 1986 },
  { title: "50 Reais", artist: "Naiara Azevedo", year: 2016 },
  { title: "Erro Gostoso", artist: "Simone Mendes", year: 2020 },
  { title: "Ilê Pérola Negra", artist: "Daniela Mercury", year: 1996 },
  { title: "Você Abusou", artist: "Os Originais do Samba", year: 1971 },
  { title: "Verdes Anos", artist: "Carlos Paião", year: 1981 },
  { title: "Como Nossos Pais", artist: "Belchior", year: 1976 },
  { title: "Apenas um Rapaz Latino-Americano", artist: "Belchior", year: 1976 },
  { title: "Velha Roupa Colorida", artist: "Belchior", year: 1976 },
  { title: "Borbulhas de Amor", artist: "Fagner", year: 1991 },
  { title: "Canteiros", artist: "Fagner", year: 1973 },
  { title: "Espumas ao Vento", artist: "Fagner", year: 1997 },
  { title: "Dona da Minha Cabeça", artist: "Geraldo Azevedo", year: 1984 },
  { title: "Moça Bonita", artist: "Geraldo Azevedo", year: 1984 },
  { title: "Dia Branco", artist: "Geraldo Azevedo", year: 1981 },
  { title: "Caravana", artist: "Geraldo Azevedo", year: 1979 },
  { title: "Sabiá", artist: "Luiz Gonzaga", year: 1968 },
];
