// songs/pt.js — מאגר שירים בפורטוגזית (ללא youtubeId — ניגון בחיפוש אוטומטי).
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.pt = [
  { title: "Garota de Ipanema", artist: "Tom Jobim & Vinícius de Moraes", year: 1962 },
  { title: "Águas de Março", artist: "Tom Jobim", year: 1972 },
  { title: "Chega de Saudade", artist: "João Gilberto", year: 1958 },
  { title: "Desafinado", artist: "João Gilberto", year: 1959 },
  { title: "Aquarela do Brasil", artist: "Ary Barroso", year: 1939 },
  { title: "Mas Que Nada", artist: "Jorge Ben Jor", year: 1963 },
  { title: "País Tropical", artist: "Jorge Ben Jor", year: 1969 },
  { title: "Taj Mahal", artist: "Jorge Ben Jor", year: 1972 },
  { title: "Aquele Abraço", artist: "Gilberto Gil", year: 1969 },
  { title: "Andar Com Fé", artist: "Gilberto Gil", year: 1982 },
  { title: "Toda Menina Baiana", artist: "Gilberto Gil", year: 1980 },
  { title: "Você Não Me Ensinou a Te Esquecer", artist: "Caetano Veloso", year: 1993 },
  { title: "Sozinho", artist: "Caetano Veloso", year: 1993 },
  { title: "Alegria, Alegria", artist: "Caetano Veloso", year: 1967 },
  { title: "Como Nossos Pais", artist: "Elis Regina", year: 1976 },
  { title: "Águas de Março (Elis version)", artist: "Elis Regina", year: 1974 },
  { title: "O Bêbado e a Equilibrista", artist: "Elis Regina", year: 1979 },
  { title: "Anunciação", artist: "Alceu Valença", year: 1979 },
  { title: "Morena Tropicana", artist: "Alceu Valença", year: 1978 },
  { title: "Evidências", artist: "Chitãozinho & Xororó", year: 1990 },
  { title: "Fio de Cabelo", artist: "Chitãozinho & Xororó", year: 1990 },
  { title: "Ai Se Eu Te Pego", artist: "Michel Teló", year: 2011 },
  { title: "Fugidinha", artist: "Michel Teló", year: 2012 },
  { title: "Como É Grande o Meu Amor Por Você", artist: "Roberto Carlos", year: 1967 },
  { title: "Detalhes", artist: "Roberto Carlos", year: 1971 },
  { title: "Emoções", artist: "Roberto Carlos", year: 1981 },
  { title: "Amada Amante", artist: "Roberto Carlos", year: 1975 },
  { title: "Além do Horizonte", artist: "Roberto Carlos", year: 1963 },
  { title: "É Preciso Saber Viver", artist: "Roberto Carlos & Erasmo Carlos", year: 1968 },
  { title: "Mulher de Fases", artist: "Zeca Pagodinho", year: 1997 },
  { title: "Deixa a Vida Me Levar", artist: "Zeca Pagodinho", year: 1997 },
  { title: "Verdade", artist: "Zeca Pagodinho", year: 2001 },
  { title: "O Show Tem Que Continuar", artist: "Zeca Pagodinho", year: 1999 },
  { title: "Apesar de Você", artist: "Chico Buarque", year: 1970 },
  { title: "Construção", artist: "Chico Buarque", year: 1971 },
  { title: "A Banda", artist: "Chico Buarque", year: 1966 },
  { title: "Roda Viva", artist: "Chico Buarque", year: 1968 },
  { title: "Cálice", artist: "Chico Buarque & Gilberto Gil", year: 1973 },
  { title: "Xote das Meninas", artist: "Luiz Gonzaga", year: 1953 },
  { title: "Asa Branca", artist: "Luiz Gonzaga", year: 1947 },
  { title: "Qui Nem Jiló", artist: "Luiz Gonzaga", year: 1951 },
  { title: "Ai Ai Ai De Mim", artist: "Roupa Nova", year: 1985 },
  { title: "Whisky a Go Go", artist: "Roupa Nova", year: 1982 },
  { title: "Dona", artist: "Roupa Nova", year: 1988 },
  { title: "Anna Júlia", artist: "Los Hermanos", year: 1999 },
  { title: "O Vencedor", artist: "Los Hermanos", year: 1999 },
  { title: "Sofrência", artist: "Marília Mendonça", year: 2018 },
  { title: "Infiel", artist: "Marília Mendonça", year: 2016 },
  { title: "Todo Mundo Vai Sofrer", artist: "Marília Mendonça", year: 2016 },
  { title: "Fala Mal de Mim", artist: "Marília Mendonça", year: 2021 },
  { title: "Batendo Estrela", artist: "Jorge & Mateus", year: 2011 },
  { title: "Pé na Areia", artist: "Jorge & Mateus", year: 2013 },
  { title: "Os Anjos Cantam", artist: "Jorge & Mateus", year: 2013 },
  { title: "Amor de Chocolate", artist: "Jorge & Mateus", year: 2009 },
  { title: "Trem-Bala", artist: "Ana Vilela", year: 2017 },
  { title: "Bandida", artist: "Anitta", year: 2013 },
  { title: "Show das Poderosas", artist: "Anitta", year: 2013 },
  { title: "Vai Malandra", artist: "Anitta", year: 2017 },
  { title: "Envolver", artist: "Anitta", year: 2021 },
  { title: "Paradinha", artist: "Anitta", year: 2017 },
  { title: "Deixa Isso Pra Lá", artist: "Legião Urbana", year: 1985 },
  { title: "Tempo Perdido", artist: "Legião Urbana", year: 1986 },
  { title: "Eduardo e Mônica", artist: "Legião Urbana", year: 1986 },
  { title: "Faroeste Caboclo", artist: "Legião Urbana", year: 1987 },
  { title: "Pais e Filhos", artist: "Legião Urbana", year: 1989 },
  { title: "Metamorfose Ambulante", artist: "Raul Seixas", year: 1973 },
  { title: "Ouro de Tolo", artist: "Raul Seixas", year: 1973 },
  { title: "Maluco Beleza", artist: "Raul Seixas", year: 1977 },
  { title: "Como Uma Onda", artist: "Lulu Santos", year: 1983 },
  { title: "Assum Preto", artist: "Lulu Santos", year: 1984 },
  { title: "Tempos Modernos", artist: "Lulu Santos", year: 1982 },
  { title: "Aquele 99", artist: "Skank", year: 1998 },
  { title: "É Uma Partida de Futebol", artist: "Skank", year: 1996 },
  { title: "Garota Nacional", artist: "Skank", year: 2000 },
  { title: "A Sua", artist: "Skank", year: 2003 },
  { title: "Vira-Lata", artist: "Titãs", year: 1986 },
  { title: "Comida", artist: "Titãs", year: 1987 },
  { title: "Epitáfio", artist: "Titãs", year: 1989 },
  { title: "Sonífera Ilha", artist: "Titãs", year: 1986 },
  { title: "Amor Não Correspondido", artist: "Charlie Brown Jr.", year: 1999 },
  { title: "Só os Loucos Sabem", artist: "Charlie Brown Jr.", year: 1997 },
  { title: "Zoio de Lula", artist: "Charlie Brown Jr.", year: 1997 },
  { title: "Não Deixe o Samba Morrer", artist: "Alcione", year: 1981 },
  { title: "Ilariê", artist: "Rita Lee", year: 1978 },
  { title: "Mania de Você", artist: "Rita Lee", year: 1979 },
  { title: "Lança Perfume", artist: "Rita Lee", year: 1980 },
  { title: "Balada Boa", artist: "Gusttavo Lima", year: 2011 },
  { title: "Apelido Carinhoso", artist: "Gusttavo Lima", year: 2013 },
  { title: "Diz Pra Mim", artist: "Gusttavo Lima", year: 2012 },
  { title: "Chora Me Liga", artist: "Wesley Safadão", year: 2017 },
  { title: "Camarote", artist: "Wesley Safadão", year: 2015 },
];
