// songs/pt.js — מאגר שירים בפורטוגזית (ללא youtubeId — ניגון בחיפוש אוטומטי).
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.pt = [
  { title: "Garota de Ipanema", artist: "Tom Jobim & Vinícius de Moraes", year: 1962 },
  { title: "Águas de Março", artist: "Tom Jobim", year: 1972 },
  { title: "Chega de Saudade", artist: "João Gilberto", year: 1958 },
  { title: "Desafinado", artist: "João Gilberto", year: 1959 },
  { title: "Aquarela do Brasil", artist: "Ary Barroso", year: 1939 },
  { title: "Mas Que Nada", artist: "Jorge Ben Jor", year: 1963 },
  { title: "País Tropical", artist: "Jorge Ben Jor", year: 1969 },
  { title: "Taj Mahal", artist: "Jorge Ben Jor", year: 1972 },
  { title: "Aquele Abraço", artist: "Gilberto Gil", year: 1969 },
  { title: "Andar Com Fé", artist: "Gilberto Gil", year: 1982 },
  { title: "Toda Menina Baiana", artist: "Gilberto Gil", year: 1980 },
  { title: "Você Não Me Ensinou a Te Esquecer", artist: "Caetano Veloso", year: 1993 },
  { title: "Sozinho", artist: "Caetano Veloso", year: 1993 },
  { title: "Alegria, Alegria", artist: "Caetano Veloso", year: 1967 },
  { title: "Como Nossos Pais", artist: "Elis Regina", year: 1976 },
  { title: "Águas de Março (Elis version)", artist: "Elis Regina", year: 1974 },
  { title: "O Bêbado e a Equilibrista", artist: "Elis Regina", year: 1979 },
  { title: "Anunciação", artist: "Alceu Valença", year: 1979 },
  { title: "Morena Tropicana", artist: "Alceu Valença", year: 1978 },
  { title: "Evidências", artist: "Chitãozinho & Xororó", year: 1990 },
  { title: "Fio de Cabelo", artist: "Chitãozinho & Xororó", year: 1990 },
  { title: "Ai Se Eu Te Pego", artist: "Michel Teló", year: 2011 },
  { title: "Fugidinha", artist: "Michel Teló", year: 2012 },
  { title: "Como É Grande o Meu Amor Por Você", artist: "Roberto Carlos", year: 1967 },
  { title: "Detalhes", artist: "Roberto Carlos", year: 1971 },
  { title: "Emoções", artist: "Roberto Carlos", year: 1981 },
  { title: "Amada Amante", artist: "Roberto Carlos", year: 1975 },
  { title: "Além do Horizonte", artist: "Roberto Carlos", year: 1963 },
  { title: "É Preciso Saber Viver", artist: "Roberto Carlos & Erasmo Carlos", year: 1968 },
  { title: "Mulher de Fases", artist: "Zeca Pagodinho", year: 1997 },
  { title: "Deixa a Vida Me Levar", artist: "Zeca Pagodinho", year: 1997 },
  { title: "Verdade", artist: "Zeca Pagodinho", year: 2001 },
  { title: "O Show Tem Que Continuar", artist: "Zeca Pagodinho", year: 1999 },
  { title: "Apesar de Você", artist: "Chico Buarque", year: 1970 },
  { title: "Construção", artist: "Chico Buarque", year: 1971 },
  { title: "A Banda", artist: "Chico Buarque", year: 1966 },
  { title: "Roda Viva", artist: "Chico Buarque", year: 1968 },
  { title: "Cálice", artist: "Chico Buarque & Gilberto Gil", year: 1973 },
  { title: "Xote das Meninas", artist: "Luiz Gonzaga", year: 1953 },
  { title: "Asa Branca", artist: "Luiz Gonzaga", year: 1947 },
  { title: "Qui Nem Jiló", artist: "Luiz Gonzaga", year: 1951 },
  { title: "Ai Ai Ai De Mim", artist: "Roupa Nova", year: 1985 },
  { title: "Whisky a Go Go", artist: "Roupa Nova", year: 1982 },
  { title: "Dona", artist: "Roupa Nova", year: 1988 },
  { title: "Anna Júlia", artist: "Los Hermanos", year: 1999 },
  { title: "O Vencedor", artist: "Los Hermanos", year: 1999 },
  { title: "Sofrência", artist: "Marília Mendonça", year: 2018 },
  { title: "Infiel", artist: "Marília Mendonça", year: 2016 },
  { title: "Todo Mundo Vai Sofrer", artist: "Marília Mendonça", year: 2016 },
  { title: "Fala Mal de Mim", artist: "Marília Mendonça", year: 2021 },
  { title: "Batendo Estrela", artist: "Jorge & Mateus", year: 2011 },
  { title: "Pé na Areia", artist: "Jorge & Mateus", year: 2013 },
  { title: "Os Anjos Cantam", artist: "Jorge & Mateus", year: 2013 },
  { title: "Amor de Chocolate", artist: "Jorge & Mateus", year: 2009 },
  { title: "Trem-Bala", artist: "Ana Vilela", year: 2017 },
  { title: "Bandida", artist: "Anitta", year: 2013 },
  { title: "Show das Poderosas", artist: "Anitta", year: 2013 },
  { title: "Vai Malandra", artist: "Anitta", year: 2017 },
  { title: "Envolver", artist: "Anitta", year: 2021 },
  { title: "Paradinha", artist: "Anitta", year: 2017 },
  { title: "Deixa Isso Pra Lá", artist: "Legião Urbana", year: 1985 },
  { title: "Tempo Perdido", artist: "Legião Urbana", year: 1986 },
  { title: "Eduardo e Mônica", artist: "Legião Urbana", year: 1986 },
  { title: "Faroeste Caboclo", artist: "Legião Urbana", year: 1987 },
  { title: "Pais e Filhos", artist: "Legião Urbana", year: 1989 },
  { title: "Metamorfose Ambulante", artist: "Raul Seixas", year: 1973 },
  { title: "Ouro de Tolo", artist: "Raul Seixas", year: 1973 },
  { title: "Maluco Beleza", artist: "Raul Seixas", year: 1977 },
  { title: "Como Uma Onda", artist: "Lulu Santos", year: 1983 },
  { title: "Assum Preto", artist: "Lulu Santos", year: 1984 },
  { title: "Tempos Modernos", artist: "Lulu Santos", year: 1982 },
  { title: "Aquele 99", artist: "Skank", year: 1998 },
  { title: "É Uma Partida de Futebol", artist: "Skank", year: 1996 },
  { title: "Garota Nacional", artist: "Skank", year: 2000 },
  { title: "A Sua", artist: "Skank", year: 2003 },
  { title: "Vira-Lata", artist: "Titãs", year: 1986 },
  { title: "Comida", artist: "Titãs", year: 1987 },
  { title: "Epitáfio", artist: "Titãs", year: 1989 },
  { title: "Sonífera Ilha", artist: "Titãs", year: 1986 },
  { title: "Amor Não Correspondido", artist: "Charlie Brown Jr.", year: 1999 },
  { title: "Só os Loucos Sabem", artist: "Charlie Brown Jr.", year: 1997 },
  { title: "Zoio de Lula", artist: "Charlie Brown Jr.", year: 1997 },
  { title: "Não Deixe o Samba Morrer", artist: "Alcione", year: 1981 },
  { title: "Ilariê", artist: "Rita Lee", year: 1978 },
  { title: "Mania de Você", artist: "Rita Lee", year: 1979 },
  { title: "Lança Perfume", artist: "Rita Lee", year: 1980 },
  { title: "Balada Boa", artist: "Gusttavo Lima", year: 2011 },
  { title: "Apelido Carinhoso", artist: "Gusttavo Lima", year: 2013 },
  { title: "Diz Pra Mim", artist: "Gusttavo Lima", year: 2012 },
  { title: "Chora Me Liga", artist: "Wesley Safadão", year: 2017 },
  { title: "Camarote", artist: "Wesley Safadão", year: 2015 },

  // --- Fado (Portugal) ---
  { title: "Uma Casa Portuguesa", artist: "Amália Rodrigues", year: 1953 },
  { title: "Estranha Forma de Vida", artist: "Amália Rodrigues", year: 1962 },
  { title: "Povo Que Lavas No Rio", artist: "Amália Rodrigues", year: 1945 },
  { title: "Barco Negro", artist: "Amália Rodrigues", year: 1955 },
  { title: "Gaivota", artist: "Amália Rodrigues", year: 1963 },
  { title: "Meu Fado Meu", artist: "Mariza", year: 2001 },
  { title: "Ó Gente da Minha Terra", artist: "Mariza", year: 2001 },
  { title: "Barco Negro (Mariza)", artist: "Mariza", year: 2005 },
  { title: "Chuva", artist: "Mariza", year: 2010 },
  { title: "Cavaleiro Monge", artist: "Carlos do Carmo", year: 1977 },
  { title: "Lisboa Menina e Moça", artist: "Carlos do Carmo", year: 1984 },
  { title: "Os Putos", artist: "Carlos do Carmo", year: 1982 },

  // --- Rock/Pop português ---
  { title: "A Minha Casinha", artist: "Xutos & Pontapés", year: 1993 },
  { title: "Os Emigrantes", artist: "Xutos & Pontapés", year: 1989 },
  { title: "Circo de Feras", artist: "Xutos & Pontapés", year: 1996 },
  { title: "Contentores de Nós", artist: "Xutos & Pontapés", year: 2000 },
  { title: "Photograph", artist: "GNR", year: 1988 },
  { title: "Independência", artist: "GNR", year: 1982 },
  { title: "Sei Lá Navegar", artist: "Rui Veloso", year: 1980 },
  { title: "Chico Fininho", artist: "Rui Veloso", year: 1980 },
  { title: "Porto Cancão", artist: "Rui Veloso", year: 1980 },
  { title: "Amanhã Depois do Almoço", artist: "Da Weasel", year: 2004 },
  { title: "Toda a Gente Sabe", artist: "Da Weasel", year: 2007 },
  { title: "Mensagem Automática", artist: "Da Weasel", year: 2002 },
  { title: "Chamamos-lhe Amor", artist: "Da Weasel", year: 2011 },
  { title: "Toy", artist: "Salvador Sobral", year: 2017 },
  { title: "Amar Pelos Dois", artist: "Salvador Sobral", year: 2017 },

  // --- MPB ---
  { title: "Travessia", artist: "Milton Nascimento", year: 1967 },
  { title: "Cais", artist: "Milton Nascimento", year: 1978 },
  { title: "Bola de Meia, Bola de Gude", artist: "Milton Nascimento", year: 1972 },
  { title: "Nada Será Como Antes", artist: "Milton Nascimento", year: 1972 },
  { title: "Flor de Lis", artist: "Djavan", year: 1976 },
  { title: "Oceano", artist: "Djavan", year: 1989 },
  { title: "Samurai", artist: "Djavan", year: 1988 },
  { title: "Açaí", artist: "Djavan", year: 1981 },
  { title: "É Preciso Perdoar", artist: "Maria Bethânia", year: 1972 },
  { title: "Explode Coração", artist: "Maria Bethânia", year: 1988 },
  { title: "Ternura Antiga", artist: "Maria Bethânia", year: 1980 },
  { title: "Baby", artist: "Gal Costa", year: 1969 },
  { title: "Vapor Barato", artist: "Gal Costa", year: 1972 },
  { title: "Meu Nome É Gal", artist: "Gal Costa", year: 1969 },
  { title: "Festa do Interior", artist: "Gal Costa", year: 1977 },
  { title: "Modinha", artist: "Gal Costa", year: 1988 },
  { title: "Upa Neguinho", artist: "Elis Regina", year: 1967 },
  { title: "Madalena", artist: "Elis Regina", year: 1970 },
  { title: "Loucas Ilusões", artist: "Nara Leão", year: 1971 },
  { title: "Berimbau", artist: "Baden Powell", year: 1963 },
  { title: "Consolação", artist: "Baden Powell & Vinícius de Moraes", year: 1966 },
  { title: "Domingo No Parque", artist: "Gilberto Gil", year: 1967 },
  { title: "Expresso 2222", artist: "Gilberto Gil", year: 1972 },
  { title: "Palco", artist: "Gilberto Gil", year: 1977 },
  { title: "Filhos de Gandhi", artist: "Gilberto Gil", year: 1977 },
  { title: "Cucurrucucu Paloma (versão)", artist: "Caetano Veloso", year: 1984 },
  { title: "Cajuína", artist: "Caetano Veloso", year: 1971 },
  { title: "Odara", artist: "Caetano Veloso", year: 1977 },
  { title: "Terra", artist: "Caetano Veloso", year: 1978 },
  { title: "London London", artist: "Caetano Veloso", year: 1971 },
  { title: "Como 2 e 2", artist: "Marisa Monte", year: 1998 },
  { title: "Ainda Bem", artist: "Marisa Monte", year: 2006 },
  { title: "Bem Que Se Quis", artist: "Marisa Monte", year: 1994 },
  { title: "Diminuta", artist: "Marisa Monte", year: 2011 },
  { title: "Amor I Love You", artist: "Marisa Monte", year: 2006 },

  // --- Samba / Pagode / Axé ---
  { title: "Ela Só Pensa Em Beijar", artist: "Exaltasamba", year: 1999 },
  { title: "Espelho D'Água", artist: "Exaltasamba", year: 2000 },
  { title: "Errei Aceitar", artist: "Turma do Pagode", year: 2015 },
  { title: "Não Sei Se Choro ou Se Bebo", artist: "Turma do Pagode", year: 2014 },
  { title: "Deixa Acontecer", artist: "Thiaguinho", year: 2011 },
  { title: "Muleque Vacilão", artist: "Thiaguinho", year: 2011 },
  { title: "Ousadia e Alegria", artist: "Ivete Sangalo", year: 2000 },
  { title: "Sorte Grande", artist: "Ivete Sangalo", year: 1999 },
  { title: "Careless Whisper (Coração de Estudante remix)", artist: "Ivete Sangalo", year: 2007 },
  { title: "Se Eu Não Te Amasse Tanto Assim", artist: "Ivete Sangalo", year: 2000 },
  { title: "Swing e Simpatia", artist: "Chiclete com Banana", year: 1994 },
  { title: "Meu Erro", artist: "Chiclete com Banana", year: 1996 },
  { title: "Swing", artist: "Daniela Mercury", year: 1995 },
  { title: "O Canto da Cidade", artist: "Daniela Mercury", year: 1992 },
  { title: "Rapunzel", artist: "Daniela Mercury", year: 1993 },
  { title: "Preta", artist: "Daniela Mercury", year: 1997 },

  // --- Rock brasileiro ---
  { title: "Fátima", artist: "Capital Inicial", year: 1989 },
  { title: "Filhos da Pátria", artist: "Capital Inicial", year: 1990 },
  { title: "Música Urbana", artist: "Capital Inicial", year: 1988 },
  { title: "Independência ou Morte", artist: "Engenheiros do Hawaii", year: 1990 },
  { title: "Toda Forma de Poder", artist: "Engenheiros do Hawaii", year: 1990 },
  { title: "Infinita Highway", artist: "Engenheiros do Hawaii", year: 1990 },
  { title: "Bete Balanço", artist: "Barão Vermelho", year: 1984 },
  { title: "Maldito Serás", artist: "Barão Vermelho", year: 1982 },
  { title: "Songo do Vento", artist: "Barão Vermelho", year: 1990 },
  { title: "Menino do Rio", artist: "Baby Consuelo & Pepeu Gomes", year: 1980 },
  { title: "Metrô Linha 743", artist: "Metrô", year: 1984 },
  { title: "Não Existe Amor em SP", artist: "Rita Lee", year: 2002 },
  { title: "Ovelha Negra", artist: "Rita Lee", year: 1975 },
  { title: "Alô Alô Marciano", artist: "Rita Lee", year: 1982 },
  { title: "Chega Mais", artist: "Renato Russo & Cássia Eller", year: 2001 },
  { title: "Pelo Amor de Deus", artist: "Cássia Eller", year: 1994 },
  { title: "Malandragem", artist: "Cássia Eller", year: 1990 },
  { title: "Palavras ao Vento", artist: "Cássia Eller", year: 1994 },
];
