// songs/tr.js — מאגר שירים בטורקית (ללא youtubeId — ניגון בחיפוש אוטומטי).
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.tr = [
  { title: "Kara Sevda", artist: "Sezen Aksu", year: 1993 },
  { title: "Firuze", artist: "Sezen Aksu", year: 1993 },
  { title: "Hadi Bakalım", artist: "Sezen Aksu", year: 1991 },
  { title: "Gitme Gitme", artist: "Sezen Aksu", year: 1985 },
  { title: "Aya Benzemez", artist: "Sezen Aksu", year: 1997 },
  { title: "Şıkıdım", artist: "Sezen Aksu", year: 1998 },
  { title: "Vazgeçtim", artist: "Sezen Aksu", year: 1991 },
  { title: "Copperfield", artist: "Tarkan", year: 1994 },
  { title: "Şımarık", artist: "Tarkan", year: 1997 },
  { title: "Kuzu Kuzu", artist: "Tarkan", year: 1994 },
  { title: "Kış Güneşi", artist: "Tarkan", year: 2001 },
  { title: "Dudu", artist: "Tarkan", year: 2003 },
  { title: "Bam Bam", artist: "Tarkan", year: 2010 },
  { title: "Yolla", artist: "Tarkan", year: 1994 },
  { title: "Deli Deli Küpeli", artist: "Ferdi Tayfur", year: 1975 },
  { title: "Nazar Değmesin", artist: "Ferdi Tayfur", year: 1980 },
  { title: "Çile Bülbülüm", artist: "Ferdi Tayfur", year: 1978 },
  { title: "Yalan Dünya", artist: "Orhan Gencebay", year: 1973 },
  { title: "Batsın Bu Dünya", artist: "Orhan Gencebay", year: 1975 },
  { title: "Hor Görme Garibi", artist: "Orhan Gencebay", year: 1970 },
  { title: "Bir Teselli Ver", artist: "Barış Manço", year: 1971 },
  { title: "Dağlar Dağlar", artist: "Barış Manço", year: 1975 },
  { title: "Gülpembe", artist: "Barış Manço", year: 1983 },
  { title: "Domates Biber Patlıcan", artist: "Barış Manço", year: 1986 },
  { title: "Nane Limon Kabuğu", artist: "Barış Manço", year: 1994 },
  { title: "Deniz Üstü Köpürür", artist: "Cem Karaca", year: 1975 },
  { title: "Namus Belası", artist: "Cem Karaca", year: 1976 },
  { title: "Resimdeki Gözyaşları", artist: "Cem Karaca", year: 1974 },
  { title: "Estarabim", artist: "Erkin Koray", year: 1974 },
  { title: "Cemalim", artist: "Erkin Koray", year: 1973 },
  { title: "Mesafeler", artist: "Sertab Erener", year: 1997 },
  { title: "Everyway That I Can", artist: "Sertab Erener", year: 2003 },
  { title: "Aşk Sakızı", artist: "Sertab Erener", year: 1997 },
  { title: "Hayat Bayram Olsa", artist: "Sertab Erener", year: 1995 },
  { title: "Alkole Ver Beni", artist: "Ajda Pekkan", year: 1991 },
  { title: "Süperstar", artist: "Ajda Pekkan", year: 1980 },
  { title: "Yanlış Anlama", artist: "Ajda Pekkan", year: 1985 },
  { title: "Bambaşka Biri", artist: "Ajda Pekkan", year: 1996 },
  { title: "Sarı Sarı", artist: "İbrahim Tatlıses", year: 1985 },
  { title: "Gülbahar", artist: "İbrahim Tatlıses", year: 1988 },
  { title: "Yaşasın Anadolu", artist: "İbrahim Tatlıses", year: 1990 },
  { title: "Haydi Söyle", artist: "İbrahim Tatlıses", year: 1993 },
  { title: "Kalan Sana Helal Olsun", artist: "Ebru Gündeş", year: 1997 },
  { title: "Yalancı Bahar", artist: "Ebru Gündeş", year: 2001 },
  { title: "Sen Ağlama", artist: "Ebru Gündeş", year: 2003 },
  { title: "Gemiler", artist: "Kayahan", year: 1985 },
  { title: "Nasıl Anlatsam", artist: "Kayahan", year: 1985 },
  { title: "Adı Bende Saklı", artist: "Kayahan", year: 1997 },
  { title: "Gönül Dağı", artist: "Şevval Sam", year: 2003 },
  { title: "Yak Kendini", artist: "MFÖ", year: 1988 },
  { title: "Ele Güne Karşı", artist: "MFÖ", year: 1985 },
  { title: "Ölüyorum", artist: "MFÖ", year: 1981 },
  { title: "Herkes Kendi Evinde", artist: "MFÖ", year: 1988 },
  { title: "Deme Bana", artist: "Levent Yüksel", year: 1993 },
  { title: "Kokain", artist: "Levent Yüksel", year: 1993 },
  { title: "Gündüz Gece", artist: "Nilüfer", year: 1987 },
  { title: "Bebeğim", artist: "Nilüfer", year: 1979 },
  { title: "Sen Benim Şarkılarımsın", artist: "Nilüfer", year: 1990 },
  { title: "Popstar", artist: "Nilüfer", year: 1998 },
  { title: "Yeşil Yeşil", artist: "Emel Sayın", year: 1975 },
  { title: "Rüzgar", artist: "Emel Sayın", year: 1980 },
  { title: "Vur Gitsin Beni", artist: "Emel Sayın", year: 1973 },
  { title: "Bebek", artist: "Müslüm Gürses", year: 1994 },
  { title: "Nilüfer", artist: "Müslüm Gürses", year: 1990 },
  { title: "Yakma Beni", artist: "Müslüm Gürses", year: 1985 },
  { title: "Affet", artist: "Müslüm Gürses", year: 1988 },
  { title: "Manolyam", artist: "Bergen", year: 1985 },
  { title: "Sarmaşık", artist: "Bergen", year: 1986 },
  { title: "Yalnız Değilsin", artist: "Kenan Doğulu", year: 2004 },
  { title: "Aşk Koşacak", artist: "Kenan Doğulu", year: 2010 },
  { title: "Şaka Şaka", artist: "Kenan Doğulu", year: 2001 },
  { title: "İki Dünya", artist: "Hande Yener", year: 2008 },
  { title: "Sen Nasıl Bir Erkeksin", artist: "Hande Yener", year: 2011 },
  { title: "Acı Bal", artist: "Hande Yener", year: 2003 },
  { title: "Ah Be Dünya", artist: "Gülben Ergen", year: 1997 },
  { title: "İnsafsız", artist: "Gülben Ergen", year: 2001 },
  { title: "Gel", artist: "Mustafa Sandal", year: 2000 },
  { title: "Aşkımızın Şarkısı", artist: "Mustafa Sandal", year: 2003 },
  { title: "İsyankar", artist: "Mustafa Sandal", year: 1997 },
  { title: "Araba", artist: "Mustafa Sandal ft. Kenza Farah", year: 2007 },
  { title: "Beat Box", artist: "Mustafa Sandal ft. Rue Ka", year: 2001 },
  { title: "Yalan", artist: "Emre Aydın", year: 2010 },
  { title: "Öptüğüm Gülüm Değil mi", artist: "Yıldız Tilbe", year: 1999 },
  { title: "Delikanlım", artist: "Yıldız Tilbe", year: 1997 },
  { title: "Isyankar", artist: "Yıldız Tilbe", year: 2004 },
  { title: "Aşk Ölmedi Ki", artist: "Yıldız Tilbe", year: 2011 },
  { title: "Nikahsız", artist: "Muazzez Ersoy", year: 1980 },
  { title: "Vazgeçemem", artist: "Ferhat Göçer", year: 2003 },
  { title: "Aşk Bir Elmadır", artist: "Ferhat Göçer", year: 2005 },
];
