// songs/vi.js — Danh sách bài hát tiếng Việt (không có youtubeId — phát bằng
// tìm kiếm tự động theo "ca sĩ tên bài hát").
window.SONGS_BY_LANG = window.SONGS_BY_LANG || {};
window.SONGS_BY_LANG.vi = [
  { title: "Diễm Xưa", artist: "Trịnh Công Sơn", year: 1960 },
  { title: "Hạ Trắng", artist: "Trịnh Công Sơn", year: 1961 },
  { title: "Nối Vòng Tay Lớn", artist: "Trịnh Công Sơn", year: 1968 },
  { title: "Biển Nhớ", artist: "Trịnh Công Sơn", year: 1962 },
  { title: "Cát Bụi", artist: "Trịnh Công Sơn", year: 1965 },
  { title: "Mưa Hồng", artist: "Trịnh Công Sơn", year: 1965 },
  { title: "Một Cõi Đi Về", artist: "Trịnh Công Sơn", year: 1985 },
  { title: "Riêng Một Góc Trời", artist: "Tuấn Ngọc", year: 1997 },
  { title: "Bây Giờ Tháng Mấy", artist: "Từ Công Phụng", year: 1961 },
  { title: "Niệm Khúc Cuối", artist: "Ngô Thụy Miên", year: 1971 },
  { title: "Mùa Thu Cho Em", artist: "Ngô Thụy Miên", year: 1974 },
  { title: "Áo Lụa Hà Đông", artist: "Ngô Thụy Miên", year: 1970 },
  { title: "Tình Nhớ", artist: "Khánh Ly", year: 1970 },
  { title: "Đêm Đông", artist: "Bạch Yến", year: 1950 },
  { title: "Không", artist: "Elvis Phương", year: 1970 },
  { title: "Duyên Phận", artist: "Elvis Phương", year: 1998 },
  { title: "Đường Xưa Lối Cũ", artist: "Duy Khánh", year: 1968 },
  { title: "Xin Còn Gọi Tên Nhau", artist: "Duy Khánh", year: 1970 },
  { title: "Nửa Đêm Ngoài Phố", artist: "Thanh Thúy", year: 1965 },
  { title: "Sầu Đông", artist: "Thanh Thúy", year: 1963 },
  { title: "Chuyện Tình", artist: "Trường Vũ", year: 1995 },
  { title: "Người Tình Không Đến", artist: "Trường Vũ", year: 1996 },
  { title: "Ai Cho Tôi Tình Yêu", artist: "Như Quỳnh", year: 1996 },
  { title: "Chuyến Đò Vĩ Tuyến", artist: "Như Quỳnh", year: 1997 },
  { title: "Tình Cây Và Đất", artist: "Như Quỳnh & Trường Vũ", year: 1998 },
  { title: "Nối Lại Tình Xưa", artist: "Đan Nguyên & Lê Sang", year: 2010 },
  { title: "Sương Trắng Miền Quê Ngoại", artist: "Đan Nguyên", year: 2008 },
  { title: "Chiếc Áo Bà Ba", artist: "Bạch Yến", year: 1970 },
  { title: "Về Đâu Mái Tóc Người Thương", artist: "Chế Linh", year: 1969 },
  { title: "Đêm Buồn Tỉnh Lẻ", artist: "Chế Linh", year: 1970 },
  { title: "Mưa Rừng", artist: "Chế Linh", year: 1968 },
  { title: "Nhật Ký Đời Tôi", artist: "Chế Linh", year: 1970 },
  { title: "Tình Bơ Vơ", artist: "Chế Linh", year: 1966 },
  { title: "Người Ngoài Phố", artist: "Thái Thanh", year: 1968 },
  { title: "Tình Ca", artist: "Thái Thanh", year: 1953 },
  { title: "Nghìn Trùng Xa Cách", artist: "Thái Thanh", year: 1968 },
  { title: "Ru Ta Ngậm Ngùi", artist: "Khánh Ly", year: 1970 },
  { title: "Bống Bống Bang Bang", artist: "365daband", year: 2016 },
  { title: "Nơi Này Có Anh", artist: "Sơn Tùng M-TP", year: 2016 },
  { title: "Chạy Ngay Đi", artist: "Sơn Tùng M-TP", year: 2018 },
  { title: "Lạc Trôi", artist: "Sơn Tùng M-TP", year: 2017 },
  { title: "Em Của Ngày Hôm Qua", artist: "Sơn Tùng M-TP", year: 2014 },
  { title: "Muộn Rồi Mà Sao Còn", artist: "Sơn Tùng M-TP", year: 2020 },
  { title: "Có Chàng Trai Viết Lên Cây", artist: "Phan Mạnh Quỳnh", year: 2015 },
  { title: "Vợ Người Ta", artist: "Phan Mạnh Quỳnh", year: 2015 },
  { title: "Hồng Nhan", artist: "Jack", year: 2019 },
  { title: "Bạc Phận", artist: "Jack & K-ICM", year: 2019 },
  { title: "Sóng Gió", artist: "Jack & K-ICM", year: 2019 },
  { title: "Bức Thư Tình Đầu Tiên", artist: "Đông Nhi", year: 2016 },
  { title: "Ta Đâu Có Say", artist: "Đông Nhi", year: 2018 },
  { title: "Kề Bên", artist: "Đông Nhi", year: 2018 },
  { title: "Yêu 5", artist: "Rhymastic", year: 2014 },
  { title: "Chân Ái", artist: "Orange", year: 2019 },
  { title: "Anh Ơi Ở Lại", artist: "Chi Pu", year: 2019 },
  { title: "Đừng Yêu Nữa, Em Mệt Rồi", artist: "Min", year: 2016 },
  { title: "Ghen", artist: "Min & Erik", year: 2017 },
  { title: "Ghen Cô Vy", artist: "Min & Erik", year: 2020 },
  { title: "Bùa Yêu", artist: "Bích Phương", year: 2018 },
  { title: "Đi Đu Đưa Đi", artist: "Bích Phương", year: 2020 },
  { title: "Bao Giờ Lấy Chồng", artist: "Bích Phương", year: 2018 },
  { title: "Waiting For You", artist: "MTV & Trọng Hiếu", year: 2020 },
  { title: "Chiếc Khăn Gió Ấm", artist: "Khánh Phương", year: 2005 },
  { title: "Kiếp Đỏ Đen", artist: "Lê Bảo Bình", year: 2007 },
  { title: "Chỉ Là Không Cùng Nhau", artist: "Erik ft. Suni Hạ Linh", year: 2018 },
  { title: "Sau Tất Cả", artist: "Erik ft. Min", year: 2016 },
  { title: "Yêu Là Tha Thu", artist: "Uni5 & Bảo Anh", year: 2015 },
  { title: "Số Nhọ", artist: "Bảo Anh", year: 2016 },
  { title: "Tình Yêu Và Nước Mắt", artist: "Bảo Anh", year: 2018 },
  { title: "Cắt Đôi Nỗi Sầu", artist: "Tăng Duy Tân & Emcee L", year: 2022 },
  { title: "Waiting For You (Mono)", artist: "Mono", year: 2022 },
  { title: "Em Là", artist: "Mono", year: 2022 },
  { title: "Nàng Thơ", artist: "Hoàng Dũng", year: 2019 },
  { title: "Đường Tôi Chở Em Về", artist: "Vũ Cát Tường", year: 2016 },
  { title: "Vết Mưa", artist: "Vũ Cát Tường", year: 2019 },
];
